chmod 755 VRT_TIDAL_TRIGGER_ZUORA.ksh
chmod 755 VRT_TIDAL_TRIGGER_WORKDAY.ksh
chmod 755 VRT_TIDAL_TRIGGER_SFDC.ksh
chmod 755 VRT_TIDAL_TRIGGER_PARDOT.ksh
chmod 755 VRT_TIDAL_TRIGGER_OPRTNTY_TREND_REFRESH.ksh
chmod 755 VRT_TIDAL_TRIGGER_NETSUITEOPENAIR.ksh
chmod 755 VRT_TIDAL_TRIGGER_NETSUITE.ksh
chmod 755 VRT_TIDAL_TRIGGER_HIGHRADIUS.ksh
chmod 755 VRT_TIDAL_TRIGGER_CORP_BI_GTM_DAILY_EXTRACT_AND_UPLOAD.ksh
chmod 755 VRT_TIDAL_TRIGGER_CORP_BI_DAILY_EXTRACT_AND_UPLOAD.ksh
chmod 755 VRT_TIDAL_TRIGGER_CALLIDUS.ksh
chmod 755 VRT_TIDAL_TRIGGER_APTTUS.ksh
chmod 755 VRT_TIDAL_TRIGGER_AUDT_HIST_UPDATE_STATS_REFRESH.ksh

