SELECT 'CS_AppliedDeposit',COUNT(*) FROM ( SELECT PERIODSEQ,COUNT(PERIODSEQ) FROM SWT_RPT_BASE.CS_AppliedDeposit GROUP BY PERIODSEQ HAVING COUNT(PERIODSEQ) >1)A;
SELECT 'CS_Balance',COUNT(*) FROM ( SELECT PERIODSEQ,COUNT(PERIODSEQ) FROM SWT_RPT_BASE.CS_Balance GROUP BY PERIODSEQ HAVING COUNT(PERIODSEQ) >1)A;
SELECT 'CS_Commission',COUNT(*) FROM ( SELECT PERIODSEQ,COUNT(PERIODSEQ) FROM SWT_RPT_BASE.CS_Commission GROUP BY PERIODSEQ HAVING COUNT(PERIODSEQ) >1)A;
SELECT 'CS_Credit',COUNT(*) FROM ( SELECT PERIODSEQ,COUNT(PERIODSEQ) FROM SWT_RPT_BASE.CS_Credit GROUP BY PERIODSEQ HAVING COUNT(PERIODSEQ) >1)A;
SELECT 'CS_CreditAdjustment',COUNT(*) FROM ( SELECT PERIODSEQ,COUNT(PERIODSEQ) FROM SWT_RPT_BASE.CS_CreditAdjustment GROUP BY PERIODSEQ HAVING COUNT(PERIODSEQ) >1)A;
SELECT 'CS_Deposit',COUNT(*) FROM ( SELECT PERIODSEQ,COUNT(PERIODSEQ) FROM SWT_RPT_BASE.CS_Deposit GROUP BY PERIODSEQ HAVING COUNT(PERIODSEQ) >1)A;
SELECT 'CS_DepositAdjustment',COUNT(*) FROM ( SELECT PERIODSEQ,COUNT(PERIODSEQ) FROM SWT_RPT_BASE.CS_DepositAdjustment GROUP BY PERIODSEQ HAVING COUNT(PERIODSEQ) >1)A;
SELECT 'CS_GA_SalesOrder',COUNT(*) FROM ( SELECT SALESORDERSEQ,COUNT(SALESORDERSEQ) FROM SWT_RPT_BASE.CS_GA_SalesOrder GROUP BY SALESORDERSEQ HAVING COUNT(SALESORDERSEQ) >1)A;
SELECT 'CS_GA_SalesTransaction',COUNT(*) FROM ( SELECT SALESTRANSACTIONSEQ,COUNT(SALESTRANSACTIONSEQ) FROM SWT_RPT_BASE.CS_GA_SalesTransaction GROUP BY SALESTRANSACTIONSEQ HAVING COUNT(SALESTRANSACTIONSEQ) >1)A;
SELECT 'CS_Incentive',COUNT(*) FROM ( SELECT PERIODSEQ,COUNT(PERIODSEQ) FROM SWT_RPT_BASE.CS_Incentive GROUP BY PERIODSEQ HAVING COUNT(PERIODSEQ) >1)A;
SELECT 'CS_Measurement',COUNT(*) FROM ( SELECT PERIODSEQ,COUNT(PERIODSEQ) FROM SWT_RPT_BASE.CS_Measurement GROUP BY PERIODSEQ HAVING COUNT(PERIODSEQ) >1)A;
SELECT 'CS_Payment',COUNT(*) FROM ( SELECT PERIODSEQ,COUNT(PERIODSEQ) FROM SWT_RPT_BASE.CS_Payment GROUP BY PERIODSEQ HAVING COUNT(PERIODSEQ) >1)A;
SELECT 'CS_PaymentSummary',COUNT(*) FROM ( SELECT PERIODSEQ,COUNT(PERIODSEQ) FROM SWT_RPT_BASE.CS_PaymentSummary GROUP BY PERIODSEQ HAVING COUNT(PERIODSEQ) >1)A;
SELECT 'CS_Period',COUNT(*) FROM ( SELECT PERIODSEQ,COUNT(PERIODSEQ) FROM SWT_RPT_BASE.CS_Period GROUP BY PERIODSEQ HAVING COUNT(PERIODSEQ) >1)A;
SELECT 'CS_PeriodType',COUNT(*) FROM ( SELECT PERIODTYPESEQ,COUNT(PERIODTYPESEQ) FROM SWT_RPT_BASE.CS_PeriodType GROUP BY PERIODTYPESEQ HAVING COUNT(PERIODTYPESEQ) >1)A;
SELECT 'CS_RA_SalesTransaction',COUNT(*) FROM ( SELECT SALESTRANSACTIONSEQ,COUNT(SALESTRANSACTIONSEQ) FROM SWT_RPT_BASE.CS_RA_SalesTransaction GROUP BY SALESTRANSACTIONSEQ HAVING COUNT(SALESTRANSACTIONSEQ) >1)A;
SELECT 'CS_SalesOrder',COUNT(*) FROM ( SELECT SALESORDERSEQ,COUNT(SALESORDERSEQ) FROM SWT_RPT_BASE.CS_SalesOrder GROUP BY SALESORDERSEQ HAVING COUNT(SALESORDERSEQ) >1)A;
SELECT 'CS_SalesTransaction',COUNT(*) FROM ( SELECT SALESTRANSACTIONSEQ,COUNT(SALESTRANSACTIONSEQ) FROM SWT_RPT_BASE.CS_SalesTransaction GROUP BY SALESTRANSACTIONSEQ HAVING COUNT(SALESTRANSACTIONSEQ) >1)A;
SELECT 'CS_TransactionAddress',COUNT(*) FROM ( SELECT SALESTRANSACTIONSEQ,COUNT(SALESTRANSACTIONSEQ) FROM SWT_RPT_BASE.CS_TransactionAddress GROUP BY SALESTRANSACTIONSEQ HAVING COUNT(SALESTRANSACTIONSEQ) >1)A;
SELECT 'CS_TransactionAdjustment',COUNT(*) FROM ( SELECT SALESTRANSACTIONSEQ,COUNT(SALESTRANSACTIONSEQ) FROM SWT_RPT_BASE.CS_TransactionAdjustment GROUP BY SALESTRANSACTIONSEQ HAVING COUNT(SALESTRANSACTIONSEQ) >1)A;
SELECT 'CS_TransactionAssignment',COUNT(*) FROM ( SELECT SALESTRANSACTIONSEQ,COUNT(SALESTRANSACTIONSEQ) FROM SWT_RPT_BASE.CS_TransactionAssignment GROUP BY SALESTRANSACTIONSEQ HAVING COUNT(SALESTRANSACTIONSEQ) >1)A;
SELECT 'CS_GenericClassifier',COUNT(*) FROM ( SELECT classifierseq,COUNT(classifierseq) FROM SWT_RPT_BASE.CS_GenericClassifier GROUP BY classifierseq HAVING COUNT(classifierseq) >1)A;
SELECT 'CS_Classifier',COUNT(*) FROM ( SELECT classifierseq,COUNT(classifierseq) FROM SWT_RPT_BASE.CS_Classifier GROUP BY classifierseq HAVING COUNT(classifierseq) >1)A;
SELECT 'CS_Category_Classifiers',COUNT(*) FROM ( SELECT categoryclassifiersseq,COUNT(categoryclassifiersseq) FROM SWT_RPT_BASE.CS_Category_Classifiers GROUP BY categoryclassifiersseq HAVING COUNT(categoryclassifiersseq) >1)A;
SELECT 'CS_PipelineRun',COUNT(*) FROM ( SELECT PIPELINERUNSEQ,COUNT(PIPELINERUNSEQ) FROM SWT_RPT_BASE.CS_PipelineRun GROUP BY PIPELINERUNSEQ HAVING COUNT(PIPELINERUNSEQ) >1)A;


