/****
****Script Name   : Trnc_CS_Customer.sql
****Description   : Truncate and data load for CS_Customer
****/

/* Setting timing on**/
\timing

\set ON_ERROR_STOP on

CREATE LOCAL TEMP TABLE Start_Time_Tmp ON COMMIT PRESERVE ROWS AS select sysdate st from dual;

INSERT /*+DIRECT*/ INTO swt_rpt_stg.FAST_LD_AUDT
 (
       SUBJECT_AREA
      ,TBL_NM
      ,LD_DT
      ,START_DT_TIME
      ,END_DT_TIME
      ,SRC_REC_CNT
      ,TGT_REC_CNT
      ,COMPLTN_STAT
      )
  select 'CALLIDUS','CS_Customer',sysdate::date,sysdate,null,(select count(*) from "swt_rpt_stg"."CS_Customer") ,null,'N';

  Commit;  

TRUNCATE TABLE "swt_rpt_base".CS_Customer;


/* Deleting before seven days data from current date in the Historical Table */

delete /*+DIRECT*/ from swt_rpt_stg.CS_Customer_Hist  where LD_DT::date <= TIMESTAMPADD(DAY,-7,sysdate)::date;

INSERT /*+DIRECT*/ INTO "swt_rpt_base".CS_Customer
(
	CLASSIFIERSEQ
	,EFFECTIVESTARTDATE
	,EFFECTIVEENDDATE
	,ISLAST
	,CREATEDATE
	,REMOVEDATE
	,CONTACT
	,AREACODE
	,PHONE
	,FAX
	,ADDRESS1
	,ADDRESS2
	,ADDRESS3
	,CITY
	,STATE
	,COUNTRY
	,POSTALCODE
	,EMAIL
	,INDUSTRY
	,GEOGRAPHY
	,GENERICATTRIBUTE1
	,GENERICATTRIBUTE2
	,GENERICATTRIBUTE3
	,GENERICATTRIBUTE4
	,GENERICATTRIBUTE5
	,GENERICATTRIBUTE6
	,GENERICATTRIBUTE7
	,GENERICATTRIBUTE8
	,GENERICATTRIBUTE9
	,GENERICATTRIBUTE10
	,GENERICATTRIBUTE11
	,GENERICATTRIBUTE12
	,GENERICATTRIBUTE13
	,GENERICATTRIBUTE14
	,GENERICATTRIBUTE15
	,GENERICATTRIBUTE16
	,GENERICNUMBER1
	,UNITTYPEFORGENERICNUMBER1
	,GENERICNUMBER2
	,UNITTYPEFORGENERICNUMBER2
	,GENERICNUMBER3
	,UNITTYPEFORGENERICNUMBER3
	,GENERICNUMBER4
	,UNITTYPEFORGENERICNUMBER4
	,GENERICNUMBER5
	,UNITTYPEFORGENERICNUMBER5
	,GENERICNUMBER6
	,UNITTYPEFORGENERICNUMBER6
	,GENERICDATE1
	,GENERICDATE2
	,GENERICDATE3
	,GENERICDATE4
	,GENERICDATE5
	,GENERICDATE6
	,GENERICBOOLEAN1
	,GENERICBOOLEAN2
	,GENERICBOOLEAN3
	,GENERICBOOLEAN4
	,GENERICBOOLEAN5
	,GENERICBOOLEAN6
	,SWT_INS_DT
)
SELECT DISTINCT 
	CLASSIFIERSEQ
	,EFFECTIVESTARTDATE
	,EFFECTIVEENDDATE
	,ISLAST
	,CREATEDATE
	,REMOVEDATE
	,CONTACT
	,AREACODE
	,PHONE
	,FAX
	,ADDRESS1
	,ADDRESS2
	,ADDRESS3
	,CITY
	,STATE
	,COUNTRY
	,POSTALCODE
	,EMAIL
	,INDUSTRY
	,GEOGRAPHY
	,GENERICATTRIBUTE1
	,GENERICATTRIBUTE2
	,GENERICATTRIBUTE3
	,GENERICATTRIBUTE4
	,GENERICATTRIBUTE5
	,GENERICATTRIBUTE6
	,GENERICATTRIBUTE7
	,GENERICATTRIBUTE8
	,GENERICATTRIBUTE9
	,GENERICATTRIBUTE10
	,GENERICATTRIBUTE11
	,GENERICATTRIBUTE12
	,GENERICATTRIBUTE13
	,GENERICATTRIBUTE14
	,GENERICATTRIBUTE15
	,GENERICATTRIBUTE16
	,GENERICNUMBER1
	,UNITTYPEFORGENERICNUMBER1
	,GENERICNUMBER2
	,UNITTYPEFORGENERICNUMBER2
	,GENERICNUMBER3
	,UNITTYPEFORGENERICNUMBER3
	,GENERICNUMBER4
	,UNITTYPEFORGENERICNUMBER4
	,GENERICNUMBER5
	,UNITTYPEFORGENERICNUMBER5
	,GENERICNUMBER6
	,UNITTYPEFORGENERICNUMBER6
	,GENERICDATE1
	,GENERICDATE2
	,GENERICDATE3
	,GENERICDATE4
	,GENERICDATE5
	,GENERICDATE6
	,GENERICBOOLEAN1
	,GENERICBOOLEAN2
	,GENERICBOOLEAN3
	,GENERICBOOLEAN4
	,GENERICBOOLEAN5
	,GENERICBOOLEAN6
	,SYSDATE
FROM "swt_rpt_stg".CS_Customer;

/* Deleting partial audit entry */

DELETE FROM swt_rpt_stg.FAST_LD_AUDT where SUBJECT_AREA = 'CALLIDUS' and
TBL_NM = 'CS_Customer' and
COMPLTN_STAT = 'N' and
LD_DT=sysdate::date and 
SEQ_ID = (select max(SEQ_ID) from swt_rpt_stg.FAST_LD_AUDT where  SUBJECT_AREA = 'CALLIDUS' and  TBL_NM = 'CS_Customer' and  COMPLTN_STAT = 'N');


/* Inserting new audit entry with all stats */

INSERT INTO swt_rpt_stg.FAST_LD_AUDT
(
SUBJECT_AREA
,TBL_NM
,LD_DT
,START_DT_TIME
,END_DT_TIME
,SRC_REC_CNT
,TGT_REC_CNT
,COMPLTN_STAT
)
select 'CALLIDUS','CS_Customer',sysdate::date,(select st from Start_Time_Tmp),sysdate,(select count(*) from "swt_rpt_stg"."CS_Customer") ,(select count(*) from swt_rpt_base.CS_Customer where SWT_INS_DT::date = sysdate::date),'Y';

COMMIT;

INSERT /*+DIRECT*/ INTO swt_rpt_stg.CS_Customer_Hist SELECT * FROM swt_rpt_stg.CS_Customer;

COMMIT;


TRUNCATE TABLE swt_rpt_stg.CS_Customer;

select do_tm_task('mergeout','swt_rpt_stg.CS_Customer_Hist');
select do_tm_task('mergeout','swt_rpt_base.CS_Customer');
select do_tm_task('mergeout','swt_rpt_stg.FAST_LD_AUDT');
select ANALYZE_STATISTICS('swt_rpt_base.CS_Customer');
