/****
****Script Name   : Trun_CS_GA_Position.sql
****Description   : Truncate and data load for CS_GA_Position
****/

/* Setting timing on**/
\timing

\set ON_ERROR_STOP on

CREATE LOCAL TEMP TABLE Start_Time_Tmp ON COMMIT PRESERVE ROWS AS select sysdate st from dual;

INSERT /*+DIRECT*/ INTO swt_rpt_stg.FAST_LD_AUDT
 (
       SUBJECT_AREA
      ,TBL_NM
      ,LD_DT
      ,START_DT_TIME
      ,END_DT_TIME
      ,SRC_REC_CNT
      ,TGT_REC_CNT
      ,COMPLTN_STAT
      )
  select 'CALLIDUS','CS_GA_Position',sysdate::date,sysdate,null,(select count(*) from "swt_rpt_stg"."CS_GA_Position") ,null,'N';

  Commit;  

TRUNCATE TABLE "swt_rpt_base".CS_GA_Position;

/* Deleting before seven days data from current date in the Historical Table */

delete /*+DIRECT*/ from swt_rpt_stg.CS_GA_Position_Hist  where LD_DT::date <= TIMESTAMPADD(DAY,-7,sysdate)::date;

INSERT /*+DIRECT*/ INTO "swt_rpt_base".CS_GA_Position
(
	RULEELEMENTOWNERSEQ
	,EFFECTIVESTARTDATE
	,EFFECTIVEENDDATE
	,CREATEDATE
	,REMOVEDATE
	,PAGENUMBER
	,GENERICATTRIBUTE1
	,GENERICATTRIBUTE2
	,GENERICATTRIBUTE3
	,GENERICATTRIBUTE4
	,GENERICATTRIBUTE5
	,GENERICATTRIBUTE6
	,GENERICATTRIBUTE7
	,GENERICATTRIBUTE8
	,GENERICATTRIBUTE9
	,GENERICATTRIBUTE10
	,GENERICATTRIBUTE11
	,GENERICATTRIBUTE12
	,GENERICATTRIBUTE13
	,GENERICATTRIBUTE14
	,GENERICATTRIBUTE15
	,GENERICATTRIBUTE16
	,GENERICATTRIBUTE17
	,GENERICATTRIBUTE18
	,GENERICATTRIBUTE19
	,GENERICATTRIBUTE20
	,GENERICDATE1
	,GENERICDATE2
	,GENERICDATE3
	,GENERICDATE4
	,GENERICDATE5
	,GENERICDATE6
	,GENERICDATE7
	,GENERICDATE8
	,GENERICDATE9
	,GENERICDATE10
	,GENERICDATE11
	,GENERICDATE12
	,GENERICDATE13
	,GENERICDATE14
	,GENERICDATE15
	,GENERICDATE16
	,GENERICDATE17
	,GENERICDATE18
	,GENERICDATE19
	,GENERICDATE20
	,GENERICBOOLEAN1
	,GENERICBOOLEAN2
	,GENERICBOOLEAN3
	,GENERICBOOLEAN4
	,GENERICBOOLEAN5
	,GENERICBOOLEAN6
	,GENERICBOOLEAN7
	,GENERICBOOLEAN8
	,GENERICBOOLEAN9
	,GENERICBOOLEAN10
	,GENERICBOOLEAN11
	,GENERICBOOLEAN12
	,GENERICBOOLEAN13
	,GENERICBOOLEAN14
	,GENERICBOOLEAN15
	,GENERICBOOLEAN16
	,GENERICBOOLEAN17
	,GENERICBOOLEAN18
	,GENERICBOOLEAN19
	,GENERICBOOLEAN20
	,GENERICNUMBER1
	,UNITTYPEFORGENERICNUMBER1
	,GENERICNUMBER2
	,UNITTYPEFORGENERICNUMBER2
	,GENERICNUMBER3
	,UNITTYPEFORGENERICNUMBER3
	,GENERICNUMBER4
	,UNITTYPEFORGENERICNUMBER4
	,GENERICNUMBER5
	,UNITTYPEFORGENERICNUMBER5
	,GENERICNUMBER6
	,UNITTYPEFORGENERICNUMBER6
	,GENERICNUMBER7
	,UNITTYPEFORGENERICNUMBER7
	,GENERICNUMBER8
	,UNITTYPEFORGENERICNUMBER8
	,GENERICNUMBER9
	,UNITTYPEFORGENERICNUMBER9
	,GENERICNUMBER10
	,UNITTYPEFORGENERICNUMBER10
	,GENERICNUMBER11
	,UNITTYPEFORGENERICNUMBER11
	,GENERICNUMBER12
	,UNITTYPEFORGENERICNUMBER12
	,GENERICNUMBER13
	,UNITTYPEFORGENERICNUMBER13
	,GENERICNUMBER14
	,UNITTYPEFORGENERICNUMBER14
	,GENERICNUMBER15
	,UNITTYPEFORGENERICNUMBER15
	,GENERICNUMBER16
	,UNITTYPEFORGENERICNUMBER16
	,GENERICNUMBER17
	,UNITTYPEFORGENERICNUMBER17
	,GENERICNUMBER18
	,UNITTYPEFORGENERICNUMBER18
	,GENERICNUMBER19
	,UNITTYPEFORGENERICNUMBER19
	,GENERICNUMBER20
	,UNITTYPEFORGENERICNUMBER20
	,SWT_INS_DT
)
SELECT DISTINCT 
	RULEELEMENTOWNERSEQ
	,EFFECTIVESTARTDATE
	,EFFECTIVEENDDATE
	,CREATEDATE
	,REMOVEDATE
	,PAGENUMBER
	,GENERICATTRIBUTE1
	,GENERICATTRIBUTE2
	,GENERICATTRIBUTE3
	,GENERICATTRIBUTE4
	,GENERICATTRIBUTE5
	,GENERICATTRIBUTE6
	,GENERICATTRIBUTE7
	,GENERICATTRIBUTE8
	,GENERICATTRIBUTE9
	,GENERICATTRIBUTE10
	,GENERICATTRIBUTE11
	,GENERICATTRIBUTE12
	,GENERICATTRIBUTE13
	,GENERICATTRIBUTE14
	,GENERICATTRIBUTE15
	,GENERICATTRIBUTE16
	,GENERICATTRIBUTE17
	,GENERICATTRIBUTE18
	,GENERICATTRIBUTE19
	,GENERICATTRIBUTE20
	,GENERICDATE1
	,GENERICDATE2
	,GENERICDATE3
	,GENERICDATE4
	,GENERICDATE5
	,GENERICDATE6
	,GENERICDATE7
	,GENERICDATE8
	,GENERICDATE9
	,GENERICDATE10
	,GENERICDATE11
	,GENERICDATE12
	,GENERICDATE13
	,GENERICDATE14
	,GENERICDATE15
	,GENERICDATE16
	,GENERICDATE17
	,GENERICDATE18
	,GENERICDATE19
	,GENERICDATE20
	,GENERICBOOLEAN1
	,GENERICBOOLEAN2
	,GENERICBOOLEAN3
	,GENERICBOOLEAN4
	,GENERICBOOLEAN5
	,GENERICBOOLEAN6
	,GENERICBOOLEAN7
	,GENERICBOOLEAN8
	,GENERICBOOLEAN9
	,GENERICBOOLEAN10
	,GENERICBOOLEAN11
	,GENERICBOOLEAN12
	,GENERICBOOLEAN13
	,GENERICBOOLEAN14
	,GENERICBOOLEAN15
	,GENERICBOOLEAN16
	,GENERICBOOLEAN17
	,GENERICBOOLEAN18
	,GENERICBOOLEAN19
	,GENERICBOOLEAN20
	,GENERICNUMBER1
	,UNITTYPEFORGENERICNUMBER1
	,GENERICNUMBER2
	,UNITTYPEFORGENERICNUMBER2
	,GENERICNUMBER3
	,UNITTYPEFORGENERICNUMBER3
	,GENERICNUMBER4
	,UNITTYPEFORGENERICNUMBER4
	,GENERICNUMBER5
	,UNITTYPEFORGENERICNUMBER5
	,GENERICNUMBER6
	,UNITTYPEFORGENERICNUMBER6
	,GENERICNUMBER7
	,UNITTYPEFORGENERICNUMBER7
	,GENERICNUMBER8
	,UNITTYPEFORGENERICNUMBER8
	,GENERICNUMBER9
	,UNITTYPEFORGENERICNUMBER9
	,GENERICNUMBER10
	,UNITTYPEFORGENERICNUMBER10
	,GENERICNUMBER11
	,UNITTYPEFORGENERICNUMBER11
	,GENERICNUMBER12
	,UNITTYPEFORGENERICNUMBER12
	,GENERICNUMBER13
	,UNITTYPEFORGENERICNUMBER13
	,GENERICNUMBER14
	,UNITTYPEFORGENERICNUMBER14
	,GENERICNUMBER15
	,UNITTYPEFORGENERICNUMBER15
	,GENERICNUMBER16
	,UNITTYPEFORGENERICNUMBER16
	,GENERICNUMBER17
	,UNITTYPEFORGENERICNUMBER17
	,GENERICNUMBER18
	,UNITTYPEFORGENERICNUMBER18
	,GENERICNUMBER19
	,UNITTYPEFORGENERICNUMBER19
	,GENERICNUMBER20
	,UNITTYPEFORGENERICNUMBER20
	,SYSDATE
FROM "swt_rpt_stg".CS_GA_Position;

/* Deleting partial audit entry */

DELETE FROM swt_rpt_stg.FAST_LD_AUDT where SUBJECT_AREA = 'CALLIDUS' and
TBL_NM = 'CS_GA_Position' and
COMPLTN_STAT = 'N' and
LD_DT=sysdate::date and 
SEQ_ID = (select max(SEQ_ID) from swt_rpt_stg.FAST_LD_AUDT where  SUBJECT_AREA = 'CALLIDUS' and  TBL_NM = 'CS_GA_Position' and  COMPLTN_STAT = 'N');


/* Inserting new audit entry with all stats */

INSERT INTO swt_rpt_stg.FAST_LD_AUDT
(
SUBJECT_AREA
,TBL_NM
,LD_DT
,START_DT_TIME
,END_DT_TIME
,SRC_REC_CNT
,TGT_REC_CNT
,COMPLTN_STAT
)
select 'CALLIDUS','CS_GA_Position',sysdate::date,(select st from Start_Time_Tmp),sysdate,(select count(*) from "swt_rpt_stg"."CS_GA_Position") ,(select count(*) from swt_rpt_base.CS_GA_Position where SWT_INS_DT::date = sysdate::date),'Y';

COMMIT;

INSERT /*+DIRECT*/ INTO swt_rpt_stg.CS_GA_Position_Hist SELECT * FROM swt_rpt_stg.CS_GA_Position;

COMMIT;

SELECT PURGE_TABLE('swt_rpt_stg.CS_GA_Position_Hist');
SELECT ANALYZE_STATISTICS('swt_rpt_base.CS_GA_Position');
TRUNCATE TABLE swt_rpt_stg.CS_GA_Position;

