
/****
****Script Name   : CS_GA_SalesOrder.sql
****Description   : Incremental  data load for CS_GA_SalesOrder
****/
/* Setting timing on**/
\timing

\set ON_ERROR_STOP on

CREATE LOCAL TEMP TABLE Start_Time_Tmp ON COMMIT PRESERVE ROWS AS select sysdate st from dual;

INSERT /*+DIRECT*/ INTO swt_rpt_stg.FAST_LD_AUDT
(
SUBJECT_AREA
,TBL_NM
,LD_DT
,START_DT_TIME
,END_DT_TIME
,SRC_REC_CNT
,TGT_REC_CNT
,COMPLTN_STAT
)
select 'CALLIDUS','CS_GA_SalesOrder',sysdate::date,sysdate,null,(select count(*) from "swt_rpt_stg"."CS_GA_SalesOrder") ,null,'N';

Commit;

CREATE LOCAL TEMP TABLE CS_GA_SalesOrder_stg_Tmp ON COMMIT PRESERVE ROWS AS
(
SELECT DISTINCT * FROM swt_rpt_stg.CS_GA_SalesOrder)
SEGMENTED BY HASH(SALESORDERSEQ) ALL NODES;

CREATE LOCAL TEMP TABLE CS_SalesOrder_base_Tmp ON COMMIT PRESERVE ROWS AS
(
SELECT DISTINCT * FROM swt_rpt_base.CS_SalesOrder)
SEGMENTED BY HASH(SALESORDERSEQ) ALL NODES;


INSERT /*+DIRECT*/ INTO "swt_rpt_stg"."CS_GA_SalesOrder_Hist"
(
SALESORDERSEQ
,PAGENUMBER
,CREATEDATE
,REMOVEDATE
,GENERICATTRIBUTE1
,GENERICATTRIBUTE2
,GENERICATTRIBUTE3
,GENERICATTRIBUTE4
,GENERICATTRIBUTE5
,GENERICATTRIBUTE6
,GENERICATTRIBUTE7
,GENERICATTRIBUTE8
,GENERICATTRIBUTE9
,GENERICATTRIBUTE10
,GENERICATTRIBUTE11
,GENERICATTRIBUTE12
,GENERICATTRIBUTE13
,GENERICATTRIBUTE14
,GENERICATTRIBUTE15
,GENERICATTRIBUTE16
,GENERICATTRIBUTE17
,GENERICATTRIBUTE18
,GENERICATTRIBUTE19
,GENERICATTRIBUTE20
,GENERICDATE1
,GENERICDATE2
,GENERICDATE3
,GENERICDATE4
,GENERICDATE5
,GENERICDATE6
,GENERICDATE7
,GENERICDATE8
,GENERICDATE9
,GENERICDATE10
,GENERICDATE11
,GENERICDATE12
,GENERICDATE13
,GENERICDATE14
,GENERICDATE15
,GENERICDATE16
,GENERICDATE17
,GENERICDATE18
,GENERICDATE19
,GENERICDATE20
,GENERICBOOLEAN1
,GENERICBOOLEAN2
,GENERICBOOLEAN3
,GENERICBOOLEAN4
,GENERICBOOLEAN5
,GENERICBOOLEAN6
,GENERICBOOLEAN7
,GENERICBOOLEAN8
,GENERICBOOLEAN9
,GENERICBOOLEAN10
,GENERICBOOLEAN11
,GENERICBOOLEAN12
,GENERICBOOLEAN13
,GENERICBOOLEAN14
,GENERICBOOLEAN15
,GENERICBOOLEAN16
,GENERICBOOLEAN17
,GENERICBOOLEAN18
,GENERICBOOLEAN19
,GENERICBOOLEAN20
,GENERICNUMBER1
,UNITTYPEFORGENERICNUMBER1
,GENERICNUMBER2
,UNITTYPEFORGENERICNUMBER2
,GENERICNUMBER3
,UNITTYPEFORGENERICNUMBER3
,GENERICNUMBER4
,UNITTYPEFORGENERICNUMBER4
,GENERICNUMBER5
,UNITTYPEFORGENERICNUMBER5
,GENERICNUMBER6
,UNITTYPEFORGENERICNUMBER6
,GENERICNUMBER7
,UNITTYPEFORGENERICNUMBER7
,GENERICNUMBER8
,UNITTYPEFORGENERICNUMBER8
,GENERICNUMBER9
,UNITTYPEFORGENERICNUMBER9
,GENERICNUMBER10
,UNITTYPEFORGENERICNUMBER10
,GENERICNUMBER11
,UNITTYPEFORGENERICNUMBER11
,GENERICNUMBER12
,UNITTYPEFORGENERICNUMBER12
,GENERICNUMBER13
,UNITTYPEFORGENERICNUMBER13
,GENERICNUMBER14
,UNITTYPEFORGENERICNUMBER14
,GENERICNUMBER15
,UNITTYPEFORGENERICNUMBER15
,GENERICNUMBER16
,UNITTYPEFORGENERICNUMBER16
,GENERICNUMBER17
,UNITTYPEFORGENERICNUMBER17
,GENERICNUMBER18
,UNITTYPEFORGENERICNUMBER18
,GENERICNUMBER19
,UNITTYPEFORGENERICNUMBER19
,GENERICNUMBER20
,UNITTYPEFORGENERICNUMBER20
,LD_DT
,SWT_INS_DT
,d_source
)
SELECT DISTINCT
SALESORDERSEQ
,PAGENUMBER
,CREATEDATE
,REMOVEDATE
,GENERICATTRIBUTE1
,GENERICATTRIBUTE2
,GENERICATTRIBUTE3
,GENERICATTRIBUTE4
,GENERICATTRIBUTE5
,GENERICATTRIBUTE6
,GENERICATTRIBUTE7
,GENERICATTRIBUTE8
,GENERICATTRIBUTE9
,GENERICATTRIBUTE10
,GENERICATTRIBUTE11
,GENERICATTRIBUTE12
,GENERICATTRIBUTE13
,GENERICATTRIBUTE14
,GENERICATTRIBUTE15
,GENERICATTRIBUTE16
,GENERICATTRIBUTE17
,GENERICATTRIBUTE18
,GENERICATTRIBUTE19
,GENERICATTRIBUTE20
,GENERICDATE1
,GENERICDATE2
,GENERICDATE3
,GENERICDATE4
,GENERICDATE5
,GENERICDATE6
,GENERICDATE7
,GENERICDATE8
,GENERICDATE9
,GENERICDATE10
,GENERICDATE11
,GENERICDATE12
,GENERICDATE13
,GENERICDATE14
,GENERICDATE15
,GENERICDATE16
,GENERICDATE17
,GENERICDATE18
,GENERICDATE19
,GENERICDATE20
,GENERICBOOLEAN1
,GENERICBOOLEAN2
,GENERICBOOLEAN3
,GENERICBOOLEAN4
,GENERICBOOLEAN5
,GENERICBOOLEAN6
,GENERICBOOLEAN7
,GENERICBOOLEAN8
,GENERICBOOLEAN9
,GENERICBOOLEAN10
,GENERICBOOLEAN11
,GENERICBOOLEAN12
,GENERICBOOLEAN13
,GENERICBOOLEAN14
,GENERICBOOLEAN15
,GENERICBOOLEAN16
,GENERICBOOLEAN17
,GENERICBOOLEAN18
,GENERICBOOLEAN19
,GENERICBOOLEAN20
,GENERICNUMBER1
,UNITTYPEFORGENERICNUMBER1
,GENERICNUMBER2
,UNITTYPEFORGENERICNUMBER2
,GENERICNUMBER3
,UNITTYPEFORGENERICNUMBER3
,GENERICNUMBER4
,UNITTYPEFORGENERICNUMBER4
,GENERICNUMBER5
,UNITTYPEFORGENERICNUMBER5
,GENERICNUMBER6
,UNITTYPEFORGENERICNUMBER6
,GENERICNUMBER7
,UNITTYPEFORGENERICNUMBER7
,GENERICNUMBER8
,UNITTYPEFORGENERICNUMBER8
,GENERICNUMBER9
,UNITTYPEFORGENERICNUMBER9
,GENERICNUMBER10
,UNITTYPEFORGENERICNUMBER10
,GENERICNUMBER11
,UNITTYPEFORGENERICNUMBER11
,GENERICNUMBER12
,UNITTYPEFORGENERICNUMBER12
,GENERICNUMBER13
,UNITTYPEFORGENERICNUMBER13
,GENERICNUMBER14
,UNITTYPEFORGENERICNUMBER14
,GENERICNUMBER15
,UNITTYPEFORGENERICNUMBER15
,GENERICNUMBER16
,UNITTYPEFORGENERICNUMBER16
,GENERICNUMBER17
,UNITTYPEFORGENERICNUMBER17
,GENERICNUMBER18
,UNITTYPEFORGENERICNUMBER18
,GENERICNUMBER19
,UNITTYPEFORGENERICNUMBER19
,GENERICNUMBER20
,UNITTYPEFORGENERICNUMBER20
,SYSDATE AS LD_DT
,SWT_INS_DT
,'base'
FROM "swt_rpt_base"."CS_GA_SalesOrder" WHERE SALESORDERSEQ IN
(SELECT STG.SALESORDERSEQ FROM CS_GA_SalesOrder_stg_Tmp STG JOIN CS_SalesOrder_base_Tmp BASE ON STG.SALESORDERSEQ=BASE.SALESORDERSEQ);;

DELETE /*+DIRECT*/ from "swt_rpt_stg"."CS_GA_SalesOrder_Hist"  where LD_DT::date <= TIMESTAMPADD(DAY,-7,sysdate)::date;

DELETE /*+DIRECT*/ FROM "swt_rpt_base"."CS_GA_SalesOrder" WHERE SALESORDERSEQ IN
(SELECT STG.SALESORDERSEQ FROM CS_GA_SalesOrder_stg_Tmp STG JOIN CS_SalesOrder_base_Tmp BASE ON STG.SALESORDERSEQ=BASE.SALESORDERSEQ);

INSERT /*+DIRECT*/ INTO "swt_rpt_base"."CS_GA_SalesOrder"
(
SALESORDERSEQ
,PAGENUMBER
,CREATEDATE
,REMOVEDATE
,GENERICATTRIBUTE1
,GENERICATTRIBUTE2
,GENERICATTRIBUTE3
,GENERICATTRIBUTE4
,GENERICATTRIBUTE5
,GENERICATTRIBUTE6
,GENERICATTRIBUTE7
,GENERICATTRIBUTE8
,GENERICATTRIBUTE9
,GENERICATTRIBUTE10
,GENERICATTRIBUTE11
,GENERICATTRIBUTE12
,GENERICATTRIBUTE13
,GENERICATTRIBUTE14
,GENERICATTRIBUTE15
,GENERICATTRIBUTE16
,GENERICATTRIBUTE17
,GENERICATTRIBUTE18
,GENERICATTRIBUTE19
,GENERICATTRIBUTE20
,GENERICDATE1
,GENERICDATE2
,GENERICDATE3
,GENERICDATE4
,GENERICDATE5
,GENERICDATE6
,GENERICDATE7
,GENERICDATE8
,GENERICDATE9
,GENERICDATE10
,GENERICDATE11
,GENERICDATE12
,GENERICDATE13
,GENERICDATE14
,GENERICDATE15
,GENERICDATE16
,GENERICDATE17
,GENERICDATE18
,GENERICDATE19
,GENERICDATE20
,GENERICBOOLEAN1
,GENERICBOOLEAN2
,GENERICBOOLEAN3
,GENERICBOOLEAN4
,GENERICBOOLEAN5
,GENERICBOOLEAN6
,GENERICBOOLEAN7
,GENERICBOOLEAN8
,GENERICBOOLEAN9
,GENERICBOOLEAN10
,GENERICBOOLEAN11
,GENERICBOOLEAN12
,GENERICBOOLEAN13
,GENERICBOOLEAN14
,GENERICBOOLEAN15
,GENERICBOOLEAN16
,GENERICBOOLEAN17
,GENERICBOOLEAN18
,GENERICBOOLEAN19
,GENERICBOOLEAN20
,GENERICNUMBER1
,UNITTYPEFORGENERICNUMBER1
,GENERICNUMBER2
,UNITTYPEFORGENERICNUMBER2
,GENERICNUMBER3
,UNITTYPEFORGENERICNUMBER3
,GENERICNUMBER4
,UNITTYPEFORGENERICNUMBER4
,GENERICNUMBER5
,UNITTYPEFORGENERICNUMBER5
,GENERICNUMBER6
,UNITTYPEFORGENERICNUMBER6
,GENERICNUMBER7
,UNITTYPEFORGENERICNUMBER7
,GENERICNUMBER8
,UNITTYPEFORGENERICNUMBER8
,GENERICNUMBER9
,UNITTYPEFORGENERICNUMBER9
,GENERICNUMBER10
,UNITTYPEFORGENERICNUMBER10
,GENERICNUMBER11
,UNITTYPEFORGENERICNUMBER11
,GENERICNUMBER12
,UNITTYPEFORGENERICNUMBER12
,GENERICNUMBER13
,UNITTYPEFORGENERICNUMBER13
,GENERICNUMBER14
,UNITTYPEFORGENERICNUMBER14
,GENERICNUMBER15
,UNITTYPEFORGENERICNUMBER15
,GENERICNUMBER16
,UNITTYPEFORGENERICNUMBER16
,GENERICNUMBER17
,UNITTYPEFORGENERICNUMBER17
,GENERICNUMBER18
,UNITTYPEFORGENERICNUMBER18
,GENERICNUMBER19
,UNITTYPEFORGENERICNUMBER19
,GENERICNUMBER20
,UNITTYPEFORGENERICNUMBER20
,SWT_INS_DT
)
SELECT DISTINCT
STG.SALESORDERSEQ
,STG.PAGENUMBER
,STG.CREATEDATE
,STG.REMOVEDATE
,STG.GENERICATTRIBUTE1
,STG.GENERICATTRIBUTE2
,STG.GENERICATTRIBUTE3
,STG.GENERICATTRIBUTE4
,STG.GENERICATTRIBUTE5
,STG.GENERICATTRIBUTE6
,STG.GENERICATTRIBUTE7
,STG.GENERICATTRIBUTE8
,STG.GENERICATTRIBUTE9
,STG.GENERICATTRIBUTE10
,STG.GENERICATTRIBUTE11
,STG.GENERICATTRIBUTE12
,STG.GENERICATTRIBUTE13
,STG.GENERICATTRIBUTE14
,STG.GENERICATTRIBUTE15
,STG.GENERICATTRIBUTE16
,STG.GENERICATTRIBUTE17
,STG.GENERICATTRIBUTE18
,STG.GENERICATTRIBUTE19
,STG.GENERICATTRIBUTE20
,STG.GENERICDATE1
,STG.GENERICDATE2
,STG.GENERICDATE3
,STG.GENERICDATE4
,STG.GENERICDATE5
,STG.GENERICDATE6
,STG.GENERICDATE7
,STG.GENERICDATE8
,STG.GENERICDATE9
,STG.GENERICDATE10
,STG.GENERICDATE11
,STG.GENERICDATE12
,STG.GENERICDATE13
,STG.GENERICDATE14
,STG.GENERICDATE15
,STG.GENERICDATE16
,STG.GENERICDATE17
,STG.GENERICDATE18
,STG.GENERICDATE19
,STG.GENERICDATE20
,STG.GENERICBOOLEAN1
,STG.GENERICBOOLEAN2
,STG.GENERICBOOLEAN3
,STG.GENERICBOOLEAN4
,STG.GENERICBOOLEAN5
,STG.GENERICBOOLEAN6
,STG.GENERICBOOLEAN7
,STG.GENERICBOOLEAN8
,STG.GENERICBOOLEAN9
,STG.GENERICBOOLEAN10
,STG.GENERICBOOLEAN11
,STG.GENERICBOOLEAN12
,STG.GENERICBOOLEAN13
,STG.GENERICBOOLEAN14
,STG.GENERICBOOLEAN15
,STG.GENERICBOOLEAN16
,STG.GENERICBOOLEAN17
,STG.GENERICBOOLEAN18
,STG.GENERICBOOLEAN19
,STG.GENERICBOOLEAN20
,STG.GENERICNUMBER1
,STG.UNITTYPEFORGENERICNUMBER1
,STG.GENERICNUMBER2
,STG.UNITTYPEFORGENERICNUMBER2
,STG.GENERICNUMBER3
,STG.UNITTYPEFORGENERICNUMBER3
,STG.GENERICNUMBER4
,STG.UNITTYPEFORGENERICNUMBER4
,STG.GENERICNUMBER5
,STG.UNITTYPEFORGENERICNUMBER5
,STG.GENERICNUMBER6
,STG.UNITTYPEFORGENERICNUMBER6
,STG.GENERICNUMBER7
,STG.UNITTYPEFORGENERICNUMBER7
,STG.GENERICNUMBER8
,STG.UNITTYPEFORGENERICNUMBER8
,STG.GENERICNUMBER9
,STG.UNITTYPEFORGENERICNUMBER9
,STG.GENERICNUMBER10
,STG.UNITTYPEFORGENERICNUMBER10
,STG.GENERICNUMBER11
,STG.UNITTYPEFORGENERICNUMBER11
,STG.GENERICNUMBER12
,STG.UNITTYPEFORGENERICNUMBER12
,STG.GENERICNUMBER13
,STG.UNITTYPEFORGENERICNUMBER13
,STG.GENERICNUMBER14
,STG.UNITTYPEFORGENERICNUMBER14
,STG.GENERICNUMBER15
,STG.UNITTYPEFORGENERICNUMBER15
,STG.GENERICNUMBER16
,STG.UNITTYPEFORGENERICNUMBER16
,STG.GENERICNUMBER17
,STG.UNITTYPEFORGENERICNUMBER17
,STG.GENERICNUMBER18
,STG.UNITTYPEFORGENERICNUMBER18
,STG.GENERICNUMBER19
,STG.UNITTYPEFORGENERICNUMBER19
,STG.GENERICNUMBER20
,STG.UNITTYPEFORGENERICNUMBER20
,SYSDATE AS SWT_INS_DT
FROM CS_GA_SalesOrder_stg_Tmp STG JOIN CS_SalesOrder_base_Tmp BASE ON STG.SALESORDERSEQ=BASE.SALESORDERSEQ;


/* Deleting partial audit entry */

DELETE FROM swt_rpt_stg.FAST_LD_AUDT where SUBJECT_AREA = 'CALLIDUS' and
TBL_NM = 'CS_GA_SalesOrder' and
COMPLTN_STAT = 'N' and
LD_DT=sysdate::date and 
SEQ_ID = (select max(SEQ_ID) from swt_rpt_stg.FAST_LD_AUDT where  SUBJECT_AREA = 'CALLIDUS' and  TBL_NM = 'CS_GA_SalesOrder' and  COMPLTN_STAT = 'N');


/* Inserting new audit entry with all stats */

INSERT INTO swt_rpt_stg.FAST_LD_AUDT
(
SUBJECT_AREA
,TBL_NM
,LD_DT
,START_DT_TIME
,END_DT_TIME
,SRC_REC_CNT
,TGT_REC_CNT
,COMPLTN_STAT
)
select 'CALLIDUS','CS_GA_SalesOrder',sysdate::date,(select st from Start_Time_Tmp),sysdate,(select count(*) from "swt_rpt_stg"."CS_GA_SalesOrder") ,(select count(*) from swt_rpt_base.CS_GA_SalesOrder where SWT_INS_DT::date = sysdate::date),'Y';

Commit;


SELECT PURGE_TABLE('swt_rpt_base.CS_GA_SalesOrder');
SELECT PURGE_TABLE('swt_rpt_stg.CS_GA_SalesOrder_Hist');
SELECT ANALYZE_STATISTICS('swt_rpt_base.CS_GA_SalesOrder');
INSERT /*+Direct*/ INTO swt_rpt_stg.CS_GA_SalesOrder_Hist SELECT * from swt_rpt_stg.CS_GA_SalesOrder;
COMMIT;
TRUNCATE TABLE swt_rpt_stg.CS_GA_SalesOrder;
