/****
****Script Name   : CS_RA_SalesTransaction.sql
****Description   : Incremental  data load for CS_RA_SalesTransaction
****/

/* Setting timing on**/
\timing

/* SET SESSION AUTOCOMMIT TO OFF; */
\set ON_ERROR_STOP on

CREATE LOCAL TEMP TABLE Start_Time_Tmp ON COMMIT PRESERVE ROWS AS select sysdate st from dual;

/* Inserting values into Audit table  */

INSERT INTO swt_rpt_stg.FAST_LD_AUDT
(
SUBJECT_AREA
,TBL_NM
,LD_DT
,START_DT_TIME
,END_DT_TIME
,SRC_REC_CNT
,TGT_REC_CNT
,COMPLTN_STAT
)
select 'CALLIDUS','CS_RA_SalesTransaction',sysdate::date,sysdate,null,(select count(*) from "swt_rpt_stg"."CS_RA_SalesTransaction") ,null,'N';

Commit;

CREATE LOCAL TEMP TABLE CS_RA_SalesTransaction_stg_Tmp ON COMMIT PRESERVE ROWS AS
(
SELECT DISTINCT * FROM swt_rpt_stg.CS_RA_SalesTransaction)
SEGMENTED BY HASH(SALESTRANSACTIONSEQ) ALL NODES;

CREATE LOCAL TEMP TABLE CS_SalesTransaction_base_Tmp ON COMMIT PRESERVE ROWS AS
(
SELECT DISTINCT SALESTRANSACTIONSEQ,COMPENSATIONDATE FROM swt_rpt_base.CS_SALESTRANSACTION)
SEGMENTED BY HASH(SALESTRANSACTIONSEQ) ALL NODES;

/* Inserting Stage table data into Historical Table */

insert /*+DIRECT*/ into swt_rpt_stg.CS_RA_SalesTransaction_Hist
(
SALESTRANSACTIONSEQ
,PAGENUMBER
,REPORTATTRIBUTE1
,REPORTATTRIBUTE2
,REPORTATTRIBUTE3
,REPORTATTRIBUTE4
,REPORTATTRIBUTE5
,REPORTATTRIBUTE6
,REPORTATTRIBUTE7
,REPORTATTRIBUTE8
,REPORTATTRIBUTE9
,REPORTATTRIBUTE10
,REPORTATTRIBUTE11
,REPORTATTRIBUTE12
,REPORTATTRIBUTE13
,REPORTATTRIBUTE14
,REPORTATTRIBUTE15
,REPORTATTRIBUTE16
,REPORTATTRIBUTE17
,REPORTATTRIBUTE18
,REPORTATTRIBUTE19
,REPORTATTRIBUTE20
,LD_DT
,SWT_INS_DT
,d_source
)
select
SALESTRANSACTIONSEQ
,PAGENUMBER
,REPORTATTRIBUTE1
,REPORTATTRIBUTE2
,REPORTATTRIBUTE3
,REPORTATTRIBUTE4
,REPORTATTRIBUTE5
,REPORTATTRIBUTE6
,REPORTATTRIBUTE7
,REPORTATTRIBUTE8
,REPORTATTRIBUTE9
,REPORTATTRIBUTE10
,REPORTATTRIBUTE11
,REPORTATTRIBUTE12
,REPORTATTRIBUTE13
,REPORTATTRIBUTE14
,REPORTATTRIBUTE15
,REPORTATTRIBUTE16
,REPORTATTRIBUTE17
,REPORTATTRIBUTE18
,REPORTATTRIBUTE19
,REPORTATTRIBUTE20
,SYSDATE AS LD_DT
,SWT_INS_DT
,'base'
FROM "swt_rpt_base".CS_RA_SalesTransaction WHERE SALESTRANSACTIONSEQ IN
(
SELECT DISTINCT  SALESTRANSACTIONSEQ from CS_SalesTransaction_base_Tmp
WHERE COMPENSATIONDATE >= (SELECT MIN(StartDate) from "swt_rpt_stg".CS_PERIOD WHERE PERIODSEQ IN (SELECT DISTINCT PERIODSEQ from "swt_rpt_stg".CS_CREDIT))
AND COMPENSATIONDATE <= (SELECT  MAX(EndDate)-1 from "swt_rpt_stg".CS_PERIOD WHERE PERIODSEQ IN (SELECT DISTINCT PERIODSEQ from "swt_rpt_stg".CS_CREDIT))
);



/* Deleting before seven days data from current date in the Historical Table */

delete /*+DIRECT*/ from "swt_rpt_stg"."CS_RA_SalesTransaction_Hist"  where LD_DT::date <= TIMESTAMPADD(DAY,-7,sysdate)::date;





/* Incremental VSQL script for loading data from Stage to Base */


DELETE /*+DIRECT*/ FROM "swt_rpt_base".CS_RA_SalesTransaction
WHERE SALESTRANSACTIONSEQ IN
(
SELECT DISTINCT  SALESTRANSACTIONSEQ from CS_SalesTransaction_base_Tmp
WHERE COMPENSATIONDATE >= (SELECT MIN(StartDate) from "swt_rpt_stg".CS_PERIOD WHERE PERIODSEQ IN (SELECT DISTINCT PERIODSEQ from "swt_rpt_stg".CS_CREDIT))
AND COMPENSATIONDATE <= (SELECT  MAX(EndDate)-1 from "swt_rpt_stg".CS_PERIOD WHERE PERIODSEQ IN (SELECT DISTINCT PERIODSEQ from "swt_rpt_stg".CS_CREDIT))
);

INSERT /*+DIRECT*/ INTO "swt_rpt_base"."CS_RA_SalesTransaction"
(
SALESTRANSACTIONSEQ
,PAGENUMBER
,REPORTATTRIBUTE1
,REPORTATTRIBUTE2
,REPORTATTRIBUTE3
,REPORTATTRIBUTE4
,REPORTATTRIBUTE5
,REPORTATTRIBUTE6
,REPORTATTRIBUTE7
,REPORTATTRIBUTE8
,REPORTATTRIBUTE9
,REPORTATTRIBUTE10
,REPORTATTRIBUTE11
,REPORTATTRIBUTE12
,REPORTATTRIBUTE13
,REPORTATTRIBUTE14
,REPORTATTRIBUTE15
,REPORTATTRIBUTE16
,REPORTATTRIBUTE17
,REPORTATTRIBUTE18
,REPORTATTRIBUTE19
,REPORTATTRIBUTE20
,SWT_INS_DT
)
SELECT DISTINCT
SALESTRANSACTIONSEQ
,PAGENUMBER
,REPORTATTRIBUTE1
,REPORTATTRIBUTE2
,REPORTATTRIBUTE3
,REPORTATTRIBUTE4
,REPORTATTRIBUTE5
,REPORTATTRIBUTE6
,REPORTATTRIBUTE7
,REPORTATTRIBUTE8
,REPORTATTRIBUTE9
,REPORTATTRIBUTE10
,REPORTATTRIBUTE11
,REPORTATTRIBUTE12
,REPORTATTRIBUTE13
,REPORTATTRIBUTE14
,REPORTATTRIBUTE15
,REPORTATTRIBUTE16
,REPORTATTRIBUTE17
,REPORTATTRIBUTE18
,REPORTATTRIBUTE19
,REPORTATTRIBUTE20
,SYSDATE
FROM CS_RA_SalesTransaction_stg_Tmp;



/* Deleting partial audit entry */

DELETE FROM swt_rpt_stg.FAST_LD_AUDT where SUBJECT_AREA = 'CALLIDUS' and
TBL_NM = 'CS_RA_SalesTransaction' and
COMPLTN_STAT = 'N' and
LD_DT=sysdate::date and 
SEQ_ID = (select max(SEQ_ID) from swt_rpt_stg.FAST_LD_AUDT where  SUBJECT_AREA = 'CALLIDUS' and  TBL_NM = 'CS_RA_SalesTransaction' and  COMPLTN_STAT = 'N');


/* Inserting new audit entry with all stats */

INSERT INTO swt_rpt_stg.FAST_LD_AUDT
(
SUBJECT_AREA
,TBL_NM
,LD_DT
,START_DT_TIME
,END_DT_TIME
,SRC_REC_CNT
,TGT_REC_CNT
,COMPLTN_STAT
)
select 'CALLIDUS','CS_RA_SalesTransaction',sysdate::date,(select st from Start_Time_Tmp),sysdate,(select count(*) from "swt_rpt_stg"."CS_RA_SalesTransaction") ,(select count(*) from swt_rpt_base.CS_RA_SalesTransaction where SWT_INS_DT::date = sysdate::date),'Y';

Commit;


SELECT PURGE_TABLE('swt_rpt_base.CS_RA_SalesTransaction');
SELECT PURGE_TABLE('swt_rpt_stg.CS_RA_SalesTransaction_Hist');
SELECT ANALYZE_STATISTICS('swt_rpt_base.CS_RA_SalesTransaction');
INSERT /*+Direct*/ INTO swt_rpt_stg.CS_RA_SalesTransaction_Hist SELECT * from swt_rpt_stg.CS_RA_SalesTransaction;
COMMIT;
TRUNCATE TABLE swt_rpt_stg.CS_RA_SalesTransaction;
