/****
****Script Name   : CS_SalesTransaction.sql
****Description   : Incremental  data load for CS_SalesTransaction
****/

/* Setting timing on**/
\timing

/*SET SESSION AUTOCOMMIT TO OFF;*/

\set ON_ERROR_STOP on

CREATE LOCAL TEMP TABLE Start_Time_Tmp ON COMMIT PRESERVE ROWS AS select sysdate st from dual;

/* Inserting values into Audit table  */

INSERT INTO swt_rpt_stg.FAST_LD_AUDT
(
SUBJECT_AREA
,TBL_NM
,LD_DT
,START_DT_TIME
,END_DT_TIME
,SRC_REC_CNT
,TGT_REC_CNT
,COMPLTN_STAT
)
select 'CALLIDUS','CS_SalesTransaction',sysdate::date,sysdate,null,(select count(*) from "swt_rpt_stg"."CS_SalesTransaction") ,null,'N';

Commit;

CREATE LOCAL TEMP TABLE CS_SalesTransaction_stg_Tmp ON COMMIT PRESERVE ROWS AS
(
SELECT DISTINCT * FROM swt_rpt_stg.CS_SalesTransaction)
SEGMENTED BY HASH(SALESTRANSACTIONSEQ) ALL NODES;


CREATE LOCAL TEMP TABLE CS_SalesTransaction_base_Tmp ON COMMIT PRESERVE ROWS AS
(
SELECT DISTINCT * from swt_rpt_base.CS_SalesTransaction)
SEGMENTED BY HASH(SALESTRANSACTIONSEQ) ALL NODES;

/* Inserting Stage table data into Historical Table */

insert /*+DIRECT*/ into swt_rpt_stg.CS_SalesTransaction_Hist
(
SALESTRANSACTIONSEQ
,SALESORDERSEQ
,LINENUMBER
,SUBLINENUMBER
,EVENTTYPESEQ
,PIPELINERUNSEQ
,ORIGINTYPEID
,COMPENSATIONDATE
,BILLTOADDRESSSEQ
,SHIPTOADDRESSSEQ
,OTHERTOADDRESSSEQ
,ISRUNNABLE
,BUSINESSUNITMAP
,ACCOUNTINGDATE
,PRODUCTID
,PRODUCTNAME
,PRODUCTDESCRIPTION
,NUMBEROFUNITS
,UNITVALUE
,UNITTYPEFORUNITVALUE
,PREADJUSTEDVALUE
,UNITTYPEFORPREADJUSTEDVALUE
,VALUE
,UNITTYPEFORVALUE
,NATIVECURRENCY
,NATIVECURRENCYAMOUNT
,DISCOUNTPERCENT
,DISCOUNTTYPE
,PAYMENTTERMS
,PONUMBER
,CHANNEL
,ALTERNATEORDERNUMBER
,DATASOURCE
,REASONSEQ
,COMMENTS
,GENERICATTRIBUTE1
,GENERICATTRIBUTE2
,GENERICATTRIBUTE3
,GENERICATTRIBUTE4
,GENERICATTRIBUTE5
,GENERICATTRIBUTE6
,GENERICATTRIBUTE7
,GENERICATTRIBUTE8
,GENERICATTRIBUTE9
,GENERICATTRIBUTE10
,GENERICATTRIBUTE11
,GENERICATTRIBUTE12
,GENERICATTRIBUTE13
,GENERICATTRIBUTE14
,GENERICATTRIBUTE15
,GENERICATTRIBUTE16
,GENERICATTRIBUTE17
,GENERICATTRIBUTE18
,GENERICATTRIBUTE19
,GENERICATTRIBUTE20
,GENERICATTRIBUTE21
,GENERICATTRIBUTE22
,GENERICATTRIBUTE23
,GENERICATTRIBUTE24
,GENERICATTRIBUTE25
,GENERICATTRIBUTE26
,GENERICATTRIBUTE27
,GENERICATTRIBUTE28
,GENERICATTRIBUTE29
,GENERICATTRIBUTE30
,GENERICATTRIBUTE31
,GENERICATTRIBUTE32
,GENERICNUMBER1
,UNITTYPEFORGENERICNUMBER1
,GENERICNUMBER2
,UNITTYPEFORGENERICNUMBER2
,GENERICNUMBER3
,UNITTYPEFORGENERICNUMBER3
,GENERICNUMBER4
,UNITTYPEFORGENERICNUMBER4
,GENERICNUMBER5
,UNITTYPEFORGENERICNUMBER5
,GENERICNUMBER6
,UNITTYPEFORGENERICNUMBER6
,GENERICDATE1
,GENERICDATE2
,GENERICDATE3
,GENERICDATE4
,GENERICDATE5
,GENERICDATE6
,GENERICBOOLEAN1
,GENERICBOOLEAN2
,GENERICBOOLEAN3
,GENERICBOOLEAN4
,GENERICBOOLEAN5
,GENERICBOOLEAN6
,PROCESSINGUNITSEQ
,MODIFICATIONDATE
,UNITTYPEFORLINENUMBER
,UNITTYPEFORSUBLINENUMBER
,UNITTYPEFORNUMBEROFUNITS
,UNITTYPEFORDISCOUNTPERCENT
,UNITTYPEFORNATIVECURRENCYAMT
,LD_DT
,SWT_INS_DT
,d_source
)
select
SALESTRANSACTIONSEQ
,SALESORDERSEQ
,LINENUMBER
,SUBLINENUMBER
,EVENTTYPESEQ
,PIPELINERUNSEQ
,ORIGINTYPEID
,COMPENSATIONDATE
,BILLTOADDRESSSEQ
,SHIPTOADDRESSSEQ
,OTHERTOADDRESSSEQ
,ISRUNNABLE
,BUSINESSUNITMAP
,ACCOUNTINGDATE
,PRODUCTID
,PRODUCTNAME
,PRODUCTDESCRIPTION
,NUMBEROFUNITS
,UNITVALUE
,UNITTYPEFORUNITVALUE
,PREADJUSTEDVALUE
,UNITTYPEFORPREADJUSTEDVALUE
,VALUE
,UNITTYPEFORVALUE
,NATIVECURRENCY
,NATIVECURRENCYAMOUNT
,DISCOUNTPERCENT
,DISCOUNTTYPE
,PAYMENTTERMS
,PONUMBER
,CHANNEL
,ALTERNATEORDERNUMBER
,DATASOURCE
,REASONSEQ
,COMMENTS
,GENERICATTRIBUTE1
,GENERICATTRIBUTE2
,GENERICATTRIBUTE3
,GENERICATTRIBUTE4
,GENERICATTRIBUTE5
,GENERICATTRIBUTE6
,GENERICATTRIBUTE7
,GENERICATTRIBUTE8
,GENERICATTRIBUTE9
,GENERICATTRIBUTE10
,GENERICATTRIBUTE11
,GENERICATTRIBUTE12
,GENERICATTRIBUTE13
,GENERICATTRIBUTE14
,GENERICATTRIBUTE15
,GENERICATTRIBUTE16
,GENERICATTRIBUTE17
,GENERICATTRIBUTE18
,GENERICATTRIBUTE19
,GENERICATTRIBUTE20
,GENERICATTRIBUTE21
,GENERICATTRIBUTE22
,GENERICATTRIBUTE23
,GENERICATTRIBUTE24
,GENERICATTRIBUTE25
,GENERICATTRIBUTE26
,GENERICATTRIBUTE27
,GENERICATTRIBUTE28
,GENERICATTRIBUTE29
,GENERICATTRIBUTE30
,GENERICATTRIBUTE31
,GENERICATTRIBUTE32
,GENERICNUMBER1
,UNITTYPEFORGENERICNUMBER1
,GENERICNUMBER2
,UNITTYPEFORGENERICNUMBER2
,GENERICNUMBER3
,UNITTYPEFORGENERICNUMBER3
,GENERICNUMBER4
,UNITTYPEFORGENERICNUMBER4
,GENERICNUMBER5
,UNITTYPEFORGENERICNUMBER5
,GENERICNUMBER6
,UNITTYPEFORGENERICNUMBER6
,GENERICDATE1
,GENERICDATE2
,GENERICDATE3
,GENERICDATE4
,GENERICDATE5
,GENERICDATE6
,GENERICBOOLEAN1
,GENERICBOOLEAN2
,GENERICBOOLEAN3
,GENERICBOOLEAN4
,GENERICBOOLEAN5
,GENERICBOOLEAN6
,PROCESSINGUNITSEQ
,MODIFICATIONDATE
,UNITTYPEFORLINENUMBER
,UNITTYPEFORSUBLINENUMBER
,UNITTYPEFORNUMBEROFUNITS
,UNITTYPEFORDISCOUNTPERCENT
,UNITTYPEFORNATIVECURRENCYAMT
,SYSDATE AS LD_DT
,SWT_INS_DT
,'base'
FROM CS_SalesTransaction_base_Tmp WHERE SALESTRANSACTIONSEQ IN
(
SELECT DISTINCT  SALESTRANSACTIONSEQ from CS_SalesTransaction_base_Tmp
WHERE COMPENSATIONDATE >= (SELECT MIN(StartDate) from "swt_rpt_stg".CS_PERIOD WHERE PERIODSEQ IN (SELECT DISTINCT PERIODSEQ from "swt_rpt_stg".CS_CREDIT))
AND COMPENSATIONDATE <= (SELECT  MAX(EndDate)-1 from "swt_rpt_stg".CS_PERIOD WHERE PERIODSEQ IN (SELECT DISTINCT PERIODSEQ from "swt_rpt_stg".CS_CREDIT))
);

/* Deleting before seven days data from current date in the Historical Table */

delete /*+DIRECT*/ from "swt_rpt_stg"."CS_SalesTransaction_Hist"  where LD_DT::date <= TIMESTAMPADD(DAY,-7,sysdate)::date;


/* Incremental VSQL script for loading data from Stage to Base */


DELETE /*+DIRECT*/ FROM "swt_rpt_base".CS_SalesTransaction
WHERE SALESTRANSACTIONSEQ IN
(
SELECT DISTINCT  SALESTRANSACTIONSEQ from CS_SalesTransaction_base_Tmp
WHERE COMPENSATIONDATE >= (SELECT MIN(StartDate) from "swt_rpt_stg".CS_PERIOD WHERE PERIODSEQ IN (SELECT DISTINCT PERIODSEQ from "swt_rpt_stg".CS_CREDIT))
AND COMPENSATIONDATE <= (SELECT  MAX(EndDate)-1 from "swt_rpt_stg".CS_PERIOD WHERE PERIODSEQ IN (SELECT DISTINCT PERIODSEQ from "swt_rpt_stg".CS_CREDIT))
);


INSERT /*+DIRECT*/ INTO "swt_rpt_base"."CS_SalesTransaction"
(
SALESTRANSACTIONSEQ
,SALESORDERSEQ
,LINENUMBER
,SUBLINENUMBER
,EVENTTYPESEQ
,PIPELINERUNSEQ
,ORIGINTYPEID
,COMPENSATIONDATE
,BILLTOADDRESSSEQ
,SHIPTOADDRESSSEQ
,OTHERTOADDRESSSEQ
,ISRUNNABLE
,BUSINESSUNITMAP
,ACCOUNTINGDATE
,PRODUCTID
,PRODUCTNAME
,PRODUCTDESCRIPTION
,NUMBEROFUNITS
,UNITVALUE
,UNITTYPEFORUNITVALUE
,PREADJUSTEDVALUE
,UNITTYPEFORPREADJUSTEDVALUE
,VALUE
,UNITTYPEFORVALUE
,NATIVECURRENCY
,NATIVECURRENCYAMOUNT
,DISCOUNTPERCENT
,DISCOUNTTYPE
,PAYMENTTERMS
,PONUMBER
,CHANNEL
,ALTERNATEORDERNUMBER
,DATASOURCE
,REASONSEQ
,COMMENTS
,GENERICATTRIBUTE1
,GENERICATTRIBUTE2
,GENERICATTRIBUTE3
,GENERICATTRIBUTE4
,GENERICATTRIBUTE5
,GENERICATTRIBUTE6
,GENERICATTRIBUTE7
,GENERICATTRIBUTE8
,GENERICATTRIBUTE9
,GENERICATTRIBUTE10
,GENERICATTRIBUTE11
,GENERICATTRIBUTE12
,GENERICATTRIBUTE13
,GENERICATTRIBUTE14
,GENERICATTRIBUTE15
,GENERICATTRIBUTE16
,GENERICATTRIBUTE17
,GENERICATTRIBUTE18
,GENERICATTRIBUTE19
,GENERICATTRIBUTE20
,GENERICATTRIBUTE21
,GENERICATTRIBUTE22
,GENERICATTRIBUTE23
,GENERICATTRIBUTE24
,GENERICATTRIBUTE25
,GENERICATTRIBUTE26
,GENERICATTRIBUTE27
,GENERICATTRIBUTE28
,GENERICATTRIBUTE29
,GENERICATTRIBUTE30
,GENERICATTRIBUTE31
,GENERICATTRIBUTE32
,GENERICNUMBER1
,UNITTYPEFORGENERICNUMBER1
,GENERICNUMBER2
,UNITTYPEFORGENERICNUMBER2
,GENERICNUMBER3
,UNITTYPEFORGENERICNUMBER3
,GENERICNUMBER4
,UNITTYPEFORGENERICNUMBER4
,GENERICNUMBER5
,UNITTYPEFORGENERICNUMBER5
,GENERICNUMBER6
,UNITTYPEFORGENERICNUMBER6
,GENERICDATE1
,GENERICDATE2
,GENERICDATE3
,GENERICDATE4
,GENERICDATE5
,GENERICDATE6
,GENERICBOOLEAN1
,GENERICBOOLEAN2
,GENERICBOOLEAN3
,GENERICBOOLEAN4
,GENERICBOOLEAN5
,GENERICBOOLEAN6
,PROCESSINGUNITSEQ
,MODIFICATIONDATE
,UNITTYPEFORLINENUMBER
,UNITTYPEFORSUBLINENUMBER
,UNITTYPEFORNUMBEROFUNITS
,UNITTYPEFORDISCOUNTPERCENT
,UNITTYPEFORNATIVECURRENCYAMT
,SWT_INS_DT
)
SELECT DISTINCT
SALESTRANSACTIONSEQ
,SALESORDERSEQ
,LINENUMBER
,SUBLINENUMBER
,EVENTTYPESEQ
,PIPELINERUNSEQ
,ORIGINTYPEID
,COMPENSATIONDATE
,BILLTOADDRESSSEQ
,SHIPTOADDRESSSEQ
,OTHERTOADDRESSSEQ
,ISRUNNABLE
,BUSINESSUNITMAP
,ACCOUNTINGDATE
,PRODUCTID
,PRODUCTNAME
,PRODUCTDESCRIPTION
,NUMBEROFUNITS
,UNITVALUE
,UNITTYPEFORUNITVALUE
,PREADJUSTEDVALUE
,UNITTYPEFORPREADJUSTEDVALUE
,VALUE
,UNITTYPEFORVALUE
,NATIVECURRENCY
,NATIVECURRENCYAMOUNT
,DISCOUNTPERCENT
,DISCOUNTTYPE
,PAYMENTTERMS
,PONUMBER
,CHANNEL
,ALTERNATEORDERNUMBER
,DATASOURCE
,REASONSEQ
,COMMENTS
,GENERICATTRIBUTE1
,GENERICATTRIBUTE2
,GENERICATTRIBUTE3
,GENERICATTRIBUTE4
,GENERICATTRIBUTE5
,GENERICATTRIBUTE6
,GENERICATTRIBUTE7
,GENERICATTRIBUTE8
,GENERICATTRIBUTE9
,GENERICATTRIBUTE10
,GENERICATTRIBUTE11
,GENERICATTRIBUTE12
,GENERICATTRIBUTE13
,GENERICATTRIBUTE14
,GENERICATTRIBUTE15
,GENERICATTRIBUTE16
,GENERICATTRIBUTE17
,GENERICATTRIBUTE18
,GENERICATTRIBUTE19
,GENERICATTRIBUTE20
,GENERICATTRIBUTE21
,GENERICATTRIBUTE22
,GENERICATTRIBUTE23
,GENERICATTRIBUTE24
,GENERICATTRIBUTE25
,GENERICATTRIBUTE26
,GENERICATTRIBUTE27
,GENERICATTRIBUTE28
,GENERICATTRIBUTE29
,GENERICATTRIBUTE30
,GENERICATTRIBUTE31
,GENERICATTRIBUTE32
,GENERICNUMBER1
,UNITTYPEFORGENERICNUMBER1
,GENERICNUMBER2
,UNITTYPEFORGENERICNUMBER2
,GENERICNUMBER3
,UNITTYPEFORGENERICNUMBER3
,GENERICNUMBER4
,UNITTYPEFORGENERICNUMBER4
,GENERICNUMBER5
,UNITTYPEFORGENERICNUMBER5
,GENERICNUMBER6
,UNITTYPEFORGENERICNUMBER6
,GENERICDATE1
,GENERICDATE2
,GENERICDATE3
,GENERICDATE4
,GENERICDATE5
,GENERICDATE6
,GENERICBOOLEAN1
,GENERICBOOLEAN2
,GENERICBOOLEAN3
,GENERICBOOLEAN4
,GENERICBOOLEAN5
,GENERICBOOLEAN6
,PROCESSINGUNITSEQ
,MODIFICATIONDATE
,UNITTYPEFORLINENUMBER
,UNITTYPEFORSUBLINENUMBER
,UNITTYPEFORNUMBEROFUNITS
,UNITTYPEFORDISCOUNTPERCENT
,UNITTYPEFORNATIVECURRENCYAMT
,SYSDATE AS SWT_INS_DT
FROM CS_SalesTransaction_stg_Tmp;


/* Deleting partial audit entry */

DELETE FROM swt_rpt_stg.FAST_LD_AUDT where SUBJECT_AREA = 'CALLIDUS' and
TBL_NM = 'CS_SalesTransaction' and
COMPLTN_STAT = 'N' and
LD_DT=sysdate::date and 
SEQ_ID = (select max(SEQ_ID) from swt_rpt_stg.FAST_LD_AUDT where  SUBJECT_AREA = 'CALLIDUS' and  TBL_NM = 'CS_SalesTransaction' and  COMPLTN_STAT = 'N');


/* Inserting new audit entry with all stats */

INSERT INTO swt_rpt_stg.FAST_LD_AUDT
(
SUBJECT_AREA
,TBL_NM
,LD_DT
,START_DT_TIME
,END_DT_TIME
,SRC_REC_CNT
,TGT_REC_CNT
,COMPLTN_STAT
)
select 'CALLIDUS','CS_SalesTransaction',sysdate::date,(select st from Start_Time_Tmp),sysdate,(select count(*) from "swt_rpt_stg"."CS_SalesTransaction") ,(select count(*) from swt_rpt_base.CS_SalesTransaction where SWT_INS_DT::date = sysdate::date),'Y';

Commit;


SELECT PURGE_TABLE('swt_rpt_base.CS_SalesTransaction');
SELECT PURGE_TABLE('swt_rpt_stg.CS_SalesTransaction_Hist');
SELECT ANALYZE_STATISTICS('swt_rpt_base.CS_SalesTransaction');
INSERT /*+Direct*/ INTO swt_rpt_stg.CS_SalesTransaction_Hist SELECT * from swt_rpt_stg.CS_SalesTransaction;
COMMIT;
TRUNCATE TABLE swt_rpt_stg.CS_SalesTransaction;
