/****
****Script Name   : SF_Opportunity.sql
****Description   : Incremental data load for SF_Opportunity
****/

/*Setting timing on */
\timing

/**SET SESSION AUTOCOMMIT TO OFF;**/

--SET SESSION AUTOCOMMIT TO OFF;

\set ON_ERROR_STOP on

CREATE LOCAL TEMP TABLE Start_Time_Tmp ON COMMIT PRESERVE ROWS AS select count(*) count, sysdate st from "swt_rpt_stg"."SF_Opportunity";

/* Inserting values into Audit table  */

INSERT INTO swt_rpt_stg.FAST_LD_AUDT
(
SUBJECT_AREA
,TBL_NM
,LD_DT
,START_DT_TIME
,END_DT_TIME
,SRC_REC_CNT
,TGT_REC_CNT
,COMPLTN_STAT
)
select 'SFDC','SF_Opportunity',sysdate::date,sysdate,null,(select count from Start_Time_Tmp) ,null,'N';

Commit;

INSERT /*+Direct*/ INTO swt_rpt_stg.SF_Opportunity_Hist SELECT * from swt_rpt_stg.SF_Opportunity;
COMMIT;


CREATE LOCAL TEMP TABLE duplicates_records ON COMMIT PRESERVE ROWS AS (
select id,max(auto_id) as auto_id from swt_rpt_stg.SF_Opportunity where id in (
select id from swt_rpt_stg.SF_Opportunity group by id,LASTMODIFIEDDATE having count(1)>1)
group by id);


delete from swt_rpt_stg.SF_Opportunity where exists(
select 1 from duplicates_records t2 where swt_rpt_stg.SF_Opportunity.id=t2.id and swt_rpt_stg.SF_Opportunity.auto_id<t2.auto_id);

commit;

CREATE LOCAL TEMP TABLE SF_Opportunity_stg_Tmp ON COMMIT PRESERVE ROWS AS
(
SELECT DISTINCT * FROM swt_rpt_stg.SF_Opportunity)
SEGMENTED BY HASH(ID,LASTMODIFIEDDATE) ALL NODES;

TRUNCATE TABLE swt_rpt_stg.SF_Opportunity;

CREATE LOCAL TEMP TABLE SF_Opportunity_base_Tmp ON COMMIT PRESERVE ROWS AS
(
SELECT DISTINCT ID,LASTMODIFIEDDATE FROM swt_rpt_base.SF_Opportunity)
SEGMENTED BY HASH(ID,LASTMODIFIEDDATE) ALL NODES;


CREATE LOCAL TEMP TABLE SF_Opportunity_stg_Tmp_Key ON COMMIT PRESERVE ROWS AS
(
SELECT id, max(lastmodifieddate) as lastmodifieddate FROM SF_Opportunity_stg_Tmp group by id)
SEGMENTED BY HASH(ID,LASTMODIFIEDDATE) ALL NODES;


/* Inserting Stage table data into Historical Table */

insert /*+DIRECT*/ into swt_rpt_stg.SF_Opportunity_Hist
(
AccountId
,Additional_Influence_ReferralPartnerRole__c
,Amount
,Apttus_Approval__Approval_Status__c
,Apttus_Proposal__Discount_Percent__c
,Budget_Confirmed__c
,CampaignId
,CloseDate
,Competitor_Details__c
,ContractId
,CreatedById
,CreatedDate
,CurrencyIsoCode
,Description
,Discovery_Completed__c
,DSE__MainCompetitors__c
,DSE__OrderNumber__c
,ExpectedRevenue
,ForecastCategory
,ForecastCategoryName
,HasOpenActivity
,HasOpportunityLineItem
,HasOverdueTask
,Id
,IsClosed
,IsDeleted
,IsPrivate
,IsSplit
,IsWon
,LastActivityDate
,LastModifiedById
,LastModifiedDate
,LastReferencedDate
,LastViewedDate
,LeadSource
,Loss_Reason__c
,Name
,NextStep
,OwnerId
,PartnerAccountId
,Price_List__c
,Pricebook2Id
,Primary_Competitor__c
,Probability
,RecordTypeId
,ROI_Analysis_Completed__c
,Sample__c
,Secondary_Competitor__c
,StageName
,SWT_Account_Verification__c
,SWT_Actual_quote_amount__c
,SWT_Alliance_Partner__c
,SWT_Alliance_Partner_Role__c
,SWT_Approval_Level_Indicator__c
,SWT_Approved_for_Professional_Services__c
,SWT_Approver_Level_1__c
,SWT_Approver_Level_2__c
,SWT_Approver_Level_3__c
,SWT_At_Risk__c
,SWT_Bid_Cost__c
,SWT_Big_Deal_Review__c
,SWT_BU__c
,SWT_Budget_Confimed__c
,SWT_Business_Case__c
,SWT_Client_Urgency_Commitment__c
,SWT_Clone_SaaS_Renewal_Parent_ID__c
,SWT_Cloned_Opportunity__c
,SWT_Comments__c
,SWT_Compelling_Event_Description__c
,SWT_Compelling_Evnt_Custmr_Reason_to_Buy__c
,SWT_Competitor__c
,SWT_Confidential__c
,SWT_Contract_End_Date__c
,SWT_Contract_Start_Date__c
,SWT_Contract_Status__c
,SWT_Converted_from_Lead__c
,SWT_Customer_Engagement__c
,SWT_Customer_Executive_Sponsor__c
,SWT_Date_Deal_Slipped__c
,SWT_Days_in_Sales_Stage_Develop_Qualify__c
,SWT_Days_in_Sales_Stage_Negotiate__c
,SWT_Days_in_Sales_Stage_Open__c
,SWT_Days_in_Sales_Stage_Propose__c
,SWT_Days_in_Sales_Stage_Validate__c
,SWT_Deal_Source__c
,SWT_Decision_Process_Known__c
,SWT_Detailed_Reason_Won_Lost_per_Rep__c
,SWT_Discount__c
,SWT_Executive_Ask__c
,SWT_Executive_Ask_Due_Date__c
,SWT_Executive_Name__c
,SWT_ExternalId__c
,SWT_Forecast_Category__c
,SWT_Fulfillment_Type__c
,SWT_Help_Needed__c
,SWT_Incumbent__c
,SWT_Is_a_Primary_Opportunity__c
,SWT_Is_Owner_Logged_In_User__c
,SWT_Lead_Qualifier__c
,SWT_License_Shipment_Value__c
,SWT_Lost_Opportunity__c
,SWT_Managed_By__c
,SWT_Managed_Service_Provider__c
,SWT_Month_Date_of_Update__c
,SWT_Next_Milestones_Actions_to_Close__c
,SWT_No_Alliance_Partner__c
,SWT_No_of_Products__c
,SWT_Opportunity_Access__c
,SWT_Opportunity_Currency_Formula__c
,SWT_Opportunity_Number__c
,SWT_Opportunity_Role_Type__c
,SWT_Opportunity_Type__c
,SWT_OpportunityFieldID__c
,SWT_Original_Slipped_Quarter__c
,SWT_Other_Executive_Name__c
,SWT_Our_Competitive_Relationship_Strengt__c
,SWT_Our_Solution_Relative_to_Competitors__c
,SWT_Painpoint_Problem_Trying_to_Solve__c
,SWT_Pillar__c
,SWT_Primary_Contact__c
,SWT_Primary_Opportunity_MultiPartnerDeal__c
,SWT_Procurement_Process_Known__c
,SWT_Product_Type__c
,SWT_Professional_Services_Initiated__c
,SWT_Project_Resources_Defined__c
,SWT_PS_Opportunity__c
,SWT_Push_Counter_Increment__c
,SWT_Qualification_Score__c
,SWT_Quote_Id__c
,SWT_Reason_Abandoned__c
,SWT_Reason_Won_Lost_per_Rep__c
,SWT_Region__c
,SWT_Revenue_Management__c
,SWT_Risks_Barriers_to_Close__c
,SWT_SaaS_Contract_Length_in_Months__c
,SWT_Sales_Play__c
,SWT_Slipped_Deal__c
,SWT_Slipped_Deal_Counter__c
,SWT_Sourced_Partner__c
,SWT_Specific_Ask__c
,SWT_Status_Update_from_Last_Actions__c
,SWT_Technical_Decision_Status_TDS__c
,SWT_Tier_1_Partner__c
,SWT_Tier_1_Partner_Agreement__c
,SWT_Tier_1_Partner_Type__c
,SWT_Tier_2_Partner__c
,SWT_Tier_2_Partner_Agreement__c
,SWT_Tier_2_Partner_Type__c
,SWT_Total_Appliance_Rollup__c
,SWT_Total_ArcSightApplianceLicenseRollup__c
,SWT_Total_Data_Security_ApplianceLicense__c
,SWT_Total_Education_Roll_up__c
,SWT_Total_FortifyApplianceLicense_Rollup__c
,SWT_Total_License_Shipment_Value__c
,SWT_Total_Opportunity_Value__c
,SWT_Total_Saas_Product__c
,SWT_Total_SaaS_Roll_up__c
,SWT_Total_Score__c
,SWT_Total_Services_Roll_up__c
,SWT_Total_Support_Roll_Up__c
,SWTAdditional_Influence_Referral_Partner__c
,SyncedQuoteId
,SystemModstamp
,TotalOpportunityQuantity
,Type
,SWT_Uplift_Percentage__c
,SWT_Presales_WBS_Code__c
,SWT_Approved_Bid_Cost__c
,SWT_Sourced_Referral_Approved__c
,SWT_Partner_Account_Number__c
,SWT_Annualized_Contract_Value__c
,SWT_Partner_Influencer_Approved__c
,HPSW_LMO_Engagement__c
,SWT_ELA__c
,SWT_Manual_Revenue__c
,SWT_Prepaid__c
,SWT_Forecast_Risk__c
,SWT_Loss_Risk__c
,SWT_Manager_Comments__c
,SWT_Renewal_Comments__c
,SWT_Renewal_End_Date__c
,SWT_Renewal_Start_Date__c
,Segmentation__c
,SWT_Previous_SaaS_Value__c
,SWT_Pipeline_Exclusion_Check__c
,SWT_Order_Number__c
,SWT_Cancellation_Reason__c
,SWT_Cancellation_Type__c
,SWT_Cancellation_Note__c
,SWT_CAM__c
,SWT_CAM_Type__c
,HPSW_Renewal_Opportunity_Quarter__c
,SWT_Under_Forecast_Upsell_Reason__c
,SWT_Total_List_Price_Calculated__c
,SWT_Contract_End_Financial_Year__c
,SWT_Current_Financial_Year__c
,SWT_Delivery_To_Contact__c
,SWT_Bill_To_Contact__c
,SWT_CMT_1__c
,SWT_CMT_2__c
,SWT_Order_is_Booked__c
,SWT_PO_Number__c
,SWT_Rejected_By__c
,SWT_Opportunity_Total_Price__c
,SWT_Annualized_Foundation__c
,SWT_Renewal_Quote_Created__c
,SWT_Quote_Created__c
,SWT_Product_Line__c
,SWT_Last_Year_s_Contract_Value__c
,SWT_Total_Professional_Services__c
,SWT_Total_Services__c
,SWT_Approved_Bid_Cost_formula__c
,SWT_Renewal_Quote_Creation_Date__c
,SWT_Add_on_Opportunity__c
,SWT_Subscription_Link__c
,SWT_Education_Opportunity__c
,SWT_Number_Of_Product_Services__c
,SWT_Date_Approved__c
,SWT_No_Bid_Costs_Needed__c
,SWT_Total_List_Price__c
,SWT_New_Logo_Master__c
,SWT_Total_Initial_Opportunity_Value__c
,SWT_Total_License_Appliance__c
,SWT_Subscription_End_Financial_Year__c
,SWT_Order_booked_Date__c
,SWT_Under_Forecast_Upsell__c
,SWT_Prior_Renewal__c
,SWT_Renewal_Status__c
,SWT_Current_Quarter__c
,SWT_Forecast_Status__c
,SWT_Previous_Opportunity__c
,Number_Of_Deals_Approved_Rejected__c
,SWT_Account_Country__c
,SWT_Customer_Budget__c
,SWT_Expected_close_date__c
,SWT_Number_Of_Deals_Registered__c
,SWT_Original_Parent_Account__c
,SWT_Parent_Opportunity_Link__c
,SWT_Partner_Business_Manager__c
,SWT_Term__c
,SWT_Valid_for_CQ_Pipeline__c
,SWT_Zuora_Subscription_Id__c
,SWT_Annualized_Contract_Value_USD__c
,SWT_Sent_email_to_ITOM__c
,Sent_email_to_IMG__c
,Sent_email_to_ESP__c
,SWT_Sent_email_to_BDP__c
,SWT_Sent_email_to_ADM__c
,SWT_Total_RTS_USD__c
,SWT_Total_RTS_RollUp__c
,SWT_Total_Foundation_USD__c
,SWT_Total_Foundation_RollUp__c
,SWT_Annualized_Foundation_USD__c
,SWT_Renewals_Total_CQ_Rev_USD__c
,SWT_Currency_Conversion_Factor__c
,SWT_Renewal_Quote_Creation__c
,SWT_No_of_products_Packaged__c
,SWT_Legacy_Opportunity_ID__c
,SWT_SOW_Deadline__c
,SWT_OrderStatus__c
,SWT_Pipeline_Category__c
,SWT_Cut_off_Date__c
,SWT_Adopt_a_Deal__c
,SWT_Quote_Stage__c
,SWT_Adjustment_Type__c
,SWT_Invoiced__c
,SWT_ATR_Type__c
,SWT_Renewal_Mgr_Forecast_Modified__c
,SWT_Mgr_Override__c
,SWT_Renewal_Mgr_Forecast_Override__c
,SWT_Contract_Expiration_Quarter__c
,SWT_SubscriptionName__c
,SWT_TotalOpportunityValueUSD__c
,SWT_Opportunity_Classification__c
,SWT_ProductsWithSubType__c
,SWT_Will_Delivery_Include_GDC__c
,SWT_SVI_Partner__c
,SWT_Product_Category__c
,SWT_Update_from_Quote__c
,SWT_Detailed_Reason_Lost_per_Rep__c
,SWT_Invalid_Reason__c
,Product_Line__c
,SWT_CheckSubscription__c
,SWT_Original_Quarter_Skipped__c
,SWT_Subcontractor_Involved__c
,SWT_Came_from_License_Deal__c
,SWT_Customer_Subscription_Name_Zuora__c
,SWT_Subscription_ID_Zuora__c
,SWT_Service_Offering__c
,SWT_Lead_Business_Area__c
,SWT_SVI__c
,SWT_Transition__c
,SWT_Total_Forecast_Value__c
,SWT_Anniversary__c
,SWT_Close_Date_Financial_Year__c
,SWT_Close_Date_Quarter__c
,SWT_Is_Last_Month_of_Quarter__c
,SWT_Manager_Forecast_Override__c
,SWT_Partner_Role__c
,SWT_Subscription__c
,SWT_Linked_Opportunity_for_Currency__c
,SWT_EoT_Date__c
,SWT_Manager_Forecast_Category__c
,SWT_Total_Forecast_Value_USD__c
,SWT_ProductsWithSalesPriceSubTypeRollup__c
,SWT_Flexcare_Status__c
,SWT_Came_from_Add_On__c
,SWT_Manager_Judgement__c
,SWT_Subscription_present__c 
,SWT_Deals_Approved__c
,SWT_LQID__c
,CFCR_BU_ADM__c
,CFCR_BU_BDP__c
,CFCR_BU_ESP__c
,CFCR_BU_IM_G__c
,CFCR_BU_ITOM__c
,CFCR_Business_Unit_Formula__c
,CFCR_Velocity_Won__c
,CFCR_Count__c
,FCRM__FCR_First_Campaign_Touch__c
,FCRM__FCR_Last_Campaign_Touch__c
,FCRM__FCR_Response_ID__c
,CFCR_of_Business_Units__c
,CFCR_Exclude_From_Campaign_Influence__c
,CFCR_SQO_Date__c
,FCRM__FCR_Admin_CMArchive__c
,FCRM__FCR_Admin_Originating_Contact__c
,FCRM__FCR_Admin_Update_Counter__c
,FCRM__FCR_Campaign_Attribution__c
,GS_CTA__c
,SWT_Account_Name__c
,SWT_Account_RPL_Status__c
,SWT_Agreement_Created__c
,SWT_Approvers__c
,SWT_Attach_Type__c
,SWT_Bypass_Addon_Validation__c
,SWT_Champion__c
,SWT_Contract_T_C_s__c
,SWT_Country_Name__c
,SWT_Country_Region__c
,SWT_Country_Type__c
,SWT_CrossBorderTransaction__c
,SWT_Decision_Criteria__c
,SWT_Decision_Process__c
,SWT_Exclude_Validation_Rule__c
,SWT_Has_Product_Service__c
,SWT_Manager_Forecast_Value__c
,SWT_Marketing_Comments__c
,SWT_Metrics__c
,SWT_Opportunity_WIth_Order_from_Agree__c
,SWT_OwnerId__c
,SWT_PO_Process_Description__c
,SWT_Presales_Budget_RequestedUSD__c
,SWT_Price_List__c
,Swt_Renewal_Quote_Creation_Failed__c
,SWT_Revenue_Date__c
,SWT_ServiceOffering__c
,SWT_Sold_To_Contact__c
,SWT_Special_Pricing_Deep_Discount__c
,SWT_Status_Change_From_Order__c
,SWT_Total_Appliance_USD__c
,SWT_Total_Education_USD__c
,SWT_Total_License_and_ACV__c
,SWT_Total_License_and_Appliance_USD__c
,SWT_Total_License_USD__c
,SWT_Total_Saas_USD__c
,SWT_Total_Services_USD__c
,SWT_Total_Support_USD__c
,RevenueValue__c
,IqScore
,SWT_Are_Products_being_removed__c
,SWT_Bid_Service__c
,SWT_Bid_Type__c
,SWT_Current_ELA_Names__c
,SWT_ELA_Amendment__c
,SWT_ELA_Business_Proposal__c
,SWT_Estimated_Extension_Term__c
,SWT_Estimated_Term__c
,Eval_License_key_Duration__c
,Eval_License_key_Grace__c
,Eval_License_key_Start__c
,SWT_Existing_ELA_Effective_Date__c
,SWT_Existing_ELA_Expiration_Date__c
,SWT_Existing_ELA_Type__c
,SWT_Is_Merged_Primary_Opportunity__c
,SWT_Legacy_System__c
,SWT_Master_Opportunity__c
,SWT_New_BU_s_to_be_added__c
,Nodes__c
,SWT_Non_Primary_Merged_Opportunity__c
,Opportunity_Database_Size__c
,Opportunity_URL__c
,SWT_Parent_Opportunity__c
,SWT_Previous_ELA_Customer__c
,Product__c
,SWT_Product_being_removed__c
,SWT_Proposed_Amendment_Effective_Date__c
,SWT_Proposed_ELA_Amendment_Type__c
,SWT_Proposed_ELA_Business_Units__c
,SWT_Proposed_ELA_Effective_Date__c
,SWT_Proposed_ELA_Type__c
,SWT_Requested_Changes_to_ELA__c
,SWT_Primary_Quote__c
,SWT_QuoteStage__c
,SWT_Switch_to_Product_Services__c
,SWT_Total_Support_Renewal_Revenue__c
,SWT_Total_Support_Renewal_Value__c
,SWT_Transition_Zero_Out_CSV_fields__c
,SWT_DealForProfServices__c
,SWT_Gov_LLC__c
,GS_Relationship__c
,Manager_Forecast_Value_CFR__c
,SWT_MSP_Prog_Type__c
,SWT_Multi_Tenant__c
,Presales_Owner__c
,SFDC_Opportunity_Number__c
,SWT_Single_Tenant__c
,SWT_Tenant_Type__c
,SWT_Total_Support_Renewal_Value_USD__c
,LD_DT
,SWT_INS_DT
,d_source
)
select
AccountId
,Additional_Influence_ReferralPartnerRole__c
,Amount
,Apttus_Approval__Approval_Status__c
,Apttus_Proposal__Discount_Percent__c
,Budget_Confirmed__c
,CampaignId
,CloseDate
,Competitor_Details__c
,ContractId
,CreatedById
,CreatedDate
,CurrencyIsoCode
,Description
,Discovery_Completed__c
,DSE__MainCompetitors__c
,DSE__OrderNumber__c
,ExpectedRevenue
,ForecastCategory
,ForecastCategoryName
,HasOpenActivity
,HasOpportunityLineItem
,HasOverdueTask
,Id
,IsClosed
,IsDeleted
,IsPrivate
,IsSplit
,IsWon
,LastActivityDate
,LastModifiedById
,LastModifiedDate
,LastReferencedDate
,LastViewedDate
,LeadSource
,Loss_Reason__c
,Name
,NextStep
,OwnerId
,PartnerAccountId
,Price_List__c
,Pricebook2Id
,Primary_Competitor__c
,Probability
,RecordTypeId
,ROI_Analysis_Completed__c
,Sample__c
,Secondary_Competitor__c
,StageName
,SWT_Account_Verification__c
,SWT_Actual_quote_amount__c
,SWT_Alliance_Partner__c
,SWT_Alliance_Partner_Role__c
,SWT_Approval_Level_Indicator__c
,SWT_Approved_for_Professional_Services__c
,SWT_Approver_Level_1__c
,SWT_Approver_Level_2__c
,SWT_Approver_Level_3__c
,SWT_At_Risk__c
,SWT_Bid_Cost__c
,SWT_Big_Deal_Review__c
,SWT_BU__c
,SWT_Budget_Confimed__c
,SWT_Business_Case__c
,SWT_Client_Urgency_Commitment__c
,SWT_Clone_SaaS_Renewal_Parent_ID__c
,SWT_Cloned_Opportunity__c
,SWT_Comments__c
,SWT_Compelling_Event_Description__c
,SWT_Compelling_Evnt_Custmr_Reason_to_Buy__c
,SWT_Competitor__c
,SWT_Confidential__c
,SWT_Contract_End_Date__c
,SWT_Contract_Start_Date__c
,SWT_Contract_Status__c
,SWT_Converted_from_Lead__c
,SWT_Customer_Engagement__c
,SWT_Customer_Executive_Sponsor__c
,SWT_Date_Deal_Slipped__c
,SWT_Days_in_Sales_Stage_Develop_Qualify__c
,SWT_Days_in_Sales_Stage_Negotiate__c
,SWT_Days_in_Sales_Stage_Open__c
,SWT_Days_in_Sales_Stage_Propose__c
,SWT_Days_in_Sales_Stage_Validate__c
,SWT_Deal_Source__c
,SWT_Decision_Process_Known__c
,SWT_Detailed_Reason_Won_Lost_per_Rep__c
,SWT_Discount__c
,SWT_Executive_Ask__c
,SWT_Executive_Ask_Due_Date__c
,SWT_Executive_Name__c
,SWT_ExternalId__c
,SWT_Forecast_Category__c
,SWT_Fulfillment_Type__c
,SWT_Help_Needed__c
,SWT_Incumbent__c
,SWT_Is_a_Primary_Opportunity__c
,SWT_Is_Owner_Logged_In_User__c
,SWT_Lead_Qualifier__c
,SWT_License_Shipment_Value__c
,SWT_Lost_Opportunity__c
,SWT_Managed_By__c
,SWT_Managed_Service_Provider__c
,SWT_Month_Date_of_Update__c
,SWT_Next_Milestones_Actions_to_Close__c
,SWT_No_Alliance_Partner__c
,SWT_No_of_Products__c
,SWT_Opportunity_Access__c
,SWT_Opportunity_Currency_Formula__c
,SWT_Opportunity_Number__c
,SWT_Opportunity_Role_Type__c
,SWT_Opportunity_Type__c
,SWT_OpportunityFieldID__c
,SWT_Original_Slipped_Quarter__c
,SWT_Other_Executive_Name__c
,SWT_Our_Competitive_Relationship_Strengt__c
,SWT_Our_Solution_Relative_to_Competitors__c
,SWT_Painpoint_Problem_Trying_to_Solve__c
,SWT_Pillar__c
,SWT_Primary_Contact__c
,SWT_Primary_Opportunity_MultiPartnerDeal__c
,SWT_Procurement_Process_Known__c
,SWT_Product_Type__c
,SWT_Professional_Services_Initiated__c
,SWT_Project_Resources_Defined__c
,SWT_PS_Opportunity__c
,SWT_Push_Counter_Increment__c
,SWT_Qualification_Score__c
,SWT_Quote_Id__c
,SWT_Reason_Abandoned__c
,SWT_Reason_Won_Lost_per_Rep__c
,SWT_Region__c
,SWT_Revenue_Management__c
,SWT_Risks_Barriers_to_Close__c
,SWT_SaaS_Contract_Length_in_Months__c
,SWT_Sales_Play__c
,SWT_Slipped_Deal__c
,SWT_Slipped_Deal_Counter__c
,SWT_Sourced_Partner__c
,SWT_Specific_Ask__c
,SWT_Status_Update_from_Last_Actions__c
,SWT_Technical_Decision_Status_TDS__c
,SWT_Tier_1_Partner__c
,SWT_Tier_1_Partner_Agreement__c
,SWT_Tier_1_Partner_Type__c
,SWT_Tier_2_Partner__c
,SWT_Tier_2_Partner_Agreement__c
,SWT_Tier_2_Partner_Type__c
,SWT_Total_Appliance_Rollup__c
,SWT_Total_ArcSightApplianceLicenseRollup__c
,SWT_Total_Data_Security_ApplianceLicense__c
,SWT_Total_Education_Roll_up__c
,SWT_Total_FortifyApplianceLicense_Rollup__c
,SWT_Total_License_Shipment_Value__c
,SWT_Total_Opportunity_Value__c
,SWT_Total_Saas_Product__c
,SWT_Total_SaaS_Roll_up__c
,SWT_Total_Score__c
,SWT_Total_Services_Roll_up__c
,SWT_Total_Support_Roll_Up__c
,SWTAdditional_Influence_Referral_Partner__c
,SyncedQuoteId
,SystemModstamp
,TotalOpportunityQuantity
,Type
,SWT_Uplift_Percentage__c
,SWT_Presales_WBS_Code__c
,SWT_Approved_Bid_Cost__c
,SWT_Sourced_Referral_Approved__c
,SWT_Partner_Account_Number__c
,SWT_Annualized_Contract_Value__c
,SWT_Partner_Influencer_Approved__c
,HPSW_LMO_Engagement__c
,SWT_ELA__c
,SWT_Manual_Revenue__c
,SWT_Prepaid__c
,SWT_Forecast_Risk__c
,SWT_Loss_Risk__c
,SWT_Manager_Comments__c
,SWT_Renewal_Comments__c
,SWT_Renewal_End_Date__c
,SWT_Renewal_Start_Date__c
,Segmentation__c
,SWT_Previous_SaaS_Value__c
,SWT_Pipeline_Exclusion_Check__c
,SWT_Order_Number__c
,SWT_Cancellation_Reason__c
,SWT_Cancellation_Type__c
,SWT_Cancellation_Note__c
,SWT_CAM__c
,SWT_CAM_Type__c
,HPSW_Renewal_Opportunity_Quarter__c
,SWT_Under_Forecast_Upsell_Reason__c
,SWT_Total_List_Price_Calculated__c
,SWT_Contract_End_Financial_Year__c
,SWT_Current_Financial_Year__c
,SWT_Delivery_To_Contact__c
,SWT_Bill_To_Contact__c
,SWT_CMT_1__c
,SWT_CMT_2__c
,SWT_Order_is_Booked__c
,SWT_PO_Number__c
,SWT_Rejected_By__c
,SWT_Opportunity_Total_Price__c
,SWT_Annualized_Foundation__c
,SWT_Renewal_Quote_Created__c
,SWT_Quote_Created__c
,SWT_Product_Line__c
,SWT_Last_Year_s_Contract_Value__c
,SWT_Total_Professional_Services__c
,SWT_Total_Services__c
,SWT_Approved_Bid_Cost_formula__c
,SWT_Renewal_Quote_Creation_Date__c
,SWT_Add_on_Opportunity__c
,SWT_Subscription_Link__c
,SWT_Education_Opportunity__c
,SWT_Number_Of_Product_Services__c
,SWT_Date_Approved__c
,SWT_No_Bid_Costs_Needed__c
,SWT_Total_List_Price__c
,SWT_New_Logo_Master__c
,SWT_Total_Initial_Opportunity_Value__c
,SWT_Total_License_Appliance__c
,SWT_Subscription_End_Financial_Year__c
,SWT_Order_booked_Date__c
,SWT_Under_Forecast_Upsell__c
,SWT_Prior_Renewal__c
,SWT_Renewal_Status__c
,SWT_Current_Quarter__c
,SWT_Forecast_Status__c
,SWT_Previous_Opportunity__c
,Number_Of_Deals_Approved_Rejected__c
,SWT_Account_Country__c
,SWT_Customer_Budget__c
,SWT_Expected_close_date__c
,SWT_Number_Of_Deals_Registered__c
,SWT_Original_Parent_Account__c
,SWT_Parent_Opportunity_Link__c
,SWT_Partner_Business_Manager__c
,SWT_Term__c
,SWT_Valid_for_CQ_Pipeline__c
,SWT_Zuora_Subscription_Id__c
,SWT_Annualized_Contract_Value_USD__c
,SWT_Sent_email_to_ITOM__c
,Sent_email_to_IMG__c
,Sent_email_to_ESP__c
,SWT_Sent_email_to_BDP__c
,SWT_Sent_email_to_ADM__c
,SWT_Total_RTS_USD__c
,SWT_Total_RTS_RollUp__c
,SWT_Total_Foundation_USD__c
,SWT_Total_Foundation_RollUp__c
,SWT_Annualized_Foundation_USD__c
,SWT_Renewals_Total_CQ_Rev_USD__c
,SWT_Currency_Conversion_Factor__c
,SWT_Renewal_Quote_Creation__c
,SWT_No_of_products_Packaged__c
,SWT_Legacy_Opportunity_ID__c
,SWT_SOW_Deadline__c
,SWT_OrderStatus__c
,SWT_Pipeline_Category__c
,SWT_Cut_off_Date__c
,SWT_Adopt_a_Deal__c
,SWT_Quote_Stage__c
,SWT_Adjustment_Type__c
,SWT_Invoiced__c
,SWT_ATR_Type__c
,SWT_Renewal_Mgr_Forecast_Modified__c
,SWT_Mgr_Override__c
,SWT_Renewal_Mgr_Forecast_Override__c
,SWT_Contract_Expiration_Quarter__c
,SWT_SubscriptionName__c
,SWT_TotalOpportunityValueUSD__c
,SWT_Opportunity_Classification__c
,SWT_ProductsWithSubType__c
,SWT_Will_Delivery_Include_GDC__c
,SWT_SVI_Partner__c
,SWT_Product_Category__c
,SWT_Update_from_Quote__c
,SWT_Detailed_Reason_Lost_per_Rep__c
,SWT_Invalid_Reason__c
,Product_Line__c
,SWT_CheckSubscription__c
,SWT_Original_Quarter_Skipped__c
,SWT_Subcontractor_Involved__c
,SWT_Came_from_License_Deal__c
,SWT_Customer_Subscription_Name_Zuora__c
,SWT_Subscription_ID_Zuora__c
,SWT_Service_Offering__c
,SWT_Lead_Business_Area__c
,SWT_SVI__c
,SWT_Transition__c
,SWT_Total_Forecast_Value__c
,SWT_Anniversary__c
,SWT_Close_Date_Financial_Year__c
,SWT_Close_Date_Quarter__c
,SWT_Is_Last_Month_of_Quarter__c
,SWT_Manager_Forecast_Override__c
,SWT_Partner_Role__c
,SWT_Subscription__c
,SWT_Linked_Opportunity_for_Currency__c
,SWT_EoT_Date__c
,SWT_Manager_Forecast_Category__c
,SWT_Total_Forecast_Value_USD__c
,SWT_ProductsWithSalesPriceSubTypeRollup__c
,SWT_Flexcare_Status__c
,SWT_Came_from_Add_On__c
,SWT_Manager_Judgement__c
,SWT_Subscription_present__c 
,SWT_Deals_Approved__c 
,SWT_LQID__c
,CFCR_BU_ADM__c
,CFCR_BU_BDP__c
,CFCR_BU_ESP__c
,CFCR_BU_IM_G__c
,CFCR_BU_ITOM__c
,CFCR_Business_Unit_Formula__c
,CFCR_Velocity_Won__c
,CFCR_Count__c
,FCRM__FCR_First_Campaign_Touch__c
,FCRM__FCR_Last_Campaign_Touch__c
,FCRM__FCR_Response_ID__c
,CFCR_of_Business_Units__c
,CFCR_Exclude_From_Campaign_Influence__c
,CFCR_SQO_Date__c
,FCRM__FCR_Admin_CMArchive__c
,FCRM__FCR_Admin_Originating_Contact__c
,FCRM__FCR_Admin_Update_Counter__c
,FCRM__FCR_Campaign_Attribution__c
,GS_CTA__c
,SWT_Account_Name__c
,SWT_Account_RPL_Status__c
,SWT_Agreement_Created__c
,SWT_Approvers__c
,SWT_Attach_Type__c
,SWT_Bypass_Addon_Validation__c
,SWT_Champion__c
,SWT_Contract_T_C_s__c
,SWT_Country_Name__c
,SWT_Country_Region__c
,SWT_Country_Type__c
,SWT_CrossBorderTransaction__c
,SWT_Decision_Criteria__c
,SWT_Decision_Process__c
,SWT_Exclude_Validation_Rule__c
,SWT_Has_Product_Service__c
,SWT_Manager_Forecast_Value__c
,SWT_Marketing_Comments__c
,SWT_Metrics__c
,SWT_Opportunity_WIth_Order_from_Agree__c
,SWT_OwnerId__c
,SWT_PO_Process_Description__c
,SWT_Presales_Budget_RequestedUSD__c
,SWT_Price_List__c
,Swt_Renewal_Quote_Creation_Failed__c
,SWT_Revenue_Date__c
,SWT_ServiceOffering__c
,SWT_Sold_To_Contact__c
,SWT_Special_Pricing_Deep_Discount__c
,SWT_Status_Change_From_Order__c
,SWT_Total_Appliance_USD__c
,SWT_Total_Education_USD__c
,SWT_Total_License_and_ACV__c
,SWT_Total_License_and_Appliance_USD__c
,SWT_Total_License_USD__c
,SWT_Total_Saas_USD__c
,SWT_Total_Services_USD__c
,SWT_Total_Support_USD__c
,RevenueValue__c
,IqScore
,SWT_Are_Products_being_removed__c
,SWT_Bid_Service__c
,SWT_Bid_Type__c
,SWT_Current_ELA_Names__c
,SWT_ELA_Amendment__c
,SWT_ELA_Business_Proposal__c
,SWT_Estimated_Extension_Term__c
,SWT_Estimated_Term__c
,Eval_License_key_Duration__c
,Eval_License_key_Grace__c
,Eval_License_key_Start__c
,SWT_Existing_ELA_Effective_Date__c
,SWT_Existing_ELA_Expiration_Date__c
,SWT_Existing_ELA_Type__c
,SWT_Is_Merged_Primary_Opportunity__c
,SWT_Legacy_System__c
,SWT_Master_Opportunity__c
,SWT_New_BU_s_to_be_added__c
,Nodes__c
,SWT_Non_Primary_Merged_Opportunity__c
,Opportunity_Database_Size__c
,Opportunity_URL__c
,SWT_Parent_Opportunity__c
,SWT_Previous_ELA_Customer__c
,Product__c
,SWT_Product_being_removed__c
,SWT_Proposed_Amendment_Effective_Date__c
,SWT_Proposed_ELA_Amendment_Type__c
,SWT_Proposed_ELA_Business_Units__c
,SWT_Proposed_ELA_Effective_Date__c
,SWT_Proposed_ELA_Type__c
,SWT_Requested_Changes_to_ELA__c
,SWT_Primary_Quote__c
,SWT_QuoteStage__c
,SWT_Switch_to_Product_Services__c
,SWT_Total_Support_Renewal_Revenue__c
,SWT_Total_Support_Renewal_Value__c
,SWT_Transition_Zero_Out_CSV_fields__c
,SWT_DealForProfServices__c
,SWT_Gov_LLC__c
,GS_Relationship__c
,Manager_Forecast_Value_CFR__c
,SWT_MSP_Prog_Type__c
,SWT_Multi_Tenant__c
,Presales_Owner__c
,SFDC_Opportunity_Number__c
,SWT_Single_Tenant__c
,SWT_Tenant_Type__c
,SWT_Total_Support_Renewal_Value_USD__c
,SYSDATE AS LD_DT
,SWT_INS_DT
,'base'
FROM "swt_rpt_base".SF_Opportunity WHERE id in
(SELECT STG.id FROM SF_Opportunity_stg_Tmp_Key STG JOIN SF_Opportunity_base_Tmp
ON STG.id = SF_Opportunity_base_Tmp.id AND STG.LastModifiedDate >= SF_Opportunity_base_Tmp.LastModifiedDate);



/* Deleting before seven days data from current date in the Historical Table */

delete /*+DIRECT*/ from "swt_rpt_stg"."SF_Opportunity_HIST"  where LD_DT::date <= TIMESTAMPADD(DAY,-7,sysdate)::date;


/* Incremental VSQL script for loading data from Stage to Base */

DELETE /*+DIRECT*/ FROM "swt_rpt_base".SF_Opportunity WHERE id in
(SELECT STG.id FROM SF_Opportunity_stg_Tmp_Key STG JOIN SF_Opportunity_base_Tmp
ON STG.id = SF_Opportunity_base_Tmp.id AND STG.LastModifiedDate >= SF_Opportunity_base_Tmp.LastModifiedDate);

INSERT /*+DIRECT*/ INTO "swt_rpt_base".SF_Opportunity
(
AccountId
,Additional_Influence_ReferralPartnerRole__c
,Amount
,Apttus_Approval__Approval_Status__c
,Apttus_Proposal__Discount_Percent__c
,Budget_Confirmed__c
,CampaignId
,CloseDate
,Competitor_Details__c
,ContractId
,CreatedById
,CreatedDate
,CurrencyIsoCode
,Description
,Discovery_Completed__c
,DSE__MainCompetitors__c
,DSE__OrderNumber__c
,ExpectedRevenue
,ForecastCategory
,ForecastCategoryName
,HasOpenActivity
,HasOpportunityLineItem
,HasOverdueTask
,Id
,IsClosed
,IsDeleted
,IsPrivate
,IsSplit
,IsWon
,LastActivityDate
,LastModifiedById
,LastModifiedDate
,LastReferencedDate
,LastViewedDate
,LeadSource
,Loss_Reason__c
,Name
,NextStep
,OwnerId
,PartnerAccountId
,Price_List__c
,Pricebook2Id
,Primary_Competitor__c
,Probability
,RecordTypeId
,ROI_Analysis_Completed__c
,Sample__c
,Secondary_Competitor__c
,StageName
,SWT_Account_Verification__c
,SWT_Actual_quote_amount__c
,SWT_Alliance_Partner__c
,SWT_Alliance_Partner_Role__c
,SWT_Approval_Level_Indicator__c
,SWT_Approved_for_Professional_Services__c
,SWT_Approver_Level_1__c
,SWT_Approver_Level_2__c
,SWT_Approver_Level_3__c
,SWT_At_Risk__c
,SWT_Bid_Cost__c
,SWT_Big_Deal_Review__c
,SWT_BU__c
,SWT_Budget_Confimed__c
,SWT_Business_Case__c
,SWT_Client_Urgency_Commitment__c
,SWT_Clone_SaaS_Renewal_Parent_ID__c
,SWT_Cloned_Opportunity__c
,SWT_Comments__c
,SWT_Compelling_Event_Description__c
,SWT_Compelling_Evnt_Custmr_Reason_to_Buy__c
,SWT_Competitor__c
,SWT_Confidential__c
,SWT_Contract_End_Date__c
,SWT_Contract_Start_Date__c
,SWT_Contract_Status__c
,SWT_Converted_from_Lead__c
,SWT_Customer_Engagement__c
,SWT_Customer_Executive_Sponsor__c
,SWT_Date_Deal_Slipped__c
,SWT_Days_in_Sales_Stage_Develop_Qualify__c
,SWT_Days_in_Sales_Stage_Negotiate__c
,SWT_Days_in_Sales_Stage_Open__c
,SWT_Days_in_Sales_Stage_Propose__c
,SWT_Days_in_Sales_Stage_Validate__c
,SWT_Deal_Source__c
,SWT_Decision_Process_Known__c
,SWT_Detailed_Reason_Won_Lost_per_Rep__c
,SWT_Discount__c
,SWT_Executive_Ask__c
,SWT_Executive_Ask_Due_Date__c
,SWT_Executive_Name__c
,SWT_ExternalId__c
,SWT_Forecast_Category__c
,SWT_Fulfillment_Type__c
,SWT_Help_Needed__c
,SWT_Incumbent__c
,SWT_Is_a_Primary_Opportunity__c
,SWT_Is_Owner_Logged_In_User__c
,SWT_Lead_Qualifier__c
,SWT_License_Shipment_Value__c
,SWT_Lost_Opportunity__c
,SWT_Managed_By__c
,SWT_Managed_Service_Provider__c
,SWT_Month_Date_of_Update__c
,SWT_Next_Milestones_Actions_to_Close__c
,SWT_No_Alliance_Partner__c
,SWT_No_of_Products__c
,SWT_Opportunity_Access__c
,SWT_Opportunity_Currency_Formula__c
,SWT_Opportunity_Number__c
,SWT_Opportunity_Role_Type__c
,SWT_Opportunity_Type__c
,SWT_OpportunityFieldID__c
,SWT_Original_Slipped_Quarter__c
,SWT_Other_Executive_Name__c
,SWT_Our_Competitive_Relationship_Strengt__c
,SWT_Our_Solution_Relative_to_Competitors__c
,SWT_Painpoint_Problem_Trying_to_Solve__c
,SWT_Pillar__c
,SWT_Primary_Contact__c
,SWT_Primary_Opportunity_MultiPartnerDeal__c
,SWT_Procurement_Process_Known__c
,SWT_Product_Type__c
,SWT_Professional_Services_Initiated__c
,SWT_Project_Resources_Defined__c
,SWT_PS_Opportunity__c
,SWT_Push_Counter_Increment__c
,SWT_Qualification_Score__c
,SWT_Quote_Id__c
,SWT_Reason_Abandoned__c
,SWT_Reason_Won_Lost_per_Rep__c
,SWT_Region__c
,SWT_Revenue_Management__c
,SWT_Risks_Barriers_to_Close__c
,SWT_SaaS_Contract_Length_in_Months__c
,SWT_Sales_Play__c
,SWT_Slipped_Deal__c
,SWT_Slipped_Deal_Counter__c
,SWT_Sourced_Partner__c
,SWT_Specific_Ask__c
,SWT_Status_Update_from_Last_Actions__c
,SWT_Technical_Decision_Status_TDS__c
,SWT_Tier_1_Partner__c
,SWT_Tier_1_Partner_Agreement__c
,SWT_Tier_1_Partner_Type__c
,SWT_Tier_2_Partner__c
,SWT_Tier_2_Partner_Agreement__c
,SWT_Tier_2_Partner_Type__c
,SWT_Total_Appliance_Rollup__c
,SWT_Total_ArcSightApplianceLicenseRollup__c
,SWT_Total_Data_Security_ApplianceLicense__c
,SWT_Total_Education_Roll_up__c
,SWT_Total_FortifyApplianceLicense_Rollup__c
,SWT_Total_License_Shipment_Value__c
,SWT_Total_Opportunity_Value__c
,SWT_Total_Saas_Product__c
,SWT_Total_SaaS_Roll_up__c
,SWT_Total_Score__c
,SWT_Total_Services_Roll_up__c
,SWT_Total_Support_Roll_Up__c
,SWTAdditional_Influence_Referral_Partner__c
,SyncedQuoteId
,SystemModstamp
,TotalOpportunityQuantity
,Type
,SWT_Uplift_Percentage__c
,SWT_Presales_WBS_Code__c
,SWT_Approved_Bid_Cost__c
,SWT_Sourced_Referral_Approved__c
,SWT_Partner_Account_Number__c
,SWT_Annualized_Contract_Value__c
,SWT_Partner_Influencer_Approved__c
,HPSW_LMO_Engagement__c
,SWT_ELA__c
,SWT_Manual_Revenue__c
,SWT_Prepaid__c
,SWT_Forecast_Risk__c
,SWT_Loss_Risk__c
,SWT_Manager_Comments__c
,SWT_Renewal_Comments__c
,SWT_Renewal_End_Date__c
,SWT_Renewal_Start_Date__c
,Segmentation__c
,SWT_Previous_SaaS_Value__c
,SWT_Pipeline_Exclusion_Check__c
,SWT_Order_Number__c
,SWT_Cancellation_Reason__c
,SWT_Cancellation_Type__c
,SWT_Cancellation_Note__c
,SWT_CAM__c
,SWT_CAM_Type__c
,HPSW_Renewal_Opportunity_Quarter__c
,SWT_Under_Forecast_Upsell_Reason__c
,SWT_Total_List_Price_Calculated__c
,SWT_Contract_End_Financial_Year__c
,SWT_Current_Financial_Year__c
,SWT_Delivery_To_Contact__c
,SWT_Bill_To_Contact__c
,SWT_CMT_1__c
,SWT_CMT_2__c
,SWT_Order_is_Booked__c
,SWT_PO_Number__c
,SWT_Rejected_By__c
,SWT_Opportunity_Total_Price__c
,SWT_Annualized_Foundation__c
,SWT_Renewal_Quote_Created__c
,SWT_Quote_Created__c
,SWT_Product_Line__c
,SWT_Last_Year_s_Contract_Value__c
,SWT_Total_Professional_Services__c
,SWT_Total_Services__c
,SWT_Approved_Bid_Cost_formula__c
,SWT_Renewal_Quote_Creation_Date__c
,SWT_Add_on_Opportunity__c
,SWT_Subscription_Link__c
,SWT_Education_Opportunity__c
,SWT_Number_Of_Product_Services__c
,SWT_Date_Approved__c
,SWT_No_Bid_Costs_Needed__c
,SWT_Total_List_Price__c
,SWT_New_Logo_Master__c
,SWT_Total_Initial_Opportunity_Value__c
,SWT_Total_License_Appliance__c
,SWT_Subscription_End_Financial_Year__c
,SWT_Order_booked_Date__c
,SWT_Under_Forecast_Upsell__c
,SWT_Prior_Renewal__c
,SWT_Renewal_Status__c
,SWT_Current_Quarter__c
,SWT_Forecast_Status__c
,SWT_Previous_Opportunity__c
,Number_Of_Deals_Approved_Rejected__c
,SWT_Account_Country__c
,SWT_Customer_Budget__c
,SWT_Expected_close_date__c
,SWT_Number_Of_Deals_Registered__c
,SWT_Original_Parent_Account__c
,SWT_Parent_Opportunity_Link__c
,SWT_Partner_Business_Manager__c
,SWT_Term__c
,SWT_Valid_for_CQ_Pipeline__c
,SWT_Zuora_Subscription_Id__c
,SWT_Annualized_Contract_Value_USD__c
,SWT_Sent_email_to_ITOM__c
,Sent_email_to_IMG__c
,Sent_email_to_ESP__c
,SWT_Sent_email_to_BDP__c
,SWT_Sent_email_to_ADM__c
,SWT_Total_RTS_USD__c
,SWT_Total_RTS_RollUp__c
,SWT_Total_Foundation_USD__c
,SWT_Total_Foundation_RollUp__c
,SWT_Annualized_Foundation_USD__c
,SWT_Renewals_Total_CQ_Rev_USD__c
,SWT_Currency_Conversion_Factor__c
,SWT_Renewal_Quote_Creation__c
,SWT_No_of_products_Packaged__c
,SWT_Legacy_Opportunity_ID__c
,SWT_SOW_Deadline__c
,SWT_OrderStatus__c
,SWT_Pipeline_Category__c
,SWT_Cut_off_Date__c
,SWT_Adopt_a_Deal__c
,SWT_Quote_Stage__c
,SWT_Adjustment_Type__c
,SWT_Invoiced__c
,SWT_ATR_Type__c
,SWT_Renewal_Mgr_Forecast_Modified__c
,SWT_Mgr_Override__c
,SWT_Renewal_Mgr_Forecast_Override__c
,SWT_Contract_Expiration_Quarter__c
,SWT_SubscriptionName__c
,SWT_TotalOpportunityValueUSD__c
,SWT_Opportunity_Classification__c
,SWT_ProductsWithSubType__c
,SWT_Will_Delivery_Include_GDC__c
,SWT_SVI_Partner__c
,SWT_Product_Category__c
,SWT_Update_from_Quote__c
,SWT_Detailed_Reason_Lost_per_Rep__c
,SWT_Invalid_Reason__c
,Product_Line__c
,SWT_CheckSubscription__c
,SWT_Original_Quarter_Skipped__c
,SWT_Subcontractor_Involved__c
,SWT_Came_from_License_Deal__c
,SWT_Customer_Subscription_Name_Zuora__c
,SWT_Subscription_ID_Zuora__c
,SWT_Service_Offering__c
,SWT_Lead_Business_Area__c
,SWT_SVI__c
,SWT_Transition__c
,SWT_Total_Forecast_Value__c
,SWT_Anniversary__c
,SWT_Close_Date_Financial_Year__c
,SWT_Close_Date_Quarter__c
,SWT_Is_Last_Month_of_Quarter__c
,SWT_Manager_Forecast_Override__c
,SWT_Partner_Role__c
,SWT_Subscription__c
,SWT_Linked_Opportunity_for_Currency__c
,SWT_EoT_Date__c
,SWT_Manager_Forecast_Category__c
,SWT_Total_Forecast_Value_USD__c
,SWT_ProductsWithSalesPriceSubTypeRollup__c
,SWT_Flexcare_Status__c
,SWT_Came_from_Add_On__c
,SWT_Manager_Judgement__c
,SWT_Subscription_present__c 
,SWT_Deals_Approved__c 
,SWT_LQID__c
,CFCR_BU_ADM__c
,CFCR_BU_BDP__c
,CFCR_BU_ESP__c
,CFCR_BU_IM_G__c
,CFCR_BU_ITOM__c
,CFCR_Business_Unit_Formula__c
,CFCR_Velocity_Won__c
,CFCR_Count__c
,FCRM__FCR_First_Campaign_Touch__c
,FCRM__FCR_Last_Campaign_Touch__c
,FCRM__FCR_Response_ID__c
,CFCR_of_Business_Units__c
,CFCR_Exclude_From_Campaign_Influence__c
,CFCR_SQO_Date__c
,FCRM__FCR_Admin_CMArchive__c
,FCRM__FCR_Admin_Originating_Contact__c
,FCRM__FCR_Admin_Update_Counter__c
,FCRM__FCR_Campaign_Attribution__c
,GS_CTA__c
,SWT_Account_Name__c
,SWT_Account_RPL_Status__c
,SWT_Agreement_Created__c
,SWT_Approvers__c
,SWT_Attach_Type__c
,SWT_Bypass_Addon_Validation__c
,SWT_Champion__c
,SWT_Contract_T_C_s__c
,SWT_Country_Name__c
,SWT_Country_Region__c
,SWT_Country_Type__c
,SWT_CrossBorderTransaction__c
,SWT_Decision_Criteria__c
,SWT_Decision_Process__c
,SWT_Exclude_Validation_Rule__c
,SWT_Has_Product_Service__c
,SWT_Manager_Forecast_Value__c
,SWT_Marketing_Comments__c
,SWT_Metrics__c
,SWT_Opportunity_WIth_Order_from_Agree__c
,SWT_OwnerId__c
,SWT_PO_Process_Description__c
,SWT_Presales_Budget_RequestedUSD__c
,SWT_Price_List__c
,Swt_Renewal_Quote_Creation_Failed__c
,SWT_Revenue_Date__c
,SWT_ServiceOffering__c
,SWT_Sold_To_Contact__c
,SWT_Special_Pricing_Deep_Discount__c
,SWT_Status_Change_From_Order__c
,SWT_Total_Appliance_USD__c
,SWT_Total_Education_USD__c
,SWT_Total_License_and_ACV__c
,SWT_Total_License_and_Appliance_USD__c
,SWT_Total_License_USD__c
,SWT_Total_Saas_USD__c
,SWT_Total_Services_USD__c
,SWT_Total_Support_USD__c
,RevenueValue__c
,IqScore
,SWT_Are_Products_being_removed__c
,SWT_Bid_Service__c
,SWT_Bid_Type__c
,SWT_Current_ELA_Names__c
,SWT_ELA_Amendment__c
,SWT_ELA_Business_Proposal__c
,SWT_Estimated_Extension_Term__c
,SWT_Estimated_Term__c
,Eval_License_key_Duration__c
,Eval_License_key_Grace__c
,Eval_License_key_Start__c
,SWT_Existing_ELA_Effective_Date__c
,SWT_Existing_ELA_Expiration_Date__c
,SWT_Existing_ELA_Type__c
,SWT_Is_Merged_Primary_Opportunity__c
,SWT_Legacy_System__c
,SWT_Master_Opportunity__c
,SWT_New_BU_s_to_be_added__c
,Nodes__c
,SWT_Non_Primary_Merged_Opportunity__c
,Opportunity_Database_Size__c
,Opportunity_URL__c
,SWT_Parent_Opportunity__c
,SWT_Previous_ELA_Customer__c
,Product__c
,SWT_Product_being_removed__c
,SWT_Proposed_Amendment_Effective_Date__c
,SWT_Proposed_ELA_Amendment_Type__c
,SWT_Proposed_ELA_Business_Units__c
,SWT_Proposed_ELA_Effective_Date__c
,SWT_Proposed_ELA_Type__c
,SWT_Requested_Changes_to_ELA__c
,SWT_Primary_Quote__c
,SWT_QuoteStage__c
,SWT_Switch_to_Product_Services__c
,SWT_Total_Support_Renewal_Revenue__c
,SWT_Total_Support_Renewal_Value__c
,SWT_Transition_Zero_Out_CSV_fields__c
,SWT_DealForProfServices__c
,SWT_Gov_LLC__c
,GS_Relationship__c
,Manager_Forecast_Value_CFR__c
,SWT_MSP_Prog_Type__c
,SWT_Multi_Tenant__c
,Presales_Owner__c
,SFDC_Opportunity_Number__c
,SWT_Single_Tenant__c
,SWT_Tenant_Type__c
,SWT_Total_Support_Renewal_Value_USD__c
,SWT_INS_DT
)
SELECT DISTINCT 
AccountId
,Additional_Influence_ReferralPartnerRole__c
,Amount
,Apttus_Approval__Approval_Status__c
,Apttus_Proposal__Discount_Percent__c
,Budget_Confirmed__c
,CampaignId
,CloseDate
,Competitor_Details__c
,ContractId
,CreatedById
,CreatedDate
,CurrencyIsoCode
,Description
,Discovery_Completed__c
,DSE__MainCompetitors__c
,DSE__OrderNumber__c
,ExpectedRevenue
,ForecastCategory
,ForecastCategoryName
,HasOpenActivity
,HasOpportunityLineItem
,HasOverdueTask
,SF_Opportunity_stg_Tmp.Id
,IsClosed
,IsDeleted
,IsPrivate
,IsSplit
,IsWon
,LastActivityDate
,LastModifiedById
,SF_Opportunity_stg_Tmp.LastModifiedDate
,LastReferencedDate
,LastViewedDate
,LeadSource
,Loss_Reason__c
,Name
,NextStep
,OwnerId
,PartnerAccountId
,Price_List__c
,Pricebook2Id
,Primary_Competitor__c
,Probability
,RecordTypeId
,ROI_Analysis_Completed__c
,Sample__c
,Secondary_Competitor__c
,StageName
,SWT_Account_Verification__c
,SWT_Actual_quote_amount__c
,SWT_Alliance_Partner__c
,SWT_Alliance_Partner_Role__c
,SWT_Approval_Level_Indicator__c
,SWT_Approved_for_Professional_Services__c
,SWT_Approver_Level_1__c
,SWT_Approver_Level_2__c
,SWT_Approver_Level_3__c
,SWT_At_Risk__c
,SWT_Bid_Cost__c
,SWT_Big_Deal_Review__c
,SWT_BU__c
,SWT_Budget_Confimed__c
,SWT_Business_Case__c
,SWT_Client_Urgency_Commitment__c
,SWT_Clone_SaaS_Renewal_Parent_ID__c
,SWT_Cloned_Opportunity__c
,SWT_Comments__c
,SWT_Compelling_Event_Description__c
,SWT_Compelling_Evnt_Custmr_Reason_to_Buy__c
,SWT_Competitor__c
,SWT_Confidential__c
,SWT_Contract_End_Date__c
,SWT_Contract_Start_Date__c
,SWT_Contract_Status__c
,SWT_Converted_from_Lead__c
,SWT_Customer_Engagement__c
,SWT_Customer_Executive_Sponsor__c
,SWT_Date_Deal_Slipped__c
,SWT_Days_in_Sales_Stage_Develop_Qualify__c
,SWT_Days_in_Sales_Stage_Negotiate__c
,SWT_Days_in_Sales_Stage_Open__c
,SWT_Days_in_Sales_Stage_Propose__c
,SWT_Days_in_Sales_Stage_Validate__c
,SWT_Deal_Source__c
,SWT_Decision_Process_Known__c
,SWT_Detailed_Reason_Won_Lost_per_Rep__c
,SWT_Discount__c
,SWT_Executive_Ask__c
,SWT_Executive_Ask_Due_Date__c
,SWT_Executive_Name__c
,SWT_ExternalId__c
,SWT_Forecast_Category__c
,SWT_Fulfillment_Type__c
,SWT_Help_Needed__c
,SWT_Incumbent__c
,SWT_Is_a_Primary_Opportunity__c
,SWT_Is_Owner_Logged_In_User__c
,SWT_Lead_Qualifier__c
,SWT_License_Shipment_Value__c
,SWT_Lost_Opportunity__c
,SWT_Managed_By__c
,SWT_Managed_Service_Provider__c
,SWT_Month_Date_of_Update__c
,SWT_Next_Milestones_Actions_to_Close__c
,SWT_No_Alliance_Partner__c
,SWT_No_of_Products__c
,SWT_Opportunity_Access__c
,SWT_Opportunity_Currency_Formula__c
,SWT_Opportunity_Number__c
,SWT_Opportunity_Role_Type__c
,SWT_Opportunity_Type__c
,SWT_OpportunityFieldID__c
,SWT_Original_Slipped_Quarter__c
,SWT_Other_Executive_Name__c
,SWT_Our_Competitive_Relationship_Strengt__c
,SWT_Our_Solution_Relative_to_Competitors__c
,SWT_Painpoint_Problem_Trying_to_Solve__c
,SWT_Pillar__c
,SWT_Primary_Contact__c
,SWT_Primary_Opportunity_MultiPartnerDeal__c
,SWT_Procurement_Process_Known__c
,SWT_Product_Type__c
,SWT_Professional_Services_Initiated__c
,SWT_Project_Resources_Defined__c
,SWT_PS_Opportunity__c
,SWT_Push_Counter_Increment__c
,SWT_Qualification_Score__c
,SWT_Quote_Id__c
,SWT_Reason_Abandoned__c
,SWT_Reason_Won_Lost_per_Rep__c
,SWT_Region__c
,SWT_Revenue_Management__c
,SWT_Risks_Barriers_to_Close__c
,SWT_SaaS_Contract_Length_in_Months__c
,SWT_Sales_Play__c
,SWT_Slipped_Deal__c
,SWT_Slipped_Deal_Counter__c
,SWT_Sourced_Partner__c
,SWT_Specific_Ask__c
,SWT_Status_Update_from_Last_Actions__c
,SWT_Technical_Decision_Status_TDS__c
,SWT_Tier_1_Partner__c
,SWT_Tier_1_Partner_Agreement__c
,SWT_Tier_1_Partner_Type__c
,SWT_Tier_2_Partner__c
,SWT_Tier_2_Partner_Agreement__c
,SWT_Tier_2_Partner_Type__c
,SWT_Total_Appliance_Rollup__c
,SWT_Total_ArcSightApplianceLicenseRollup__c
,SWT_Total_Data_Security_ApplianceLicense__c
,SWT_Total_Education_Roll_up__c
,SWT_Total_FortifyApplianceLicense_Rollup__c
,SWT_Total_License_Shipment_Value__c
,SWT_Total_Opportunity_Value__c
,SWT_Total_Saas_Product__c
,SWT_Total_SaaS_Roll_up__c
,SWT_Total_Score__c
,SWT_Total_Services_Roll_up__c
,SWT_Total_Support_Roll_Up__c
,SWTAdditional_Influence_Referral_Partner__c
,SyncedQuoteId
,SystemModstamp
,TotalOpportunityQuantity
,Type
,SWT_Uplift_Percentage__c
,SWT_Presales_WBS_Code__c
,SWT_Approved_Bid_Cost__c
,SWT_Sourced_Referral_Approved__c
,SWT_Partner_Account_Number__c
,SWT_Annualized_Contract_Value__c
,SWT_Partner_Influencer_Approved__c
,HPSW_LMO_Engagement__c
,SWT_ELA__c
,SWT_Manual_Revenue__c
,SWT_Prepaid__c
,SWT_Forecast_Risk__c
,SWT_Loss_Risk__c
,SWT_Manager_Comments__c
,SWT_Renewal_Comments__c
,SWT_Renewal_End_Date__c
,SWT_Renewal_Start_Date__c
,Segmentation__c
,SWT_Previous_SaaS_Value__c
,SWT_Pipeline_Exclusion_Check__c
,SWT_Order_Number__c
,SWT_Cancellation_Reason__c
,SWT_Cancellation_Type__c
,SWT_Cancellation_Note__c
,SWT_CAM__c
,SWT_CAM_Type__c
,HPSW_Renewal_Opportunity_Quarter__c
,SWT_Under_Forecast_Upsell_Reason__c
,SWT_Total_List_Price_Calculated__c
,SWT_Contract_End_Financial_Year__c
,SWT_Current_Financial_Year__c
,SWT_Delivery_To_Contact__c
,SWT_Bill_To_Contact__c
,SWT_CMT_1__c
,SWT_CMT_2__c
,SWT_Order_is_Booked__c
,SWT_PO_Number__c
,SWT_Rejected_By__c
,SWT_Opportunity_Total_Price__c
,SWT_Annualized_Foundation__c
,SWT_Renewal_Quote_Created__c
,SWT_Quote_Created__c
,SWT_Product_Line__c
,SWT_Last_Year_s_Contract_Value__c
,SWT_Total_Professional_Services__c
,SWT_Total_Services__c
,SWT_Approved_Bid_Cost_formula__c
,SWT_Renewal_Quote_Creation_Date__c
,SWT_Add_on_Opportunity__c
,SWT_Subscription_Link__c
,SWT_Education_Opportunity__c
,SWT_Number_Of_Product_Services__c
,SWT_Date_Approved__c
,SWT_No_Bid_Costs_Needed__c
,SWT_Total_List_Price__c
,SWT_New_Logo_Master__c
,SWT_Total_Initial_Opportunity_Value__c
,SWT_Total_License_Appliance__c
,SWT_Subscription_End_Financial_Year__c
,SWT_Order_booked_Date__c
,SWT_Under_Forecast_Upsell__c
,SWT_Prior_Renewal__c
,SWT_Renewal_Status__c
,SWT_Current_Quarter__c
,SWT_Forecast_Status__c
,SWT_Previous_Opportunity__c
,Number_Of_Deals_Approved_Rejected__c
,SWT_Account_Country__c
,SWT_Customer_Budget__c
,SWT_Expected_close_date__c
,SWT_Number_Of_Deals_Registered__c
,SWT_Original_Parent_Account__c
,SWT_Parent_Opportunity_Link__c
,SWT_Partner_Business_Manager__c
,SWT_Term__c
,SWT_Valid_for_CQ_Pipeline__c
,SWT_Zuora_Subscription_Id__c
,SWT_Annualized_Contract_Value_USD__c
,SWT_Sent_email_to_ITOM__c
,Sent_email_to_IMG__c
,Sent_email_to_ESP__c
,SWT_Sent_email_to_BDP__c
,SWT_Sent_email_to_ADM__c
,SWT_Total_RTS_USD__c
,SWT_Total_RTS_RollUp__c
,SWT_Total_Foundation_USD__c
,SWT_Total_Foundation_RollUp__c
,SWT_Annualized_Foundation_USD__c
,SWT_Renewals_Total_CQ_Rev_USD__c
,SWT_Currency_Conversion_Factor__c
,SWT_Renewal_Quote_Creation__c
,SWT_No_of_products_Packaged__c
,SWT_Legacy_Opportunity_ID__c
,SWT_SOW_Deadline__c
,SWT_OrderStatus__c
,SWT_Pipeline_Category__c
,SWT_Cut_off_Date__c
,SWT_Adopt_a_Deal__c
,SWT_Quote_Stage__c
,SWT_Adjustment_Type__c
,SWT_Invoiced__c
,SWT_ATR_Type__c
,SWT_Renewal_Mgr_Forecast_Modified__c
,SWT_Mgr_Override__c
,SWT_Renewal_Mgr_Forecast_Override__c
,SWT_Contract_Expiration_Quarter__c
,SWT_SubscriptionName__c
,SWT_TotalOpportunityValueUSD__c
,SWT_Opportunity_Classification__c
,SWT_ProductsWithSubType__c
,SWT_Will_Delivery_Include_GDC__c
,SWT_SVI_Partner__c
,SWT_Product_Category__c
,SWT_Update_from_Quote__c
,SWT_Detailed_Reason_Lost_per_Rep__c
,SWT_Invalid_Reason__c
,Product_Line__c
,SWT_CheckSubscription__c
,SWT_Original_Quarter_Skipped__c
,SWT_Subcontractor_Involved__c
,SWT_Came_from_License_Deal__c
,SWT_Customer_Subscription_Name_Zuora__c
,SWT_Subscription_ID_Zuora__c
,SWT_Service_Offering__c
,SWT_Lead_Business_Area__c
,SWT_SVI__c
,SWT_Transition__c
,SWT_Total_Forecast_Value__c
,SWT_Anniversary__c
,SWT_Close_Date_Financial_Year__c
,SWT_Close_Date_Quarter__c
,SWT_Is_Last_Month_of_Quarter__c
,SWT_Manager_Forecast_Override__c
,SWT_Partner_Role__c
,SWT_Subscription__c
,SWT_Linked_Opportunity_for_Currency__c
,SWT_EoT_Date__c
,SWT_Manager_Forecast_Category__c
,SWT_Total_Forecast_Value_USD__c
,SWT_ProductsWithSalesPriceSubTypeRollup__c
,SWT_Flexcare_Status__c
,SWT_Came_from_Add_On__c
,SWT_Manager_Judgement__c
,SWT_Subscription_present__c 
,SWT_Deals_Approved__c 
,SWT_LQID__c
,CFCR_BU_ADM__c
,CFCR_BU_BDP__c
,CFCR_BU_ESP__c
,CFCR_BU_IM_G__c
,CFCR_BU_ITOM__c
,CFCR_Business_Unit_Formula__c
,CFCR_Velocity_Won__c
,CFCR_Count__c
,FCRM__FCR_First_Campaign_Touch__c
,FCRM__FCR_Last_Campaign_Touch__c
,FCRM__FCR_Response_ID__c
,CFCR_of_Business_Units__c
,CFCR_Exclude_From_Campaign_Influence__c
,CFCR_SQO_Date__c
,FCRM__FCR_Admin_CMArchive__c
,FCRM__FCR_Admin_Originating_Contact__c
,FCRM__FCR_Admin_Update_Counter__c
,FCRM__FCR_Campaign_Attribution__c
,GS_CTA__c
,SWT_Account_Name__c
,SWT_Account_RPL_Status__c
,SWT_Agreement_Created__c
,SWT_Approvers__c
,SWT_Attach_Type__c
,SWT_Bypass_Addon_Validation__c
,SWT_Champion__c
,SWT_Contract_T_C_s__c
,SWT_Country_Name__c
,SWT_Country_Region__c
,SWT_Country_Type__c
,SWT_CrossBorderTransaction__c
,SWT_Decision_Criteria__c
,SWT_Decision_Process__c
,SWT_Exclude_Validation_Rule__c
,SWT_Has_Product_Service__c
,SWT_Manager_Forecast_Value__c
,SWT_Marketing_Comments__c
,SWT_Metrics__c
,SWT_Opportunity_WIth_Order_from_Agree__c
,SWT_OwnerId__c
,SWT_PO_Process_Description__c
,SWT_Presales_Budget_RequestedUSD__c
,SWT_Price_List__c
,Swt_Renewal_Quote_Creation_Failed__c
,SWT_Revenue_Date__c
,SWT_ServiceOffering__c
,SWT_Sold_To_Contact__c
,SWT_Special_Pricing_Deep_Discount__c
,SWT_Status_Change_From_Order__c
,SWT_Total_Appliance_USD__c
,SWT_Total_Education_USD__c
,SWT_Total_License_and_ACV__c
,SWT_Total_License_and_Appliance_USD__c
,SWT_Total_License_USD__c
,SWT_Total_Saas_USD__c
,SWT_Total_Services_USD__c
,SWT_Total_Support_USD__c
,RevenueValue__c
,IqScore
,SWT_Are_Products_being_removed__c
,SWT_Bid_Service__c
,SWT_Bid_Type__c
,SWT_Current_ELA_Names__c
,SWT_ELA_Amendment__c
,SWT_ELA_Business_Proposal__c
,SWT_Estimated_Extension_Term__c
,SWT_Estimated_Term__c
,Eval_License_key_Duration__c
,Eval_License_key_Grace__c
,Eval_License_key_Start__c
,SWT_Existing_ELA_Effective_Date__c
,SWT_Existing_ELA_Expiration_Date__c
,SWT_Existing_ELA_Type__c
,SWT_Is_Merged_Primary_Opportunity__c
,SWT_Legacy_System__c
,SWT_Master_Opportunity__c
,SWT_New_BU_s_to_be_added__c
,Nodes__c
,SWT_Non_Primary_Merged_Opportunity__c
,Opportunity_Database_Size__c
,Opportunity_URL__c
,SWT_Parent_Opportunity__c
,SWT_Previous_ELA_Customer__c
,Product__c
,SWT_Product_being_removed__c
,SWT_Proposed_Amendment_Effective_Date__c
,SWT_Proposed_ELA_Amendment_Type__c
,SWT_Proposed_ELA_Business_Units__c
,SWT_Proposed_ELA_Effective_Date__c
,SWT_Proposed_ELA_Type__c
,SWT_Requested_Changes_to_ELA__c
,SWT_Primary_Quote__c
,SWT_QuoteStage__c
,SWT_Switch_to_Product_Services__c
,SWT_Total_Support_Renewal_Revenue__c
,SWT_Total_Support_Renewal_Value__c
,SWT_Transition_Zero_Out_CSV_fields__c
,SWT_DealForProfServices__c
,SWT_Gov_LLC__c
,GS_Relationship__c
,Manager_Forecast_Value_CFR__c
,SWT_MSP_Prog_Type__c
,SWT_Multi_Tenant__c
,Presales_Owner__c
,SFDC_Opportunity_Number__c
,SWT_Single_Tenant__c
,SWT_Tenant_Type__c
,SWT_Total_Support_Renewal_Value_USD__c
,SYSDATE AS SWT_INS_DT
FROM SF_Opportunity_stg_Tmp JOIN SF_Opportunity_stg_Tmp_Key ON SF_Opportunity_stg_Tmp.id=SF_Opportunity_stg_Tmp_Key.id AND SF_Opportunity_stg_Tmp.LastModifiedDate=SF_Opportunity_stg_Tmp_Key.LastModifiedDate
WHERE NOT EXISTS
(SELECT 1 from "swt_rpt_base".SF_Opportunity BASE
WHERE SF_Opportunity_stg_Tmp.id = BASE.id);


/* Deleting partial audit entry */

DELETE FROM swt_rpt_stg.FAST_LD_AUDT where SUBJECT_AREA = 'SFDC' and
TBL_NM = 'SF_Opportunity' and
COMPLTN_STAT = 'N' and
LD_DT=sysdate::date and 
SEQ_ID = (select max(SEQ_ID) from swt_rpt_stg.FAST_LD_AUDT where  SUBJECT_AREA = 'SFDC' and  TBL_NM = 'SF_Opportunity' and  COMPLTN_STAT = 'N');


/* Inserting new audit entry with all stats */

INSERT INTO swt_rpt_stg.FAST_LD_AUDT
(
SUBJECT_AREA
,TBL_NM
,LD_DT
,START_DT_TIME
,END_DT_TIME
,SRC_REC_CNT
,TGT_REC_CNT
,COMPLTN_STAT
)
select 'SFDC','SF_Opportunity',sysdate::date,(select st from Start_Time_Tmp),sysdate,(select count from Start_Time_Tmp) ,(select count(*) from swt_rpt_base.SF_Opportunity where SWT_INS_DT::date = sysdate::date),'Y';

Commit;


select do_tm_task('mergeout','swt_rpt_stg.SF_Opportunity_Hist');
select do_tm_task('mergeout','swt_rpt_base.SF_Opportunity');
select do_tm_task('mergeout','swt_rpt_stg.FAST_LD_AUDT');
select ANALYZE_STATISTICS('swt_rpt_base.SF_Opportunity');


