/****
****Script Name	  : SF_User.sql
****Description   : Incremental data load for SF_User
****/

/*Setting timing on */
\timing

/**SET SESSION AUTOCOMMIT TO OFF;**/

\set ON_ERROR_STOP on

CREATE LOCAL TEMP TABLE Start_Time_Tmp ON COMMIT PRESERVE ROWS AS select count(*) count, sysdate st from "swt_rpt_stg"."SF_User";

/* Inserting values into Audit table  */

INSERT INTO swt_rpt_stg.FAST_LD_AUDT
(
SUBJECT_AREA
,TBL_NM
,LD_DT
,START_DT_TIME
,END_DT_TIME
,SRC_REC_CNT
,TGT_REC_CNT
,COMPLTN_STAT
)
select 'SFDC','SF_User',sysdate::date,sysdate,null,(select count from Start_Time_Tmp) ,null,'N';

Commit;

INSERT /*+DIRECT*/ INTO "swt_rpt_stg".SF_User_Hist SELECT * from "swt_rpt_stg".SF_User;
COMMIT;

CREATE LOCAL TEMP TABLE duplicates_records ON COMMIT PRESERVE ROWS AS (
select id,max(auto_id) as auto_id from swt_rpt_stg.SF_User where id in (
select id from swt_rpt_stg.SF_User group by id,LASTMODIFIEDDATE having count(1)>1)
group by id);


delete from swt_rpt_stg.SF_User where exists(
select 1 from duplicates_records t2 where swt_rpt_stg.SF_User.id=t2.id and swt_rpt_stg.SF_User.auto_id<t2.auto_id);

commit;

CREATE LOCAL TEMP TABLE SF_User_stg_Tmp ON COMMIT PRESERVE ROWS AS
(
SELECT DISTINCT * FROM swt_rpt_stg.SF_User)
SEGMENTED BY HASH(ID,LastModifiedDate) ALL NODES;

TRUNCATE TABLE swt_rpt_stg.SF_User;

CREATE LOCAL TEMP TABLE SF_User_base_Tmp ON COMMIT PRESERVE ROWS AS
(
SELECT DISTINCT ID,LastModifiedDate FROM swt_rpt_base.SF_User)
SEGMENTED BY HASH(ID,LastModifiedDate) ALL NODES;


CREATE LOCAL TEMP TABLE SF_User_stg_Tmp_Key ON COMMIT PRESERVE ROWS AS
(
SELECT id, max(LastModifiedDate) as LastModifiedDate FROM SF_User_stg_Tmp group by id)
SEGMENTED BY HASH(ID,LastModifiedDate) ALL NODES;

/* Inserting Stage table data into Historical Table */

insert /*+DIRECT*/ into swt_rpt_stg.SF_User_Hist
(
AboutMe
,IsActive
,Address
,ReceivesAdminInfoEmails
,Alias
,ForecastEnabled
,CallCenterId
,MobilePhone
,DigestFrequency
,CompanyName
,ContactId
,JigsawImportLimitOverride
,DefaultCurrencyIsoCode
,DelegatedApproverId
,Department
,Division
,Email
,EmailEncodingKey
,SenderEmail
,SenderName
,Signature
,EmployeeNumber
,Extension
,Fax
,ReceivesInfoEmails
,CurrencyIsoCode
,Usertype
,LanguageLocaleKey
,LocaleSidKey
,ManagerId
,Name
,CommunityNickname
,Phone
,PortalRole
,ProfileId
,UserRoleId
,FederationIdentifier
,StayInTouchNote
,StayInTouchSignature
,StayInTouchSubject
,TimeZoneSidKey
,Title
,Username
,echosign_dev1__EchoSign_Allow_Delegated_Sending__c
,echosign_dev1__EchoSign_Email_Verified__c
,Apttus_Approval__Approval_Level__c
,pi__Can_View_Not_Assigned_Prospects__c
,DSE__DS_Data_Scout_Profile__c
,SWT_Currency__c
,Apttus_Approval__Next_Level_Approver__c
,pi__Pardot_Api_Key__c
,pi__Pardot_Api_Version__c
,pi__Pardot_User_Id__c
,pi__Pardot_User_Key__c
,pi__Pardot_User_Role__c
,SWT_Partner_User_AccountID__c
,SWT_Region__c
,SWT_Requested_By__c
,SWT_RPL_Last_Sync__c
,SWT_RPL_Status__c
,SWT_Speciality__c
,Sub_Region__c
,SWT_User_Profile_Review_Comment__c
,SWT_User_Role_Type__c
,Id
,LastModifiedDate
,SWT_CAM_Type__c
,Approver_Role__c
,SWT_Front_Line_Manager__c
,SWT_Business_Unit__c
,LastName
,FirstName
,MiddleName
,Suffix
,Street
,City
,State
,PostalCode
,Country
,Latitude
,Longitude
,GeocodeAccuracy
,EmailPreferencesAutoBcc
,EmailPreferencesAutoBccStayInTouch
,EmailPreferencesStayInTouchReminder
,BadgeText
,LastLoginDate
,LastPasswordChangeDate
,CreatedDate
,CreatedById
,LastModifiedById
,SystemModstamp
,OfflineTrialExpirationDate
,OfflinePdaTrialExpirationDate
,UserPermissionsMarketingUser
,UserPermissionsOfflineUser
,UserPermissionsAvantgoUser
,UserPermissionsCallCenterAutoLogin
,UserPermissionsMobileUser
,UserPermissionsSFContentUser
,UserPermissionsKnowledgeUser
,UserPermissionsInteractionUser
,UserPermissionsSupportUser
,UserPermissionsJigsawProspectingUser
,UserPreferencesActivityRemindersPopup
,UserPreferencesEventRemindersCheckboxDefault
,UserPreferencesReminderSoundOff
,UserPreferencesDisableAllFeedsEmail
,UserPreferencesDisableFollowersEmail
,UserPreferencesDisableProfilePostEmail
,UserPreferencesDisableChangeCommentEmail
,UserPreferencesDisableLaterCommentEmail
,UserPreferencesDisProfPostCommentEmail
,UserPreferencesApexPagesDeveloperMode
,UserPreferencesHideCSNGetChatterMobileTask
,UserPreferencesDisableMentionsPostEmail
,UserPreferencesDisMentionsCommentEmail
,UserPreferencesHideCSNDesktopTask
,UserPreferencesHideChatterOnboardingSplash
,UserPreferencesHideSecondChatterOnboardingSplash
,UserPreferencesDisCommentAfterLikeEmail
,UserPreferencesDisableLikeEmail
,UserPreferencesSortFeedByComment
,UserPreferencesDisableMessageEmail
,UserPreferencesJigsawListUser
,UserPreferencesDisableBookmarkEmail
,UserPreferencesDisableSharePostEmail
,UserPreferencesEnableAutoSubForFeeds
,UserPreferencesDisableFileShareNotificationsForApi
,UserPreferencesShowTitleToExternalUsers
,UserPreferencesShowManagerToExternalUsers
,UserPreferencesShowEmailToExternalUsers
,UserPreferencesShowWorkPhoneToExternalUsers
,UserPreferencesShowMobilePhoneToExternalUsers
,UserPreferencesShowFaxToExternalUsers
,UserPreferencesShowStreetAddressToExternalUsers
,UserPreferencesShowCityToExternalUsers
,UserPreferencesShowStateToExternalUsers
,UserPreferencesShowPostalCodeToExternalUsers
,UserPreferencesShowCountryToExternalUsers
,UserPreferencesShowProfilePicToGuestUsers
,UserPreferencesShowTitleToGuestUsers
,UserPreferencesShowCityToGuestUsers
,UserPreferencesShowStateToGuestUsers
,UserPreferencesShowPostalCodeToGuestUsers
,UserPreferencesShowCountryToGuestUsers
,UserPreferencesHideS1BrowserUI
,UserPreferencesDisableEndorsementEmail
,UserPreferencesPathAssistantCollapsed
,UserPreferencesCacheDiagnostics
,UserPreferencesShowEmailToGuestUsers
,UserPreferencesShowManagerToGuestUsers
,UserPreferencesShowWorkPhoneToGuestUsers
,UserPreferencesShowMobilePhoneToGuestUsers
,UserPreferencesShowFaxToGuestUsers
,UserPreferencesShowStreetAddressToGuestUsers
,UserPreferencesLightningExperiencePreferred
,UserPreferencesPreviewLightning
,UserPreferencesHideEndUserOnboardingAssistantModal
,UserPreferencesHideLightningMigrationModal
,UserPreferencesHideSfxWelcomeMat
,UserPreferencesHideBiggerPhotoCallout
,UserPreferencesGlobalNavBarWTShown
,UserPreferencesGlobalNavGridMenuWTShown
,UserPreferencesCreateLEXAppsWTShown
,UserPreferencesFavoritesWTShown
,IsPortalEnabled
,IsProfilePhotoActive
,et4ae5__ExactTargetForAppExchangeAdmin__c
,et4ae5__ExactTargetForAppExchangeUser__c
,et4ae5__ValidExactTargetAdmin__c
,et4ae5__ValidExactTargetUser__c
,et4ae5__Default_ET_Page__c
,et4ae5__Default_MID__c
,et4ae5__ExactTargetUsername__c
,SWT_Account_Number__c
,SWT_HPE_Passport_Id__c
,SWT_Partner_Type__c
,LastViewedDate
,LastReferencedDate
,DefaultGroupNotificationFrequency
,FullPhotoUrl
,SmallPhotoUrl
,MediumPhotoUrl
,BannerPhotoUrl
,SmallBannerPhotoUrl
,MediumBannerPhotoUrl
,et4ae5__ExactTarget_OAuth_Token__c
,AccountId
,UserPreferencesTaskRemindersCheckboxDefault
,SWT_Edu_Admin__c
,SWT_Learner_ID__c
,SWT_Okto_Email__c
,SWT_Okto_Mail__c
,SWT_Okto_Phone__c
,SWT_Portal_Admin__c
,SWT_Training_Admin__c
,SWT_Account_City__c
,SWT_Account_PostalCode__c
,SWT_Account_State__c
,SWT_Account_Country__c
,UserPreferencesRecordHomeSectionCollapseWTShown
,UserPreferencesRecordHomeReservedWTShown
,UserPreferencesFavoritesShowTopFavorites
,SWT_Account_Street__c
,LD_DT
,SWT_INS_DT
,d_source
)
select
AboutMe
,IsActive
,Address
,ReceivesAdminInfoEmails
,Alias
,ForecastEnabled
,CallCenterId
,MobilePhone
,DigestFrequency
,CompanyName
,ContactId
,JigsawImportLimitOverride
,DefaultCurrencyIsoCode
,DelegatedApproverId
,Department
,Division
,Email
,EmailEncodingKey
,SenderEmail
,SenderName
,Signature
,EmployeeNumber
,Extension
,Fax
,ReceivesInfoEmails
,CurrencyIsoCode
,Usertype
,LanguageLocaleKey
,LocaleSidKey
,ManagerId
,Name
,CommunityNickname
,Phone
,PortalRole
,ProfileId
,UserRoleId
,FederationIdentifier
,StayInTouchNote
,StayInTouchSignature
,StayInTouchSubject
,TimeZoneSidKey
,Title
,Username
,echosign_dev1__EchoSign_Allow_Delegated_Sending__c
,echosign_dev1__EchoSign_Email_Verified__c
,Apttus_Approval__Approval_Level__c
,pi__Can_View_Not_Assigned_Prospects__c
,DSE__DS_Data_Scout_Profile__c
,SWT_Currency__c
,Apttus_Approval__Next_Level_Approver__c
,pi__Pardot_Api_Key__c
,pi__Pardot_Api_Version__c
,pi__Pardot_User_Id__c
,pi__Pardot_User_Key__c
,pi__Pardot_User_Role__c
,SWT_Partner_User_AccountID__c
,SWT_Region__c
,SWT_Requested_By__c
,SWT_RPL_Last_Sync__c
,SWT_RPL_Status__c
,SWT_Speciality__c
,Sub_Region__c
,SWT_User_Profile_Review_Comment__c
,SWT_User_Role_Type__c
,Id
,LastModifiedDate
,SWT_CAM_Type__c
,Approver_Role__c
,SWT_Front_Line_Manager__c
,SWT_Business_Unit__c
,LastName
,FirstName
,MiddleName
,Suffix
,Street
,City
,State
,PostalCode
,Country
,Latitude
,Longitude
,GeocodeAccuracy
,EmailPreferencesAutoBcc
,EmailPreferencesAutoBccStayInTouch
,EmailPreferencesStayInTouchReminder
,BadgeText
,LastLoginDate
,LastPasswordChangeDate
,CreatedDate
,CreatedById
,LastModifiedById
,SystemModstamp
,OfflineTrialExpirationDate
,OfflinePdaTrialExpirationDate
,UserPermissionsMarketingUser
,UserPermissionsOfflineUser
,UserPermissionsAvantgoUser
,UserPermissionsCallCenterAutoLogin
,UserPermissionsMobileUser
,UserPermissionsSFContentUser
,UserPermissionsKnowledgeUser
,UserPermissionsInteractionUser
,UserPermissionsSupportUser
,UserPermissionsJigsawProspectingUser
,UserPreferencesActivityRemindersPopup
,UserPreferencesEventRemindersCheckboxDefault
,UserPreferencesReminderSoundOff
,UserPreferencesDisableAllFeedsEmail
,UserPreferencesDisableFollowersEmail
,UserPreferencesDisableProfilePostEmail
,UserPreferencesDisableChangeCommentEmail
,UserPreferencesDisableLaterCommentEmail
,UserPreferencesDisProfPostCommentEmail
,UserPreferencesApexPagesDeveloperMode
,UserPreferencesHideCSNGetChatterMobileTask
,UserPreferencesDisableMentionsPostEmail
,UserPreferencesDisMentionsCommentEmail
,UserPreferencesHideCSNDesktopTask
,UserPreferencesHideChatterOnboardingSplash
,UserPreferencesHideSecondChatterOnboardingSplash
,UserPreferencesDisCommentAfterLikeEmail
,UserPreferencesDisableLikeEmail
,UserPreferencesSortFeedByComment
,UserPreferencesDisableMessageEmail
,UserPreferencesJigsawListUser
,UserPreferencesDisableBookmarkEmail
,UserPreferencesDisableSharePostEmail
,UserPreferencesEnableAutoSubForFeeds
,UserPreferencesDisableFileShareNotificationsForApi
,UserPreferencesShowTitleToExternalUsers
,UserPreferencesShowManagerToExternalUsers
,UserPreferencesShowEmailToExternalUsers
,UserPreferencesShowWorkPhoneToExternalUsers
,UserPreferencesShowMobilePhoneToExternalUsers
,UserPreferencesShowFaxToExternalUsers
,UserPreferencesShowStreetAddressToExternalUsers
,UserPreferencesShowCityToExternalUsers
,UserPreferencesShowStateToExternalUsers
,UserPreferencesShowPostalCodeToExternalUsers
,UserPreferencesShowCountryToExternalUsers
,UserPreferencesShowProfilePicToGuestUsers
,UserPreferencesShowTitleToGuestUsers
,UserPreferencesShowCityToGuestUsers
,UserPreferencesShowStateToGuestUsers
,UserPreferencesShowPostalCodeToGuestUsers
,UserPreferencesShowCountryToGuestUsers
,UserPreferencesHideS1BrowserUI
,UserPreferencesDisableEndorsementEmail
,UserPreferencesPathAssistantCollapsed
,UserPreferencesCacheDiagnostics
,UserPreferencesShowEmailToGuestUsers
,UserPreferencesShowManagerToGuestUsers
,UserPreferencesShowWorkPhoneToGuestUsers
,UserPreferencesShowMobilePhoneToGuestUsers
,UserPreferencesShowFaxToGuestUsers
,UserPreferencesShowStreetAddressToGuestUsers
,UserPreferencesLightningExperiencePreferred
,UserPreferencesPreviewLightning
,UserPreferencesHideEndUserOnboardingAssistantModal
,UserPreferencesHideLightningMigrationModal
,UserPreferencesHideSfxWelcomeMat
,UserPreferencesHideBiggerPhotoCallout
,UserPreferencesGlobalNavBarWTShown
,UserPreferencesGlobalNavGridMenuWTShown
,UserPreferencesCreateLEXAppsWTShown
,UserPreferencesFavoritesWTShown
,IsPortalEnabled
,IsProfilePhotoActive
,et4ae5__ExactTargetForAppExchangeAdmin__c
,et4ae5__ExactTargetForAppExchangeUser__c
,et4ae5__ValidExactTargetAdmin__c
,et4ae5__ValidExactTargetUser__c
,et4ae5__Default_ET_Page__c
,et4ae5__Default_MID__c
,et4ae5__ExactTargetUsername__c
,SWT_Account_Number__c
,SWT_HPE_Passport_Id__c
,SWT_Partner_Type__c
,LastViewedDate
,LastReferencedDate
,DefaultGroupNotificationFrequency
,FullPhotoUrl
,SmallPhotoUrl
,MediumPhotoUrl
,BannerPhotoUrl
,SmallBannerPhotoUrl
,MediumBannerPhotoUrl
,et4ae5__ExactTarget_OAuth_Token__c
,AccountId
,UserPreferencesTaskRemindersCheckboxDefault
,SWT_Edu_Admin__c
,SWT_Learner_ID__c
,SWT_Okto_Email__c
,SWT_Okto_Mail__c
,SWT_Okto_Phone__c
,SWT_Portal_Admin__c
,SWT_Training_Admin__c
,SWT_Account_City__c
,SWT_Account_PostalCode__c
,SWT_Account_State__c
,SWT_Account_Country__c
,UserPreferencesRecordHomeSectionCollapseWTShown
,UserPreferencesRecordHomeReservedWTShown
,UserPreferencesFavoritesShowTopFavorites
,SWT_Account_Street__c
,SYSDATE AS LD_DT
,SWT_INS_DT
,'base'
FROM "swt_rpt_base".SF_User WHERE id in
(SELECT STG.id FROM SF_User_stg_Tmp_Key STG JOIN SF_User_base_Tmp
ON STG.id = SF_User_base_Tmp.id AND STG.LastModifiedDate >= SF_User_base_Tmp.LastModifiedDate);


/* Deleting before seven days data from current date in the Historical Table */

delete /*+DIRECT*/ from "swt_rpt_stg"."SF_User_Hist"  where LD_DT::date <= TIMESTAMPADD(DAY,-7,sysdate)::date;


/* Incremental VSQL script for loading data from Stage to Base */

DELETE /*+DIRECT*/ FROM "swt_rpt_base".SF_User WHERE id in
(SELECT STG.id FROM SF_User_stg_Tmp_Key STG JOIN SF_User_base_Tmp
ON STG.id = SF_User_base_Tmp.id AND STG.LastModifiedDate >= SF_User_base_Tmp.LastModifiedDate);

INSERT /*+DIRECT*/ INTO "swt_rpt_base".SF_User
(
AboutMe
,IsActive
,Address
,ReceivesAdminInfoEmails
,Alias
,ForecastEnabled
,CallCenterId
,MobilePhone
,DigestFrequency
,CompanyName
,ContactId
,JigsawImportLimitOverride
,DefaultCurrencyIsoCode
,DelegatedApproverId
,Department
,Division
,Email
,EmailEncodingKey
,SenderEmail
,SenderName
,Signature
,EmployeeNumber
,Extension
,Fax
,ReceivesInfoEmails
,CurrencyIsoCode
,Usertype
,LanguageLocaleKey
,LocaleSidKey
,ManagerId
,Name
,CommunityNickname
,Phone
,PortalRole
,ProfileId
,UserRoleId
,FederationIdentifier
,StayInTouchNote
,StayInTouchSignature
,StayInTouchSubject
,TimeZoneSidKey
,Title
,Username
,echosign_dev1__EchoSign_Allow_Delegated_Sending__c
,echosign_dev1__EchoSign_Email_Verified__c
,Apttus_Approval__Approval_Level__c
,pi__Can_View_Not_Assigned_Prospects__c
,DSE__DS_Data_Scout_Profile__c
,SWT_Currency__c
,Apttus_Approval__Next_Level_Approver__c
,pi__Pardot_Api_Key__c
,pi__Pardot_Api_Version__c
,pi__Pardot_User_Id__c
,pi__Pardot_User_Key__c
,pi__Pardot_User_Role__c
,SWT_Partner_User_AccountID__c
,SWT_Region__c
,SWT_Requested_By__c
,SWT_RPL_Last_Sync__c
,SWT_RPL_Status__c
,SWT_Speciality__c
,Sub_Region__c
,SWT_User_Profile_Review_Comment__c
,SWT_User_Role_Type__c
,Id
,LastModifiedDate
,SWT_CAM_Type__c
,Approver_Role__c
,SWT_Front_Line_Manager__c
,SWT_Business_Unit__c
,LastName
,FirstName
,MiddleName
,Suffix
,Street
,City
,State
,PostalCode
,Country
,Latitude
,Longitude
,GeocodeAccuracy
,EmailPreferencesAutoBcc
,EmailPreferencesAutoBccStayInTouch
,EmailPreferencesStayInTouchReminder
,BadgeText
,LastLoginDate
,LastPasswordChangeDate
,CreatedDate
,CreatedById
,LastModifiedById
,SystemModstamp
,OfflineTrialExpirationDate
,OfflinePdaTrialExpirationDate
,UserPermissionsMarketingUser
,UserPermissionsOfflineUser
,UserPermissionsAvantgoUser
,UserPermissionsCallCenterAutoLogin
,UserPermissionsMobileUser
,UserPermissionsSFContentUser
,UserPermissionsKnowledgeUser
,UserPermissionsInteractionUser
,UserPermissionsSupportUser
,UserPermissionsJigsawProspectingUser
,UserPreferencesActivityRemindersPopup
,UserPreferencesEventRemindersCheckboxDefault
,UserPreferencesReminderSoundOff
,UserPreferencesDisableAllFeedsEmail
,UserPreferencesDisableFollowersEmail
,UserPreferencesDisableProfilePostEmail
,UserPreferencesDisableChangeCommentEmail
,UserPreferencesDisableLaterCommentEmail
,UserPreferencesDisProfPostCommentEmail
,UserPreferencesApexPagesDeveloperMode
,UserPreferencesHideCSNGetChatterMobileTask
,UserPreferencesDisableMentionsPostEmail
,UserPreferencesDisMentionsCommentEmail
,UserPreferencesHideCSNDesktopTask
,UserPreferencesHideChatterOnboardingSplash
,UserPreferencesHideSecondChatterOnboardingSplash
,UserPreferencesDisCommentAfterLikeEmail
,UserPreferencesDisableLikeEmail
,UserPreferencesSortFeedByComment
,UserPreferencesDisableMessageEmail
,UserPreferencesJigsawListUser
,UserPreferencesDisableBookmarkEmail
,UserPreferencesDisableSharePostEmail
,UserPreferencesEnableAutoSubForFeeds
,UserPreferencesDisableFileShareNotificationsForApi
,UserPreferencesShowTitleToExternalUsers
,UserPreferencesShowManagerToExternalUsers
,UserPreferencesShowEmailToExternalUsers
,UserPreferencesShowWorkPhoneToExternalUsers
,UserPreferencesShowMobilePhoneToExternalUsers
,UserPreferencesShowFaxToExternalUsers
,UserPreferencesShowStreetAddressToExternalUsers
,UserPreferencesShowCityToExternalUsers
,UserPreferencesShowStateToExternalUsers
,UserPreferencesShowPostalCodeToExternalUsers
,UserPreferencesShowCountryToExternalUsers
,UserPreferencesShowProfilePicToGuestUsers
,UserPreferencesShowTitleToGuestUsers
,UserPreferencesShowCityToGuestUsers
,UserPreferencesShowStateToGuestUsers
,UserPreferencesShowPostalCodeToGuestUsers
,UserPreferencesShowCountryToGuestUsers
,UserPreferencesHideS1BrowserUI
,UserPreferencesDisableEndorsementEmail
,UserPreferencesPathAssistantCollapsed
,UserPreferencesCacheDiagnostics
,UserPreferencesShowEmailToGuestUsers
,UserPreferencesShowManagerToGuestUsers
,UserPreferencesShowWorkPhoneToGuestUsers
,UserPreferencesShowMobilePhoneToGuestUsers
,UserPreferencesShowFaxToGuestUsers
,UserPreferencesShowStreetAddressToGuestUsers
,UserPreferencesLightningExperiencePreferred
,UserPreferencesPreviewLightning
,UserPreferencesHideEndUserOnboardingAssistantModal
,UserPreferencesHideLightningMigrationModal
,UserPreferencesHideSfxWelcomeMat
,UserPreferencesHideBiggerPhotoCallout
,UserPreferencesGlobalNavBarWTShown
,UserPreferencesGlobalNavGridMenuWTShown
,UserPreferencesCreateLEXAppsWTShown
,UserPreferencesFavoritesWTShown
,IsPortalEnabled
,IsProfilePhotoActive
,et4ae5__ExactTargetForAppExchangeAdmin__c
,et4ae5__ExactTargetForAppExchangeUser__c
,et4ae5__ValidExactTargetAdmin__c
,et4ae5__ValidExactTargetUser__c
,et4ae5__Default_ET_Page__c
,et4ae5__Default_MID__c
,et4ae5__ExactTargetUsername__c
,SWT_Account_Number__c
,SWT_HPE_Passport_Id__c
,SWT_Partner_Type__c
,LastViewedDate
,LastReferencedDate
,DefaultGroupNotificationFrequency
,FullPhotoUrl
,SmallPhotoUrl
,MediumPhotoUrl
,BannerPhotoUrl
,SmallBannerPhotoUrl
,MediumBannerPhotoUrl
,et4ae5__ExactTarget_OAuth_Token__c
,AccountId
,UserPreferencesTaskRemindersCheckboxDefault
,SWT_Edu_Admin__c
,SWT_Learner_ID__c
,SWT_Okto_Email__c
,SWT_Okto_Mail__c
,SWT_Okto_Phone__c
,SWT_Portal_Admin__c
,SWT_Training_Admin__c
,SWT_Account_City__c
,SWT_Account_PostalCode__c
,SWT_Account_State__c
,SWT_Account_Country__c
,UserPreferencesRecordHomeSectionCollapseWTShown
,UserPreferencesRecordHomeReservedWTShown
,UserPreferencesFavoritesShowTopFavorites
,SWT_Account_Street__c
,SWT_INS_DT
)
SELECT DISTINCT 
AboutMe
,IsActive
,Address
,ReceivesAdminInfoEmails
,Alias
,ForecastEnabled
,CallCenterId
,MobilePhone
,DigestFrequency
,CompanyName
,ContactId
,JigsawImportLimitOverride
,DefaultCurrencyIsoCode
,DelegatedApproverId
,Department
,Division
,Email
,EmailEncodingKey
,SenderEmail
,SenderName
,Signature
,EmployeeNumber
,Extension
,Fax
,ReceivesInfoEmails
,CurrencyIsoCode
,Usertype
,LanguageLocaleKey
,LocaleSidKey
,ManagerId
,Name
,CommunityNickname
,Phone
,PortalRole
,ProfileId
,UserRoleId
,FederationIdentifier
,StayInTouchNote
,StayInTouchSignature
,StayInTouchSubject
,TimeZoneSidKey
,Title
,Username
,echosign_dev1__EchoSign_Allow_Delegated_Sending__c
,echosign_dev1__EchoSign_Email_Verified__c
,Apttus_Approval__Approval_Level__c
,pi__Can_View_Not_Assigned_Prospects__c
,DSE__DS_Data_Scout_Profile__c
,SWT_Currency__c
,Apttus_Approval__Next_Level_Approver__c
,pi__Pardot_Api_Key__c
,pi__Pardot_Api_Version__c
,pi__Pardot_User_Id__c
,pi__Pardot_User_Key__c
,pi__Pardot_User_Role__c
,SWT_Partner_User_AccountID__c
,SWT_Region__c
,SWT_Requested_By__c
,SWT_RPL_Last_Sync__c
,SWT_RPL_Status__c
,SWT_Speciality__c
,Sub_Region__c
,SWT_User_Profile_Review_Comment__c
,SWT_User_Role_Type__c
,SF_User_stg_Tmp.Id
,SF_User_stg_Tmp.LastModifiedDate
,SWT_CAM_Type__c
,Approver_Role__c
,SWT_Front_Line_Manager__c
,SWT_Business_Unit__c
,LastName
,FirstName
,MiddleName
,Suffix
,Street
,City
,State
,PostalCode
,Country
,Latitude
,Longitude
,GeocodeAccuracy
,EmailPreferencesAutoBcc
,EmailPreferencesAutoBccStayInTouch
,EmailPreferencesStayInTouchReminder
,BadgeText
,LastLoginDate
,LastPasswordChangeDate
,CreatedDate
,CreatedById
,LastModifiedById
,SystemModstamp
,OfflineTrialExpirationDate
,OfflinePdaTrialExpirationDate
,UserPermissionsMarketingUser
,UserPermissionsOfflineUser
,UserPermissionsAvantgoUser
,UserPermissionsCallCenterAutoLogin
,UserPermissionsMobileUser
,UserPermissionsSFContentUser
,UserPermissionsKnowledgeUser
,UserPermissionsInteractionUser
,UserPermissionsSupportUser
,UserPermissionsJigsawProspectingUser
,UserPreferencesActivityRemindersPopup
,UserPreferencesEventRemindersCheckboxDefault
,UserPreferencesReminderSoundOff
,UserPreferencesDisableAllFeedsEmail
,UserPreferencesDisableFollowersEmail
,UserPreferencesDisableProfilePostEmail
,UserPreferencesDisableChangeCommentEmail
,UserPreferencesDisableLaterCommentEmail
,UserPreferencesDisProfPostCommentEmail
,UserPreferencesApexPagesDeveloperMode
,UserPreferencesHideCSNGetChatterMobileTask
,UserPreferencesDisableMentionsPostEmail
,UserPreferencesDisMentionsCommentEmail
,UserPreferencesHideCSNDesktopTask
,UserPreferencesHideChatterOnboardingSplash
,UserPreferencesHideSecondChatterOnboardingSplash
,UserPreferencesDisCommentAfterLikeEmail
,UserPreferencesDisableLikeEmail
,UserPreferencesSortFeedByComment
,UserPreferencesDisableMessageEmail
,UserPreferencesJigsawListUser
,UserPreferencesDisableBookmarkEmail
,UserPreferencesDisableSharePostEmail
,UserPreferencesEnableAutoSubForFeeds
,UserPreferencesDisableFileShareNotificationsForApi
,UserPreferencesShowTitleToExternalUsers
,UserPreferencesShowManagerToExternalUsers
,UserPreferencesShowEmailToExternalUsers
,UserPreferencesShowWorkPhoneToExternalUsers
,UserPreferencesShowMobilePhoneToExternalUsers
,UserPreferencesShowFaxToExternalUsers
,UserPreferencesShowStreetAddressToExternalUsers
,UserPreferencesShowCityToExternalUsers
,UserPreferencesShowStateToExternalUsers
,UserPreferencesShowPostalCodeToExternalUsers
,UserPreferencesShowCountryToExternalUsers
,UserPreferencesShowProfilePicToGuestUsers
,UserPreferencesShowTitleToGuestUsers
,UserPreferencesShowCityToGuestUsers
,UserPreferencesShowStateToGuestUsers
,UserPreferencesShowPostalCodeToGuestUsers
,UserPreferencesShowCountryToGuestUsers
,UserPreferencesHideS1BrowserUI
,UserPreferencesDisableEndorsementEmail
,UserPreferencesPathAssistantCollapsed
,UserPreferencesCacheDiagnostics
,UserPreferencesShowEmailToGuestUsers
,UserPreferencesShowManagerToGuestUsers
,UserPreferencesShowWorkPhoneToGuestUsers
,UserPreferencesShowMobilePhoneToGuestUsers
,UserPreferencesShowFaxToGuestUsers
,UserPreferencesShowStreetAddressToGuestUsers
,UserPreferencesLightningExperiencePreferred
,UserPreferencesPreviewLightning
,UserPreferencesHideEndUserOnboardingAssistantModal
,UserPreferencesHideLightningMigrationModal
,UserPreferencesHideSfxWelcomeMat
,UserPreferencesHideBiggerPhotoCallout
,UserPreferencesGlobalNavBarWTShown
,UserPreferencesGlobalNavGridMenuWTShown
,UserPreferencesCreateLEXAppsWTShown
,UserPreferencesFavoritesWTShown
,IsPortalEnabled
,IsProfilePhotoActive
,et4ae5__ExactTargetForAppExchangeAdmin__c
,et4ae5__ExactTargetForAppExchangeUser__c
,et4ae5__ValidExactTargetAdmin__c
,et4ae5__ValidExactTargetUser__c
,et4ae5__Default_ET_Page__c
,et4ae5__Default_MID__c
,et4ae5__ExactTargetUsername__c
,SWT_Account_Number__c
,SWT_HPE_Passport_Id__c
,SWT_Partner_Type__c
,LastViewedDate
,LastReferencedDate
,DefaultGroupNotificationFrequency
,FullPhotoUrl
,SmallPhotoUrl
,MediumPhotoUrl
,BannerPhotoUrl
,SmallBannerPhotoUrl
,MediumBannerPhotoUrl
,et4ae5__ExactTarget_OAuth_Token__c
,AccountId
,UserPreferencesTaskRemindersCheckboxDefault
,SWT_Edu_Admin__c
,SWT_Learner_ID__c
,SWT_Okto_Email__c
,SWT_Okto_Mail__c
,SWT_Okto_Phone__c
,SWT_Portal_Admin__c
,SWT_Training_Admin__c
,SWT_Account_City__c
,SWT_Account_PostalCode__c
,SWT_Account_State__c
,SWT_Account_Country__c
,UserPreferencesRecordHomeSectionCollapseWTShown
,UserPreferencesRecordHomeReservedWTShown
,UserPreferencesFavoritesShowTopFavorites
,SWT_Account_Street__c
,SYSDATE
FROM SF_User_stg_Tmp JOIN SF_User_stg_Tmp_Key ON SF_User_stg_Tmp.id= SF_User_stg_Tmp_Key.id AND SF_User_stg_Tmp.LastModifiedDate=SF_User_stg_Tmp_Key.LastModifiedDate
WHERE NOT EXISTS
(SELECT 1 from "swt_rpt_base".SF_User BASE
WHERE SF_User_stg_Tmp.id = BASE.id);

/* Deleting partial audit entry */

DELETE FROM swt_rpt_stg.FAST_LD_AUDT where SUBJECT_AREA = 'SFDC' and
TBL_NM = 'SF_User' and
COMPLTN_STAT = 'N' and
LD_DT=sysdate::date and 
SEQ_ID = (select max(SEQ_ID) from swt_rpt_stg.FAST_LD_AUDT where  SUBJECT_AREA = 'SFDC' and  TBL_NM = 'SF_User' and  COMPLTN_STAT = 'N');


/* Inserting new audit entry with all stats */

INSERT INTO swt_rpt_stg.FAST_LD_AUDT
(
SUBJECT_AREA
,TBL_NM
,LD_DT
,START_DT_TIME
,END_DT_TIME
,SRC_REC_CNT
,TGT_REC_CNT
,COMPLTN_STAT
)
select 'SFDC','SF_User',sysdate::date,(select st from Start_Time_Tmp),sysdate,(select count from Start_Time_Tmp) ,(select count(*) from swt_rpt_base.SF_User where SWT_INS_DT::date = sysdate::date),'Y';

Commit;


select do_tm_task('mergeout','swt_rpt_stg.SF_User_Hist');
select do_tm_task('mergeout','swt_rpt_base.SF_User');
select do_tm_task('mergeout','swt_rpt_stg.FAST_LD_AUDT');
select ANALYZE_STATISTICS('swt_rpt_base.SF_User');


