
#!/bin/ksh
export DAYTIME=`date +%Y%m%d_%H%M%S`

#export DUMMY_PATH=/home/omtsmgr/FAST/sh/DUMMY_SCRIPT
#export SH_PATH=/home/omtsmgr/FAST/sh
#export SCRIPT_PATH=/home/omtsmgr/FAST/sh

export DUMMY_PATH=/opt/FAST/sh/DUMMY_SCRIPT
export SH_PATH=/opt/FAST/sh
export SCRIPT_PATH=/opt/FAST/sh

#Go to super user omtsmgr

#pbrun -su omtsmgr


#Renames the original ksh script to _DUMMY script.

#mv (option) filename1.ext filename2.ext

echo "Renaming the original file to dummy file."

mv $SH_PATH/VRT_TIDAL_TRIGGER_CORP_BI_GTM_DAILY_EXTRACT_AND_UPLOAD.ksh $SH_PATH/VRT_TIDAL_TRIGGER_CORP_BI_GTM_DAILY_EXTRACT_AND_UPLOAD_DUMMY.ksh
mv $SH_PATH/VRT_TIDAL_TRIGGER_CORP_BI_DAILY_EXTRACT_AND_UPLOAD.ksh $SH_PATH/VRT_TIDAL_TRIGGER_CORP_BI_DAILY_EXTRACT_AND_UPLOAD_DUMMY.ksh
mv $SH_PATH/VRT_TIDAL_TRIGGER_NETSUITE.ksh $SH_PATH/VRT_TIDAL_TRIGGER_NETSUITE_DUMMY.ksh
mv $SH_PATH/VRT_TIDAL_TRIGGER_CALLIDUS.ksh $SH_PATH/VRT_TIDAL_TRIGGER_CALLIDUS_DUMMY.ksh
mv $SH_PATH/VRT_TIDAL_TRIGGER_WORKDAY.ksh $SH_PATH/VRT_TIDAL_TRIGGER_WORKDAY_DUMMY.ksh
mv $SH_PATH/VRT_TIDAL_TRIGGER_APTTUS.ksh $SH_PATH/VRT_TIDAL_TRIGGER_APTTUS_DUMMY.ksh
mv $SH_PATH/VRT_TIDAL_TRIGGER_PARDOT.ksh $SH_PATH/VRT_TIDAL_TRIGGER_PARDOT_DUMMY.ksh
mv $SH_PATH/VRT_TIDAL_TRIGGER_NETSUITEOPENAIR.ksh $SH_PATH/VRT_TIDAL_TRIGGER_NETSUITEOPENAIR_DUMMY.ksh
mv $SH_PATH/VRT_TIDAL_TRIGGER_HIGHRADIUS.ksh $SH_PATH/VRT_TIDAL_TRIGGER_HIGHRADIUS_DUMMY.ksh
mv $SH_PATH/VRT_TIDAL_TRIGGER_SFDC.ksh $SH_PATH/VRT_TIDAL_TRIGGER_SFDC_DUMMY.ksh
mv $SH_PATH/VRT_TIDAL_TRIGGER_AUDT_HIST_UPDATE_STATS_REFRESH.ksh $SH_PATH/VRT_TIDAL_TRIGGER_AUDT_HIST_UPDATE_STATS_REFRESH_DUMMY.ksh
mv $SH_PATH/VRT_TIDAL_TRIGGER_WORKDAY_without_zero_byte_dependency.ksh $SH_PATH/VRT_TIDAL_TRIGGER_WORKDAY_without_zero_byte_dependency_DUMMY.ksh
mv $SH_PATH/VRT_TIDAL_TRIGGER_ZUORA.ksh $SH_PATH/VRT_TIDAL_TRIGGER_ZUORA_DUMMY.ksh
mv $SH_PATH/VRT_TIDAL_TRIGGER_OPRTNTY_TREND_REFRESH.ksh $SH_PATH/VRT_TIDAL_TRIGGER_OPRTNTY_TREND_REFRESH_DUMMY.ksh
mv $SH_PATH/Duplicate_Checker.ksh $SH_PATH/Duplicate_Checker_DUMMY.ksh
mv $SH_PATH/Special_Cases.ksh $SH_PATH/Special_Cases_DUMMY.ksh

cp -av $DUMMY_PATH/VRT_TIDAL_TRIGGER_CORP_BI_GTM_DAILY_EXTRACT_AND_UPLOAD.ksh $SH_PATH/VRT_TIDAL_TRIGGER_CORP_BI_GTM_DAILY_EXTRACT_AND_UPLOAD.ksh
cp -av $DUMMY_PATH/VRT_TIDAL_TRIGGER_CORP_BI_DAILY_EXTRACT_AND_UPLOAD.ksh $SH_PATH/VRT_TIDAL_TRIGGER_CORP_BI_DAILY_EXTRACT_AND_UPLOAD.ksh
cp -av $DUMMY_PATH/VRT_TIDAL_TRIGGER_NETSUITE.ksh $SH_PATH/VRT_TIDAL_TRIGGER_NETSUITE.ksh
cp -av $DUMMY_PATH/VRT_TIDAL_TRIGGER_CALLIDUS.ksh $SH_PATH/VRT_TIDAL_TRIGGER_CALLIDUS.ksh
cp -av $DUMMY_PATH/VRT_TIDAL_TRIGGER_WORKDAY.ksh $SH_PATH/VRT_TIDAL_TRIGGER_WORKDAY.ksh
cp -av $DUMMY_PATH/VRT_TIDAL_TRIGGER_APTTUS.ksh $SH_PATH/VRT_TIDAL_TRIGGER_APTTUS.ksh
cp -av $DUMMY_PATH/VRT_TIDAL_TRIGGER_PARDOT.ksh $SH_PATH/VRT_TIDAL_TRIGGER_PARDOT.ksh
cp -av $DUMMY_PATH/VRT_TIDAL_TRIGGER_NETSUITEOPENAIR.ksh $SH_PATH/VRT_TIDAL_TRIGGER_NETSUITEOPENAIR.ksh
cp -av $DUMMY_PATH/VRT_TIDAL_TRIGGER_HIGHRADIUS.ksh $SH_PATH/VRT_TIDAL_TRIGGER_HIGHRADIUS.ksh
cp -av $DUMMY_PATH/VRT_TIDAL_TRIGGER_SFDC.ksh $SH_PATH/VRT_TIDAL_TRIGGER_SFDC.ksh
cp -av $DUMMY_PATH/VRT_TIDAL_TRIGGER_AUDT_HIST_UPDATE_STATS_REFRESH.ksh $SH_PATH/VRT_TIDAL_TRIGGER_AUDT_HIST_UPDATE_STATS_REFRESH.ksh
cp -av $DUMMY_PATH/VRT_TIDAL_TRIGGER_WORKDAY_without_zero_byte_dependency.ksh $SH_PATH/VRT_TIDAL_TRIGGER_WORKDAY_without_zero_byte_dependency.ksh
cp -av $DUMMY_PATH/VRT_TIDAL_TRIGGER_ZUORA.ksh $SH_PATH/VRT_TIDAL_TRIGGER_ZUORA.ksh
cp -av $DUMMY_PATH/VRT_TIDAL_TRIGGER_OPRTNTY_TREND_REFRESH.ksh $SH_PATH/VRT_TIDAL_TRIGGER_OPRTNTY_TREND_REFRESH.ksh
cp -av $DUMMY_PATH/Duplicate_Checker.ksh $SH_PATH/Duplicate_Checker.ksh
cp -av $DUMMY_PATH/Special_Cases.ksh $SH_PATH/Special_Cases.ksh

echo " Deactivation Completed"

exit 0



