/****Script Name	  : WD_Employee.sql
****Description   : Incremental data load for WD_Employee.sql
****/
\timing
\set ON_ERROR_STOP on

CREATE LOCAL TEMP TABLE Start_Time_Tmp ON COMMIT PRESERVE ROWS AS select sysdate st from dual;

/* Inserting values into the Audit table  */

INSERT INTO swt_rpt_stg.FAST_LD_AUDT
 (
       SUBJECT_AREA
      ,TBL_NM
      ,LD_DT
      ,START_DT_TIME
      ,END_DT_TIME
      ,SRC_REC_CNT
      ,TGT_REC_CNT
      ,COMPLTN_STAT
      )
  select 'WORKDAY','WD_Employee',sysdate::date,sysdate,null,(select count(*) from "swt_rpt_stg"."WD_Employee") ,null,'N';

Commit;  

CREATE LOCAL TEMP TABLE WD_Employee_stg_Tmp ON COMMIT PRESERVE ROWS AS
(
SELECT DISTINCT *,(RUNDATE ||' ' || RUNTIME):: timestamp as Updated_Date FROM swt_rpt_stg.WD_Employee)
SEGMENTED BY HASH(EXTERNALID,Updated_Date) ALL NODES;

CREATE LOCAL TEMP TABLE WD_Employee_base_Tmp ON COMMIT PRESERVE ROWS AS
(
SELECT DISTINCT EXTERNALID,(RUNDATE ||' ' || RUNTIME):: timestamp as Updated_Date FROM swt_rpt_base.WD_Employee)
SEGMENTED BY HASH(EXTERNALID,Updated_Date) ALL NODES;


CREATE LOCAL TEMP TABLE WD_Employee_stg_Tmp_Key ON COMMIT PRESERVE ROWS AS
(
SELECT EXTERNALID, max(Updated_Date) as Updated_Date FROM WD_Employee_stg_Tmp group by EXTERNALID )
SEGMENTED BY HASH(EXTERNALID,Updated_Date) ALL NODES;


/* Inserting deleted records into the Historical Table */

insert /*+DIRECT*/ into swt_rpt_stg.WD_Employee_Hist
(
EMAIL,
ENTITYID,
EXTERNALID,
FIRSTNAME,
MIDDLENAME,
LASTNAME,
ISINACTIVE,
OFFICEPHONE,
TITLE,
LEGACY_COSTCENTER,
SUBSIDIARY,
CUSTOMRECORD_CSEG_HPE_BUSAREA,
DEPARTMENT,
CSEG_HPE_COSTCENTER,
ACCOUNT,
CUSTBODY_CSEGCSEG_HPE_FNAREA,
CSEG_HPE_PROFIT_CTR,
CUSTENTITY_ASIAN_NAME1,
CUSTENTITY_ASIAN_NAME2,
SUPERVISOR_ID,
CURRENCY_CD,
HOME_PHONE,
REG_TEMP,
FULL_PART_TIME,
JOBCODE,
JOBTITLE,
FTE,
DEPTID,
HP_BUS_UNIT_DESCR,
HP_BUS_ORGN_ACR,
HP_BUS_ORGN_DN,
HP_BUS_REGION_ACR,
HP_BUS_REGION_NM,
HP_BUS_SECTOR_CD,
HP_BUS_SECTOR_DN,
PER_STATUS,
RUNDATE,
RUNTIME,
MANAGER_EMAIL,
HP_MGR_NAME,
HP_MGR_BUS_UNIT,
LH_SUBREG_CD,
LH_SUBREG_DESC,
LD_DT,
SWT_INS_DT
,d_source
)
select 
EMAIL,
ENTITYID,
EXTERNALID,
FIRSTNAME,
MIDDLENAME,
LASTNAME,
ISINACTIVE,
OFFICEPHONE,
TITLE,
LEGACY_COSTCENTER,
SUBSIDIARY,
CUSTOMRECORD_CSEG_HPE_BUSAREA,
DEPARTMENT,
CSEG_HPE_COSTCENTER,
ACCOUNT,
CUSTBODY_CSEGCSEG_HPE_FNAREA,
CSEG_HPE_PROFIT_CTR,
CUSTENTITY_ASIAN_NAME1,
CUSTENTITY_ASIAN_NAME2,
SUPERVISOR_ID,
CURRENCY_CD,
HOME_PHONE,
REG_TEMP,
FULL_PART_TIME,
JOBCODE,
JOBTITLE,
FTE,
DEPTID,
HP_BUS_UNIT_DESCR,
HP_BUS_ORGN_ACR,
HP_BUS_ORGN_DN,
HP_BUS_REGION_ACR,
HP_BUS_REGION_NM,
HP_BUS_SECTOR_CD,
HP_BUS_SECTOR_DN,
PER_STATUS,
RUNDATE,
RUNTIME,
MANAGER_EMAIL,
HP_MGR_NAME,
HP_MGR_BUS_UNIT,
LH_SUBREG_CD,
LH_SUBREG_DESC,
SYSDATE AS LD_DT,
SWT_INS_DT
,'base'

FROM "swt_rpt_base".WD_Employee WHERE EXTERNALID in
(SELECT STG.EXTERNALID FROM WD_Employee_stg_Tmp_Key STG JOIN WD_Employee_base_Tmp
ON STG.EXTERNALID = WD_Employee_base_Tmp.EXTERNALID AND STG.Updated_Date >= WD_Employee_base_Tmp.Updated_Date);





/* Deleting seven days data from current date in the Historical Table */  

delete /*+DIRECT*/ from "swt_rpt_stg"."WD_Employee_Hist"  where LD_DT::date <= TIMESTAMPADD(DAY,-7,sysdate)::date;


/* Incremental VSQL script for loading data from Stage to Base */


DELETE /*+DIRECT*/ FROM "swt_rpt_base".WD_Employee WHERE EXTERNALID in
(SELECT STG.EXTERNALID FROM WD_Employee_stg_Tmp_Key STG JOIN WD_Employee_base_Tmp
ON STG.EXTERNALID = WD_Employee_base_Tmp.EXTERNALID AND STG.Updated_Date >= WD_Employee_base_Tmp.Updated_Date);


INSERT /*+DIRECT*/ INTO "swt_rpt_base".WD_Employee
(
EMAIL,
ENTITYID,
EXTERNALID,
FIRSTNAME,
MIDDLENAME,
LASTNAME,
ISINACTIVE,
OFFICEPHONE,
TITLE,
LEGACY_COSTCENTER,
SUBSIDIARY,
CUSTOMRECORD_CSEG_HPE_BUSAREA,
DEPARTMENT,
CSEG_HPE_COSTCENTER,
ACCOUNT,
CUSTBODY_CSEGCSEG_HPE_FNAREA,
CSEG_HPE_PROFIT_CTR,
CUSTENTITY_ASIAN_NAME1,
CUSTENTITY_ASIAN_NAME2,
SUPERVISOR_ID,
CURRENCY_CD,
HOME_PHONE,
REG_TEMP,
FULL_PART_TIME,
JOBCODE,
JOBTITLE,
FTE,
DEPTID,
HP_BUS_UNIT_DESCR,
HP_BUS_ORGN_ACR,
HP_BUS_ORGN_DN,
HP_BUS_REGION_ACR,
HP_BUS_REGION_NM,
HP_BUS_SECTOR_CD,
HP_BUS_SECTOR_DN,
PER_STATUS,
RUNDATE,
RUNTIME,
MANAGER_EMAIL,
HP_MGR_NAME,
HP_MGR_BUS_UNIT,
LH_SUBREG_CD,
LH_SUBREG_DESC,
SWT_INS_DT
)
SELECT
DISTINCT 
EMAIL,
ENTITYID,
WD_Employee_stg_Tmp.EXTERNALID,
FIRSTNAME,
MIDDLENAME,
LASTNAME,
ISINACTIVE,
OFFICEPHONE,
TITLE,
LEGACY_COSTCENTER,
SUBSIDIARY,
CUSTOMRECORD_CSEG_HPE_BUSAREA,
DEPARTMENT,
CSEG_HPE_COSTCENTER,
ACCOUNT,
CUSTBODY_CSEGCSEG_HPE_FNAREA,
CSEG_HPE_PROFIT_CTR,
CUSTENTITY_ASIAN_NAME1,
CUSTENTITY_ASIAN_NAME2,
SUPERVISOR_ID,
CURRENCY_CD,
HOME_PHONE,
REG_TEMP,
FULL_PART_TIME,
JOBCODE,
JOBTITLE,
FTE,
DEPTID,
HP_BUS_UNIT_DESCR,
HP_BUS_ORGN_ACR,
HP_BUS_ORGN_DN,
HP_BUS_REGION_ACR,
HP_BUS_REGION_NM,
HP_BUS_SECTOR_CD,
HP_BUS_SECTOR_DN,
PER_STATUS,
RUNDATE,
RUNTIME,
MANAGER_EMAIL,
HP_MGR_NAME,
HP_MGR_BUS_UNIT,
LH_SUBREG_CD,
LH_SUBREG_DESC,
SYSDATE
FROM WD_Employee_stg_Tmp JOIN WD_Employee_stg_Tmp_Key ON WD_Employee_stg_Tmp.EXTERNALID= WD_Employee_stg_Tmp_Key.EXTERNALID AND WD_Employee_stg_Tmp.Updated_Date=WD_Employee_stg_Tmp_Key.Updated_Date
WHERE NOT EXISTS
(SELECT 1 FROM "swt_rpt_base".WD_Employee BASE
WHERE WD_Employee_stg_Tmp.EXTERNALID = BASE.EXTERNALID);

		
/*
DELETE FROM swt_rpt_stg.FAST_LD_AUDT where SUBJECT_AREA = 'WORKDAY' and
TBL_NM = 'WD_Employee' and
COMPLTN_STAT = 'N' and
LD_DT=sysdate::date and 
SEQ_ID = (select max(SEQ_ID) from swt_rpt_stg.FAST_LD_AUDT where  SUBJECT_AREA = 'WORKDAY' and  TBL_NM = 'WD_Employee' and  COMPLTN_STAT = 'N');
*/

INSERT INTO swt_rpt_stg.FAST_LD_AUDT
(
SUBJECT_AREA
,TBL_NM
,LD_DT
,START_DT_TIME
,END_DT_TIME
,SRC_REC_CNT
,TGT_REC_CNT
,COMPLTN_STAT
)
select 'WORKDAY','WD_Employee',sysdate::date,(select st from Start_Time_Tmp),sysdate,(select count(*) from "swt_rpt_stg"."WD_Employee") ,(select count(*) from swt_rpt_base.WD_Employee where SWT_INS_DT::date = sysdate::date),'Y';

Commit;

SELECT DO_TM_TASK('mergeout', 'swt_rpt_base.WD_Employee');
SELECT DO_TM_TASK('mergeout', 'swt_rpt_stg.WD_Employee_Hist');
SELECT DO_TM_TASK('mergeout', 'swt_rpt_stg.FAST_LD_AUDT');
select ANALYZE_STATISTICS('swt_rpt_base.WD_Employee');

INSERT /*+DIRECT*/ INTO "swt_rpt_stg".WD_Employee_Hist SELECT * from "swt_rpt_stg".WD_Employee;
COMMIT;
TRUNCATE TABLE swt_rpt_stg.WD_Employee;


