/*******
**** Script Name	  : NS_Customers.sql
****Description   : Incremental data load for NS_Customers
****/

/* Setting timing on**/
\timing
/**SET SESSION AUTOCOMMIT TO OFF;**/

\set ON_ERROR_STOP on

CREATE LOCAL TEMP TABLE Start_Time_Tmp ON COMMIT PRESERVE ROWS AS select count(*) count, sysdate st from "swt_rpt_stg"."NS_Customers";

/* Inserting values into Audit table  */

INSERT INTO swt_rpt_stg.FAST_LD_AUDT
(
SUBJECT_AREA
,TBL_NM
,LD_DT
,START_DT_TIME
,END_DT_TIME
,SRC_REC_CNT
,TGT_REC_CNT
,COMPLTN_STAT
)
select 'NETSUITE','NS_Customers',sysdate::date,sysdate,null,(select count from Start_Time_Tmp) ,null,'N';

Commit;

INSERT /*+DIRECT*/ INTO "swt_rpt_stg".NS_Customers_Hist SELECT * from "swt_rpt_stg".NS_Customers;

CREATE LOCAL TEMP TABLE duplicates_Customers ON COMMIT PRESERVE ROWS AS 
select max(auto_id) as auto_id,customer_id from swt_rpt_stg.NS_Customers where customer_id in(
select customer_id from swt_rpt_stg.NS_Customers
group by customer_id,last_modified_date having count(1)>1)
group by customer_id;


delete from swt_rpt_stg.NS_Customers  where exists(
select 1 from duplicates_Customers t2 where swt_rpt_stg.NS_Customers.customer_id=t2.customer_id and swt_rpt_stg.NS_Customers.auto_id<t2.auto_id);

COMMIT;

CREATE LOCAL TEMP TABLE NS_Customers_stg_Tmp ON COMMIT PRESERVE ROWS AS
(
SELECT DISTINCT * FROM swt_rpt_stg.NS_Customers)
SEGMENTED BY HASH(customer_id,last_modified_date) ALL NODES;

TRUNCATE TABLE swt_rpt_stg.NS_Customers;

CREATE LOCAL TEMP TABLE NS_Customers_base_Tmp ON COMMIT PRESERVE ROWS AS
(
SELECT DISTINCT customer_id,last_modified_date FROM swt_rpt_base.NS_Customers)
SEGMENTED BY HASH(customer_id,last_modified_date) ALL NODES;


CREATE LOCAL TEMP TABLE NS_Customers_stg_Tmp_Key ON COMMIT PRESERVE ROWS AS
(
SELECT customer_id, max(last_modified_date) as last_modified_date FROM NS_Customers_stg_Tmp group by customer_id)
SEGMENTED BY HASH(customer_id,last_modified_date) ALL NODES;





/* Inserting Stage table data into Historical Table */

insert /*+DIRECT*/ into swt_rpt_stg.NS_Customers_Hist
(
accountnumber
,alcohol_recipient_type
,allow_task_time_for_allocation
,altemail
,alternate_contact_id
,altphone
,amount_complete
,billaddress
,billing_rate_card_id
,billing_schedule_id
,billing_schedule_type
,billing_transaction_type
,calculated_end
,category_0
,city
,comments
,companyname
,consol_days_overdue
,consol_deposit_balance
,consol_deposit_balance_foreign
,consol_openbalance
,consol_openbalance_foreign
,consol_unbilled_orders
,consol_unbilled_orders_foreign
,converted_to_contact_id
,converted_to_id
,cost_estimate
,country
,create_date
,credithold
,creditlimit
,currency_id
,customer_extid
,customer_id
,customer_type_id
,date_closed
,date_convsersion
,date_first_order
,date_first_sale
,date_gross_lead
,date_last_modified
,date_last_order
,date_last_sale
,date_lead
,date_prospect
,days_overdue
,default_order_priority
,default_receivables_account_id
,deposit_balance
,deposit_balance_foreign
,email
,expected_close
,fax
,first_sale_period_id
,first_visit
,firstname
,forecast_based_on_allocations
,full_name
,home_phone
,is_exempt_time
,is_explicit_conversion
,is_job
,is_limit_time_to_assignees
,is_person
,is_productive_time
,is_project_completely_billed
,is_utilized_time
,isemailhtml
,isemailpdf
,isinactive
,istaxable
,job_end
,job_start
,job_type_id
,labor_budget_from_allocations
,language_id
,last_modified_date
,last_sale_period_id
,last_visit
,lastname
,lead_source_id
,line1
,line2
,line3
,loginaccess
,middlename
,mobile_phone
,multiple_price_id
,name
,openbalance
,openbalance_foreign
,parent_id
,partner_id
,payment_terms_id
,phone
,primary_contact_id
,print_on_check_as
,probability
,project_expense_type_id
,projected_end
,referrer
,reminderdays
,renewal
,represents_subsidiary_id
,resalenumber
,rev_rec_forecast_rule_id
,rev_rec_forecast_template
,revenue_estimate
,sales_rep_id
,sales_territory_id
,salutation
,ship_complete
,shipaddress
,state
,status
,status_descr
,status_probability
,status_read_only
,subsidiary_id
,tax_item_id
,third_party_acct
,third_party_carrier
,third_party_country
,third_party_zip_code
,top_level_parent_id
,unbilled_orders
,unbilled_orders_foreign
,url
,use_calculated_billing_budget
,use_calculated_cost_budget
,use_percent_complete_override
,web_lead
,zipcode
,account_name
,actual_cost_migration
,ariba_network_id
,ariba_system_id
,asian_name_1st
,asian_name_2nd
,bank_account_currency_id
,bank_account_number
,bank_address_1
,bank_address_2
,bank_city
,bank_country_id
,bank_name
,bank_routingswift_code
,bank_routing_number
,bank_state
,bank_zip
,baseline_cost
,baseline_hours
,baseline_revenue
,bic
,bmc_cumulus_pmo_user
,bulstat_number
,business_area_id
,central_bank_id
,check_bill
,client_principal_id
,cumulative__completed
,customer_fiscal_representativ
,customer_fiscal_representati_0
,customer_fiscal_representati_1
,customer_fiscal_representati_2
,customer_fiscal_representati_3
,customer_subsidiary_sub_code
,default_transaction_type_id
,delivery_manager_id
,dic
,domestic_parent_duns_
,domestic_parent_name
,duns_
,duplicate_cost_types
,duplicate_dashboard_settings
,duplicate_expense_policy
,duplicate_invoice_layout_sett
,duplicate_issues
,duplicate_loaded_costs
,duplicate_notification_settin
,duplicate_phase_and_task_cust
,duplicate_project_approvers
,duplicate_project_autobill_se
,duplicate_project_billing_rul
,duplicate_project_budget
,duplicate_project_pricing
,duplicate_recognition_autorun
,duplicate_revenue_recognition
,dwo_cost_budget
,estimated_actual_cost
,estimate_at_completion_eac
,expected_order_close_dwo
,export_to_openair
,fte
,functional_area_id
,global_parent_duns_
,global_parent_name
,custom_legal_name
,ico
,identifier_type
,identifier_value
,immediate_parent_duns_
,immediate_parent_name
,individual_bill_payment
,intermediary_bank
,intermediary_bic
,is_engagement
,je_approval_routing_id
,je_approver_id
,kyriba_entity_name
,last_sales_activity
,lcci_id
,lsa_link
,lsa_link_name
,mru_id
,national_identification
,ns_actual_cost_calculation
,openair_create_project_worksp
,openair_employee_is_ns_purcha
,openair_export_error
,openair_internal_id
,openair_map_exp__rep__to_pare
,openair_map_exp__rep__to_vend
,openair_opportunity_id
,openair_parent_vendor_id
,openair_percent_complete_over
,openair_project_currency_id
,openair_project_rate_card_id
,openair_project_stage_id
,openair_project_template_id
,openair_sfa_id
,openair_user_currency
,openair_user_or_vendor_id
,openair_user_tax_nexus_type_id
,parent_customer_id
,payment_hold
,payment_method_id
,physical_work_location
,pmo_toolkit_user
,prepaid
,procurement_organization_id
,profit_center_id
,project_billing_type_id
,project_category_id
,project_id
,project_program_id
,project_revenue_type_id
,project_type_id
,proj_functional_area_id
,proj_lcci_id
,proj_profit_center_id
,reason_for_hold
,remittance_purpose_code
,resource_type_id
,source_system_id
,statutory_bank_payment_code
,tax_contact_first_name
,tax_contact_id
,tax_contact_last_name
,tax_contact_middle_name
,vat_registration_no
,vsoe_customer_type_id
,business_style_id
,ctc
,default_wt_code_id
,is_vat_id
,philhealth
,edi
,einvoicing
,email_0
,print
,project_cmt_id
,project_manager_id
,project_market_offering_id
,project_region_id
,project_service_offering_id
,account_timezone
,cmt_1_id
,cmt_2_id
,corporate_status_id
,country_iso_code_id
,english_name
,federal
,federal_tax_id
,forecast_charge_run_on_demand
,industry_segment_id
,industry_vertical_id
,language_iso_code
,person_type_id
,po_required
,primary_city_area_nonlatin
,private_0
,project_type_labor_costing_id
,receipts_required
,region_id
,sled
,state_tax_id
,tin
,ACCOUNT_NAME_NONLATIN
,COUNTRY_GROUP
,ECO_ID
,EDOCUMENT_PACKAGE_ID
,FINANCE_MANAGER_ID
,JOB_CODE
,JOB_LEVEL
,OPENAIR_PROGPROJ_STAGE_ID
,SENDER_EMAIL_DOMAIN
,USE_SENDER_EMAIL_LIST
,nibs_billing_entity_id
,LD_DT
,SWT_INS_DT
,d_source
,SWT_Ins_Date_Backup
)
select
accountnumber
,alcohol_recipient_type
,allow_task_time_for_allocation
,altemail
,alternate_contact_id
,altphone
,amount_complete
,billaddress
,billing_rate_card_id
,billing_schedule_id
,billing_schedule_type
,billing_transaction_type
,calculated_end
,category_0
,city
,comments
,companyname
,consol_days_overdue
,consol_deposit_balance
,consol_deposit_balance_foreign
,consol_openbalance
,consol_openbalance_foreign
,consol_unbilled_orders
,consol_unbilled_orders_foreign
,converted_to_contact_id
,converted_to_id
,cost_estimate
,country
,create_date
,credithold
,creditlimit
,currency_id
,customer_extid
,customer_id
,customer_type_id
,date_closed
,date_convsersion
,date_first_order
,date_first_sale
,date_gross_lead
,date_last_modified
,date_last_order
,date_last_sale
,date_lead
,date_prospect
,days_overdue
,default_order_priority
,default_receivables_account_id
,deposit_balance
,deposit_balance_foreign
,email
,expected_close
,fax
,first_sale_period_id
,first_visit
,firstname
,forecast_based_on_allocations
,full_name
,home_phone
,is_exempt_time
,is_explicit_conversion
,is_job
,is_limit_time_to_assignees
,is_person
,is_productive_time
,is_project_completely_billed
,is_utilized_time
,isemailhtml
,isemailpdf
,isinactive
,istaxable
,job_end
,job_start
,job_type_id
,labor_budget_from_allocations
,language_id
,last_modified_date
,last_sale_period_id
,last_visit
,lastname
,lead_source_id
,line1
,line2
,line3
,loginaccess
,middlename
,mobile_phone
,multiple_price_id
,name
,openbalance
,openbalance_foreign
,parent_id
,partner_id
,payment_terms_id
,phone
,primary_contact_id
,print_on_check_as
,probability
,project_expense_type_id
,projected_end
,referrer
,reminderdays
,renewal
,represents_subsidiary_id
,resalenumber
,rev_rec_forecast_rule_id
,rev_rec_forecast_template
,revenue_estimate
,sales_rep_id
,sales_territory_id
,salutation
,ship_complete
,shipaddress
,state
,status
,status_descr
,status_probability
,status_read_only
,subsidiary_id
,tax_item_id
,third_party_acct
,third_party_carrier
,third_party_country
,third_party_zip_code
,top_level_parent_id
,unbilled_orders
,unbilled_orders_foreign
,url
,use_calculated_billing_budget
,use_calculated_cost_budget
,use_percent_complete_override
,web_lead
,zipcode
,account_name
,actual_cost_migration
,ariba_network_id
,ariba_system_id
,asian_name_1st
,asian_name_2nd
,bank_account_currency_id
,bank_account_number
,bank_address_1
,bank_address_2
,bank_city
,bank_country_id
,bank_name
,bank_routingswift_code
,bank_routing_number
,bank_state
,bank_zip
,baseline_cost
,baseline_hours
,baseline_revenue
,bic
,bmc_cumulus_pmo_user
,bulstat_number
,business_area_id
,central_bank_id
,check_bill
,client_principal_id
,cumulative__completed
,customer_fiscal_representativ
,customer_fiscal_representati_0
,customer_fiscal_representati_1
,customer_fiscal_representati_2
,customer_fiscal_representati_3
,customer_subsidiary_sub_code
,default_transaction_type_id
,delivery_manager_id
,dic
,domestic_parent_duns_
,domestic_parent_name
,duns_
,duplicate_cost_types
,duplicate_dashboard_settings
,duplicate_expense_policy
,duplicate_invoice_layout_sett
,duplicate_issues
,duplicate_loaded_costs
,duplicate_notification_settin
,duplicate_phase_and_task_cust
,duplicate_project_approvers
,duplicate_project_autobill_se
,duplicate_project_billing_rul
,duplicate_project_budget
,duplicate_project_pricing
,duplicate_recognition_autorun
,duplicate_revenue_recognition
,dwo_cost_budget
,estimated_actual_cost
,estimate_at_completion_eac
,expected_order_close_dwo
,export_to_openair
,fte
,functional_area_id
,global_parent_duns_
,global_parent_name
,custom_legal_name
,ico
,identifier_type
,identifier_value
,immediate_parent_duns_
,immediate_parent_name
,individual_bill_payment
,intermediary_bank
,intermediary_bic
,is_engagement
,je_approval_routing_id
,je_approver_id
,kyriba_entity_name
,last_sales_activity
,lcci_id
,lsa_link
,lsa_link_name
,mru_id
,national_identification
,ns_actual_cost_calculation
,openair_create_project_worksp
,openair_employee_is_ns_purcha
,openair_export_error
,openair_internal_id
,openair_map_exp__rep__to_pare
,openair_map_exp__rep__to_vend
,openair_opportunity_id
,openair_parent_vendor_id
,openair_percent_complete_over
,openair_project_currency_id
,openair_project_rate_card_id
,openair_project_stage_id
,openair_project_template_id
,openair_sfa_id
,openair_user_currency
,openair_user_or_vendor_id
,openair_user_tax_nexus_type_id
,parent_customer_id
,payment_hold
,payment_method_id
,physical_work_location
,pmo_toolkit_user
,prepaid
,procurement_organization_id
,profit_center_id
,project_billing_type_id
,project_category_id
,project_id
,project_program_id
,project_revenue_type_id
,project_type_id
,proj_functional_area_id
,proj_lcci_id
,proj_profit_center_id
,reason_for_hold
,remittance_purpose_code
,resource_type_id
,source_system_id
,statutory_bank_payment_code
,tax_contact_first_name
,tax_contact_id
,tax_contact_last_name
,tax_contact_middle_name
,vat_registration_no
,vsoe_customer_type_id
,business_style_id
,ctc
,default_wt_code_id
,is_vat_id
,philhealth
,edi
,einvoicing
,email_0
,print
,project_cmt_id
,project_manager_id
,project_market_offering_id
,project_region_id
,project_service_offering_id
,account_timezone
,cmt_1_id
,cmt_2_id
,corporate_status_id
,country_iso_code_id
,english_name
,federal
,federal_tax_id
,forecast_charge_run_on_demand
,industry_segment_id
,industry_vertical_id
,language_iso_code
,person_type_id
,po_required
,primary_city_area_nonlatin
,private_0
,project_type_labor_costing_id
,receipts_required
,region_id
,sled
,state_tax_id
,tin
,ACCOUNT_NAME_NONLATIN
,COUNTRY_GROUP
,ECO_ID
,EDOCUMENT_PACKAGE_ID
,FINANCE_MANAGER_ID
,JOB_CODE
,JOB_LEVEL
,OPENAIR_PROGPROJ_STAGE_ID
,SENDER_EMAIL_DOMAIN
,USE_SENDER_EMAIL_LIST
,nibs_billing_entity_id
,SYSDATE AS LD_DT
,SWT_INS_DT
,'base'
,SWT_Ins_Date_Backup
FROM "swt_rpt_base".NS_Customers WHERE customer_id in 
(SELECT STG.customer_id FROM NS_Customers_stg_Tmp_Key STG JOIN NS_Customers_base_Tmp
ON STG.customer_id = NS_Customers_base_Tmp.customer_id AND STG.last_modified_date >= NS_Customers_base_Tmp.last_modified_date);



/* Deleting before seven days data from current date in the Historical Table */

delete /*+DIRECT*/ from "swt_rpt_stg"."NS_Customers_Hist"  where LD_DT::date <= TIMESTAMPADD(DAY,-7,sysdate)::date;



/* Incremental VSQL script for loading data from Stage to Base */


DELETE /*+DIRECT*/ FROM "swt_rpt_base".NS_Customers WHERE customer_id in 
(SELECT STG.customer_id FROM NS_Customers_stg_Tmp_Key STG JOIN NS_Customers_base_Tmp
ON STG.customer_id = NS_Customers_base_Tmp.customer_id AND STG.last_modified_date >= NS_Customers_base_Tmp.last_modified_date);

INSERT /*+DIRECT*/ INTO "swt_rpt_base".NS_Customers
(
accountnumber
,alcohol_recipient_type
,allow_task_time_for_allocation
,altemail
,alternate_contact_id
,altphone
,amount_complete
,billaddress
,billing_rate_card_id
,billing_schedule_id
,billing_schedule_type
,billing_transaction_type
,calculated_end
,category_0
,city
,comments
,companyname
,consol_days_overdue
,consol_deposit_balance
,consol_deposit_balance_foreign
,consol_openbalance
,consol_openbalance_foreign
,consol_unbilled_orders
,consol_unbilled_orders_foreign
,converted_to_contact_id
,converted_to_id
,cost_estimate
,country
,create_date
,credithold
,creditlimit
,currency_id
,customer_extid
,customer_id
,customer_type_id
,date_closed
,date_convsersion
,date_first_order
,date_first_sale
,date_gross_lead
,date_last_modified
,date_last_order
,date_last_sale
,date_lead
,date_prospect
,days_overdue
,default_order_priority
,default_receivables_account_id
,deposit_balance
,deposit_balance_foreign
,email
,expected_close
,fax
,first_sale_period_id
,first_visit
,firstname
,forecast_based_on_allocations
,full_name
,home_phone
,is_exempt_time
,is_explicit_conversion
,is_job
,is_limit_time_to_assignees
,is_person
,is_productive_time
,is_project_completely_billed
,is_utilized_time
,isemailhtml
,isemailpdf
,isinactive
,istaxable
,job_end
,job_start
,job_type_id
,labor_budget_from_allocations
,language_id
,last_modified_date
,last_sale_period_id
,last_visit
,lastname
,lead_source_id
,line1
,line2
,line3
,loginaccess
,middlename
,mobile_phone
,multiple_price_id
,name
,openbalance
,openbalance_foreign
,parent_id
,partner_id
,payment_terms_id
,phone
,primary_contact_id
,print_on_check_as
,probability
,project_expense_type_id
,projected_end
,referrer
,reminderdays
,renewal
,represents_subsidiary_id
,resalenumber
,rev_rec_forecast_rule_id
,rev_rec_forecast_template
,revenue_estimate
,sales_rep_id
,sales_territory_id
,salutation
,ship_complete
,shipaddress
,state
,status
,status_descr
,status_probability
,status_read_only
,subsidiary_id
,tax_item_id
,third_party_acct
,third_party_carrier
,third_party_country
,third_party_zip_code
,top_level_parent_id
,unbilled_orders
,unbilled_orders_foreign
,url
,use_calculated_billing_budget
,use_calculated_cost_budget
,use_percent_complete_override
,web_lead
,zipcode
,account_name
,actual_cost_migration
,ariba_network_id
,ariba_system_id
,asian_name_1st
,asian_name_2nd
,bank_account_currency_id
,bank_account_number
,bank_address_1
,bank_address_2
,bank_city
,bank_country_id
,bank_name
,bank_routingswift_code
,bank_routing_number
,bank_state
,bank_zip
,baseline_cost
,baseline_hours
,baseline_revenue
,bic
,bmc_cumulus_pmo_user
,bulstat_number
,business_area_id
,central_bank_id
,check_bill
,client_principal_id
,cumulative__completed
,customer_fiscal_representativ
,customer_fiscal_representati_0
,customer_fiscal_representati_1
,customer_fiscal_representati_2
,customer_fiscal_representati_3
,customer_subsidiary_sub_code
,default_transaction_type_id
,delivery_manager_id
,dic
,domestic_parent_duns_
,domestic_parent_name
,duns_
,duplicate_cost_types
,duplicate_dashboard_settings
,duplicate_expense_policy
,duplicate_invoice_layout_sett
,duplicate_issues
,duplicate_loaded_costs
,duplicate_notification_settin
,duplicate_phase_and_task_cust
,duplicate_project_approvers
,duplicate_project_autobill_se
,duplicate_project_billing_rul
,duplicate_project_budget
,duplicate_project_pricing
,duplicate_recognition_autorun
,duplicate_revenue_recognition
,dwo_cost_budget
,estimated_actual_cost
,estimate_at_completion_eac
,expected_order_close_dwo
,export_to_openair
,fte
,functional_area_id
,global_parent_duns_
,global_parent_name
,custom_legal_name
,ico
,identifier_type
,identifier_value
,immediate_parent_duns_
,immediate_parent_name
,individual_bill_payment
,intermediary_bank
,intermediary_bic
,is_engagement
,je_approval_routing_id
,je_approver_id
,kyriba_entity_name
,last_sales_activity
,lcci_id
,lsa_link
,lsa_link_name
,mru_id
,national_identification
,ns_actual_cost_calculation
,openair_create_project_worksp
,openair_employee_is_ns_purcha
,openair_export_error
,openair_internal_id
,openair_map_exp__rep__to_pare
,openair_map_exp__rep__to_vend
,openair_opportunity_id
,openair_parent_vendor_id
,openair_percent_complete_over
,openair_project_currency_id
,openair_project_rate_card_id
,openair_project_stage_id
,openair_project_template_id
,openair_sfa_id
,openair_user_currency
,openair_user_or_vendor_id
,openair_user_tax_nexus_type_id
,parent_customer_id
,payment_hold
,payment_method_id
,physical_work_location
,pmo_toolkit_user
,prepaid
,procurement_organization_id
,profit_center_id
,project_billing_type_id
,project_category_id
,project_id
,project_program_id
,project_revenue_type_id
,project_type_id
,proj_functional_area_id
,proj_lcci_id
,proj_profit_center_id
,reason_for_hold
,remittance_purpose_code
,resource_type_id
,source_system_id
,statutory_bank_payment_code
,tax_contact_first_name
,tax_contact_id
,tax_contact_last_name
,tax_contact_middle_name
,vat_registration_no
,vsoe_customer_type_id
,business_style_id
,ctc
,default_wt_code_id
,is_vat_id
,philhealth
,edi
,einvoicing
,email_0
,print
,project_cmt_id
,project_manager_id
,project_market_offering_id
,project_region_id
,project_service_offering_id
,account_timezone
,cmt_1_id
,cmt_2_id
,corporate_status_id
,country_iso_code_id
,english_name
,federal
,federal_tax_id
,forecast_charge_run_on_demand
,industry_segment_id
,industry_vertical_id
,language_iso_code
,person_type_id
,po_required
,primary_city_area_nonlatin
,private_0
,project_type_labor_costing_id
,receipts_required
,region_id
,sled
,state_tax_id
,tin
,ACCOUNT_NAME_NONLATIN
,COUNTRY_GROUP
,ECO_ID
,EDOCUMENT_PACKAGE_ID
,FINANCE_MANAGER_ID
,JOB_CODE
,JOB_LEVEL
,OPENAIR_PROGPROJ_STAGE_ID
,SENDER_EMAIL_DOMAIN
,USE_SENDER_EMAIL_LIST
,nibs_billing_entity_id
,SWT_INS_DT
,SWT_Ins_Date_Backup
)
SELECT DISTINCT
accountnumber
,alcohol_recipient_type
,allow_task_time_for_allocation
,altemail
,alternate_contact_id
,altphone
,amount_complete
,billaddress
,billing_rate_card_id
,billing_schedule_id
,billing_schedule_type
,billing_transaction_type
,calculated_end
,category_0
,city
,comments
,companyname
,consol_days_overdue
,consol_deposit_balance
,consol_deposit_balance_foreign
,consol_openbalance
,consol_openbalance_foreign
,consol_unbilled_orders
,consol_unbilled_orders_foreign
,converted_to_contact_id
,converted_to_id
,cost_estimate
,country
,create_date
,credithold
,creditlimit
,currency_id
,customer_extid
,NS_Customers_stg_Tmp.customer_id
,customer_type_id
,date_closed
,date_convsersion
,date_first_order
,date_first_sale
,date_gross_lead
,date_last_modified
,date_last_order
,date_last_sale
,date_lead
,date_prospect
,days_overdue
,default_order_priority
,default_receivables_account_id
,deposit_balance
,deposit_balance_foreign
,email
,expected_close
,fax
,first_sale_period_id
,first_visit
,firstname
,forecast_based_on_allocations
,full_name
,home_phone
,is_exempt_time
,is_explicit_conversion
,is_job
,is_limit_time_to_assignees
,is_person
,is_productive_time
,is_project_completely_billed
,is_utilized_time
,isemailhtml
,isemailpdf
,isinactive
,istaxable
,job_end
,job_start
,job_type_id
,labor_budget_from_allocations
,language_id
,NS_Customers_stg_Tmp.last_modified_date
,last_sale_period_id
,last_visit
,lastname
,lead_source_id
,line1
,line2
,line3
,loginaccess
,middlename
,mobile_phone
,multiple_price_id
,name
,openbalance
,openbalance_foreign
,parent_id
,partner_id
,payment_terms_id
,phone
,primary_contact_id
,print_on_check_as
,probability
,project_expense_type_id
,projected_end
,referrer
,reminderdays
,renewal
,represents_subsidiary_id
,resalenumber
,rev_rec_forecast_rule_id
,rev_rec_forecast_template
,revenue_estimate
,sales_rep_id
,sales_territory_id
,salutation
,ship_complete
,shipaddress
,state
,status
,status_descr
,status_probability
,status_read_only
,subsidiary_id
,tax_item_id
,third_party_acct
,third_party_carrier
,third_party_country
,third_party_zip_code
,top_level_parent_id
,unbilled_orders
,unbilled_orders_foreign
,url
,use_calculated_billing_budget
,use_calculated_cost_budget
,use_percent_complete_override
,web_lead
,zipcode
,account_name
,actual_cost_migration
,ariba_network_id
,ariba_system_id
,asian_name_1st
,asian_name_2nd
,bank_account_currency_id
,bank_account_number
,bank_address_1
,bank_address_2
,bank_city
,bank_country_id
,bank_name
,bank_routingswift_code
,bank_routing_number
,bank_state
,bank_zip
,baseline_cost
,baseline_hours
,baseline_revenue
,bic
,bmc_cumulus_pmo_user
,bulstat_number
,business_area_id
,central_bank_id
,check_bill
,client_principal_id
,cumulative__completed
,customer_fiscal_representativ
,customer_fiscal_representati_0
,customer_fiscal_representati_1
,customer_fiscal_representati_2
,customer_fiscal_representati_3
,customer_subsidiary_sub_code
,default_transaction_type_id
,delivery_manager_id
,dic
,domestic_parent_duns_
,domestic_parent_name
,duns_
,duplicate_cost_types
,duplicate_dashboard_settings
,duplicate_expense_policy
,duplicate_invoice_layout_sett
,duplicate_issues
,duplicate_loaded_costs
,duplicate_notification_settin
,duplicate_phase_and_task_cust
,duplicate_project_approvers
,duplicate_project_autobill_se
,duplicate_project_billing_rul
,duplicate_project_budget
,duplicate_project_pricing
,duplicate_recognition_autorun
,duplicate_revenue_recognition
,dwo_cost_budget
,estimated_actual_cost
,estimate_at_completion_eac
,expected_order_close_dwo
,export_to_openair
,fte
,functional_area_id
,global_parent_duns_
,global_parent_name
,custom_legal_name
,ico
,identifier_type
,identifier_value
,immediate_parent_duns_
,immediate_parent_name
,individual_bill_payment
,intermediary_bank
,intermediary_bic
,is_engagement
,je_approval_routing_id
,je_approver_id
,kyriba_entity_name
,last_sales_activity
,lcci_id
,lsa_link
,lsa_link_name
,mru_id
,national_identification
,ns_actual_cost_calculation
,openair_create_project_worksp
,openair_employee_is_ns_purcha
,openair_export_error
,openair_internal_id
,openair_map_exp__rep__to_pare
,openair_map_exp__rep__to_vend
,openair_opportunity_id
,openair_parent_vendor_id
,openair_percent_complete_over
,openair_project_currency_id
,openair_project_rate_card_id
,openair_project_stage_id
,openair_project_template_id
,openair_sfa_id
,openair_user_currency
,openair_user_or_vendor_id
,openair_user_tax_nexus_type_id
,parent_customer_id
,payment_hold
,payment_method_id
,physical_work_location
,pmo_toolkit_user
,prepaid
,procurement_organization_id
,profit_center_id
,project_billing_type_id
,project_category_id
,project_id
,project_program_id
,project_revenue_type_id
,project_type_id
,proj_functional_area_id
,proj_lcci_id
,proj_profit_center_id
,reason_for_hold
,remittance_purpose_code
,resource_type_id
,source_system_id
,statutory_bank_payment_code
,tax_contact_first_name
,tax_contact_id
,tax_contact_last_name
,tax_contact_middle_name
,vat_registration_no
,vsoe_customer_type_id
,business_style_id
,ctc
,default_wt_code_id
,is_vat_id
,philhealth
,edi
,einvoicing
,email_0
,print
,project_cmt_id
,project_manager_id
,project_market_offering_id
,project_region_id
,project_service_offering_id
,account_timezone
,cmt_1_id
,cmt_2_id
,corporate_status_id
,country_iso_code_id
,english_name
,federal
,federal_tax_id
,forecast_charge_run_on_demand
,industry_segment_id
,industry_vertical_id
,language_iso_code
,person_type_id
,po_required
,primary_city_area_nonlatin
,private_0
,project_type_labor_costing_id
,receipts_required
,region_id
,sled
,state_tax_id
,tin
,ACCOUNT_NAME_NONLATIN
,COUNTRY_GROUP
,ECO_ID
,EDOCUMENT_PACKAGE_ID
,FINANCE_MANAGER_ID
,JOB_CODE
,JOB_LEVEL
,OPENAIR_PROGPROJ_STAGE_ID
,SENDER_EMAIL_DOMAIN
,USE_SENDER_EMAIL_LIST
,nibs_billing_entity_id
,sysdate as SWT_INS_DT
,sysdate as SWT_Ins_Date_Backup
FROM NS_Customers_stg_Tmp JOIN NS_Customers_stg_Tmp_Key ON NS_Customers_stg_Tmp.customer_id= NS_Customers_stg_Tmp_Key.customer_id AND NS_Customers_stg_Tmp.last_modified_date=NS_Customers_stg_Tmp_Key.last_modified_date
WHERE NOT EXISTS
(SELECT 1 FROM "swt_rpt_base".NS_Customers BASE
WHERE NS_Customers_stg_Tmp.customer_id = BASE.customer_id);

COMMIT;

/* Inserting new audit entry with all stats */

INSERT INTO swt_rpt_stg.FAST_LD_AUDT
(
SUBJECT_AREA
,TBL_NM
,LD_DT
,START_DT_TIME
,END_DT_TIME
,SRC_REC_CNT
,TGT_REC_CNT
,COMPLTN_STAT
)
select 'NETSUITE','NS_Customers',sysdate::date,(select st from Start_Time_Tmp),sysdate,(select count from Start_Time_Tmp) ,(select count(*) from swt_rpt_base.NS_Customers where SWT_INS_DT::date = sysdate::date),'Y';

Commit;

-->>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
CREATE LOCAL TEMP TABLE Start_Time_Tmp_Id ON COMMIT PRESERVE ROWS AS select count(*) count, sysdate st from swt_rpt_stg.NS_Customers_Id;

/* Inserting values into Audit table for ID table */

INSERT INTO swt_rpt_stg.FAST_LD_AUDT
(
SUBJECT_AREA
,TBL_NM
,LD_DT
,START_DT_TIME
,END_DT_TIME
,SRC_REC_CNT
,TGT_REC_CNT
,COMPLTN_STAT
)
select 'NETSUITE','NS_Customers_Id',sysdate::date,sysdate,null,(select count from Start_Time_Tmp_Id) ,null,'N';

Commit;

INSERT /*+DIRECT*/ INTO swt_rpt_base.NS_Customers_ID
( customer_id,
SWT_INS_DT
)
SELECT
customer_id,
SYSDATE
FROM swt_rpt_stg.NS_Customers_ID;


CREATE LOCAL TEMP TABLE NS_Customers_base_deleted ON COMMIT PRESERVE ROWS AS
(
SELECT DISTINCT * FROM swt_rpt_base.NS_Customers where Is_Deleted <> 'true' and customer_id not in ( select distinct customer_id from swt_rpt_stg.NS_Customers_Id))
SEGMENTED BY HASH(customer_id) ALL NODES;

DELETE /*+DIRECT*/ FROM swt_rpt_base.NS_Customers where Is_Deleted <> 'true' and customer_id  in ( select distinct customer_id from NS_Customers_base_deleted);


INSERT /*+DIRECT*/ INTO swt_rpt_base.NS_Customers_Deleted_Ids
( customer_id,
SWT_INS_DT,
status
)
SELECT
customer_id,
SYSDATE,
'deleted'
FROM NS_Customers_base_deleted;


INSERT /*+DIRECT*/ INTO swt_rpt_base.NS_Customers
(
accountnumber,
alcohol_recipient_type,
allow_task_time_for_allocation,
altemail,
alternate_contact_id,
altphone,
amount_complete,
billaddress,
billing_rate_card_id,
billing_schedule_id,
billing_schedule_type,
billing_transaction_type,
calculated_end,
category_0,
city,
comments,
companyname,
consol_days_overdue,
consol_deposit_balance,
consol_deposit_balance_foreign,
consol_openbalance,
consol_openbalance_foreign,
consol_unbilled_orders,
consol_unbilled_orders_foreign,
converted_to_contact_id,
converted_to_id,
cost_estimate,
country,
create_date,
credithold,
creditlimit,
currency_id,
customer_extid,
customer_id,
customer_type_id,
date_closed,
date_convsersion,
date_first_order,
date_first_sale,
date_gross_lead,
date_last_modified,
date_last_order,
date_last_sale,
date_lead,
date_prospect,
days_overdue,
default_order_priority,
default_receivables_account_id,
deposit_balance,
deposit_balance_foreign,
email,
expected_close,
fax,
first_sale_period_id,
first_visit,
firstname,
forecast_based_on_allocations,
full_name,
home_phone,
is_exempt_time,
is_explicit_conversion,
is_job,
is_limit_time_to_assignees,
is_person,
is_productive_time,
is_project_completely_billed,
is_utilized_time,
isemailhtml,
isemailpdf,
isinactive,
istaxable,
job_end,
job_start,
job_type_id,
labor_budget_from_allocations,
language_id,
last_modified_date,
last_sale_period_id,
last_visit,
lastname,
lead_source_id,
line1,
line2,
line3,
loginaccess,
middlename,
mobile_phone,
multiple_price_id,
name,
openbalance,
openbalance_foreign,
parent_id,
partner_id,
payment_terms_id,
phone,
primary_contact_id,
print_on_check_as,
probability,
project_expense_type_id,
projected_end,
referrer,
reminderdays,
renewal,
represents_subsidiary_id,
resalenumber,
rev_rec_forecast_rule_id,
rev_rec_forecast_template,
revenue_estimate,
sales_rep_id,
sales_territory_id,
salutation,
ship_complete,
shipaddress,
state,
status,
status_descr,
status_probability,
status_read_only,
subsidiary_id,
tax_item_id,
third_party_acct,
third_party_carrier,
third_party_country,
third_party_zip_code,
top_level_parent_id,
unbilled_orders,
unbilled_orders_foreign,
url,
use_calculated_billing_budget,
use_calculated_cost_budget,
use_percent_complete_override,
web_lead,
zipcode,
account_name,
actual_cost_migration,
ariba_network_id,
ariba_system_id,
asian_name_1st,
asian_name_2nd,
bank_account_currency_id,
bank_account_number,
bank_address_1,
bank_address_2,
bank_city,
bank_country_id,
bank_name,
bank_routingswift_code,
bank_routing_number,
bank_state,
bank_zip,
baseline_cost,
baseline_hours,
baseline_revenue,
bic,
bmc_cumulus_pmo_user,
bulstat_number,
business_area_id,
central_bank_id,
check_bill,
client_principal_id,
cumulative__completed,
customer_fiscal_representativ,
customer_fiscal_representati_0,
customer_fiscal_representati_1,
customer_fiscal_representati_2,
customer_fiscal_representati_3,
customer_subsidiary_sub_code,
default_transaction_type_id,
delivery_manager_id,
dic,
domestic_parent_duns_,
domestic_parent_name,
duns_,
duplicate_cost_types,
duplicate_dashboard_settings,
duplicate_expense_policy,
duplicate_invoice_layout_sett,
duplicate_issues,
duplicate_loaded_costs,
duplicate_notification_settin,
duplicate_phase_and_task_cust,
duplicate_project_approvers,
duplicate_project_autobill_se,
duplicate_project_billing_rul,
duplicate_project_budget,
duplicate_project_pricing,
duplicate_recognition_autorun,
duplicate_revenue_recognition,
dwo_cost_budget,
estimated_actual_cost,
estimate_at_completion_eac,
expected_order_close_dwo,
export_to_openair,
fte,
functional_area_id,
global_parent_duns_,
global_parent_name,
custom_legal_name,
ico,
identifier_type,
identifier_value,
immediate_parent_duns_,
immediate_parent_name,
individual_bill_payment,
intermediary_bank,
intermediary_bic,
is_engagement,
je_approval_routing_id,
je_approver_id,
kyriba_entity_name,
last_sales_activity,
lcci_id,
lsa_link,
lsa_link_name,
mru_id,
national_identification,
ns_actual_cost_calculation,
openair_create_project_worksp,
openair_employee_is_ns_purcha,
openair_export_error,
openair_internal_id,
openair_map_exp__rep__to_pare,
openair_map_exp__rep__to_vend,
openair_opportunity_id,
openair_parent_vendor_id,
openair_percent_complete_over,
openair_project_currency_id,
openair_project_rate_card_id,
openair_project_stage_id,
openair_project_template_id,
openair_sfa_id,
openair_user_currency,
openair_user_or_vendor_id,
openair_user_tax_nexus_type_id,
parent_customer_id,
payment_hold,
payment_method_id,
physical_work_location,
pmo_toolkit_user,
prepaid,
procurement_organization_id,
profit_center_id,
project_billing_type_id,
project_category_id,
project_id,
project_program_id,
project_revenue_type_id,
project_type_id,
proj_functional_area_id,
proj_lcci_id,
proj_profit_center_id,
reason_for_hold,
remittance_purpose_code,
resource_type_id,
source_system_id,
statutory_bank_payment_code,
tax_contact_first_name,
tax_contact_id,
tax_contact_last_name,
tax_contact_middle_name,
vat_registration_no,
vsoe_customer_type_id,
business_style_id,
ctc,
default_wt_code_id,
is_vat_id,
philhealth,
edi,
einvoicing,
email_0,
print,
project_cmt_id,
project_manager_id,
project_market_offering_id,
project_region_id,
project_service_offering_id,
tin,
account_timezone,
cmt_1_id,
cmt_2_id,
corporate_status_id,
country_iso_code_id,
english_name,
federal,
federal_tax_id,
forecast_charge_run_on_demand,
industry_segment_id,
industry_vertical_id,
language_iso_code,
person_type_id,
po_required,
primary_city_area_nonlatin,
private_0,
project_type_labor_costing_id,
receipts_required,
region_id,
sled,
state_tax_id,
SWT_INS_DT,
account_name_nonlatin,
country_group,
eco_id,
edocument_package_id,
finance_manager_id,
job_code,
job_level,
openair_progproj_stage_id,
sender_email_domain,
use_sender_email_list,
nibs_billing_entity_id,
Is_Deleted,
SWT_Ins_Date_Backup
)
SELECT 
accountnumber,
alcohol_recipient_type,
allow_task_time_for_allocation,
altemail,
alternate_contact_id,
altphone,
amount_complete,
billaddress,
billing_rate_card_id,
billing_schedule_id,
billing_schedule_type,
billing_transaction_type,
calculated_end,
category_0,
city,
comments,
companyname,
consol_days_overdue,
consol_deposit_balance,
consol_deposit_balance_foreign,
consol_openbalance,
consol_openbalance_foreign,
consol_unbilled_orders,
consol_unbilled_orders_foreign,
converted_to_contact_id,
converted_to_id,
cost_estimate,
country,
create_date,
credithold,
creditlimit,
currency_id,
customer_extid,
customer_id,
customer_type_id,
date_closed,
date_convsersion,
date_first_order,
date_first_sale,
date_gross_lead,
date_last_modified,
date_last_order,
date_last_sale,
date_lead,
date_prospect,
days_overdue,
default_order_priority,
default_receivables_account_id,
deposit_balance,
deposit_balance_foreign,
email,
expected_close,
fax,
first_sale_period_id,
first_visit,
firstname,
forecast_based_on_allocations,
full_name,
home_phone,
is_exempt_time,
is_explicit_conversion,
is_job,
is_limit_time_to_assignees,
is_person,
is_productive_time,
is_project_completely_billed,
is_utilized_time,
isemailhtml,
isemailpdf,
isinactive,
istaxable,
job_end,
job_start,
job_type_id,
labor_budget_from_allocations,
language_id,
last_modified_date,
last_sale_period_id,
last_visit,
lastname,
lead_source_id,
line1,
line2,
line3,
loginaccess,
middlename,
mobile_phone,
multiple_price_id,
name,
openbalance,
openbalance_foreign,
parent_id,
partner_id,
payment_terms_id,
phone,
primary_contact_id,
print_on_check_as,
probability,
project_expense_type_id,
projected_end,
referrer,
reminderdays,
renewal,
represents_subsidiary_id,
resalenumber,
rev_rec_forecast_rule_id,
rev_rec_forecast_template,
revenue_estimate,
sales_rep_id,
sales_territory_id,
salutation,
ship_complete,
shipaddress,
state,
status,
status_descr,
status_probability,
status_read_only,
subsidiary_id,
tax_item_id,
third_party_acct,
third_party_carrier,
third_party_country,
third_party_zip_code,
top_level_parent_id,
unbilled_orders,
unbilled_orders_foreign,
url,
use_calculated_billing_budget,
use_calculated_cost_budget,
use_percent_complete_override,
web_lead,
zipcode,
account_name,
actual_cost_migration,
ariba_network_id,
ariba_system_id,
asian_name_1st,
asian_name_2nd,
bank_account_currency_id,
bank_account_number,
bank_address_1,
bank_address_2,
bank_city,
bank_country_id,
bank_name,
bank_routingswift_code,
bank_routing_number,
bank_state,
bank_zip,
baseline_cost,
baseline_hours,
baseline_revenue,
bic,
bmc_cumulus_pmo_user,
bulstat_number,
business_area_id,
central_bank_id,
check_bill,
client_principal_id,
cumulative__completed,
customer_fiscal_representativ,
customer_fiscal_representati_0,
customer_fiscal_representati_1,
customer_fiscal_representati_2,
customer_fiscal_representati_3,
customer_subsidiary_sub_code,
default_transaction_type_id,
delivery_manager_id,
dic,
domestic_parent_duns_,
domestic_parent_name,
duns_,
duplicate_cost_types,
duplicate_dashboard_settings,
duplicate_expense_policy,
duplicate_invoice_layout_sett,
duplicate_issues,
duplicate_loaded_costs,
duplicate_notification_settin,
duplicate_phase_and_task_cust,
duplicate_project_approvers,
duplicate_project_autobill_se,
duplicate_project_billing_rul,
duplicate_project_budget,
duplicate_project_pricing,
duplicate_recognition_autorun,
duplicate_revenue_recognition,
dwo_cost_budget,
estimated_actual_cost,
estimate_at_completion_eac,
expected_order_close_dwo,
export_to_openair,
fte,
functional_area_id,
global_parent_duns_,
global_parent_name,
custom_legal_name,
ico,
identifier_type,
identifier_value,
immediate_parent_duns_,
immediate_parent_name,
individual_bill_payment,
intermediary_bank,
intermediary_bic,
is_engagement,
je_approval_routing_id,
je_approver_id,
kyriba_entity_name,
last_sales_activity,
lcci_id,
lsa_link,
lsa_link_name,
mru_id,
national_identification,
ns_actual_cost_calculation,
openair_create_project_worksp,
openair_employee_is_ns_purcha,
openair_export_error,
openair_internal_id,
openair_map_exp__rep__to_pare,
openair_map_exp__rep__to_vend,
openair_opportunity_id,
openair_parent_vendor_id,
openair_percent_complete_over,
openair_project_currency_id,
openair_project_rate_card_id,
openair_project_stage_id,
openair_project_template_id,
openair_sfa_id,
openair_user_currency,
openair_user_or_vendor_id,
openair_user_tax_nexus_type_id,
parent_customer_id,
payment_hold,
payment_method_id,
physical_work_location,
pmo_toolkit_user,
prepaid,
procurement_organization_id,
profit_center_id,
project_billing_type_id,
project_category_id,
project_id,
project_program_id,
project_revenue_type_id,
project_type_id,
proj_functional_area_id,
proj_lcci_id,
proj_profit_center_id,
reason_for_hold,
remittance_purpose_code,
resource_type_id,
source_system_id,
statutory_bank_payment_code,
tax_contact_first_name,
tax_contact_id,
tax_contact_last_name,
tax_contact_middle_name,
vat_registration_no,
vsoe_customer_type_id,
business_style_id,
ctc,
default_wt_code_id,
is_vat_id,
philhealth,
edi,
einvoicing,
email_0,
print,
project_cmt_id,
project_manager_id,
project_market_offering_id,
project_region_id,
project_service_offering_id,
tin,
account_timezone,
cmt_1_id,
cmt_2_id,
corporate_status_id,
country_iso_code_id,
english_name,
federal,
federal_tax_id,
forecast_charge_run_on_demand,
industry_segment_id,
industry_vertical_id,
language_iso_code,
person_type_id,
po_required,
primary_city_area_nonlatin,
private_0,
project_type_labor_costing_id,
receipts_required,
region_id,
sled,
state_tax_id,
sysdate as SWT_INS_DT,
account_name_nonlatin,
country_group,
eco_id,
edocument_package_id,
finance_manager_id,
job_code,
job_level,
openair_progproj_stage_id,
sender_email_domain,
use_sender_email_list,
nibs_billing_entity_id
,'true'
,SWT_INS_DT
FROM NS_Customers_base_deleted;



CREATE LOCAL TEMP TABLE NS_Customers_base_active ON COMMIT PRESERVE ROWS AS
(
SELECT DISTINCT * FROM swt_rpt_base.NS_Customers where Is_Deleted ='true' and customer_id in ( select distinct customer_id from swt_rpt_stg.NS_Customers_Id))
SEGMENTED BY HASH(customer_id) ALL NODES;

DELETE /*+DIRECT*/ FROM swt_rpt_base.NS_Customers where Is_Deleted ='true' and customer_id in ( select distinct customer_id from NS_Customers_base_active );

INSERT /*+DIRECT*/ INTO swt_rpt_base.NS_Customers_Deleted_Ids
( customer_id,
SWT_INS_DT,
status
)
SELECT
customer_id,
SYSDATE,
'activated'
FROM NS_Customers_base_active;


INSERT /*+DIRECT*/ INTO swt_rpt_base.NS_Customers
(
accountnumber,
alcohol_recipient_type,
allow_task_time_for_allocation,
altemail,
alternate_contact_id,
altphone,
amount_complete,
billaddress,
billing_rate_card_id,
billing_schedule_id,
billing_schedule_type,
billing_transaction_type,
calculated_end,
category_0,
city,
comments,
companyname,
consol_days_overdue,
consol_deposit_balance,
consol_deposit_balance_foreign,
consol_openbalance,
consol_openbalance_foreign,
consol_unbilled_orders,
consol_unbilled_orders_foreign,
converted_to_contact_id,
converted_to_id,
cost_estimate,
country,
create_date,
credithold,
creditlimit,
currency_id,
customer_extid,
customer_id,
customer_type_id,
date_closed,
date_convsersion,
date_first_order,
date_first_sale,
date_gross_lead,
date_last_modified,
date_last_order,
date_last_sale,
date_lead,
date_prospect,
days_overdue,
default_order_priority,
default_receivables_account_id,
deposit_balance,
deposit_balance_foreign,
email,
expected_close,
fax,
first_sale_period_id,
first_visit,
firstname,
forecast_based_on_allocations,
full_name,
home_phone,
is_exempt_time,
is_explicit_conversion,
is_job,
is_limit_time_to_assignees,
is_person,
is_productive_time,
is_project_completely_billed,
is_utilized_time,
isemailhtml,
isemailpdf,
isinactive,
istaxable,
job_end,
job_start,
job_type_id,
labor_budget_from_allocations,
language_id,
last_modified_date,
last_sale_period_id,
last_visit,
lastname,
lead_source_id,
line1,
line2,
line3,
loginaccess,
middlename,
mobile_phone,
multiple_price_id,
name,
openbalance,
openbalance_foreign,
parent_id,
partner_id,
payment_terms_id,
phone,
primary_contact_id,
print_on_check_as,
probability,
project_expense_type_id,
projected_end,
referrer,
reminderdays,
renewal,
represents_subsidiary_id,
resalenumber,
rev_rec_forecast_rule_id,
rev_rec_forecast_template,
revenue_estimate,
sales_rep_id,
sales_territory_id,
salutation,
ship_complete,
shipaddress,
state,
status,
status_descr,
status_probability,
status_read_only,
subsidiary_id,
tax_item_id,
third_party_acct,
third_party_carrier,
third_party_country,
third_party_zip_code,
top_level_parent_id,
unbilled_orders,
unbilled_orders_foreign,
url,
use_calculated_billing_budget,
use_calculated_cost_budget,
use_percent_complete_override,
web_lead,
zipcode,
account_name,
actual_cost_migration,
ariba_network_id,
ariba_system_id,
asian_name_1st,
asian_name_2nd,
bank_account_currency_id,
bank_account_number,
bank_address_1,
bank_address_2,
bank_city,
bank_country_id,
bank_name,
bank_routingswift_code,
bank_routing_number,
bank_state,
bank_zip,
baseline_cost,
baseline_hours,
baseline_revenue,
bic,
bmc_cumulus_pmo_user,
bulstat_number,
business_area_id,
central_bank_id,
check_bill,
client_principal_id,
cumulative__completed,
customer_fiscal_representativ,
customer_fiscal_representati_0,
customer_fiscal_representati_1,
customer_fiscal_representati_2,
customer_fiscal_representati_3,
customer_subsidiary_sub_code,
default_transaction_type_id,
delivery_manager_id,
dic,
domestic_parent_duns_,
domestic_parent_name,
duns_,
duplicate_cost_types,
duplicate_dashboard_settings,
duplicate_expense_policy,
duplicate_invoice_layout_sett,
duplicate_issues,
duplicate_loaded_costs,
duplicate_notification_settin,
duplicate_phase_and_task_cust,
duplicate_project_approvers,
duplicate_project_autobill_se,
duplicate_project_billing_rul,
duplicate_project_budget,
duplicate_project_pricing,
duplicate_recognition_autorun,
duplicate_revenue_recognition,
dwo_cost_budget,
estimated_actual_cost,
estimate_at_completion_eac,
expected_order_close_dwo,
export_to_openair,
fte,
functional_area_id,
global_parent_duns_,
global_parent_name,
custom_legal_name,
ico,
identifier_type,
identifier_value,
immediate_parent_duns_,
immediate_parent_name,
individual_bill_payment,
intermediary_bank,
intermediary_bic,
is_engagement,
je_approval_routing_id,
je_approver_id,
kyriba_entity_name,
last_sales_activity,
lcci_id,
lsa_link,
lsa_link_name,
mru_id,
national_identification,
ns_actual_cost_calculation,
openair_create_project_worksp,
openair_employee_is_ns_purcha,
openair_export_error,
openair_internal_id,
openair_map_exp__rep__to_pare,
openair_map_exp__rep__to_vend,
openair_opportunity_id,
openair_parent_vendor_id,
openair_percent_complete_over,
openair_project_currency_id,
openair_project_rate_card_id,
openair_project_stage_id,
openair_project_template_id,
openair_sfa_id,
openair_user_currency,
openair_user_or_vendor_id,
openair_user_tax_nexus_type_id,
parent_customer_id,
payment_hold,
payment_method_id,
physical_work_location,
pmo_toolkit_user,
prepaid,
procurement_organization_id,
profit_center_id,
project_billing_type_id,
project_category_id,
project_id,
project_program_id,
project_revenue_type_id,
project_type_id,
proj_functional_area_id,
proj_lcci_id,
proj_profit_center_id,
reason_for_hold,
remittance_purpose_code,
resource_type_id,
source_system_id,
statutory_bank_payment_code,
tax_contact_first_name,
tax_contact_id,
tax_contact_last_name,
tax_contact_middle_name,
vat_registration_no,
vsoe_customer_type_id,
business_style_id,
ctc,
default_wt_code_id,
is_vat_id,
philhealth,
edi,
einvoicing,
email_0,
print,
project_cmt_id,
project_manager_id,
project_market_offering_id,
project_region_id,
project_service_offering_id,
tin,
account_timezone,
cmt_1_id,
cmt_2_id,
corporate_status_id,
country_iso_code_id,
english_name,
federal,
federal_tax_id,
forecast_charge_run_on_demand,
industry_segment_id,
industry_vertical_id,
language_iso_code,
person_type_id,
po_required,
primary_city_area_nonlatin,
private_0,
project_type_labor_costing_id,
receipts_required,
region_id,
sled,
state_tax_id,
SWT_INS_DT,
account_name_nonlatin,
country_group,
eco_id,
edocument_package_id,
finance_manager_id,
job_code,
job_level,
openair_progproj_stage_id,
sender_email_domain,
use_sender_email_list,
nibs_billing_entity_id,
Is_Deleted,
SWT_Ins_Date_Backup
)
SELECT 
accountnumber,
alcohol_recipient_type,
allow_task_time_for_allocation,
altemail,
alternate_contact_id,
altphone,
amount_complete,
billaddress,
billing_rate_card_id,
billing_schedule_id,
billing_schedule_type,
billing_transaction_type,
calculated_end,
category_0,
city,
comments,
companyname,
consol_days_overdue,
consol_deposit_balance,
consol_deposit_balance_foreign,
consol_openbalance,
consol_openbalance_foreign,
consol_unbilled_orders,
consol_unbilled_orders_foreign,
converted_to_contact_id,
converted_to_id,
cost_estimate,
country,
create_date,
credithold,
creditlimit,
currency_id,
customer_extid,
customer_id,
customer_type_id,
date_closed,
date_convsersion,
date_first_order,
date_first_sale,
date_gross_lead,
date_last_modified,
date_last_order,
date_last_sale,
date_lead,
date_prospect,
days_overdue,
default_order_priority,
default_receivables_account_id,
deposit_balance,
deposit_balance_foreign,
email,
expected_close,
fax,
first_sale_period_id,
first_visit,
firstname,
forecast_based_on_allocations,
full_name,
home_phone,
is_exempt_time,
is_explicit_conversion,
is_job,
is_limit_time_to_assignees,
is_person,
is_productive_time,
is_project_completely_billed,
is_utilized_time,
isemailhtml,
isemailpdf,
isinactive,
istaxable,
job_end,
job_start,
job_type_id,
labor_budget_from_allocations,
language_id,
last_modified_date,
last_sale_period_id,
last_visit,
lastname,
lead_source_id,
line1,
line2,
line3,
loginaccess,
middlename,
mobile_phone,
multiple_price_id,
name,
openbalance,
openbalance_foreign,
parent_id,
partner_id,
payment_terms_id,
phone,
primary_contact_id,
print_on_check_as,
probability,
project_expense_type_id,
projected_end,
referrer,
reminderdays,
renewal,
represents_subsidiary_id,
resalenumber,
rev_rec_forecast_rule_id,
rev_rec_forecast_template,
revenue_estimate,
sales_rep_id,
sales_territory_id,
salutation,
ship_complete,
shipaddress,
state,
status,
status_descr,
status_probability,
status_read_only,
subsidiary_id,
tax_item_id,
third_party_acct,
third_party_carrier,
third_party_country,
third_party_zip_code,
top_level_parent_id,
unbilled_orders,
unbilled_orders_foreign,
url,
use_calculated_billing_budget,
use_calculated_cost_budget,
use_percent_complete_override,
web_lead,
zipcode,
account_name,
actual_cost_migration,
ariba_network_id,
ariba_system_id,
asian_name_1st,
asian_name_2nd,
bank_account_currency_id,
bank_account_number,
bank_address_1,
bank_address_2,
bank_city,
bank_country_id,
bank_name,
bank_routingswift_code,
bank_routing_number,
bank_state,
bank_zip,
baseline_cost,
baseline_hours,
baseline_revenue,
bic,
bmc_cumulus_pmo_user,
bulstat_number,
business_area_id,
central_bank_id,
check_bill,
client_principal_id,
cumulative__completed,
customer_fiscal_representativ,
customer_fiscal_representati_0,
customer_fiscal_representati_1,
customer_fiscal_representati_2,
customer_fiscal_representati_3,
customer_subsidiary_sub_code,
default_transaction_type_id,
delivery_manager_id,
dic,
domestic_parent_duns_,
domestic_parent_name,
duns_,
duplicate_cost_types,
duplicate_dashboard_settings,
duplicate_expense_policy,
duplicate_invoice_layout_sett,
duplicate_issues,
duplicate_loaded_costs,
duplicate_notification_settin,
duplicate_phase_and_task_cust,
duplicate_project_approvers,
duplicate_project_autobill_se,
duplicate_project_billing_rul,
duplicate_project_budget,
duplicate_project_pricing,
duplicate_recognition_autorun,
duplicate_revenue_recognition,
dwo_cost_budget,
estimated_actual_cost,
estimate_at_completion_eac,
expected_order_close_dwo,
export_to_openair,
fte,
functional_area_id,
global_parent_duns_,
global_parent_name,
custom_legal_name,
ico,
identifier_type,
identifier_value,
immediate_parent_duns_,
immediate_parent_name,
individual_bill_payment,
intermediary_bank,
intermediary_bic,
is_engagement,
je_approval_routing_id,
je_approver_id,
kyriba_entity_name,
last_sales_activity,
lcci_id,
lsa_link,
lsa_link_name,
mru_id,
national_identification,
ns_actual_cost_calculation,
openair_create_project_worksp,
openair_employee_is_ns_purcha,
openair_export_error,
openair_internal_id,
openair_map_exp__rep__to_pare,
openair_map_exp__rep__to_vend,
openair_opportunity_id,
openair_parent_vendor_id,
openair_percent_complete_over,
openair_project_currency_id,
openair_project_rate_card_id,
openair_project_stage_id,
openair_project_template_id,
openair_sfa_id,
openair_user_currency,
openair_user_or_vendor_id,
openair_user_tax_nexus_type_id,
parent_customer_id,
payment_hold,
payment_method_id,
physical_work_location,
pmo_toolkit_user,
prepaid,
procurement_organization_id,
profit_center_id,
project_billing_type_id,
project_category_id,
project_id,
project_program_id,
project_revenue_type_id,
project_type_id,
proj_functional_area_id,
proj_lcci_id,
proj_profit_center_id,
reason_for_hold,
remittance_purpose_code,
resource_type_id,
source_system_id,
statutory_bank_payment_code,
tax_contact_first_name,
tax_contact_id,
tax_contact_last_name,
tax_contact_middle_name,
vat_registration_no,
vsoe_customer_type_id,
business_style_id,
ctc,
default_wt_code_id,
is_vat_id,
philhealth,
edi,
einvoicing,
email_0,
print,
project_cmt_id,
project_manager_id,
project_market_offering_id,
project_region_id,
project_service_offering_id,
tin,
account_timezone,
cmt_1_id,
cmt_2_id,
corporate_status_id,
country_iso_code_id,
english_name,
federal,
federal_tax_id,
forecast_charge_run_on_demand,
industry_segment_id,
industry_vertical_id,
language_iso_code,
person_type_id,
po_required,
primary_city_area_nonlatin,
private_0,
project_type_labor_costing_id,
receipts_required,
region_id,
sled,
state_tax_id,
sysdate as SWT_INS_DT,
account_name_nonlatin,
country_group,
eco_id,
edocument_package_id,
finance_manager_id,
job_code,
job_level,
openair_progproj_stage_id,
sender_email_domain,
use_sender_email_list,
nibs_billing_entity_id
,'false'
,SWT_INS_DT
FROM NS_Customers_base_active;


COMMIT;


/* Deleting partial audit entry */
/*
DELETE FROM swt_rpt_stg.FAST_LD_AUDT where SUBJECT_AREA = 'NETSUITE' and
TBL_NM = 'NS_Customers' and
COMPLTN_STAT = 'N' and
LD_DT=sysdate::date and 
SEQ_ID = (select max(SEQ_ID) from swt_rpt_stg.FAST_LD_AUDT where  SUBJECT_AREA = 'NETSUITE' and  TBL_NM = 'NS_Customers' and  COMPLTN_STAT = 'N');
*/

/* Inserting new audit entry with all stats */

INSERT INTO swt_rpt_stg.FAST_LD_AUDT
(
SUBJECT_AREA
,TBL_NM
,LD_DT
,START_DT_TIME
,END_DT_TIME
,SRC_REC_CNT
,TGT_REC_CNT
,COMPLTN_STAT
)
select 'NETSUITE','NS_Customers_Id',sysdate::date,(select st from Start_Time_Tmp_Id),sysdate,(select count from Start_Time_Tmp_Id) ,(select count(*) from swt_rpt_base.NS_Customers where SWT_INS_DT>=(select max(START_DT_TIME) from swt_rpt_stg.FAST_LD_AUDT where TBL_NM='NS_Customers_Id') and is_deleted='true'),'Y';

Commit;

SELECT DO_TM_TASK('mergeout', 'swt_rpt_base.NS_Customers');
SELECT DO_TM_TASK('mergeout', 'swt_rpt_stg.NS_Customers_Hist');
SELECT DO_TM_TASK('mergeout', 'swt_rpt_stg.FAST_LD_AUDT');
SELECT ANALYZE_STATISTICS('swt_rpt_base.NS_Customers');
SELECT ANALYZE_STATISTICS('swt_rpt_base.NS_Customers_deleted_IDS');
-->>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
TRUNCATE TABLE swt_rpt_stg.NS_Customers_Id;
delete /*+DIRECT*/ from "swt_rpt_base"."NS_Customers_Id"  where swt_ins_dt::date <= TIMESTAMPADD(DAY,-7,sysdate)::date;
commit;

--<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<





