/******
*******Script Name	  : NS_Entity.sql
****Description   : Incremental data load for NS_Entity
****/

/* Setting timing on**/
\timing
/**SET SESSION AUTOCOMMIT TO OFF;**/

\set ON_ERROR_STOP on

CREATE LOCAL TEMP TABLE Start_Time_Tmp ON COMMIT PRESERVE ROWS AS select count(*) count, sysdate st from swt_rpt_stg.NS_Entity;

/* Inserting values into Audit table  */

INSERT INTO swt_rpt_stg.FAST_LD_AUDT
(
SUBJECT_AREA
,TBL_NM
,LD_DT
,START_DT_TIME
,END_DT_TIME
,SRC_REC_CNT
,TGT_REC_CNT
,COMPLTN_STAT
)
select 'NETSUITE','NS_Entity',sysdate::date,sysdate,null,(select count from Start_Time_Tmp) ,null,'N';

Commit;

INSERT /*+DIRECT*/ INTO "swt_rpt_stg".NS_Entity_Hist SELECT * from "swt_rpt_stg".NS_Entity;

CREATE LOCAL TEMP TABLE duplicates_Entity ON COMMIT PRESERVE ROWS AS 
select max(auto_id) as auto_id,entity_id from swt_rpt_stg.NS_Entity where entity_id in(
select entity_id from swt_rpt_stg.NS_Entity
group by entity_id,date_last_modified having count(1)>1)
group by entity_id;

delete from swt_rpt_stg.NS_Entity  where exists(
select 1 from duplicates_Entity t2 where swt_rpt_stg.NS_Entity.entity_id=t2.entity_id and swt_rpt_stg.NS_Entity.auto_id<t2.auto_id);

COMMIT;

CREATE LOCAL TEMP TABLE NS_Entity_stg_Tmp ON COMMIT PRESERVE ROWS AS
(
SELECT DISTINCT * FROM swt_rpt_stg.NS_Entity)
SEGMENTED BY HASH(entity_id,date_last_modified) ALL NODES;

TRUNCATE TABLE swt_rpt_stg.NS_Entity;


CREATE LOCAL TEMP TABLE NS_Entity_base_Tmp ON COMMIT PRESERVE ROWS AS
(
SELECT DISTINCT entity_id,date_last_modified FROM swt_rpt_base.NS_Entity)
SEGMENTED BY HASH(entity_id,date_last_modified) ALL NODES;


CREATE LOCAL TEMP TABLE NS_Entity_stg_Tmp_Key ON COMMIT PRESERVE ROWS AS
(
SELECT entity_id, max(date_last_modified) as date_last_modified FROM NS_Entity_stg_Tmp group by entity_id)
SEGMENTED BY HASH(entity_id,date_last_modified) ALL NODES;





/* Inserting Stage table data into Historical Table */

insert /*+DIRECT*/ into swt_rpt_stg.NS_Entity_Hist
(
account_name
,actual_cost_migration
,address_one
,address_three
,address_two
,ariba_network_id
,ariba_system_id
,asian_name_1st
,asian_name_2nd
,bank_account_currency_id
,bank_account_number
,bank_address_1
,bank_address_2
,bank_city
,bank_country_id
,bank_name
,bank_routing_number
,bank_routingswift_code
,bank_state
,bank_zip
,baseline_cost
,baseline_hours
,baseline_revenue
,bic
,bmc_cumulus_pmo_user
,bulstat_number
,business_area_id
,business_style_id
,central_bank_id
,check_bill
,city
,client_principal_id
,country
,create_date
,ctc
,cumulative__completed
,customer_fiscal_representati_0
,customer_fiscal_representati_1
,customer_fiscal_representati_2
,customer_fiscal_representati_3
,customer_fiscal_representativ
,customer_subsidiary_sub_code
,date_last_modified
,default_transaction_type_id
,default_wt_code_id
,delivery_manager_id
,dic
,domestic_parent_duns_
,domestic_parent_name
,duns_
,duplicate_cost_types
,duplicate_dashboard_settings
,duplicate_expense_policy
,duplicate_invoice_layout_sett
,duplicate_issues
,duplicate_loaded_costs
,duplicate_notification_settin
,duplicate_phase_and_task_cust
,duplicate_project_approvers
,duplicate_project_autobill_se
,duplicate_project_billing_rul
,duplicate_project_budget
,duplicate_project_pricing
,duplicate_recognition_autorun
,duplicate_revenue_recognition
,dwo_cost_budget
,email
,entity_extid
,entity_id
,entity_type
,estimate_at_completion_eac
,estimated_actual_cost
,expected_order_close_dwo
,export_to_openair
,first_name
,fte
,full_name
,functional_area_id
,global_parent_duns_
,global_parent_name
,global_subscription_status
,custom_legal_name
,ico
,identifier_type
,identifier_value
,immediate_parent_duns_
,immediate_parent_name
,individual_bill_payment
,intermediary_bank
,intermediary_bic
,is_engagement
,is_inactive
,is_online_bill_pay
,is_unavailable
,is_vat_id
,je_approval_routing_id
,je_approver_id
,kyriba_entity_name
,last_modified_date
,last_name
,last_sales_activity
,lcci_id
,login_access
,lsa_link
,lsa_link_name
,middle_name
,mru_id
,name
,national_identification
,notes
,ns_actual_cost_calculation
,openair_create_project_worksp
,openair_employee_is_ns_purcha
,openair_export_error
,openair_internal_id
,openair_map_exp__rep__to_pare
,openair_map_exp__rep__to_vend
,openair_opportunity_id
,openair_parent_vendor_id
,openair_percent_complete_over
,openair_project_currency_id
,openair_project_rate_card_id
,openair_project_stage_id
,openair_project_template_id
,openair_sfa_id
,openair_user_currency
,openair_user_or_vendor_id
,openair_user_tax_nexus_type_id
,originator_id
,parent_customer_id
,parent_id
,payment_hold
,payment_method_id
,philhealth
,phone
,physical_work_location
,pmo_toolkit_user
,prepaid
,procurement_organization_id
,profit_center_id
,proj_functional_area_id
,proj_lcci_id
,proj_profit_center_id
,project_billing_type_id
,project_category_id
,project_id
,project_program_id
,project_revenue_type_id
,project_type_id
,reason_for_hold
,remittance_purpose_code
,resource_type_id
,salutation
,source_system_id
,state
,statutory_bank_payment_code
,subsidiary
,tax_contact_first_name
,tax_contact_id
,tax_contact_last_name
,tax_contact_middle_name
,tin
,unsubscribed
,vat_registration_no
,vsoe_customer_type_id
,account_timezone
,cmt_1_id
,cmt_2_id
,corporate_status_id
,country_iso_code_id
,edi
,einvoicing
,email_0
,english_name
,federal
,federal_tax_id
,industry_segment_id
,industry_vertical_id
,language_iso_code
,person_type_id
,po_required
,primary_city_area_nonlatin
,print
,private_0
,project_cmt_id
,project_manager_id
,project_market_offering_id
,project_region_id
,project_service_offering_id
,project_type_labor_costing_id
,receipts_required
,region_id
,sled
,state_tax_id
,zipcode
,ACCOUNT_NAME_NONLATIN
,COUNTRY_GROUP
,ECO_ID
,EDOCUMENT_PACKAGE_ID
,FINANCE_MANAGER_ID
,JOB_CODE
,JOB_LEVEL
,OPENAIR_PROGPROJ_STAGE_ID
,SENDER_EMAIL_DOMAIN
,USE_SENDER_EMAIL_LIST
,LD_DT
,SWT_INS_DT
,d_source
,SWT_Ins_Date_Backup
)
select
account_name
,actual_cost_migration
,address_one
,address_three
,address_two
,ariba_network_id
,ariba_system_id
,asian_name_1st
,asian_name_2nd
,bank_account_currency_id
,bank_account_number
,bank_address_1
,bank_address_2
,bank_city
,bank_country_id
,bank_name
,bank_routing_number
,bank_routingswift_code
,bank_state
,bank_zip
,baseline_cost
,baseline_hours
,baseline_revenue
,bic
,bmc_cumulus_pmo_user
,bulstat_number
,business_area_id
,business_style_id
,central_bank_id
,check_bill
,city
,client_principal_id
,country
,create_date
,ctc
,cumulative__completed
,customer_fiscal_representati_0
,customer_fiscal_representati_1
,customer_fiscal_representati_2
,customer_fiscal_representati_3
,customer_fiscal_representativ
,customer_subsidiary_sub_code
,date_last_modified
,default_transaction_type_id
,default_wt_code_id
,delivery_manager_id
,dic
,domestic_parent_duns_
,domestic_parent_name
,duns_
,duplicate_cost_types
,duplicate_dashboard_settings
,duplicate_expense_policy
,duplicate_invoice_layout_sett
,duplicate_issues
,duplicate_loaded_costs
,duplicate_notification_settin
,duplicate_phase_and_task_cust
,duplicate_project_approvers
,duplicate_project_autobill_se
,duplicate_project_billing_rul
,duplicate_project_budget
,duplicate_project_pricing
,duplicate_recognition_autorun
,duplicate_revenue_recognition
,dwo_cost_budget
,email
,entity_extid
,entity_id
,entity_type
,estimate_at_completion_eac
,estimated_actual_cost
,expected_order_close_dwo
,export_to_openair
,first_name
,fte
,full_name
,functional_area_id
,global_parent_duns_
,global_parent_name
,global_subscription_status
,custom_legal_name
,ico
,identifier_type
,identifier_value
,immediate_parent_duns_
,immediate_parent_name
,individual_bill_payment
,intermediary_bank
,intermediary_bic
,is_engagement
,is_inactive
,is_online_bill_pay
,is_unavailable
,is_vat_id
,je_approval_routing_id
,je_approver_id
,kyriba_entity_name
,last_modified_date
,last_name
,last_sales_activity
,lcci_id
,login_access
,lsa_link
,lsa_link_name
,middle_name
,mru_id
,name
,national_identification
,notes
,ns_actual_cost_calculation
,openair_create_project_worksp
,openair_employee_is_ns_purcha
,openair_export_error
,openair_internal_id
,openair_map_exp__rep__to_pare
,openair_map_exp__rep__to_vend
,openair_opportunity_id
,openair_parent_vendor_id
,openair_percent_complete_over
,openair_project_currency_id
,openair_project_rate_card_id
,openair_project_stage_id
,openair_project_template_id
,openair_sfa_id
,openair_user_currency
,openair_user_or_vendor_id
,openair_user_tax_nexus_type_id
,originator_id
,parent_customer_id
,parent_id
,payment_hold
,payment_method_id
,philhealth
,phone
,physical_work_location
,pmo_toolkit_user
,prepaid
,procurement_organization_id
,profit_center_id
,proj_functional_area_id
,proj_lcci_id
,proj_profit_center_id
,project_billing_type_id
,project_category_id
,project_id
,project_program_id
,project_revenue_type_id
,project_type_id
,reason_for_hold
,remittance_purpose_code
,resource_type_id
,salutation
,source_system_id
,state
,statutory_bank_payment_code
,subsidiary
,tax_contact_first_name
,tax_contact_id
,tax_contact_last_name
,tax_contact_middle_name
,tin
,unsubscribed
,vat_registration_no
,vsoe_customer_type_id
,account_timezone
,cmt_1_id
,cmt_2_id
,corporate_status_id
,country_iso_code_id
,edi
,einvoicing
,email_0
,english_name
,federal
,federal_tax_id
,industry_segment_id
,industry_vertical_id
,language_iso_code
,person_type_id
,po_required
,primary_city_area_nonlatin
,print
,private_0
,project_cmt_id
,project_manager_id
,project_market_offering_id
,project_region_id
,project_service_offering_id
,project_type_labor_costing_id
,receipts_required
,region_id
,sled
,state_tax_id
,zipcode
,ACCOUNT_NAME_NONLATIN
,COUNTRY_GROUP
,ECO_ID
,EDOCUMENT_PACKAGE_ID
,FINANCE_MANAGER_ID
,JOB_CODE
,JOB_LEVEL
,OPENAIR_PROGPROJ_STAGE_ID
,SENDER_EMAIL_DOMAIN
,USE_SENDER_EMAIL_LIST
,SYSDATE AS LD_DT
,SWT_INS_DT
,'base'
,SWT_Ins_Date_Backup
FROM "swt_rpt_base".NS_Entity WHERE entity_id in
(SELECT STG.entity_id FROM NS_Entity_stg_Tmp_Key STG JOIN NS_Entity_base_Tmp
ON STG.entity_id = NS_Entity_base_Tmp.entity_id AND STG.date_last_modified >= NS_Entity_base_Tmp.date_last_modified);



/* Deleting before seven days data from current date in the Historical Table */

delete /*+DIRECT*/ from "swt_rpt_stg"."NS_Entity_Hist"  where LD_DT::date <= TIMESTAMPADD(DAY,-7,sysdate)::date;



/* Incremental VSQL script for loading data from Stage to Base */


DELETE /*+DIRECT*/ FROM "swt_rpt_base".NS_Entity WHERE entity_id in
(SELECT STG.entity_id FROM NS_Entity_stg_Tmp_Key STG JOIN NS_Entity_base_Tmp
ON STG.entity_id = NS_Entity_base_Tmp.entity_id AND STG.date_last_modified >= NS_Entity_base_Tmp.date_last_modified);

INSERT /*+DIRECT*/ INTO "swt_rpt_base".NS_Entity
(
account_name
,actual_cost_migration
,address_one
,address_three
,address_two
,ariba_network_id
,ariba_system_id
,asian_name_1st
,asian_name_2nd
,bank_account_currency_id
,bank_account_number
,bank_address_1
,bank_address_2
,bank_city
,bank_country_id
,bank_name
,bank_routing_number
,bank_routingswift_code
,bank_state
,bank_zip
,baseline_cost
,baseline_hours
,baseline_revenue
,bic
,bmc_cumulus_pmo_user
,bulstat_number
,business_area_id
,business_style_id
,central_bank_id
,check_bill
,city
,client_principal_id
,country
,create_date
,ctc
,cumulative__completed
,customer_fiscal_representati_0
,customer_fiscal_representati_1
,customer_fiscal_representati_2
,customer_fiscal_representati_3
,customer_fiscal_representativ
,customer_subsidiary_sub_code
,date_last_modified
,default_transaction_type_id
,default_wt_code_id
,delivery_manager_id
,dic
,domestic_parent_duns_
,domestic_parent_name
,duns_
,duplicate_cost_types
,duplicate_dashboard_settings
,duplicate_expense_policy
,duplicate_invoice_layout_sett
,duplicate_issues
,duplicate_loaded_costs
,duplicate_notification_settin
,duplicate_phase_and_task_cust
,duplicate_project_approvers
,duplicate_project_autobill_se
,duplicate_project_billing_rul
,duplicate_project_budget
,duplicate_project_pricing
,duplicate_recognition_autorun
,duplicate_revenue_recognition
,dwo_cost_budget
,email
,entity_extid
,entity_id
,entity_type
,estimate_at_completion_eac
,estimated_actual_cost
,expected_order_close_dwo
,export_to_openair
,first_name
,fte
,full_name
,functional_area_id
,global_parent_duns_
,global_parent_name
,global_subscription_status
,custom_legal_name
,ico
,identifier_type
,identifier_value
,immediate_parent_duns_
,immediate_parent_name
,individual_bill_payment
,intermediary_bank
,intermediary_bic
,is_engagement
,is_inactive
,is_online_bill_pay
,is_unavailable
,is_vat_id
,je_approval_routing_id
,je_approver_id
,kyriba_entity_name
,last_modified_date
,last_name
,last_sales_activity
,lcci_id
,login_access
,lsa_link
,lsa_link_name
,middle_name
,mru_id
,name
,national_identification
,notes
,ns_actual_cost_calculation
,openair_create_project_worksp
,openair_employee_is_ns_purcha
,openair_export_error
,openair_internal_id
,openair_map_exp__rep__to_pare
,openair_map_exp__rep__to_vend
,openair_opportunity_id
,openair_parent_vendor_id
,openair_percent_complete_over
,openair_project_currency_id
,openair_project_rate_card_id
,openair_project_stage_id
,openair_project_template_id
,openair_sfa_id
,openair_user_currency
,openair_user_or_vendor_id
,openair_user_tax_nexus_type_id
,originator_id
,parent_customer_id
,parent_id
,payment_hold
,payment_method_id
,philhealth
,phone
,physical_work_location
,pmo_toolkit_user
,prepaid
,procurement_organization_id
,profit_center_id
,proj_functional_area_id
,proj_lcci_id
,proj_profit_center_id
,project_billing_type_id
,project_category_id
,project_id
,project_program_id
,project_revenue_type_id
,project_type_id
,reason_for_hold
,remittance_purpose_code
,resource_type_id
,salutation
,source_system_id
,state
,statutory_bank_payment_code
,subsidiary
,tax_contact_first_name
,tax_contact_id
,tax_contact_last_name
,tax_contact_middle_name
,tin
,unsubscribed
,vat_registration_no
,vsoe_customer_type_id
,account_timezone
,cmt_1_id
,cmt_2_id
,corporate_status_id
,country_iso_code_id
,edi
,einvoicing
,email_0
,english_name
,federal
,federal_tax_id
,industry_segment_id
,industry_vertical_id
,language_iso_code
,person_type_id
,po_required
,primary_city_area_nonlatin
,print
,private_0
,project_cmt_id
,project_manager_id
,project_market_offering_id
,project_region_id
,project_service_offering_id
,project_type_labor_costing_id
,receipts_required
,region_id
,sled
,state_tax_id
,zipcode
,ACCOUNT_NAME_NONLATIN
,COUNTRY_GROUP
,ECO_ID
,EDOCUMENT_PACKAGE_ID
,FINANCE_MANAGER_ID
,JOB_CODE
,JOB_LEVEL
,OPENAIR_PROGPROJ_STAGE_ID
,SENDER_EMAIL_DOMAIN
,USE_SENDER_EMAIL_LIST
,SWT_INS_DT
,SWT_Ins_Date_Backup
)
SELECT DISTINCT 
account_name
,actual_cost_migration
,address_one
,address_three
,address_two
,ariba_network_id
,ariba_system_id
,asian_name_1st
,asian_name_2nd
,bank_account_currency_id
,bank_account_number
,bank_address_1
,bank_address_2
,bank_city
,bank_country_id
,bank_name
,bank_routing_number
,bank_routingswift_code
,bank_state
,bank_zip
,baseline_cost
,baseline_hours
,baseline_revenue
,bic
,bmc_cumulus_pmo_user
,bulstat_number
,business_area_id
,business_style_id
,central_bank_id
,check_bill
,city
,client_principal_id
,country
,create_date
,ctc
,cumulative__completed
,customer_fiscal_representati_0
,customer_fiscal_representati_1
,customer_fiscal_representati_2
,customer_fiscal_representati_3
,customer_fiscal_representativ
,customer_subsidiary_sub_code
,NS_Entity_stg_Tmp.date_last_modified
,default_transaction_type_id
,default_wt_code_id
,delivery_manager_id
,dic
,domestic_parent_duns_
,domestic_parent_name
,duns_
,duplicate_cost_types
,duplicate_dashboard_settings
,duplicate_expense_policy
,duplicate_invoice_layout_sett
,duplicate_issues
,duplicate_loaded_costs
,duplicate_notification_settin
,duplicate_phase_and_task_cust
,duplicate_project_approvers
,duplicate_project_autobill_se
,duplicate_project_billing_rul
,duplicate_project_budget
,duplicate_project_pricing
,duplicate_recognition_autorun
,duplicate_revenue_recognition
,dwo_cost_budget
,email
,entity_extid
,NS_Entity_stg_Tmp.entity_id
,entity_type
,estimate_at_completion_eac
,estimated_actual_cost
,expected_order_close_dwo
,export_to_openair
,first_name
,fte
,full_name
,functional_area_id
,global_parent_duns_
,global_parent_name
,global_subscription_status
,custom_legal_name
,ico
,identifier_type
,identifier_value
,immediate_parent_duns_
,immediate_parent_name
,individual_bill_payment
,intermediary_bank
,intermediary_bic
,is_engagement
,is_inactive
,is_online_bill_pay
,is_unavailable
,is_vat_id
,je_approval_routing_id
,je_approver_id
,kyriba_entity_name
,last_modified_date
,last_name
,last_sales_activity
,lcci_id
,login_access
,lsa_link
,lsa_link_name
,middle_name
,mru_id
,name
,national_identification
,notes
,ns_actual_cost_calculation
,openair_create_project_worksp
,openair_employee_is_ns_purcha
,openair_export_error
,openair_internal_id
,openair_map_exp__rep__to_pare
,openair_map_exp__rep__to_vend
,openair_opportunity_id
,openair_parent_vendor_id
,openair_percent_complete_over
,openair_project_currency_id
,openair_project_rate_card_id
,openair_project_stage_id
,openair_project_template_id
,openair_sfa_id
,openair_user_currency
,openair_user_or_vendor_id
,openair_user_tax_nexus_type_id
,originator_id
,parent_customer_id
,parent_id
,payment_hold
,payment_method_id
,philhealth
,phone
,physical_work_location
,pmo_toolkit_user
,prepaid
,procurement_organization_id
,profit_center_id
,proj_functional_area_id
,proj_lcci_id
,proj_profit_center_id
,project_billing_type_id
,project_category_id
,project_id
,project_program_id
,project_revenue_type_id
,project_type_id
,reason_for_hold
,remittance_purpose_code
,resource_type_id
,salutation
,source_system_id
,state
,statutory_bank_payment_code
,subsidiary
,tax_contact_first_name
,tax_contact_id
,tax_contact_last_name
,tax_contact_middle_name
,tin
,unsubscribed
,vat_registration_no
,vsoe_customer_type_id
,account_timezone
,cmt_1_id
,cmt_2_id
,corporate_status_id
,country_iso_code_id
,edi
,einvoicing
,email_0
,english_name
,federal
,federal_tax_id
,industry_segment_id
,industry_vertical_id
,language_iso_code
,person_type_id
,po_required
,primary_city_area_nonlatin
,print
,private_0
,project_cmt_id
,project_manager_id
,project_market_offering_id
,project_region_id
,project_service_offering_id
,project_type_labor_costing_id
,receipts_required
,region_id
,sled
,state_tax_id
,zipcode
,ACCOUNT_NAME_NONLATIN
,COUNTRY_GROUP
,ECO_ID
,EDOCUMENT_PACKAGE_ID
,FINANCE_MANAGER_ID
,JOB_CODE
,JOB_LEVEL
,OPENAIR_PROGPROJ_STAGE_ID
,SENDER_EMAIL_DOMAIN
,USE_SENDER_EMAIL_LIST
,SYSDATE as SWT_INS_DT
,sysdate as SWT_Ins_Date_Backup
FROM NS_Entity_stg_Tmp JOIN NS_Entity_stg_Tmp_Key ON NS_Entity_stg_Tmp.entity_id= NS_Entity_stg_Tmp_Key.entity_id AND NS_Entity_stg_Tmp.date_last_modified=NS_Entity_stg_Tmp_Key.date_last_modified
WHERE NOT EXISTS
(SELECT 1 FROM "swt_rpt_base".NS_Entity BASE
WHERE NS_Entity_stg_Tmp.entity_id = BASE.entity_id);

COMMIT;

/* Inserting new audit entry with all stats */

INSERT INTO swt_rpt_stg.FAST_LD_AUDT
(
SUBJECT_AREA
,TBL_NM
,LD_DT
,START_DT_TIME
,END_DT_TIME
,SRC_REC_CNT
,TGT_REC_CNT
,COMPLTN_STAT
)
select 'NETSUITE','NS_Entity',sysdate::date,(select st from Start_Time_Tmp),sysdate,(select count from Start_Time_Tmp) ,(select count(*) from swt_rpt_base.NS_Entity where SWT_INS_DT::date = sysdate::date),'Y';

Commit;

-->>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

CREATE LOCAL TEMP TABLE Start_Time_Tmp_Id ON COMMIT PRESERVE ROWS AS select count(*) count, sysdate st from swt_rpt_stg.NS_Entity_Id;

/* Inserting values into Audit table for ID table */

INSERT INTO swt_rpt_stg.FAST_LD_AUDT
(
SUBJECT_AREA
,TBL_NM
,LD_DT
,START_DT_TIME
,END_DT_TIME
,SRC_REC_CNT
,TGT_REC_CNT
,COMPLTN_STAT
)
select 'NETSUITE','NS_Entity_Id',sysdate::date,sysdate,null,(select count from Start_Time_Tmp_Id) ,null,'N';

Commit;

INSERT /*+DIRECT*/ INTO swt_rpt_base.NS_Entity_ID
( entity_id,
SWT_INS_DT
)
SELECT
entity_id,
SYSDATE
FROM swt_rpt_stg.NS_Entity_ID;


CREATE LOCAL TEMP TABLE NS_Entity_base_deleted ON COMMIT PRESERVE ROWS AS
(
SELECT DISTINCT * FROM swt_rpt_base.NS_Entity where Is_Deleted <> 'true' and entity_id not in ( select distinct entity_id from swt_rpt_stg.NS_Entity_Id))
SEGMENTED BY HASH(entity_id) ALL NODES;

DELETE /*+DIRECT*/ FROM swt_rpt_base.NS_Entity where Is_Deleted <> 'true' and entity_id  in ( select distinct entity_id from NS_Entity_base_deleted );


INSERT /*+DIRECT*/ INTO swt_rpt_base.NS_Entity_Deleted_Ids
( entity_id,
SWT_INS_DT,
status
)
SELECT
entity_id,
SYSDATE,
'deleted'
FROM NS_Entity_base_deleted;


INSERT /*+DIRECT*/ INTO swt_rpt_base.NS_Entity
(
account_name,
actual_cost_migration,
address_one,
address_three,
address_two,
ariba_network_id,
ariba_system_id,
asian_name_1st,
asian_name_2nd,
bank_account_currency_id,
bank_account_number,
bank_address_1,
bank_address_2,
bank_city,
bank_country_id,
bank_name,
bank_routing_number,
bank_routingswift_code,
bank_state,
bank_zip,
baseline_cost,
baseline_hours,
baseline_revenue,
bic,
bmc_cumulus_pmo_user,
bulstat_number,
business_area_id,
business_style_id,
central_bank_id,
check_bill,
city,
client_principal_id,
country,
create_date,
ctc,
cumulative__completed,
customer_fiscal_representati_0,
customer_fiscal_representati_1,
customer_fiscal_representati_2,
customer_fiscal_representati_3,
customer_fiscal_representativ,
customer_subsidiary_sub_code,
date_last_modified,
default_transaction_type_id,
default_wt_code_id,
delivery_manager_id,
dic,
domestic_parent_duns_,
domestic_parent_name,
duns_,
duplicate_cost_types,
duplicate_dashboard_settings,
duplicate_expense_policy,
duplicate_invoice_layout_sett,
duplicate_issues,
duplicate_loaded_costs,
duplicate_notification_settin,
duplicate_phase_and_task_cust,
duplicate_project_approvers,
duplicate_project_autobill_se,
duplicate_project_billing_rul,
duplicate_project_budget,
duplicate_project_pricing,
duplicate_recognition_autorun,
duplicate_revenue_recognition,
dwo_cost_budget,
email,
entity_extid,
entity_id,
entity_type,
estimate_at_completion_eac,
estimated_actual_cost,
expected_order_close_dwo,
export_to_openair,
first_name,
fte,
full_name,
functional_area_id,
global_parent_duns_,
global_parent_name,
global_subscription_status,
custom_legal_name,
ico,
identifier_type,
identifier_value,
immediate_parent_duns_,
immediate_parent_name,
individual_bill_payment,
intermediary_bank,
intermediary_bic,
is_engagement,
is_inactive,
is_online_bill_pay,
is_unavailable,
is_vat_id,
je_approval_routing_id,
je_approver_id,
kyriba_entity_name,
last_modified_date,
last_name,
last_sales_activity,
lcci_id,
login_access,
lsa_link,
lsa_link_name,
middle_name,
mru_id,
name,
national_identification,
notes,
ns_actual_cost_calculation,
openair_create_project_worksp,
openair_employee_is_ns_purcha,
openair_export_error,
openair_internal_id,
openair_map_exp__rep__to_pare,
openair_map_exp__rep__to_vend,
openair_opportunity_id,
openair_parent_vendor_id,
openair_percent_complete_over,
openair_project_currency_id,
openair_project_rate_card_id,
openair_project_stage_id,
openair_project_template_id,
openair_sfa_id,
openair_user_currency,
openair_user_or_vendor_id,
openair_user_tax_nexus_type_id,
originator_id,
parent_customer_id,
parent_id,
payment_hold,
payment_method_id,
philhealth,
phone,
physical_work_location,
pmo_toolkit_user,
prepaid,
procurement_organization_id,
profit_center_id,
proj_functional_area_id,
proj_lcci_id,
proj_profit_center_id,
project_billing_type_id,
project_category_id,
project_id,
project_program_id,
project_revenue_type_id,
project_type_id,
reason_for_hold,
remittance_purpose_code,
resource_type_id,
salutation,
source_system_id,
state,
statutory_bank_payment_code,
subsidiary,
tax_contact_first_name,
tax_contact_id,
tax_contact_last_name,
tax_contact_middle_name,
tin,
unsubscribed,
vat_registration_no,
vsoe_customer_type_id,
zipcode,
account_timezone,
cmt_1_id,
cmt_2_id,
corporate_status_id,
country_iso_code_id,
edi,
einvoicing,
email_0,
english_name,
federal,
federal_tax_id,
industry_segment_id,
industry_vertical_id,
language_iso_code,
person_type_id,
po_required,
primary_city_area_nonlatin,
print,
private_0,
project_cmt_id,
project_manager_id,
project_market_offering_id,
project_region_id,
project_service_offering_id,
project_type_labor_costing_id,
receipts_required,
region_id,
sled,
state_tax_id,
SWT_INS_DT,
account_name_nonlatin,
country_group,
eco_id,
edocument_package_id,
finance_manager_id,
job_code,
job_level,
openair_progproj_stage_id,
sender_email_domain,
use_sender_email_list,
Is_Deleted,
SWT_Ins_Date_Backup
)
SELECT 
account_name,
actual_cost_migration,
address_one,
address_three,
address_two,
ariba_network_id,
ariba_system_id,
asian_name_1st,
asian_name_2nd,
bank_account_currency_id,
bank_account_number,
bank_address_1,
bank_address_2,
bank_city,
bank_country_id,
bank_name,
bank_routing_number,
bank_routingswift_code,
bank_state,
bank_zip,
baseline_cost,
baseline_hours,
baseline_revenue,
bic,
bmc_cumulus_pmo_user,
bulstat_number,
business_area_id,
business_style_id,
central_bank_id,
check_bill,
city,
client_principal_id,
country,
create_date,
ctc,
cumulative__completed,
customer_fiscal_representati_0,
customer_fiscal_representati_1,
customer_fiscal_representati_2,
customer_fiscal_representati_3,
customer_fiscal_representativ,
customer_subsidiary_sub_code,
date_last_modified,
default_transaction_type_id,
default_wt_code_id,
delivery_manager_id,
dic,
domestic_parent_duns_,
domestic_parent_name,
duns_,
duplicate_cost_types,
duplicate_dashboard_settings,
duplicate_expense_policy,
duplicate_invoice_layout_sett,
duplicate_issues,
duplicate_loaded_costs,
duplicate_notification_settin,
duplicate_phase_and_task_cust,
duplicate_project_approvers,
duplicate_project_autobill_se,
duplicate_project_billing_rul,
duplicate_project_budget,
duplicate_project_pricing,
duplicate_recognition_autorun,
duplicate_revenue_recognition,
dwo_cost_budget,
email,
entity_extid,
entity_id,
entity_type,
estimate_at_completion_eac,
estimated_actual_cost,
expected_order_close_dwo,
export_to_openair,
first_name,
fte,
full_name,
functional_area_id,
global_parent_duns_,
global_parent_name,
global_subscription_status,
custom_legal_name,
ico,
identifier_type,
identifier_value,
immediate_parent_duns_,
immediate_parent_name,
individual_bill_payment,
intermediary_bank,
intermediary_bic,
is_engagement,
is_inactive,
is_online_bill_pay,
is_unavailable,
is_vat_id,
je_approval_routing_id,
je_approver_id,
kyriba_entity_name,
last_modified_date,
last_name,
last_sales_activity,
lcci_id,
login_access,
lsa_link,
lsa_link_name,
middle_name,
mru_id,
name,
national_identification,
notes,
ns_actual_cost_calculation,
openair_create_project_worksp,
openair_employee_is_ns_purcha,
openair_export_error,
openair_internal_id,
openair_map_exp__rep__to_pare,
openair_map_exp__rep__to_vend,
openair_opportunity_id,
openair_parent_vendor_id,
openair_percent_complete_over,
openair_project_currency_id,
openair_project_rate_card_id,
openair_project_stage_id,
openair_project_template_id,
openair_sfa_id,
openair_user_currency,
openair_user_or_vendor_id,
openair_user_tax_nexus_type_id,
originator_id,
parent_customer_id,
parent_id,
payment_hold,
payment_method_id,
philhealth,
phone,
physical_work_location,
pmo_toolkit_user,
prepaid,
procurement_organization_id,
profit_center_id,
proj_functional_area_id,
proj_lcci_id,
proj_profit_center_id,
project_billing_type_id,
project_category_id,
project_id,
project_program_id,
project_revenue_type_id,
project_type_id,
reason_for_hold,
remittance_purpose_code,
resource_type_id,
salutation,
source_system_id,
state,
statutory_bank_payment_code,
subsidiary,
tax_contact_first_name,
tax_contact_id,
tax_contact_last_name,
tax_contact_middle_name,
tin,
unsubscribed,
vat_registration_no,
vsoe_customer_type_id,
zipcode,
account_timezone,
cmt_1_id,
cmt_2_id,
corporate_status_id,
country_iso_code_id,
edi,
einvoicing,
email_0,
english_name,
federal,
federal_tax_id,
industry_segment_id,
industry_vertical_id,
language_iso_code,
person_type_id,
po_required,
primary_city_area_nonlatin,
print,
private_0,
project_cmt_id,
project_manager_id,
project_market_offering_id,
project_region_id,
project_service_offering_id,
project_type_labor_costing_id,
receipts_required,
region_id,
sled,
state_tax_id,
sysdate as SWT_INS_DT,
account_name_nonlatin,
country_group,
eco_id,
edocument_package_id,
finance_manager_id,
job_code,
job_level,
openair_progproj_stage_id,
sender_email_domain,
use_sender_email_list,
'true'
,SWT_INS_DT
FROM NS_Entity_base_deleted;




CREATE LOCAL TEMP TABLE NS_Entity_base_active ON COMMIT PRESERVE ROWS AS
(
SELECT DISTINCT * FROM swt_rpt_base.NS_Entity where Is_Deleted ='true' and entity_id in ( select distinct entity_id from swt_rpt_stg.NS_Entity_Id))
SEGMENTED BY HASH(entity_id) ALL NODES;

DELETE /*+DIRECT*/ FROM swt_rpt_base.NS_Entity where Is_Deleted ='true' and entity_id in ( select distinct entity_id from NS_Entity_base_active );

INSERT /*+DIRECT*/ INTO swt_rpt_base.NS_Entity_Deleted_Ids
( entity_id,
SWT_INS_DT,
status
)
SELECT
entity_id,
SYSDATE,
'activated'
FROM NS_Entity_base_active;


INSERT /*+DIRECT*/ INTO swt_rpt_base.NS_Entity
(
account_name,
actual_cost_migration,
address_one,
address_three,
address_two,
ariba_network_id,
ariba_system_id,
asian_name_1st,
asian_name_2nd,
bank_account_currency_id,
bank_account_number,
bank_address_1,
bank_address_2,
bank_city,
bank_country_id,
bank_name,
bank_routing_number,
bank_routingswift_code,
bank_state,
bank_zip,
baseline_cost,
baseline_hours,
baseline_revenue,
bic,
bmc_cumulus_pmo_user,
bulstat_number,
business_area_id,
business_style_id,
central_bank_id,
check_bill,
city,
client_principal_id,
country,
create_date,
ctc,
cumulative__completed,
customer_fiscal_representati_0,
customer_fiscal_representati_1,
customer_fiscal_representati_2,
customer_fiscal_representati_3,
customer_fiscal_representativ,
customer_subsidiary_sub_code,
date_last_modified,
default_transaction_type_id,
default_wt_code_id,
delivery_manager_id,
dic,
domestic_parent_duns_,
domestic_parent_name,
duns_,
duplicate_cost_types,
duplicate_dashboard_settings,
duplicate_expense_policy,
duplicate_invoice_layout_sett,
duplicate_issues,
duplicate_loaded_costs,
duplicate_notification_settin,
duplicate_phase_and_task_cust,
duplicate_project_approvers,
duplicate_project_autobill_se,
duplicate_project_billing_rul,
duplicate_project_budget,
duplicate_project_pricing,
duplicate_recognition_autorun,
duplicate_revenue_recognition,
dwo_cost_budget,
email,
entity_extid,
entity_id,
entity_type,
estimate_at_completion_eac,
estimated_actual_cost,
expected_order_close_dwo,
export_to_openair,
first_name,
fte,
full_name,
functional_area_id,
global_parent_duns_,
global_parent_name,
global_subscription_status,
custom_legal_name,
ico,
identifier_type,
identifier_value,
immediate_parent_duns_,
immediate_parent_name,
individual_bill_payment,
intermediary_bank,
intermediary_bic,
is_engagement,
is_inactive,
is_online_bill_pay,
is_unavailable,
is_vat_id,
je_approval_routing_id,
je_approver_id,
kyriba_entity_name,
last_modified_date,
last_name,
last_sales_activity,
lcci_id,
login_access,
lsa_link,
lsa_link_name,
middle_name,
mru_id,
name,
national_identification,
notes,
ns_actual_cost_calculation,
openair_create_project_worksp,
openair_employee_is_ns_purcha,
openair_export_error,
openair_internal_id,
openair_map_exp__rep__to_pare,
openair_map_exp__rep__to_vend,
openair_opportunity_id,
openair_parent_vendor_id,
openair_percent_complete_over,
openair_project_currency_id,
openair_project_rate_card_id,
openair_project_stage_id,
openair_project_template_id,
openair_sfa_id,
openair_user_currency,
openair_user_or_vendor_id,
openair_user_tax_nexus_type_id,
originator_id,
parent_customer_id,
parent_id,
payment_hold,
payment_method_id,
philhealth,
phone,
physical_work_location,
pmo_toolkit_user,
prepaid,
procurement_organization_id,
profit_center_id,
proj_functional_area_id,
proj_lcci_id,
proj_profit_center_id,
project_billing_type_id,
project_category_id,
project_id,
project_program_id,
project_revenue_type_id,
project_type_id,
reason_for_hold,
remittance_purpose_code,
resource_type_id,
salutation,
source_system_id,
state,
statutory_bank_payment_code,
subsidiary,
tax_contact_first_name,
tax_contact_id,
tax_contact_last_name,
tax_contact_middle_name,
tin,
unsubscribed,
vat_registration_no,
vsoe_customer_type_id,
zipcode,
account_timezone,
cmt_1_id,
cmt_2_id,
corporate_status_id,
country_iso_code_id,
edi,
einvoicing,
email_0,
english_name,
federal,
federal_tax_id,
industry_segment_id,
industry_vertical_id,
language_iso_code,
person_type_id,
po_required,
primary_city_area_nonlatin,
print,
private_0,
project_cmt_id,
project_manager_id,
project_market_offering_id,
project_region_id,
project_service_offering_id,
project_type_labor_costing_id,
receipts_required,
region_id,
sled,
state_tax_id,
SWT_INS_DT,
account_name_nonlatin,
country_group,
eco_id,
edocument_package_id,
finance_manager_id,
job_code,
job_level,
openair_progproj_stage_id,
sender_email_domain,
use_sender_email_list,
Is_Deleted,
SWT_Ins_Date_Backup
)
SELECT 
account_name,
actual_cost_migration,
address_one,
address_three,
address_two,
ariba_network_id,
ariba_system_id,
asian_name_1st,
asian_name_2nd,
bank_account_currency_id,
bank_account_number,
bank_address_1,
bank_address_2,
bank_city,
bank_country_id,
bank_name,
bank_routing_number,
bank_routingswift_code,
bank_state,
bank_zip,
baseline_cost,
baseline_hours,
baseline_revenue,
bic,
bmc_cumulus_pmo_user,
bulstat_number,
business_area_id,
business_style_id,
central_bank_id,
check_bill,
city,
client_principal_id,
country,
create_date,
ctc,
cumulative__completed,
customer_fiscal_representati_0,
customer_fiscal_representati_1,
customer_fiscal_representati_2,
customer_fiscal_representati_3,
customer_fiscal_representativ,
customer_subsidiary_sub_code,
date_last_modified,
default_transaction_type_id,
default_wt_code_id,
delivery_manager_id,
dic,
domestic_parent_duns_,
domestic_parent_name,
duns_,
duplicate_cost_types,
duplicate_dashboard_settings,
duplicate_expense_policy,
duplicate_invoice_layout_sett,
duplicate_issues,
duplicate_loaded_costs,
duplicate_notification_settin,
duplicate_phase_and_task_cust,
duplicate_project_approvers,
duplicate_project_autobill_se,
duplicate_project_billing_rul,
duplicate_project_budget,
duplicate_project_pricing,
duplicate_recognition_autorun,
duplicate_revenue_recognition,
dwo_cost_budget,
email,
entity_extid,
entity_id,
entity_type,
estimate_at_completion_eac,
estimated_actual_cost,
expected_order_close_dwo,
export_to_openair,
first_name,
fte,
full_name,
functional_area_id,
global_parent_duns_,
global_parent_name,
global_subscription_status,
custom_legal_name,
ico,
identifier_type,
identifier_value,
immediate_parent_duns_,
immediate_parent_name,
individual_bill_payment,
intermediary_bank,
intermediary_bic,
is_engagement,
is_inactive,
is_online_bill_pay,
is_unavailable,
is_vat_id,
je_approval_routing_id,
je_approver_id,
kyriba_entity_name,
last_modified_date,
last_name,
last_sales_activity,
lcci_id,
login_access,
lsa_link,
lsa_link_name,
middle_name,
mru_id,
name,
national_identification,
notes,
ns_actual_cost_calculation,
openair_create_project_worksp,
openair_employee_is_ns_purcha,
openair_export_error,
openair_internal_id,
openair_map_exp__rep__to_pare,
openair_map_exp__rep__to_vend,
openair_opportunity_id,
openair_parent_vendor_id,
openair_percent_complete_over,
openair_project_currency_id,
openair_project_rate_card_id,
openair_project_stage_id,
openair_project_template_id,
openair_sfa_id,
openair_user_currency,
openair_user_or_vendor_id,
openair_user_tax_nexus_type_id,
originator_id,
parent_customer_id,
parent_id,
payment_hold,
payment_method_id,
philhealth,
phone,
physical_work_location,
pmo_toolkit_user,
prepaid,
procurement_organization_id,
profit_center_id,
proj_functional_area_id,
proj_lcci_id,
proj_profit_center_id,
project_billing_type_id,
project_category_id,
project_id,
project_program_id,
project_revenue_type_id,
project_type_id,
reason_for_hold,
remittance_purpose_code,
resource_type_id,
salutation,
source_system_id,
state,
statutory_bank_payment_code,
subsidiary,
tax_contact_first_name,
tax_contact_id,
tax_contact_last_name,
tax_contact_middle_name,
tin,
unsubscribed,
vat_registration_no,
vsoe_customer_type_id,
zipcode,
account_timezone,
cmt_1_id,
cmt_2_id,
corporate_status_id,
country_iso_code_id,
edi,
einvoicing,
email_0,
english_name,
federal,
federal_tax_id,
industry_segment_id,
industry_vertical_id,
language_iso_code,
person_type_id,
po_required,
primary_city_area_nonlatin,
print,
private_0,
project_cmt_id,
project_manager_id,
project_market_offering_id,
project_region_id,
project_service_offering_id,
project_type_labor_costing_id,
receipts_required,
region_id,
sled,
state_tax_id,
sysdate as SWT_INS_DT,
account_name_nonlatin,
country_group,
eco_id,
edocument_package_id,
finance_manager_id,
job_code,
job_level,
openair_progproj_stage_id,
sender_email_domain,
use_sender_email_list,
'false',
SWT_INS_DT
FROM NS_Entity_base_active;


COMMIT;

/* Deleting partial audit entry */
/*
DELETE FROM swt_rpt_stg.FAST_LD_AUDT where SUBJECT_AREA = 'NETSUITE' and
TBL_NM = 'NS_Entity' and
COMPLTN_STAT = 'N' and
LD_DT=sysdate::date and 
SEQ_ID = (select max(SEQ_ID) from swt_rpt_stg.FAST_LD_AUDT where  SUBJECT_AREA = 'NETSUITE' and  TBL_NM = 'NS_Entity' and  COMPLTN_STAT = 'N');
*/

/* Inserting new audit entry with all stats */

INSERT INTO swt_rpt_stg.FAST_LD_AUDT
(
SUBJECT_AREA
,TBL_NM
,LD_DT
,START_DT_TIME
,END_DT_TIME
,SRC_REC_CNT
,TGT_REC_CNT
,COMPLTN_STAT
)
select 'NETSUITE','NS_Entity_Id',sysdate::date,(select st from Start_Time_Tmp_Id),sysdate,(select count from Start_Time_Tmp_Id) ,(select count(*) from swt_rpt_base.NS_Entity where SWT_INS_DT>=(select max(START_DT_TIME) from swt_rpt_stg.FAST_LD_AUDT where TBL_NM='NS_Entity_Id') and is_deleted='true'),'Y';

Commit;

SELECT DO_TM_TASK('mergeout', 'swt_rpt_base.NS_Entity');
SELECT DO_TM_TASK('mergeout', 'swt_rpt_stg.NS_Entity_Hist');
SELECT DO_TM_TASK('mergeout', 'swt_rpt_stg.FAST_LD_AUDT');
select ANALYZE_STATISTICS('swt_rpt_base.NS_Entity');
SELECT ANALYZE_STATISTICS('swt_rpt_base.NS_Entity_deleted_IDS');

-->>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
TRUNCATE TABLE swt_rpt_stg.NS_Entity_Id;
delete /*+DIRECT*/ from "swt_rpt_base"."NS_Entity_id"  where swt_ins_dt::date <= TIMESTAMPADD(DAY,-7,sysdate)::date;
commit;

--<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<




