/****
****Dcription   : Incremental data load for NS_Transaction_lines
****/

/* Setting timing on**/
\timing

--SET SESSION AUTOCOMMIT TO OFF;

\set ON_ERROR_STOP on

CREATE LOCAL TEMP TABLE Start_Time_Tmp ON COMMIT PRESERVE ROWS AS select count(*) count, sysdate st from swt_rpt_stg.NS_Transaction_lines;

/* Inserting values into Audit table  */

INSERT INTO swt_rpt_stg.FAST_LD_AUDT
(
SUBJECT_AREA
,TBL_NM
,LD_DT
,START_DT_TIME
,END_DT_TIME
,SRC_REC_CNT
,TGT_REC_CNT
,COMPLTN_STAT
)
select 'NETSUITE','NS_Transaction_lines',sysdate::date,sysdate,null,(select count from Start_Time_Tmp) ,null,'N';

Commit;


INSERT /*+DIRECT*/ INTO "swt_rpt_stg".NS_Transaction_lines_Hist SELECT * from "swt_rpt_stg".NS_Transaction_lines;
Commit;


CREATE LOCAL TEMP TABLE duplicates_lines ON COMMIT PRESERVE ROWS AS (
select transaction_id,transaction_line_id,is_header,max(auto_id) as auto_id from swt_rpt_stg.NS_Transaction_lines where (transaction_id,transaction_line_id,is_header) in (
select transaction_id,transaction_line_id,is_header from swt_rpt_stg.NS_Transaction_lines group by transaction_id,transaction_line_id,date_last_modified,is_header having count(1)>1)
group by transaction_id,transaction_line_id,is_header);


delete from swt_rpt_stg.NS_Transaction_lines  where exists(
select 1 from duplicates_lines t2 where swt_rpt_stg.NS_Transaction_lines.transaction_id=t2.transaction_id and swt_rpt_stg.NS_Transaction_lines.transaction_line_id=t2.transaction_line_id and 
swt_rpt_stg.NS_Transaction_lines.is_header=t2.is_header and swt_rpt_stg.NS_Transaction_lines.auto_id<t2.auto_id);

commit;

delete from "swt_rpt_stg".NS_Transaction_lines where (transaction_id,Transaction_line_id,is_header,auto_id) in 
(select transaction_id,Transaction_line_id,is_header,auto_id from (select transaction_id,Transaction_line_id,is_header,auto_id,
row_number() over (partition by transaction_id,transaction_line_id order by auto_id desc)rn from "swt_rpt_stg".NS_Transaction_lines)a where rn>1);


commit;

CREATE LOCAL TEMP TABLE NS_Transaction_lines_stg_Tmp ON COMMIT PRESERVE ROWS AS
( 
SELECT DISTINCT * FROM swt_rpt_stg.NS_Transaction_lines where is_header='true')
SEGMENTED BY HASH(transaction_line_id,transaction_id,date_last_modified) ALL NODES;

CREATE LOCAL TEMP TABLE NS_Transaction_lines_stg_Tmp_Line ON COMMIT PRESERVE ROWS AS
( 
SELECT DISTINCT * FROM swt_rpt_stg.NS_Transaction_lines where is_header<>'true')
SEGMENTED BY HASH(transaction_line_id,transaction_id,date_last_modified) ALL NODES;

TRUNCATE TABLE swt_rpt_stg.NS_Transaction_lines;

CREATE LOCAL TEMP TABLE NS_Transaction_lines_stg_Tmp_Key ON COMMIT PRESERVE ROWS AS
(
SELECT transaction_line_id,transaction_id,max(date_last_modified) as date_last_modified FROM NS_Transaction_lines_stg_Tmp group by transaction_line_id,transaction_id) 
SEGMENTED BY HASH(transaction_line_id,transaction_id,date_last_modified) ALL NODES;

/* Inserting Stage table data into Historical Table */

insert /*+DIRECT*/ into swt_rpt_stg.NS_Transaction_lines_Hist
(
account_id
,alt_sales_amount
,amortization_residual
,amount
,amount_foreign
,amount_foreign_linked
,amount_linked
,amount_pending
,amount_settlement
,amount_taxable
,amount_taxed
,bill_variance_status
,bom_quantity
,catch_up_period_id
,charge_type
,class_id
,company_id
,component_id
,component_yield
,cost_estimate_type
,date_cleared
,date_closed
,date_last_modified
,date_last_modified_gmt
,date_revenue_committed
,delay_rev_rec
,department_id
,do_not_display_line
,do_not_print_line
,do_restock
,estimated_cost
,estimated_cost_foreign
,expected_receipt_date
,expense_category_id
,gl_number
,gl_sequence
,gl_sequence_id
,gross_amount
,has_cost_line
,is_allocation
,is_amortization_rev_rec
,is_commitment_confirmed
,is_cost_line
,is_exclude_from_rate_request
,is_fx_variance
,is_item_value_adjustment
,is_landed_cost
,is_scrap
,is_vsoe_allocation_line
,isbillable
,iscleared
,isnonreimbursable
,istaxable
,item_count
,item_id
,item_received
,item_source
,item_unit_price
,kit_part_number
,landed_cost_source_line_id
,location_id
,match_bill_to_receipt
,memo
,needs_revenue_element
,net_amount
,net_amount_foreign
,non_posting_line
,number_billed
,operation_sequence_number
,order_priority
,payment_method_id
,payroll_item_id
,payroll_wage_base_amount
,payroll_year_to_date_amount
,period_closed
,project_task_id
,purchase_contract_id
,quantity_committed
,quantity_packed
,quantity_picked
,quantity_received_in_shipment
,receivebydate
,reimbursement_type
,related_company_id
,rev_rec_end_date
,rev_rec_rule_id
,rev_rec_start_date
,revenue_element_id
,schedule_id
,shipdate
,shipment_received
,subscription_line_id
,subsidiary_id
,tax_item_id
,tax_type
,term_in_months
,tobeemailed
,tobefaxed
,tobeprinted
,transaction_discount_line
,transaction_id
,transaction_line_id
,transaction_order
,transfer_order_item_line
,transfer_order_line_type
,unit_cost_override
,unit_of_measure_id
,vsoe_allocation
,vsoe_amt
,vsoe_deferral
,vsoe_delivered
,vsoe_discount
,vsoe_price
,additional_discount_
,additional_discount_amount
,adjustment_field
,adjustment_tax_code_id
,appliance_drop_ship_po_
,apply_wh_tax
,asset_id
,authority_currency_code
,billable_engagement_name
,billable_expense_category
,billable_expense_engagement
,billable_item_name
,billable_units_of_measure
,billing_frequency_id
,bill_of_lading_number
,booking_date
,box_number
,charge_type_id
,code_of_supply_id
,contractual_discount_
,contractual_discount_amount
,contract_end_date
,contract_start_date
,contract_term
,course_type_id
,display_quantity
,employee_token_id
,end_user_id
,eu_triangulation
,exempt_id
,expense_account_id
,export_to_openair
,fixed_asset_id
,functional_area_id
,goods_and_services_indicato_id
,gross_list_price
,custom_functional_area_id
,custom_lcci_id
,custom_profit_center_id
,ic_item
,ic_je_number_id
,idt_product_tax_code
,intercompany
,intercompany_discount_
,je_expense_type
,jurisdiction_text
,lcci_id
,line_item_id
,markup_amount
,notc_id
,openair_assigned_users
,openair_billing_rule_id
,openair_charge_type_id
,openair_expense_report_line_i
,openair_gsthst
,openair_invoice_line_id
,openair_journal_entry_creatio
,openair_journal_entry_error
,openair_journal_entry_error_m
,openair_line_from_openair
,openair_loaded_cost_class_id
,openair_loaded_cost_credit__id
,openair_loaded_cost_debit_a_id
,openair_loaded_cost_departm_id
,openair_loaded_cost_locatio_id
,openair_loaded_cost_subsidi_id
,openair_phases_ancestry
,openair_phase_name
,openair_primary_loaded_cost
,openair_primary_loaded_cost_id
,openair_project_task_id
,openair_project_task_id_numbe
,openair_pst
,openair_quantity_from__invoic
,openair_rate
,openair_rev_rec_rule_id
,openair_secondary_loaded_cost
,openair_secondary_loaded_co_id
,openair_task_assignment_id
,openair_task_assignment_plann
,openair_task_id
,openair_task_name
,openair_tax
,openair_tertiary_loaded_cost
,openair_tertiary_loaded_cos_id
,openair_timesheet_start_date
,openair_time_entry_id
,originator_journal_tran_typ_id
,originator_transaction_intern
,partner_discount_
,partner_discount_amount
,pid
,pl_id
,posted
,pretax_amt
,pretax_amt_quantity
,price_type_id
,product_subtype
,product_type
,profit_center_id
,project_task_type_id
,promotional_discount_
,promotional_discount_amount
,schedule_id_0
,serial_number
,related_license_id
,related_asset_id
,reason_id
,registration_unique_id
,ship_date
,statistical_procedure_for_p_id
,statistical_procedure_for_s_id
,statistical_value
,statistical_value__base_curre
,task_type_id
,tax_amt
,tax_exemption_reason_code_id
,tax_rate
,tax_rate_code
,tax_type_0
,trade_discount_
,trade_item_code_id
,trade_item_description
,user_quantity
,vendor_tax
,vsoe_customer_type_id
,vsoe_deal_size_id
,vsoe_geography_id
,vsoe_lower_band_
,vsoe_pricing_method_id
,vsoe_related_line_item_number
,vsoe_upper_band_
,wdem_settlement_id
,withholding_tax_amount
,withholding_tax_amount__expen
,withholding_tax_base_amount
,withholding_tax_base_amount__
,withholding_tax_code_id
,withholding_tax_code__expen_id
,withholding_tax_line
,withholding_tax_line__expense
,withholding_tax_rate
,withholding_tax_rate__expense
,wt_customer_id
,wt_employee_id
,wt_vendor_id
,apttus_line_id
,apttus_order_
,apttus_order_id
,billing_plan_id
,billing_schedule_id
,ela_agreement_name
,item_id_0
,item_name
,item_units_name
,legacy_equipment_
,legacy_sales_doc_id
,mark_up_
,nibs_id
,po_
,product_revenue_subtype
,revenue_element_id_0
,shipping_group_id
,unit_list_price
,uplift_
,uplift_amount
,CREDIT_REBILL_REQUIRES_UNBILL
,PRODUCT_SUBTYPE_EXTERNAL_ID
,PRODUCT_TYPE_EXTERNAL_ID
,REBILLED_LINE
,UNIQUE_KEY
,sales_order_id
,quote_line_item_id
,item_label
,cmt_id
,sales_team_id
,sales_order_label
,LD_DT
,SWT_INS_DT
,d_source
--,SWT_Ins_Date_Backup
)
select
account_id
,alt_sales_amount
,amortization_residual
,amount
,amount_foreign
,amount_foreign_linked
,amount_linked
,amount_pending
,amount_settlement
,amount_taxable
,amount_taxed
,bill_variance_status
,bom_quantity
,catch_up_period_id
,charge_type
,class_id
,company_id
,component_id
,component_yield
,cost_estimate_type
,date_cleared
,date_closed
,date_last_modified
,date_last_modified_gmt
,date_revenue_committed
,delay_rev_rec
,department_id
,do_not_display_line
,do_not_print_line
,do_restock
,estimated_cost
,estimated_cost_foreign
,expected_receipt_date
,expense_category_id
,gl_number
,gl_sequence
,gl_sequence_id
,gross_amount
,has_cost_line
,is_allocation
,is_amortization_rev_rec
,is_commitment_confirmed
,is_cost_line
,is_exclude_from_rate_request
,is_fx_variance
,is_item_value_adjustment
,is_landed_cost
,is_scrap
,is_vsoe_allocation_line
,isbillable
,iscleared
,isnonreimbursable
,istaxable
,item_count
,item_id
,item_received
,item_source
,item_unit_price
,kit_part_number
,landed_cost_source_line_id
,location_id
,match_bill_to_receipt
,memo
,needs_revenue_element
,net_amount
,net_amount_foreign
,non_posting_line
,number_billed
,operation_sequence_number
,order_priority
,payment_method_id
,payroll_item_id
,payroll_wage_base_amount
,payroll_year_to_date_amount
,period_closed
,project_task_id
,purchase_contract_id
,quantity_committed
,quantity_packed
,quantity_picked
,quantity_received_in_shipment
,receivebydate
,reimbursement_type
,related_company_id
,rev_rec_end_date
,rev_rec_rule_id
,rev_rec_start_date
,revenue_element_id
,schedule_id
,shipdate
,shipment_received
,subscription_line_id
,subsidiary_id
,tax_item_id
,tax_type
,term_in_months
,tobeemailed
,tobefaxed
,tobeprinted
,transaction_discount_line
,transaction_id
,transaction_line_id
,transaction_order
,transfer_order_item_line
,transfer_order_line_type
,unit_cost_override
,unit_of_measure_id
,vsoe_allocation
,vsoe_amt
,vsoe_deferral
,vsoe_delivered
,vsoe_discount
,vsoe_price
,additional_discount_
,additional_discount_amount
,adjustment_field
,adjustment_tax_code_id
,appliance_drop_ship_po_
,apply_wh_tax
,asset_id
,authority_currency_code
,billable_engagement_name
,billable_expense_category
,billable_expense_engagement
,billable_item_name
,billable_units_of_measure
,billing_frequency_id
,bill_of_lading_number
,booking_date
,box_number
,charge_type_id
,code_of_supply_id
,contractual_discount_
,contractual_discount_amount
,contract_end_date
,contract_start_date
,contract_term
,course_type_id
,display_quantity
,employee_token_id
,end_user_id
,eu_triangulation
,exempt_id
,expense_account_id
,export_to_openair
,fixed_asset_id
,functional_area_id
,goods_and_services_indicato_id
,gross_list_price
,custom_functional_area_id
,custom_lcci_id
,custom_profit_center_id
,ic_item
,ic_je_number_id
,idt_product_tax_code
,intercompany
,intercompany_discount_
,je_expense_type
,jurisdiction_text
,lcci_id
,line_item_id
,markup_amount
,notc_id
,openair_assigned_users
,openair_billing_rule_id
,openair_charge_type_id
,openair_expense_report_line_i
,openair_gsthst
,openair_invoice_line_id
,openair_journal_entry_creatio
,openair_journal_entry_error
,openair_journal_entry_error_m
,openair_line_from_openair
,openair_loaded_cost_class_id
,openair_loaded_cost_credit__id
,openair_loaded_cost_debit_a_id
,openair_loaded_cost_departm_id
,openair_loaded_cost_locatio_id
,openair_loaded_cost_subsidi_id
,openair_phases_ancestry
,openair_phase_name
,openair_primary_loaded_cost
,openair_primary_loaded_cost_id
,openair_project_task_id
,openair_project_task_id_numbe
,openair_pst
,openair_quantity_from__invoic
,openair_rate
,openair_rev_rec_rule_id
,openair_secondary_loaded_cost
,openair_secondary_loaded_co_id
,openair_task_assignment_id
,openair_task_assignment_plann
,openair_task_id
,openair_task_name
,openair_tax
,openair_tertiary_loaded_cost
,openair_tertiary_loaded_cos_id
,openair_timesheet_start_date
,openair_time_entry_id
,originator_journal_tran_typ_id
,originator_transaction_intern
,partner_discount_
,partner_discount_amount
,pid
,pl_id
,posted
,pretax_amt
,pretax_amt_quantity
,price_type_id
,product_subtype
,product_type
,profit_center_id
,project_task_type_id
,promotional_discount_
,promotional_discount_amount
,schedule_id_0
,serial_number
,related_license_id
,related_asset_id
,reason_id
,registration_unique_id
,ship_date
,statistical_procedure_for_p_id
,statistical_procedure_for_s_id
,statistical_value
,statistical_value__base_curre
,task_type_id
,tax_amt
,tax_exemption_reason_code_id
,tax_rate
,tax_rate_code
,tax_type_0
,trade_discount_
,trade_item_code_id
,trade_item_description
,user_quantity
,vendor_tax
,vsoe_customer_type_id
,vsoe_deal_size_id
,vsoe_geography_id
,vsoe_lower_band_
,vsoe_pricing_method_id
,vsoe_related_line_item_number
,vsoe_upper_band_
,wdem_settlement_id
,withholding_tax_amount
,withholding_tax_amount__expen
,withholding_tax_base_amount
,withholding_tax_base_amount__
,withholding_tax_code_id
,withholding_tax_code__expen_id
,withholding_tax_line
,withholding_tax_line__expense
,withholding_tax_rate
,withholding_tax_rate__expense
,wt_customer_id
,wt_employee_id
,wt_vendor_id
,apttus_line_id
,apttus_order_
,apttus_order_id
,billing_plan_id
,billing_schedule_id
,ela_agreement_name
,item_id_0
,item_name
,item_units_name
,legacy_equipment_
,legacy_sales_doc_id
,mark_up_
,nibs_id
,po_
,product_revenue_subtype
,revenue_element_id_0
,shipping_group_id
,unit_list_price
,uplift_
,uplift_amount
,CREDIT_REBILL_REQUIRES_UNBILL
,PRODUCT_SUBTYPE_EXTERNAL_ID
,PRODUCT_TYPE_EXTERNAL_ID
,REBILLED_LINE
,UNIQUE_KEY
,sales_order_id
,quote_line_item_id
,item_label
,cmt_id
,sales_team_id
,sales_order_label
,SYSDATE AS LD_DT
,SWT_INS_DT
,'base'
--,SWT_Ins_Date_Backup
FROM swt_rpt_base.NS_Transaction_lines WHERE EXISTS
(SELECT 1 FROM NS_Transaction_lines_stg_Tmp_Key STG 
WHERE STG.transaction_line_id = NS_Transaction_lines.transaction_line_id AND STG.transaction_id=NS_Transaction_lines.transaction_id);


/* Deleting before seven days data from current date in the Historical Table */

delete /*+DIRECT*/ from "swt_rpt_stg"."NS_Transaction_lines_Hist"  where LD_DT::date <= TIMESTAMPADD(DAY,-45,sysdate)::date;

DELETE /*+DIRECT*/ FROM "swt_rpt_base".NS_Transaction_lines WHERE EXISTS
(SELECT 1 FROM NS_Transaction_lines_stg_Tmp_Key STG 
WHERE STG.transaction_line_id = NS_Transaction_lines.transaction_line_id AND STG.transaction_id=NS_Transaction_lines.transaction_id);


create local temp table NS_Base_Insert on commit preserve rows as (
SELECT DISTINCT 
account_id
,alt_sales_amount
,amortization_residual
,amount
,amount_foreign
,amount_foreign_linked
,amount_linked
,amount_pending
,amount_settlement
,amount_taxable
,amount_taxed
,bill_variance_status
,bom_quantity
,catch_up_period_id
,charge_type
,class_id
,company_id
,component_id
,component_yield
,cost_estimate_type
,date_cleared
,date_closed
,NS_Transaction_lines_stg_Tmp.date_last_modified
,date_last_modified_gmt
,date_revenue_committed
,delay_rev_rec
,department_id
,do_not_display_line
,do_not_print_line
,do_restock
,estimated_cost
,estimated_cost_foreign
,expected_receipt_date
,expense_category_id
,gl_number
,gl_sequence
,gl_sequence_id
,gross_amount
,has_cost_line
,is_allocation
,is_amortization_rev_rec
,is_commitment_confirmed
,is_cost_line
,is_exclude_from_rate_request
,is_fx_variance
,is_item_value_adjustment
,is_landed_cost
,is_scrap
,is_vsoe_allocation_line
,isbillable
,iscleared
,isnonreimbursable
,istaxable
,item_count
,item_id
,item_received
,item_source
,item_unit_price
,kit_part_number
,landed_cost_source_line_id
,location_id
,match_bill_to_receipt
,memo
,needs_revenue_element
,net_amount
,net_amount_foreign
,non_posting_line
,number_billed
,operation_sequence_number
,order_priority
,payment_method_id
,payroll_item_id
,payroll_wage_base_amount
,payroll_year_to_date_amount
,period_closed
,project_task_id
,purchase_contract_id
,quantity_committed
,quantity_packed
,quantity_picked
,quantity_received_in_shipment
,receivebydate
,reimbursement_type
,related_company_id
,rev_rec_end_date
,rev_rec_rule_id
,rev_rec_start_date
,revenue_element_id
,schedule_id
,shipdate
,shipment_received
,subscription_line_id
,subsidiary_id
,tax_item_id
,tax_type
,term_in_months
,tobeemailed
,tobefaxed
,tobeprinted
,transaction_discount_line
,NS_Transaction_lines_stg_Tmp.transaction_id
,NS_Transaction_lines_stg_Tmp.transaction_line_id
,transaction_order
,transfer_order_item_line
,transfer_order_line_type
,unit_cost_override
,unit_of_measure_id
,vsoe_allocation
,vsoe_amt
,vsoe_deferral
,vsoe_delivered
,vsoe_discount
,vsoe_price
,additional_discount_
,additional_discount_amount
,adjustment_field
,adjustment_tax_code_id
,appliance_drop_ship_po_
,apply_wh_tax
,asset_id
,authority_currency_code
,billable_engagement_name
,billable_expense_category
,billable_expense_engagement
,billable_item_name
,billable_units_of_measure
,billing_frequency_id
,bill_of_lading_number
,booking_date
,box_number
,charge_type_id
,code_of_supply_id
,contractual_discount_
,contractual_discount_amount
,contract_end_date
,contract_start_date
,contract_term
,course_type_id
,display_quantity
,employee_token_id
,end_user_id
,eu_triangulation
,exempt_id
,expense_account_id
,export_to_openair
,fixed_asset_id
,functional_area_id
,goods_and_services_indicato_id
,gross_list_price
,custom_functional_area_id
,custom_lcci_id
,custom_profit_center_id
,ic_item
,ic_je_number_id
,idt_product_tax_code
,intercompany
,intercompany_discount_
,je_expense_type
,jurisdiction_text
,lcci_id
,line_item_id
,markup_amount
,notc_id
,openair_assigned_users
,openair_billing_rule_id
,openair_charge_type_id
,openair_expense_report_line_i
,openair_gsthst
,openair_invoice_line_id
,openair_journal_entry_creatio
,openair_journal_entry_error
,openair_journal_entry_error_m
,openair_line_from_openair
,openair_loaded_cost_class_id
,openair_loaded_cost_credit__id
,openair_loaded_cost_debit_a_id
,openair_loaded_cost_departm_id
,openair_loaded_cost_locatio_id
,openair_loaded_cost_subsidi_id
,openair_phases_ancestry
,openair_phase_name
,openair_primary_loaded_cost
,openair_primary_loaded_cost_id
,openair_project_task_id
,openair_project_task_id_numbe
,openair_pst
,openair_quantity_from__invoic
,openair_rate
,openair_rev_rec_rule_id
,openair_secondary_loaded_cost
,openair_secondary_loaded_co_id
,openair_task_assignment_id
,openair_task_assignment_plann
,openair_task_id
,openair_task_name
,openair_tax
,openair_tertiary_loaded_cost
,openair_tertiary_loaded_cos_id
,openair_timesheet_start_date
,openair_time_entry_id
,originator_journal_tran_typ_id
,originator_transaction_intern
,partner_discount_
,partner_discount_amount
,pid
,pl_id
,posted
,pretax_amt
,pretax_amt_quantity
,price_type_id
,product_subtype
,product_type
,profit_center_id
,project_task_type_id
,promotional_discount_
,promotional_discount_amount
,schedule_id_0
,serial_number
,related_license_id
,related_asset_id
,reason_id
,registration_unique_id
,ship_date
,statistical_procedure_for_p_id
,statistical_procedure_for_s_id
,statistical_value
,statistical_value__base_curre
,task_type_id
,tax_amt
,tax_exemption_reason_code_id
,tax_rate
,tax_rate_code
,tax_type_0
,trade_discount_
,trade_item_code_id
,trade_item_description
,user_quantity
,vendor_tax
,vsoe_customer_type_id
,vsoe_deal_size_id
,vsoe_geography_id
,vsoe_lower_band_
,vsoe_pricing_method_id
,vsoe_related_line_item_number
,vsoe_upper_band_
,wdem_settlement_id
,withholding_tax_amount
,withholding_tax_amount__expen
,withholding_tax_base_amount
,withholding_tax_base_amount__
,withholding_tax_code_id
,withholding_tax_code__expen_id
,withholding_tax_line
,withholding_tax_line__expense
,withholding_tax_rate
,withholding_tax_rate__expense
,wt_customer_id
,wt_employee_id
,wt_vendor_id
,apttus_line_id
,apttus_order_
,apttus_order_id
,billing_plan_id
,billing_schedule_id
,ela_agreement_name
,item_id_0
,item_name
,item_units_name
,legacy_equipment_
,legacy_sales_doc_id
,mark_up_
,nibs_id
,po_
,product_revenue_subtype
,revenue_element_id_0
,shipping_group_id
,unit_list_price
,uplift_
,uplift_amount
,CREDIT_REBILL_REQUIRES_UNBILL
,PRODUCT_SUBTYPE_EXTERNAL_ID
,PRODUCT_TYPE_EXTERNAL_ID
,REBILLED_LINE
,UNIQUE_KEY
,sales_order_id
,quote_line_item_id
,item_label
,cmt_id
,sales_team_id
,sales_order_label
,SYSDATE AS SWT_INS_DT
,sysdate as SWT_Ins_Date_Backup
FROM NS_Transaction_lines_stg_Tmp JOIN NS_Transaction_lines_stg_Tmp_Key ON NS_Transaction_lines_stg_Tmp.transaction_line_id=NS_Transaction_lines_stg_Tmp_Key.transaction_line_id AND NS_Transaction_lines_stg_Tmp.transaction_id=NS_Transaction_lines_stg_Tmp_Key.transaction_id and NS_Transaction_lines_stg_Tmp.date_last_modified=NS_Transaction_lines_stg_Tmp_Key.date_last_modified
);

INSERT /*+DIRECT*/ INTO "swt_rpt_base".NS_Transaction_lines
(
account_id
,alt_sales_amount
,amortization_residual
,amount
,amount_foreign
,amount_foreign_linked
,amount_linked
,amount_pending
,amount_settlement
,amount_taxable
,amount_taxed
,bill_variance_status
,bom_quantity
,catch_up_period_id
,charge_type
,class_id
,company_id
,component_id
,component_yield
,cost_estimate_type
,date_cleared
,date_closed
,date_last_modified
,date_last_modified_gmt
,date_revenue_committed
,delay_rev_rec
,department_id
,do_not_display_line
,do_not_print_line
,do_restock
,estimated_cost
,estimated_cost_foreign
,expected_receipt_date
,expense_category_id
,gl_number
,gl_sequence
,gl_sequence_id
,gross_amount
,has_cost_line
,is_allocation
,is_amortization_rev_rec
,is_commitment_confirmed
,is_cost_line
,is_exclude_from_rate_request
,is_fx_variance
,is_item_value_adjustment
,is_landed_cost
,is_scrap
,is_vsoe_allocation_line
,isbillable
,iscleared
,isnonreimbursable
,istaxable
,item_count
,item_id
,item_received
,item_source
,item_unit_price
,kit_part_number
,landed_cost_source_line_id
,location_id
,match_bill_to_receipt
,memo
,needs_revenue_element
,net_amount
,net_amount_foreign
,non_posting_line
,number_billed
,operation_sequence_number
,order_priority
,payment_method_id
,payroll_item_id
,payroll_wage_base_amount
,payroll_year_to_date_amount
,period_closed
,project_task_id
,purchase_contract_id
,quantity_committed
,quantity_packed
,quantity_picked
,quantity_received_in_shipment
,receivebydate
,reimbursement_type
,related_company_id
,rev_rec_end_date
,rev_rec_rule_id
,rev_rec_start_date
,revenue_element_id
,schedule_id
,shipdate
,shipment_received
,subscription_line_id
,subsidiary_id
,tax_item_id
,tax_type
,term_in_months
,tobeemailed
,tobefaxed
,tobeprinted
,transaction_discount_line
,transaction_id
,transaction_line_id
,transaction_order
,transfer_order_item_line
,transfer_order_line_type
,unit_cost_override
,unit_of_measure_id
,vsoe_allocation
,vsoe_amt
,vsoe_deferral
,vsoe_delivered
,vsoe_discount
,vsoe_price
,additional_discount_
,additional_discount_amount
,adjustment_field
,adjustment_tax_code_id
,appliance_drop_ship_po_
,apply_wh_tax
,asset_id
,authority_currency_code
,billable_engagement_name
,billable_expense_category
,billable_expense_engagement
,billable_item_name
,billable_units_of_measure
,billing_frequency_id
,bill_of_lading_number
,booking_date
,box_number
,charge_type_id
,code_of_supply_id
,contractual_discount_
,contractual_discount_amount
,contract_end_date
,contract_start_date
,contract_term
,course_type_id
,display_quantity
,employee_token_id
,end_user_id
,eu_triangulation
,exempt_id
,expense_account_id
,export_to_openair
,fixed_asset_id
,functional_area_id
,goods_and_services_indicato_id
,gross_list_price
,custom_functional_area_id
,custom_lcci_id
,custom_profit_center_id
,ic_item
,ic_je_number_id
,idt_product_tax_code
,intercompany
,intercompany_discount_
,je_expense_type
,jurisdiction_text
,lcci_id
,line_item_id
,markup_amount
,notc_id
,openair_assigned_users
,openair_billing_rule_id
,openair_charge_type_id
,openair_expense_report_line_i
,openair_gsthst
,openair_invoice_line_id
,openair_journal_entry_creatio
,openair_journal_entry_error
,openair_journal_entry_error_m
,openair_line_from_openair
,openair_loaded_cost_class_id
,openair_loaded_cost_credit__id
,openair_loaded_cost_debit_a_id
,openair_loaded_cost_departm_id
,openair_loaded_cost_locatio_id
,openair_loaded_cost_subsidi_id
,openair_phases_ancestry
,openair_phase_name
,openair_primary_loaded_cost
,openair_primary_loaded_cost_id
,openair_project_task_id
,openair_project_task_id_numbe
,openair_pst
,openair_quantity_from__invoic
,openair_rate
,openair_rev_rec_rule_id
,openair_secondary_loaded_cost
,openair_secondary_loaded_co_id
,openair_task_assignment_id
,openair_task_assignment_plann
,openair_task_id
,openair_task_name
,openair_tax
,openair_tertiary_loaded_cost
,openair_tertiary_loaded_cos_id
,openair_timesheet_start_date
,openair_time_entry_id
,originator_journal_tran_typ_id
,originator_transaction_intern
,partner_discount_
,partner_discount_amount
,pid
,pl_id
,posted
,pretax_amt
,pretax_amt_quantity
,price_type_id
,product_subtype
,product_type
,profit_center_id
,project_task_type_id
,promotional_discount_
,promotional_discount_amount
,schedule_id_0
,serial_number
,related_license_id
,related_asset_id
,reason_id
,registration_unique_id
,ship_date
,statistical_procedure_for_p_id
,statistical_procedure_for_s_id
,statistical_value
,statistical_value__base_curre
,task_type_id
,tax_amt
,tax_exemption_reason_code_id
,tax_rate
,tax_rate_code
,tax_type_0
,trade_discount_
,trade_item_code_id
,trade_item_description
,user_quantity
,vendor_tax
,vsoe_customer_type_id
,vsoe_deal_size_id
,vsoe_geography_id
,vsoe_lower_band_
,vsoe_pricing_method_id
,vsoe_related_line_item_number
,vsoe_upper_band_
,wdem_settlement_id
,withholding_tax_amount
,withholding_tax_amount__expen
,withholding_tax_base_amount
,withholding_tax_base_amount__
,withholding_tax_code_id
,withholding_tax_code__expen_id
,withholding_tax_line
,withholding_tax_line__expense
,withholding_tax_rate
,withholding_tax_rate__expense
,wt_customer_id
,wt_employee_id
,wt_vendor_id
,apttus_line_id
,apttus_order_
,apttus_order_id
,billing_plan_id
,billing_schedule_id
,ela_agreement_name
,item_id_0
,item_name
,item_units_name
,legacy_equipment_
,legacy_sales_doc_id
,mark_up_
,nibs_id
,po_
,product_revenue_subtype
,revenue_element_id_0
,shipping_group_id
,unit_list_price
,uplift_
,uplift_amount
,CREDIT_REBILL_REQUIRES_UNBILL
,PRODUCT_SUBTYPE_EXTERNAL_ID
,PRODUCT_TYPE_EXTERNAL_ID
,REBILLED_LINE
,UNIQUE_KEY
,sales_order_id
,quote_line_item_id
,item_label
,cmt_id
,sales_team_id
,sales_order_label
,SWT_INS_DT
,SWT_Ins_Date_Backup
)
SELECT DISTINCT 
account_id
,alt_sales_amount
,amortization_residual
,amount
,amount_foreign
,amount_foreign_linked
,amount_linked
,amount_pending
,amount_settlement
,amount_taxable
,amount_taxed
,bill_variance_status
,bom_quantity
,catch_up_period_id
,charge_type
,class_id
,company_id
,component_id
,component_yield
,cost_estimate_type
,date_cleared
,date_closed
,date_last_modified
,date_last_modified_gmt
,date_revenue_committed
,delay_rev_rec
,department_id
,do_not_display_line
,do_not_print_line
,do_restock
,estimated_cost
,estimated_cost_foreign
,expected_receipt_date
,expense_category_id
,gl_number
,gl_sequence
,gl_sequence_id
,gross_amount
,has_cost_line
,is_allocation
,is_amortization_rev_rec
,is_commitment_confirmed
,is_cost_line
,is_exclude_from_rate_request
,is_fx_variance
,is_item_value_adjustment
,is_landed_cost
,is_scrap
,is_vsoe_allocation_line
,isbillable
,iscleared
,isnonreimbursable
,istaxable
,item_count
,item_id
,item_received
,item_source
,item_unit_price
,kit_part_number
,landed_cost_source_line_id
,location_id
,match_bill_to_receipt
,memo
,needs_revenue_element
,net_amount
,net_amount_foreign
,non_posting_line
,number_billed
,operation_sequence_number
,order_priority
,payment_method_id
,payroll_item_id
,payroll_wage_base_amount
,payroll_year_to_date_amount
,period_closed
,project_task_id
,purchase_contract_id
,quantity_committed
,quantity_packed
,quantity_picked
,quantity_received_in_shipment
,receivebydate
,reimbursement_type
,related_company_id
,rev_rec_end_date
,rev_rec_rule_id
,rev_rec_start_date
,revenue_element_id
,schedule_id
,shipdate
,shipment_received
,subscription_line_id
,subsidiary_id
,tax_item_id
,tax_type
,term_in_months
,tobeemailed
,tobefaxed
,tobeprinted
,transaction_discount_line
,transaction_id
,transaction_line_id
,transaction_order
,transfer_order_item_line
,transfer_order_line_type
,unit_cost_override
,unit_of_measure_id
,vsoe_allocation
,vsoe_amt
,vsoe_deferral
,vsoe_delivered
,vsoe_discount
,vsoe_price
,additional_discount_
,additional_discount_amount
,adjustment_field
,adjustment_tax_code_id
,appliance_drop_ship_po_
,apply_wh_tax
,asset_id
,authority_currency_code
,billable_engagement_name
,billable_expense_category
,billable_expense_engagement
,billable_item_name
,billable_units_of_measure
,billing_frequency_id
,bill_of_lading_number
,booking_date
,box_number
,charge_type_id
,code_of_supply_id
,contractual_discount_
,contractual_discount_amount
,contract_end_date
,contract_start_date
,contract_term
,course_type_id
,display_quantity
,employee_token_id
,end_user_id
,eu_triangulation
,exempt_id
,expense_account_id
,export_to_openair
,fixed_asset_id
,functional_area_id
,goods_and_services_indicato_id
,gross_list_price
,custom_functional_area_id
,custom_lcci_id
,custom_profit_center_id
,ic_item
,ic_je_number_id
,idt_product_tax_code
,intercompany
,intercompany_discount_
,je_expense_type
,jurisdiction_text
,lcci_id
,line_item_id
,markup_amount
,notc_id
,openair_assigned_users
,openair_billing_rule_id
,openair_charge_type_id
,openair_expense_report_line_i
,openair_gsthst
,openair_invoice_line_id
,openair_journal_entry_creatio
,openair_journal_entry_error
,openair_journal_entry_error_m
,openair_line_from_openair
,openair_loaded_cost_class_id
,openair_loaded_cost_credit__id
,openair_loaded_cost_debit_a_id
,openair_loaded_cost_departm_id
,openair_loaded_cost_locatio_id
,openair_loaded_cost_subsidi_id
,openair_phases_ancestry
,openair_phase_name
,openair_primary_loaded_cost
,openair_primary_loaded_cost_id
,openair_project_task_id
,openair_project_task_id_numbe
,openair_pst
,openair_quantity_from__invoic
,openair_rate
,openair_rev_rec_rule_id
,openair_secondary_loaded_cost
,openair_secondary_loaded_co_id
,openair_task_assignment_id
,openair_task_assignment_plann
,openair_task_id
,openair_task_name
,openair_tax
,openair_tertiary_loaded_cost
,openair_tertiary_loaded_cos_id
,openair_timesheet_start_date
,openair_time_entry_id
,originator_journal_tran_typ_id
,originator_transaction_intern
,partner_discount_
,partner_discount_amount
,pid
,pl_id
,posted
,pretax_amt
,pretax_amt_quantity
,price_type_id
,product_subtype
,product_type
,profit_center_id
,project_task_type_id
,promotional_discount_
,promotional_discount_amount
,schedule_id_0
,serial_number
,related_license_id
,related_asset_id
,reason_id
,registration_unique_id
,ship_date
,statistical_procedure_for_p_id
,statistical_procedure_for_s_id
,statistical_value
,statistical_value__base_curre
,task_type_id
,tax_amt
,tax_exemption_reason_code_id
,tax_rate
,tax_rate_code
,tax_type_0
,trade_discount_
,trade_item_code_id
,trade_item_description
,user_quantity
,vendor_tax
,vsoe_customer_type_id
,vsoe_deal_size_id
,vsoe_geography_id
,vsoe_lower_band_
,vsoe_pricing_method_id
,vsoe_related_line_item_number
,vsoe_upper_band_
,wdem_settlement_id
,withholding_tax_amount
,withholding_tax_amount__expen
,withholding_tax_base_amount
,withholding_tax_base_amount__
,withholding_tax_code_id
,withholding_tax_code__expen_id
,withholding_tax_line
,withholding_tax_line__expense
,withholding_tax_rate
,withholding_tax_rate__expense
,wt_customer_id
,wt_employee_id
,wt_vendor_id
,apttus_line_id
,apttus_order_
,apttus_order_id
,billing_plan_id
,billing_schedule_id
,ela_agreement_name
,item_id_0
,item_name
,item_units_name
,legacy_equipment_
,legacy_sales_doc_id
,mark_up_
,nibs_id
,po_
,product_revenue_subtype
,revenue_element_id_0
,shipping_group_id
,unit_list_price
,uplift_
,uplift_amount
,CREDIT_REBILL_REQUIRES_UNBILL
,PRODUCT_SUBTYPE_EXTERNAL_ID
,PRODUCT_TYPE_EXTERNAL_ID
,REBILLED_LINE
,UNIQUE_KEY
,sales_order_id
,quote_line_item_id
,item_label
,cmt_id
,sales_team_id
,sales_order_label
,SWT_INS_DT
,SWT_Ins_Date_Backup
FROM NS_Base_Insert;


CREATE LOCAL TEMP TABLE NS_Transaction_lines_base_deleted_1 ON COMMIT PRESERVE ROWS AS
(
select transaction_id,transaction_line_id from swt_rpt_base.NS_Transaction_lines where Is_Deleted <> 'true' and exists (select 1 from NS_Transaction_lines_stg_Tmp_Key t1 where swt_rpt_base.NS_Transaction_lines.transaction_id=t1.transaction_id))
SEGMENTED BY HASH(transaction_line_id,transaction_id) ALL NODES;

DELETE /*+DIRECT*/ FROM NS_Transaction_lines_base_deleted_1 where exists ( select 1 from NS_Transaction_lines_stg_Tmp_Key t1 where NS_Transaction_lines_base_deleted_1.transaction_id=t1.transaction_id and NS_Transaction_lines_base_deleted_1.transaction_line_id=t1.transaction_line_id);

CREATE LOCAL TEMP TABLE NS_Transaction_lines_base_deleted ON COMMIT PRESERVE ROWS AS
(
select distinct * from swt_rpt_base.NS_Transaction_lines where Is_Deleted <> 'true' and exists (select 1 from NS_Transaction_lines_base_deleted_1 t1 where swt_rpt_base.NS_Transaction_lines.transaction_id=t1.transaction_id and swt_rpt_base.NS_Transaction_lines.transaction_line_id=t1.transaction_line_id))
SEGMENTED BY HASH(transaction_line_id,transaction_id) ALL NODES;

INSERT /*+DIRECT*/ INTO NS_Transaction_lines_base_deleted select distinct * from swt_rpt_base.NS_Transaction_lines where Is_Deleted <> 'true' and transaction_id in (select distinct transaction_id from swt_rpt_base.NS_Transactions where is_deleted='true');


DELETE /*+DIRECT*/ FROM swt_rpt_base.NS_Transaction_lines where Is_Deleted <> 'true' and exists ( select 1 from NS_Transaction_lines_base_deleted_1 t1
where swt_rpt_base.NS_Transaction_lines.transaction_line_id=t1.transaction_line_id and 
swt_rpt_base.NS_Transaction_lines.transaction_id=t1.transaction_id);


DELETE /*+DIRECT*/ FROM swt_rpt_base.NS_Transaction_lines where Is_Deleted <> 'true' and transaction_id in (select distinct transaction_id from swt_rpt_base.NS_Transactions where is_deleted='true');


INSERT /*+DIRECT*/ INTO swt_rpt_base.NS_Transaction_lines_deleted_Ids 
(
transaction_id,
transaction_line_id,
SWT_INS_DT,
status
)
SELECT
transaction_id,
transaction_line_id,
SYSDATE,
'deleted'
FROM NS_Transaction_lines_base_deleted;


INSERT /*+DIRECT*/ INTO swt_rpt_base.NS_Transaction_lines
(
account_id
,alt_sales_amount
,amortization_residual
,amount
,amount_foreign
,amount_foreign_linked
,amount_linked
,amount_pending
,amount_settlement
,amount_taxable
,amount_taxed
,bill_variance_status
,bom_quantity
,catch_up_period_id
,charge_type
,class_id
,company_id
,component_id
,component_yield
,cost_estimate_type
,date_cleared
,date_closed
,date_last_modified
,date_last_modified_gmt
,date_revenue_committed
,delay_rev_rec
,department_id
,do_not_display_line
,do_not_print_line
,do_restock
,estimated_cost
,estimated_cost_foreign
,expected_receipt_date
,expense_category_id
,gl_number
,gl_sequence
,gl_sequence_id
,gross_amount
,has_cost_line
,is_allocation
,is_amortization_rev_rec
,is_commitment_confirmed
,is_cost_line
,is_exclude_from_rate_request
,is_fx_variance
,is_item_value_adjustment
,is_landed_cost
,is_scrap
,is_vsoe_allocation_line
,isbillable
,iscleared
,isnonreimbursable
,istaxable
,item_count
,item_id
,item_received
,item_source
,item_unit_price
,kit_part_number
,landed_cost_source_line_id
,location_id
,match_bill_to_receipt
,memo
,needs_revenue_element
,net_amount
,net_amount_foreign
,non_posting_line
,number_billed
,operation_sequence_number
,order_priority
,payment_method_id
,payroll_item_id
,payroll_wage_base_amount
,payroll_year_to_date_amount
,period_closed
,project_task_id
,purchase_contract_id
,quantity_committed
,quantity_packed
,quantity_picked
,quantity_received_in_shipment
,receivebydate
,reimbursement_type
,related_company_id
,rev_rec_end_date
,rev_rec_rule_id
,rev_rec_start_date
,revenue_element_id
,schedule_id
,shipdate
,shipment_received
,subscription_line_id
,subsidiary_id
,tax_item_id
,tax_type
,term_in_months
,tobeemailed
,tobefaxed
,tobeprinted
,transaction_discount_line
,transaction_id
,transaction_line_id
,transaction_order
,transfer_order_item_line
,transfer_order_line_type
,unit_cost_override
,unit_of_measure_id
,vsoe_allocation
,vsoe_amt
,vsoe_deferral
,vsoe_delivered
,vsoe_discount
,vsoe_price
,additional_discount_
,additional_discount_amount
,adjustment_field
,adjustment_tax_code_id
,appliance_drop_ship_po_
,apply_wh_tax
,asset_id
,authority_currency_code
,billable_engagement_name
,billable_expense_category
,billable_expense_engagement
,billable_item_name
,billable_units_of_measure
,billing_frequency_id
,bill_of_lading_number
,booking_date
,box_number
,charge_type_id
,code_of_supply_id
,contractual_discount_
,contractual_discount_amount
,contract_end_date
,contract_start_date
,contract_term
,course_type_id
,display_quantity
,employee_token_id
,end_user_id
,eu_triangulation
,exempt_id
,expense_account_id
,export_to_openair
,fixed_asset_id
,functional_area_id
,goods_and_services_indicato_id
,gross_list_price
,custom_functional_area_id
,custom_lcci_id
,custom_profit_center_id
,ic_item
,ic_je_number_id
,idt_product_tax_code
,intercompany
,intercompany_discount_
,je_expense_type
,jurisdiction_text
,lcci_id
,line_item_id
,markup_amount
,notc_id
,openair_assigned_users
,openair_billing_rule_id
,openair_charge_type_id
,openair_expense_report_line_i
,openair_gsthst
,openair_invoice_line_id
,openair_journal_entry_creatio
,openair_journal_entry_error
,openair_journal_entry_error_m
,openair_line_from_openair
,openair_loaded_cost_class_id
,openair_loaded_cost_credit__id
,openair_loaded_cost_debit_a_id
,openair_loaded_cost_departm_id
,openair_loaded_cost_locatio_id
,openair_loaded_cost_subsidi_id
,openair_phases_ancestry
,openair_phase_name
,openair_primary_loaded_cost
,openair_primary_loaded_cost_id
,openair_project_task_id
,openair_project_task_id_numbe
,openair_pst
,openair_quantity_from__invoic
,openair_rate
,openair_rev_rec_rule_id
,openair_secondary_loaded_cost
,openair_secondary_loaded_co_id
,openair_task_assignment_id
,openair_task_assignment_plann
,openair_task_id
,openair_task_name
,openair_tax
,openair_tertiary_loaded_cost
,openair_tertiary_loaded_cos_id
,openair_timesheet_start_date
,openair_time_entry_id
,originator_journal_tran_typ_id
,originator_transaction_intern
,partner_discount_
,partner_discount_amount
,pid
,pl_id
,posted
,pretax_amt
,pretax_amt_quantity
,price_type_id
,product_subtype
,product_type
,profit_center_id
,project_task_type_id
,promotional_discount_
,promotional_discount_amount
,schedule_id_0
,serial_number
,related_license_id
,related_asset_id
,reason_id
,registration_unique_id
,ship_date
,statistical_procedure_for_p_id
,statistical_procedure_for_s_id
,statistical_value
,statistical_value__base_curre
,task_type_id
,tax_amt
,tax_exemption_reason_code_id
,tax_rate
,tax_rate_code
,tax_type_0
,trade_discount_
,trade_item_code_id
,trade_item_description
,user_quantity
,vendor_tax
,vsoe_customer_type_id
,vsoe_deal_size_id
,vsoe_geography_id
,vsoe_lower_band_
,vsoe_pricing_method_id
,vsoe_related_line_item_number
,vsoe_upper_band_
,wdem_settlement_id
,withholding_tax_amount
,withholding_tax_amount__expen
,withholding_tax_base_amount
,withholding_tax_base_amount__
,withholding_tax_code_id
,withholding_tax_code__expen_id
,withholding_tax_line
,withholding_tax_line__expense
,withholding_tax_rate
,withholding_tax_rate__expense
,wt_customer_id
,wt_employee_id
,wt_vendor_id
,apttus_line_id
,apttus_order_
,apttus_order_id
,billing_plan_id
,billing_schedule_id
,ela_agreement_name
,item_id_0
,item_name
,item_units_name
,legacy_equipment_
,legacy_sales_doc_id
,mark_up_
,nibs_id
,po_
,product_revenue_subtype
,revenue_element_id_0
,shipping_group_id
,unit_list_price
,uplift_
,uplift_amount
,SWT_INS_DT
,credit_rebill_requires_unbill
,product_subtype_external_id
,product_type_external_id
,rebilled_line
,unique_key
,sales_order_id
,quote_line_item_id
,item_label
,cmt_id
,sales_team_id
,sales_order_label
,Is_Deleted
,SWT_Ins_Date_Backup
)
SELECT
account_id
,alt_sales_amount
,amortization_residual
,amount
,amount_foreign
,amount_foreign_linked
,amount_linked
,amount_pending
,amount_settlement
,amount_taxable
,amount_taxed
,bill_variance_status
,bom_quantity
,catch_up_period_id
,charge_type
,class_id
,company_id
,component_id
,component_yield
,cost_estimate_type
,date_cleared
,date_closed
,date_last_modified
,date_last_modified_gmt
,date_revenue_committed
,delay_rev_rec
,department_id
,do_not_display_line
,do_not_print_line
,do_restock
,estimated_cost
,estimated_cost_foreign
,expected_receipt_date
,expense_category_id
,gl_number
,gl_sequence
,gl_sequence_id
,gross_amount
,has_cost_line
,is_allocation
,is_amortization_rev_rec
,is_commitment_confirmed
,is_cost_line
,is_exclude_from_rate_request
,is_fx_variance
,is_item_value_adjustment
,is_landed_cost
,is_scrap
,is_vsoe_allocation_line
,isbillable
,iscleared
,isnonreimbursable
,istaxable
,item_count
,item_id
,item_received
,item_source
,item_unit_price
,kit_part_number
,landed_cost_source_line_id
,location_id
,match_bill_to_receipt
,memo
,needs_revenue_element
,net_amount
,net_amount_foreign
,non_posting_line
,number_billed
,operation_sequence_number
,order_priority
,payment_method_id
,payroll_item_id
,payroll_wage_base_amount
,payroll_year_to_date_amount
,period_closed
,project_task_id
,purchase_contract_id
,quantity_committed
,quantity_packed
,quantity_picked
,quantity_received_in_shipment
,receivebydate
,reimbursement_type
,related_company_id
,rev_rec_end_date
,rev_rec_rule_id
,rev_rec_start_date
,revenue_element_id
,schedule_id
,shipdate
,shipment_received
,subscription_line_id
,subsidiary_id
,tax_item_id
,tax_type
,term_in_months
,tobeemailed
,tobefaxed
,tobeprinted
,transaction_discount_line
,transaction_id
,transaction_line_id
,transaction_order
,transfer_order_item_line
,transfer_order_line_type
,unit_cost_override
,unit_of_measure_id
,vsoe_allocation
,vsoe_amt
,vsoe_deferral
,vsoe_delivered
,vsoe_discount
,vsoe_price
,additional_discount_
,additional_discount_amount
,adjustment_field
,adjustment_tax_code_id
,appliance_drop_ship_po_
,apply_wh_tax
,asset_id
,authority_currency_code
,billable_engagement_name
,billable_expense_category
,billable_expense_engagement
,billable_item_name
,billable_units_of_measure
,billing_frequency_id
,bill_of_lading_number
,booking_date
,box_number
,charge_type_id
,code_of_supply_id
,contractual_discount_
,contractual_discount_amount
,contract_end_date
,contract_start_date
,contract_term
,course_type_id
,display_quantity
,employee_token_id
,end_user_id
,eu_triangulation
,exempt_id
,expense_account_id
,export_to_openair
,fixed_asset_id
,functional_area_id
,goods_and_services_indicato_id
,gross_list_price
,custom_functional_area_id
,custom_lcci_id
,custom_profit_center_id
,ic_item
,ic_je_number_id
,idt_product_tax_code
,intercompany
,intercompany_discount_
,je_expense_type
,jurisdiction_text
,lcci_id
,line_item_id
,markup_amount
,notc_id
,openair_assigned_users
,openair_billing_rule_id
,openair_charge_type_id
,openair_expense_report_line_i
,openair_gsthst
,openair_invoice_line_id
,openair_journal_entry_creatio
,openair_journal_entry_error
,openair_journal_entry_error_m
,openair_line_from_openair
,openair_loaded_cost_class_id
,openair_loaded_cost_credit__id
,openair_loaded_cost_debit_a_id
,openair_loaded_cost_departm_id
,openair_loaded_cost_locatio_id
,openair_loaded_cost_subsidi_id
,openair_phases_ancestry
,openair_phase_name
,openair_primary_loaded_cost
,openair_primary_loaded_cost_id
,openair_project_task_id
,openair_project_task_id_numbe
,openair_pst
,openair_quantity_from__invoic
,openair_rate
,openair_rev_rec_rule_id
,openair_secondary_loaded_cost
,openair_secondary_loaded_co_id
,openair_task_assignment_id
,openair_task_assignment_plann
,openair_task_id
,openair_task_name
,openair_tax
,openair_tertiary_loaded_cost
,openair_tertiary_loaded_cos_id
,openair_timesheet_start_date
,openair_time_entry_id
,originator_journal_tran_typ_id
,originator_transaction_intern
,partner_discount_
,partner_discount_amount
,pid
,pl_id
,posted
,pretax_amt
,pretax_amt_quantity
,price_type_id
,product_subtype
,product_type
,profit_center_id
,project_task_type_id
,promotional_discount_
,promotional_discount_amount
,schedule_id_0
,serial_number
,related_license_id
,related_asset_id
,reason_id
,registration_unique_id
,ship_date
,statistical_procedure_for_p_id
,statistical_procedure_for_s_id
,statistical_value
,statistical_value__base_curre
,task_type_id
,tax_amt
,tax_exemption_reason_code_id
,tax_rate
,tax_rate_code
,tax_type_0
,trade_discount_
,trade_item_code_id
,trade_item_description
,user_quantity
,vendor_tax
,vsoe_customer_type_id
,vsoe_deal_size_id
,vsoe_geography_id
,vsoe_lower_band_
,vsoe_pricing_method_id
,vsoe_related_line_item_number
,vsoe_upper_band_
,wdem_settlement_id
,withholding_tax_amount
,withholding_tax_amount__expen
,withholding_tax_base_amount
,withholding_tax_base_amount__
,withholding_tax_code_id
,withholding_tax_code__expen_id
,withholding_tax_line
,withholding_tax_line__expense
,withholding_tax_rate
,withholding_tax_rate__expense
,wt_customer_id
,wt_employee_id
,wt_vendor_id
,apttus_line_id
,apttus_order_
,apttus_order_id
,billing_plan_id
,billing_schedule_id
,ela_agreement_name
,item_id_0
,item_name
,item_units_name
,legacy_equipment_
,legacy_sales_doc_id
,mark_up_
,nibs_id
,po_
,product_revenue_subtype
,revenue_element_id_0
,shipping_group_id
,unit_list_price
,uplift_
,uplift_amount
,sysdate as SWT_INS_DT
,credit_rebill_requires_unbill
,product_subtype_external_id
,product_type_external_id
,rebilled_line
,unique_key
,sales_order_id
,quote_line_item_id
,item_label
,cmt_id
,sales_team_id
,sales_order_label
,'true'
,SWT_INS_DT
FROM NS_Transaction_lines_base_deleted;



CREATE LOCAL TEMP TABLE NS_Transaction_lines_base_active ON COMMIT PRESERVE ROWS AS
(
SELECT DISTINCT * FROM swt_rpt_base.NS_Transaction_lines_deleted_Ids t1 where status='deleted' and exists ( select 1 from swt_rpt_base.NS_Transaction_lines t2 where t1.transaction_id=t2.transaction_id and t1.transaction_line_id=t2.transaction_line_id and t2.Is_Deleted ='false'))
SEGMENTED BY HASH(transaction_id) ALL NODES;

INSERT /*+DIRECT*/ INTO swt_rpt_base.NS_Transaction_lines_deleted_Ids 
(
transaction_id,
transaction_line_id,
SWT_INS_DT,
status
)
SELECT
transaction_id,
transaction_line_id,
SYSDATE,
'activated'
FROM NS_Transaction_lines_base_active;


/* Inserting base table updated_lines data into Historical Table */

insert /*+DIRECT*/ into swt_rpt_stg.NS_Transaction_lines_Hist
(
account_id
,alt_sales_amount
,amortization_residual
,amount
,amount_foreign
,amount_foreign_linked
,amount_linked
,amount_pending
,amount_settlement
,amount_taxable
,amount_taxed
,bill_variance_status
,bom_quantity
,catch_up_period_id
,charge_type
,class_id
,company_id
,component_id
,component_yield
,cost_estimate_type
,date_cleared
,date_closed
,date_last_modified
,date_last_modified_gmt
,date_revenue_committed
,delay_rev_rec
,department_id
,do_not_display_line
,do_not_print_line
,do_restock
,estimated_cost
,estimated_cost_foreign
,expected_receipt_date
,expense_category_id
,gl_number
,gl_sequence
,gl_sequence_id
,gross_amount
,has_cost_line
,is_allocation
,is_amortization_rev_rec
,is_commitment_confirmed
,is_cost_line
,is_exclude_from_rate_request
,is_fx_variance
,is_item_value_adjustment
,is_landed_cost
,is_scrap
,is_vsoe_allocation_line
,isbillable
,iscleared
,isnonreimbursable
,istaxable
,item_count
,item_id
,item_received
,item_source
,item_unit_price
,kit_part_number
,landed_cost_source_line_id
,location_id
,match_bill_to_receipt
,memo
,needs_revenue_element
,net_amount
,net_amount_foreign
,non_posting_line
,number_billed
,operation_sequence_number
,order_priority
,payment_method_id
,payroll_item_id
,payroll_wage_base_amount
,payroll_year_to_date_amount
,period_closed
,project_task_id
,purchase_contract_id
,quantity_committed
,quantity_packed
,quantity_picked
,quantity_received_in_shipment
,receivebydate
,reimbursement_type
,related_company_id
,rev_rec_end_date
,rev_rec_rule_id
,rev_rec_start_date
,revenue_element_id
,schedule_id
,shipdate
,shipment_received
,subscription_line_id
,subsidiary_id
,tax_item_id
,tax_type
,term_in_months
,tobeemailed
,tobefaxed
,tobeprinted
,transaction_discount_line
,transaction_id
,transaction_line_id
,transaction_order
,transfer_order_item_line
,transfer_order_line_type
,unit_cost_override
,unit_of_measure_id
,vsoe_allocation
,vsoe_amt
,vsoe_deferral
,vsoe_delivered
,vsoe_discount
,vsoe_price
,additional_discount_
,additional_discount_amount
,adjustment_field
,adjustment_tax_code_id
,appliance_drop_ship_po_
,apply_wh_tax
,asset_id
,authority_currency_code
,billable_engagement_name
,billable_expense_category
,billable_expense_engagement
,billable_item_name
,billable_units_of_measure
,billing_frequency_id
,bill_of_lading_number
,booking_date
,box_number
,charge_type_id
,code_of_supply_id
,contractual_discount_
,contractual_discount_amount
,contract_end_date
,contract_start_date
,contract_term
,course_type_id
,display_quantity
,employee_token_id
,end_user_id
,eu_triangulation
,exempt_id
,expense_account_id
,export_to_openair
,fixed_asset_id
,functional_area_id
,goods_and_services_indicato_id
,gross_list_price
,custom_functional_area_id
,custom_lcci_id
,custom_profit_center_id
,ic_item
,ic_je_number_id
,idt_product_tax_code
,intercompany
,intercompany_discount_
,je_expense_type
,jurisdiction_text
,lcci_id
,line_item_id
,markup_amount
,notc_id
,openair_assigned_users
,openair_billing_rule_id
,openair_charge_type_id
,openair_expense_report_line_i
,openair_gsthst
,openair_invoice_line_id
,openair_journal_entry_creatio
,openair_journal_entry_error
,openair_journal_entry_error_m
,openair_line_from_openair
,openair_loaded_cost_class_id
,openair_loaded_cost_credit__id
,openair_loaded_cost_debit_a_id
,openair_loaded_cost_departm_id
,openair_loaded_cost_locatio_id
,openair_loaded_cost_subsidi_id
,openair_phases_ancestry
,openair_phase_name
,openair_primary_loaded_cost
,openair_primary_loaded_cost_id
,openair_project_task_id
,openair_project_task_id_numbe
,openair_pst
,openair_quantity_from__invoic
,openair_rate
,openair_rev_rec_rule_id
,openair_secondary_loaded_cost
,openair_secondary_loaded_co_id
,openair_task_assignment_id
,openair_task_assignment_plann
,openair_task_id
,openair_task_name
,openair_tax
,openair_tertiary_loaded_cost
,openair_tertiary_loaded_cos_id
,openair_timesheet_start_date
,openair_time_entry_id
,originator_journal_tran_typ_id
,originator_transaction_intern
,partner_discount_
,partner_discount_amount
,pid
,pl_id
,posted
,pretax_amt
,pretax_amt_quantity
,price_type_id
,product_subtype
,product_type
,profit_center_id
,project_task_type_id
,promotional_discount_
,promotional_discount_amount
,schedule_id_0
,serial_number
,related_license_id
,related_asset_id
,reason_id
,registration_unique_id
,ship_date
,statistical_procedure_for_p_id
,statistical_procedure_for_s_id
,statistical_value
,statistical_value__base_curre
,task_type_id
,tax_amt
,tax_exemption_reason_code_id
,tax_rate
,tax_rate_code
,tax_type_0
,trade_discount_
,trade_item_code_id
,trade_item_description
,user_quantity
,vendor_tax
,vsoe_customer_type_id
,vsoe_deal_size_id
,vsoe_geography_id
,vsoe_lower_band_
,vsoe_pricing_method_id
,vsoe_related_line_item_number
,vsoe_upper_band_
,wdem_settlement_id
,withholding_tax_amount
,withholding_tax_amount__expen
,withholding_tax_base_amount
,withholding_tax_base_amount__
,withholding_tax_code_id
,withholding_tax_code__expen_id
,withholding_tax_line
,withholding_tax_line__expense
,withholding_tax_rate
,withholding_tax_rate__expense
,wt_customer_id
,wt_employee_id
,wt_vendor_id
,apttus_line_id
,apttus_order_
,apttus_order_id
,billing_plan_id
,billing_schedule_id
,ela_agreement_name
,item_id_0
,item_name
,item_units_name
,legacy_equipment_
,legacy_sales_doc_id
,mark_up_
,nibs_id
,po_
,product_revenue_subtype
,revenue_element_id_0
,shipping_group_id
,unit_list_price
,uplift_
,uplift_amount
,CREDIT_REBILL_REQUIRES_UNBILL
,PRODUCT_SUBTYPE_EXTERNAL_ID
,PRODUCT_TYPE_EXTERNAL_ID
,REBILLED_LINE
,UNIQUE_KEY
,sales_order_id
,quote_line_item_id
,item_label
,cmt_id
,sales_team_id
,sales_order_label
,LD_DT
,SWT_INS_DT
,d_source
--,SWT_Ins_Date_Backup
)
select
account_id
,alt_sales_amount
,amortization_residual
,amount
,amount_foreign
,amount_foreign_linked
,amount_linked
,amount_pending
,amount_settlement
,amount_taxable
,amount_taxed
,bill_variance_status
,bom_quantity
,catch_up_period_id
,charge_type
,class_id
,company_id
,component_id
,component_yield
,cost_estimate_type
,date_cleared
,date_closed
,date_last_modified
,date_last_modified_gmt
,date_revenue_committed
,delay_rev_rec
,department_id
,do_not_display_line
,do_not_print_line
,do_restock
,estimated_cost
,estimated_cost_foreign
,expected_receipt_date
,expense_category_id
,gl_number
,gl_sequence
,gl_sequence_id
,gross_amount
,has_cost_line
,is_allocation
,is_amortization_rev_rec
,is_commitment_confirmed
,is_cost_line
,is_exclude_from_rate_request
,is_fx_variance
,is_item_value_adjustment
,is_landed_cost
,is_scrap
,is_vsoe_allocation_line
,isbillable
,iscleared
,isnonreimbursable
,istaxable
,item_count
,item_id
,item_received
,item_source
,item_unit_price
,kit_part_number
,landed_cost_source_line_id
,location_id
,match_bill_to_receipt
,memo
,needs_revenue_element
,net_amount
,net_amount_foreign
,non_posting_line
,number_billed
,operation_sequence_number
,order_priority
,payment_method_id
,payroll_item_id
,payroll_wage_base_amount
,payroll_year_to_date_amount
,period_closed
,project_task_id
,purchase_contract_id
,quantity_committed
,quantity_packed
,quantity_picked
,quantity_received_in_shipment
,receivebydate
,reimbursement_type
,related_company_id
,rev_rec_end_date
,rev_rec_rule_id
,rev_rec_start_date
,revenue_element_id
,schedule_id
,shipdate
,shipment_received
,subscription_line_id
,subsidiary_id
,tax_item_id
,tax_type
,term_in_months
,tobeemailed
,tobefaxed
,tobeprinted
,transaction_discount_line
,transaction_id
,transaction_line_id
,transaction_order
,transfer_order_item_line
,transfer_order_line_type
,unit_cost_override
,unit_of_measure_id
,vsoe_allocation
,vsoe_amt
,vsoe_deferral
,vsoe_delivered
,vsoe_discount
,vsoe_price
,additional_discount_
,additional_discount_amount
,adjustment_field
,adjustment_tax_code_id
,appliance_drop_ship_po_
,apply_wh_tax
,asset_id
,authority_currency_code
,billable_engagement_name
,billable_expense_category
,billable_expense_engagement
,billable_item_name
,billable_units_of_measure
,billing_frequency_id
,bill_of_lading_number
,booking_date
,box_number
,charge_type_id
,code_of_supply_id
,contractual_discount_
,contractual_discount_amount
,contract_end_date
,contract_start_date
,contract_term
,course_type_id
,display_quantity
,employee_token_id
,end_user_id
,eu_triangulation
,exempt_id
,expense_account_id
,export_to_openair
,fixed_asset_id
,functional_area_id
,goods_and_services_indicato_id
,gross_list_price
,custom_functional_area_id
,custom_lcci_id
,custom_profit_center_id
,ic_item
,ic_je_number_id
,idt_product_tax_code
,intercompany
,intercompany_discount_
,je_expense_type
,jurisdiction_text
,lcci_id
,line_item_id
,markup_amount
,notc_id
,openair_assigned_users
,openair_billing_rule_id
,openair_charge_type_id
,openair_expense_report_line_i
,openair_gsthst
,openair_invoice_line_id
,openair_journal_entry_creatio
,openair_journal_entry_error
,openair_journal_entry_error_m
,openair_line_from_openair
,openair_loaded_cost_class_id
,openair_loaded_cost_credit__id
,openair_loaded_cost_debit_a_id
,openair_loaded_cost_departm_id
,openair_loaded_cost_locatio_id
,openair_loaded_cost_subsidi_id
,openair_phases_ancestry
,openair_phase_name
,openair_primary_loaded_cost
,openair_primary_loaded_cost_id
,openair_project_task_id
,openair_project_task_id_numbe
,openair_pst
,openair_quantity_from__invoic
,openair_rate
,openair_rev_rec_rule_id
,openair_secondary_loaded_cost
,openair_secondary_loaded_co_id
,openair_task_assignment_id
,openair_task_assignment_plann
,openair_task_id
,openair_task_name
,openair_tax
,openair_tertiary_loaded_cost
,openair_tertiary_loaded_cos_id
,openair_timesheet_start_date
,openair_time_entry_id
,originator_journal_tran_typ_id
,originator_transaction_intern
,partner_discount_
,partner_discount_amount
,pid
,pl_id
,posted
,pretax_amt
,pretax_amt_quantity
,price_type_id
,product_subtype
,product_type
,profit_center_id
,project_task_type_id
,promotional_discount_
,promotional_discount_amount
,schedule_id_0
,serial_number
,related_license_id
,related_asset_id
,reason_id
,registration_unique_id
,ship_date
,statistical_procedure_for_p_id
,statistical_procedure_for_s_id
,statistical_value
,statistical_value__base_curre
,task_type_id
,tax_amt
,tax_exemption_reason_code_id
,tax_rate
,tax_rate_code
,tax_type_0
,trade_discount_
,trade_item_code_id
,trade_item_description
,user_quantity
,vendor_tax
,vsoe_customer_type_id
,vsoe_deal_size_id
,vsoe_geography_id
,vsoe_lower_band_
,vsoe_pricing_method_id
,vsoe_related_line_item_number
,vsoe_upper_band_
,wdem_settlement_id
,withholding_tax_amount
,withholding_tax_amount__expen
,withholding_tax_base_amount
,withholding_tax_base_amount__
,withholding_tax_code_id
,withholding_tax_code__expen_id
,withholding_tax_line
,withholding_tax_line__expense
,withholding_tax_rate
,withholding_tax_rate__expense
,wt_customer_id
,wt_employee_id
,wt_vendor_id
,apttus_line_id
,apttus_order_
,apttus_order_id
,billing_plan_id
,billing_schedule_id
,ela_agreement_name
,item_id_0
,item_name
,item_units_name
,legacy_equipment_
,legacy_sales_doc_id
,mark_up_
,nibs_id
,po_
,product_revenue_subtype
,revenue_element_id_0
,shipping_group_id
,unit_list_price
,uplift_
,uplift_amount
,CREDIT_REBILL_REQUIRES_UNBILL
,PRODUCT_SUBTYPE_EXTERNAL_ID
,PRODUCT_TYPE_EXTERNAL_ID
,REBILLED_LINE
,UNIQUE_KEY
,sales_order_id
,quote_line_item_id
,item_label
,cmt_id
,sales_team_id
,sales_order_label
,SYSDATE AS LD_DT
,SWT_INS_DT
,'base'
--,SWT_Ins_Date_Backup
FROM swt_rpt_base.NS_Transaction_lines WHERE EXISTS
(SELECT 1 FROM NS_Transaction_lines_stg_Tmp_Line STG 
WHERE STG.transaction_line_id = NS_Transaction_lines.transaction_line_id AND STG.transaction_id=NS_Transaction_lines.transaction_id);

DELETE /*+DIRECT*/ FROM "swt_rpt_base".NS_Transaction_lines WHERE EXISTS
(SELECT 1 FROM NS_Transaction_lines_stg_Tmp_line STG 
WHERE STG.transaction_line_id = NS_Transaction_lines.transaction_line_id AND STG.transaction_id=NS_Transaction_lines.transaction_id);


INSERT /*+DIRECT*/ INTO "swt_rpt_base".NS_Transaction_lines
(
account_id
,alt_sales_amount
,amortization_residual
,amount
,amount_foreign
,amount_foreign_linked
,amount_linked
,amount_pending
,amount_settlement
,amount_taxable
,amount_taxed
,bill_variance_status
,bom_quantity
,catch_up_period_id
,charge_type
,class_id
,company_id
,component_id
,component_yield
,cost_estimate_type
,date_cleared
,date_closed
,date_last_modified
,date_last_modified_gmt
,date_revenue_committed
,delay_rev_rec
,department_id
,do_not_display_line
,do_not_print_line
,do_restock
,estimated_cost
,estimated_cost_foreign
,expected_receipt_date
,expense_category_id
,gl_number
,gl_sequence
,gl_sequence_id
,gross_amount
,has_cost_line
,is_allocation
,is_amortization_rev_rec
,is_commitment_confirmed
,is_cost_line
,is_exclude_from_rate_request
,is_fx_variance
,is_item_value_adjustment
,is_landed_cost
,is_scrap
,is_vsoe_allocation_line
,isbillable
,iscleared
,isnonreimbursable
,istaxable
,item_count
,item_id
,item_received
,item_source
,item_unit_price
,kit_part_number
,landed_cost_source_line_id
,location_id
,match_bill_to_receipt
,memo
,needs_revenue_element
,net_amount
,net_amount_foreign
,non_posting_line
,number_billed
,operation_sequence_number
,order_priority
,payment_method_id
,payroll_item_id
,payroll_wage_base_amount
,payroll_year_to_date_amount
,period_closed
,project_task_id
,purchase_contract_id
,quantity_committed
,quantity_packed
,quantity_picked
,quantity_received_in_shipment
,receivebydate
,reimbursement_type
,related_company_id
,rev_rec_end_date
,rev_rec_rule_id
,rev_rec_start_date
,revenue_element_id
,schedule_id
,shipdate
,shipment_received
,subscription_line_id
,subsidiary_id
,tax_item_id
,tax_type
,term_in_months
,tobeemailed
,tobefaxed
,tobeprinted
,transaction_discount_line
,transaction_id
,transaction_line_id
,transaction_order
,transfer_order_item_line
,transfer_order_line_type
,unit_cost_override
,unit_of_measure_id
,vsoe_allocation
,vsoe_amt
,vsoe_deferral
,vsoe_delivered
,vsoe_discount
,vsoe_price
,additional_discount_
,additional_discount_amount
,adjustment_field
,adjustment_tax_code_id
,appliance_drop_ship_po_
,apply_wh_tax
,asset_id
,authority_currency_code
,billable_engagement_name
,billable_expense_category
,billable_expense_engagement
,billable_item_name
,billable_units_of_measure
,billing_frequency_id
,bill_of_lading_number
,booking_date
,box_number
,charge_type_id
,code_of_supply_id
,contractual_discount_
,contractual_discount_amount
,contract_end_date
,contract_start_date
,contract_term
,course_type_id
,display_quantity
,employee_token_id
,end_user_id
,eu_triangulation
,exempt_id
,expense_account_id
,export_to_openair
,fixed_asset_id
,functional_area_id
,goods_and_services_indicato_id
,gross_list_price
,custom_functional_area_id
,custom_lcci_id
,custom_profit_center_id
,ic_item
,ic_je_number_id
,idt_product_tax_code
,intercompany
,intercompany_discount_
,je_expense_type
,jurisdiction_text
,lcci_id
,line_item_id
,markup_amount
,notc_id
,openair_assigned_users
,openair_billing_rule_id
,openair_charge_type_id
,openair_expense_report_line_i
,openair_gsthst
,openair_invoice_line_id
,openair_journal_entry_creatio
,openair_journal_entry_error
,openair_journal_entry_error_m
,openair_line_from_openair
,openair_loaded_cost_class_id
,openair_loaded_cost_credit__id
,openair_loaded_cost_debit_a_id
,openair_loaded_cost_departm_id
,openair_loaded_cost_locatio_id
,openair_loaded_cost_subsidi_id
,openair_phases_ancestry
,openair_phase_name
,openair_primary_loaded_cost
,openair_primary_loaded_cost_id
,openair_project_task_id
,openair_project_task_id_numbe
,openair_pst
,openair_quantity_from__invoic
,openair_rate
,openair_rev_rec_rule_id
,openair_secondary_loaded_cost
,openair_secondary_loaded_co_id
,openair_task_assignment_id
,openair_task_assignment_plann
,openair_task_id
,openair_task_name
,openair_tax
,openair_tertiary_loaded_cost
,openair_tertiary_loaded_cos_id
,openair_timesheet_start_date
,openair_time_entry_id
,originator_journal_tran_typ_id
,originator_transaction_intern
,partner_discount_
,partner_discount_amount
,pid
,pl_id
,posted
,pretax_amt
,pretax_amt_quantity
,price_type_id
,product_subtype
,product_type
,profit_center_id
,project_task_type_id
,promotional_discount_
,promotional_discount_amount
,schedule_id_0
,serial_number
,related_license_id
,related_asset_id
,reason_id
,registration_unique_id
,ship_date
,statistical_procedure_for_p_id
,statistical_procedure_for_s_id
,statistical_value
,statistical_value__base_curre
,task_type_id
,tax_amt
,tax_exemption_reason_code_id
,tax_rate
,tax_rate_code
,tax_type_0
,trade_discount_
,trade_item_code_id
,trade_item_description
,user_quantity
,vendor_tax
,vsoe_customer_type_id
,vsoe_deal_size_id
,vsoe_geography_id
,vsoe_lower_band_
,vsoe_pricing_method_id
,vsoe_related_line_item_number
,vsoe_upper_band_
,wdem_settlement_id
,withholding_tax_amount
,withholding_tax_amount__expen
,withholding_tax_base_amount
,withholding_tax_base_amount__
,withholding_tax_code_id
,withholding_tax_code__expen_id
,withholding_tax_line
,withholding_tax_line__expense
,withholding_tax_rate
,withholding_tax_rate__expense
,wt_customer_id
,wt_employee_id
,wt_vendor_id
,apttus_line_id
,apttus_order_
,apttus_order_id
,billing_plan_id
,billing_schedule_id
,ela_agreement_name
,item_id_0
,item_name
,item_units_name
,legacy_equipment_
,legacy_sales_doc_id
,mark_up_
,nibs_id
,po_
,product_revenue_subtype
,revenue_element_id_0
,shipping_group_id
,unit_list_price
,uplift_
,uplift_amount
,CREDIT_REBILL_REQUIRES_UNBILL
,PRODUCT_SUBTYPE_EXTERNAL_ID
,PRODUCT_TYPE_EXTERNAL_ID
,REBILLED_LINE
,UNIQUE_KEY
,sales_order_id
,quote_line_item_id
,item_label
,cmt_id
,sales_team_id
,sales_order_label
,SWT_INS_DT
,SWT_Ins_Date_Backup
)
SELECT DISTINCT 
account_id
,alt_sales_amount
,amortization_residual
,amount
,amount_foreign
,amount_foreign_linked
,amount_linked
,amount_pending
,amount_settlement
,amount_taxable
,amount_taxed
,bill_variance_status
,bom_quantity
,catch_up_period_id
,charge_type
,class_id
,company_id
,component_id
,component_yield
,cost_estimate_type
,date_cleared
,date_closed
,date_last_modified
,date_last_modified_gmt
,date_revenue_committed
,delay_rev_rec
,department_id
,do_not_display_line
,do_not_print_line
,do_restock
,estimated_cost
,estimated_cost_foreign
,expected_receipt_date
,expense_category_id
,gl_number
,gl_sequence
,gl_sequence_id
,gross_amount
,has_cost_line
,is_allocation
,is_amortization_rev_rec
,is_commitment_confirmed
,is_cost_line
,is_exclude_from_rate_request
,is_fx_variance
,is_item_value_adjustment
,is_landed_cost
,is_scrap
,is_vsoe_allocation_line
,isbillable
,iscleared
,isnonreimbursable
,istaxable
,item_count
,item_id
,item_received
,item_source
,item_unit_price
,kit_part_number
,landed_cost_source_line_id
,location_id
,match_bill_to_receipt
,memo
,needs_revenue_element
,net_amount
,net_amount_foreign
,non_posting_line
,number_billed
,operation_sequence_number
,order_priority
,payment_method_id
,payroll_item_id
,payroll_wage_base_amount
,payroll_year_to_date_amount
,period_closed
,project_task_id
,purchase_contract_id
,quantity_committed
,quantity_packed
,quantity_picked
,quantity_received_in_shipment
,receivebydate
,reimbursement_type
,related_company_id
,rev_rec_end_date
,rev_rec_rule_id
,rev_rec_start_date
,revenue_element_id
,schedule_id
,shipdate
,shipment_received
,subscription_line_id
,subsidiary_id
,tax_item_id
,tax_type
,term_in_months
,tobeemailed
,tobefaxed
,tobeprinted
,transaction_discount_line
,transaction_id
,transaction_line_id
,transaction_order
,transfer_order_item_line
,transfer_order_line_type
,unit_cost_override
,unit_of_measure_id
,vsoe_allocation
,vsoe_amt
,vsoe_deferral
,vsoe_delivered
,vsoe_discount
,vsoe_price
,additional_discount_
,additional_discount_amount
,adjustment_field
,adjustment_tax_code_id
,appliance_drop_ship_po_
,apply_wh_tax
,asset_id
,authority_currency_code
,billable_engagement_name
,billable_expense_category
,billable_expense_engagement
,billable_item_name
,billable_units_of_measure
,billing_frequency_id
,bill_of_lading_number
,booking_date
,box_number
,charge_type_id
,code_of_supply_id
,contractual_discount_
,contractual_discount_amount
,contract_end_date
,contract_start_date
,contract_term
,course_type_id
,display_quantity
,employee_token_id
,end_user_id
,eu_triangulation
,exempt_id
,expense_account_id
,export_to_openair
,fixed_asset_id
,functional_area_id
,goods_and_services_indicato_id
,gross_list_price
,custom_functional_area_id
,custom_lcci_id
,custom_profit_center_id
,ic_item
,ic_je_number_id
,idt_product_tax_code
,intercompany
,intercompany_discount_
,je_expense_type
,jurisdiction_text
,lcci_id
,line_item_id
,markup_amount
,notc_id
,openair_assigned_users
,openair_billing_rule_id
,openair_charge_type_id
,openair_expense_report_line_i
,openair_gsthst
,openair_invoice_line_id
,openair_journal_entry_creatio
,openair_journal_entry_error
,openair_journal_entry_error_m
,openair_line_from_openair
,openair_loaded_cost_class_id
,openair_loaded_cost_credit__id
,openair_loaded_cost_debit_a_id
,openair_loaded_cost_departm_id
,openair_loaded_cost_locatio_id
,openair_loaded_cost_subsidi_id
,openair_phases_ancestry
,openair_phase_name
,openair_primary_loaded_cost
,openair_primary_loaded_cost_id
,openair_project_task_id
,openair_project_task_id_numbe
,openair_pst
,openair_quantity_from__invoic
,openair_rate
,openair_rev_rec_rule_id
,openair_secondary_loaded_cost
,openair_secondary_loaded_co_id
,openair_task_assignment_id
,openair_task_assignment_plann
,openair_task_id
,openair_task_name
,openair_tax
,openair_tertiary_loaded_cost
,openair_tertiary_loaded_cos_id
,openair_timesheet_start_date
,openair_time_entry_id
,originator_journal_tran_typ_id
,originator_transaction_intern
,partner_discount_
,partner_discount_amount
,pid
,pl_id
,posted
,pretax_amt
,pretax_amt_quantity
,price_type_id
,product_subtype
,product_type
,profit_center_id
,project_task_type_id
,promotional_discount_
,promotional_discount_amount
,schedule_id_0
,serial_number
,related_license_id
,related_asset_id
,reason_id
,registration_unique_id
,ship_date
,statistical_procedure_for_p_id
,statistical_procedure_for_s_id
,statistical_value
,statistical_value__base_curre
,task_type_id
,tax_amt
,tax_exemption_reason_code_id
,tax_rate
,tax_rate_code
,tax_type_0
,trade_discount_
,trade_item_code_id
,trade_item_description
,user_quantity
,vendor_tax
,vsoe_customer_type_id
,vsoe_deal_size_id
,vsoe_geography_id
,vsoe_lower_band_
,vsoe_pricing_method_id
,vsoe_related_line_item_number
,vsoe_upper_band_
,wdem_settlement_id
,withholding_tax_amount
,withholding_tax_amount__expen
,withholding_tax_base_amount
,withholding_tax_base_amount__
,withholding_tax_code_id
,withholding_tax_code__expen_id
,withholding_tax_line
,withholding_tax_line__expense
,withholding_tax_rate
,withholding_tax_rate__expense
,wt_customer_id
,wt_employee_id
,wt_vendor_id
,apttus_line_id
,apttus_order_
,apttus_order_id
,billing_plan_id
,billing_schedule_id
,ela_agreement_name
,item_id_0
,item_name
,item_units_name
,legacy_equipment_
,legacy_sales_doc_id
,mark_up_
,nibs_id
,po_
,product_revenue_subtype
,revenue_element_id_0
,shipping_group_id
,unit_list_price
,uplift_
,uplift_amount
,CREDIT_REBILL_REQUIRES_UNBILL
,PRODUCT_SUBTYPE_EXTERNAL_ID
,PRODUCT_TYPE_EXTERNAL_ID
,REBILLED_LINE
,UNIQUE_KEY
,sales_order_id
,quote_line_item_id
,item_label
,cmt_id
,sales_team_id
,sales_order_label
,Sysdate as SWT_INS_DT
,Sysdate as SWT_Ins_Date_Backup
FROM NS_Transaction_lines_stg_Tmp_line;


COMMIT;

/* Deleting partial audit entry */
/*
DELETE FROM swt_rpt_stg.FAST_LD_AUDT where SUBJECT_AREA = 'NETSUITE' and
TBL_NM = 'NS_Transaction_lines' and
COMPLTN_STAT = 'N' and
LD_DT=sysdate::date and 
SEQ_ID = (select max(SEQ_ID) from swt_rpt_stg.FAST_LD_AUDT where  SUBJECT_AREA = 'NETSUITE' and  TBL_NM = 'NS_Transaction_lines' and  COMPLTN_STAT = 'N');
*/

/* Inserting new audit entry with all stats */

INSERT INTO swt_rpt_stg.FAST_LD_AUDT
(
SUBJECT_AREA
,TBL_NM
,LD_DT
,START_DT_TIME
,END_DT_TIME
,SRC_REC_CNT
,TGT_REC_CNT
,COMPLTN_STAT
)
select 'NETSUITE','NS_Transaction_lines',sysdate::date,(select st from Start_Time_Tmp),sysdate,(select count from Start_Time_Tmp) ,(select count(*) from swt_rpt_base.NS_Transaction_lines where SWT_INS_DT::date = sysdate::date),'Y';

Commit;

--SELECT DO_TM_TASK('mergeout', 'swt_rpt_base.NS_Transaction_lines');
--SELECT DO_TM_TASK('mergeout', 'swt_rpt_stg.NS_Transaction_lines_Hist');
SELECT DO_TM_TASK('mergeout', 'swt_rpt_stg.FAST_LD_AUDT');
select ANALYZE_STATISTICS('swt_rpt_base.NS_Transaction_lines');
SELECT ANALYZE_STATISTICS('swt_rpt_base.NS_Transaction_lines_deleted_IDS');











