/******
*****Script Name	  : NS_Transactions.sql
****Description   : Incremental data load for NS_Transactions
****/

/* Setting timing on**/
\timing

/**SET SESSION AUTOCOMMIT TO OFF;**/

\set ON_ERROR_STOP on

CREATE LOCAL TEMP TABLE Start_Time_Tmp ON COMMIT PRESERVE ROWS AS select count(*) count, sysdate st from swt_rpt_stg.NS_Transactions;

/* Inserting values into Audit table  */

INSERT INTO swt_rpt_stg.FAST_LD_AUDT
(
SUBJECT_AREA
,TBL_NM
,LD_DT
,START_DT_TIME
,END_DT_TIME
,SRC_REC_CNT
,TGT_REC_CNT
,COMPLTN_STAT
)
select 'NETSUITE','NS_Transactions',sysdate::date,sysdate,null,(select count from Start_Time_Tmp) ,null,'N';

Commit;
INSERT /*+DIRECT*/ INTO "swt_rpt_stg".NS_Transactions_Hist SELECT * from "swt_rpt_stg".NS_Transactions;

CREATE LOCAL TEMP TABLE duplicates_Transactions ON COMMIT PRESERVE ROWS AS 
select max(auto_id) as auto_id,transaction_id from swt_rpt_stg.NS_Transactions where transaction_id in(
select transaction_id from swt_rpt_stg.NS_Transactions
group by transaction_id,last_modified_date having count(1)>1)
group by transaction_id;


delete from swt_rpt_stg.NS_Transactions  where exists(
select 1 from duplicates_Transactions t2 where swt_rpt_stg.NS_Transactions.transaction_id=t2.transaction_id and swt_rpt_stg.NS_Transactions.auto_id<t2.auto_id);

COMMIT;

CREATE LOCAL TEMP TABLE NS_Transactions_stg_Tmp ON COMMIT PRESERVE ROWS AS
(
SELECT DISTINCT * FROM swt_rpt_stg.NS_Transactions)
SEGMENTED BY HASH(transaction_id,last_modified_date) ALL NODES;

TRUNCATE TABLE swt_rpt_stg.NS_Transactions;

CREATE LOCAL TEMP TABLE NS_Transactions_base_Tmp ON COMMIT PRESERVE ROWS AS
(
SELECT DISTINCT transaction_id,last_modified_date FROM swt_rpt_base.NS_Transactions)
SEGMENTED BY HASH(transaction_id,last_modified_date) ALL NODES;


CREATE LOCAL TEMP TABLE NS_Transactions_stg_Tmp_Key ON COMMIT PRESERVE ROWS AS
(
SELECT transaction_id, max(last_modified_date) as last_modified_date FROM NS_Transactions_stg_Tmp group by transaction_id)
SEGMENTED BY HASH(transaction_id,last_modified_date) ALL NODES;




/* Inserting Stage table data into Historical Table */

insert /*+DIRECT*/ into swt_rpt_stg.NS_Transactions_Hist
(
account_based_number
,accounting_book_id
,accounting_period_id
,accrued_tax
,adjustment_journal
,adp_header_text
,adp_object_key
,advance_payment
,agreement_name
,agreement_number
,alternate_currency_id
,alternate_exchange_rate
,amount_after_discount
,amount_unbilled
,amount_withheld
,apttus_quote_
,ariba_bill_reference__payment
,ariba_po_number
,associated_revenue_arrangem_id
,associated_sales_transactio_id
,bank_status
,baseline_date
,batch_item_number
,batch_number
,begm
,bid_manager_id
,bill_check
,bill_pay_transaction
,bill_to_contact_id
,bill_to_country_pdf
,bill_type
,billaddress
,billing_account_id
,billing_instructions
,blended_rates
,bulk_submission_id
,business_style_id
,carrier
,cash_register
,central_bank_id
,closed
,company_status_id
,considered_by_kyriba_for_fore
,consolidated_billable_expense
,consolidated_product_type
,consolidated_tax_code
,contract_cost_amount
,contract_defer_expense_acct_id
,contract_expense_acct_id
,contract_term
,contract_terms_id
,cost_object
,create_date
,created_by_id
,created_from_id
,currency_code
,currency_id
,custom_form_id
,customer_bank_account_number
,customer_bank_routing_number
,customs_registration_number
,date_bid_close
,date_bid_open
,date_last_modified
,date_of_taxable_supply
,debooking_order_id
,debooking_processed
,delivery_terms_id
,delivery_without_approval
,deposit_bank_routing_number
,destination
,document_number
,due_date
,dwo_project_id
,edi_transaction_processed
,email
,end_date
,end_user_id
,end_user_shipping_address
,entity_id
,entity_tax_reg_num
,exchange_rate
,exchange_rate_to_usd
,expected_close
,export_to_openair
,exported_to_kyriba_for_paymen
,exported_to_openair
,external_ref_number
,fax
,federal
,file_attached
,fob
,forecast_type
,forecasting_last_export_date_
,payment_purpose_code_ppc_2
,payment_purpose_code_ppc_3
,from_contact_person_id
,from_subsidiary_country_id
,from_subsidiary_state
,functional_area_id
,go_to_market_route_id
,custom_functional_area_id
,custom_lcci_id
,custom_profit_center_id
,ic_error_message
,ic_invoice_number
,ic_je_number_id
,ic_ns_bill_number_id
,ic_ns_invoice_number_id
,ic_status_id
,ic_vendor_bill_number
,idt__bypass_tax_input_validat
,idt__do_not_calculate_tax
,include_in_forecast
,incoterm
,incoterms
,influencer_id
,inter_check
,intercompany_credit_memo_je_c
,intercompany_journal_entry_ch
,intercompany_transaction_id
,invoice_remit_name_id
,is_autocalculate_lag
,is_compliant
,is_created_from_merge
,is_finance_charge
,is_firmed
,is_intercompany
,is_merged_into_arrangements
,is_non_posting
,is_payment_hold
,is_reversal
,is_tax_reg_override
,is_wip
,iso_currency_code
,item_revision
,items_json
,itr_nexus
,je_subsidiary_netting_type_id
,je_to_subsidiary_settlement_id
,job_id
,journal_entry_amount
,kyriba_budget_code
,kyriba_payment_date
,kyriba_reference_number
,kyriba_transaction_last_ack
,kyriba_transaction_last_ack_d
,kyriba_transaction_status
,kyriba_transaction_status_dat
,kyriba_transaction_type_id
,landed_cost_allocation_method
,last_modified_date
,last_sales_activity
,lcci_id
,lead_source_id
,license_representative_id
,legacy_transaction_number
,legal_currency_exchange_rate
,legal_currency_id
,legal_currency_symbol
,letter_of_commitment
,legacy_cost_center
,license_sale_involved
,local_invoice_number
,localization_record_identif__0
,localization_record_identif__1
,localization_record_identif_id
,location_id
,lockbox_number
,lsa_link
,lsa_link_name
,memo
,memorized
,message
,misc_ic
,mode_of_transport_id
,nature_of_transaction_code_id
,needs_bill
,needs_revenue_commitment
,netsuite_project_id
,nexus_notc_id
,nondeductible_adjustment_jo_id
,nondeductible_tax_adjusted
,number_of_pricing_tiers
,onesource_document_number
,openair_created_from_time_e_id
,openair_expense_report_crea_id
,openair_expense_report_number
,openair_export_error
,openair_gsthst_amount
,openair_invoice_link
,openair_invoice_number
,openair_invoice_tax_amount
,openair_presales_id
,openair_pst_amount
,openair_revenue_recognition_i
,opening_balance_transaction
,opportunity__sfdc_id
,order_booking_owner_id
,order_source_id
,order_type_id
,original_invoice_number_id
,original_sales_order_number_id
,packing_list_instructions
,partner_id
,payer_account_number
,payer_name
,payer_routing_number
,payment_date
,payment_internal_id__source_id
,payment_method_id
,payment_terms_id
,payment_transaction_id
,pcard_number
,pn_ref_num
,po
,po_amount
,po_end_date
,po_start_date
,po_substitute
,po_substitute_type_id
,posted
,probability
,product_label_instructions
,profit_center_id
,projected_total
,promotion_code_id
,promotion_code_instance_id
,purchase_order_instructions
,quote_in_validation_date
,reason_1
,reason_2
,reason_3
,reason_4
,reason_code_id
,reason_for_hold
,rebate_create_automated_refun
,rebate_deal_id
,rebate_program_calendar_perio
,rebate_promotionprogram_id
,rebate_source_of_payment_id
,rebilled_invoice
,reference_document_internal_id
,reference_no__of_original_inv
,regime_code_of_supply_id
,region_id
,region_of_origin_id
,regular_ic
,related_sales_order_id
,related_tranid
,remittance_purpose_code
,remittance_reason_code_id
,renewal
,report_timestamp
,revenue_commitment_status
,revenue_committed
,revenue_recognition_method__id
,revenue_recognition_review
,revenue_status
,reversal_date
,reversal_number_id
,reverse_exchange_rate_id
,reversing_transaction_id
,risk_rating_id
,sales_effective_date
,sales_order_date
,sales_order_ref_id
,sales_rep_id
,scheduling_method_id
,ship_to_account_id
,ship_to_contact_id
,shipaddress
,shipment_notification_process
,shipment_received
,shipping_item_id
,sold_to_account_id
,sold_to_address_1
,sold_to_address_2
,sold_to_address_3
,sold_to_attention
,sold_to_city
,sold_to_country_id
,sold_to_phone
,sold_to_state
,sold_to_zip_code
,source_system_id
,special_instructions
,start_date
,status
,store_number
,subregion_id
,subsidiary_address_for_pdf
,tax_after_discount
,tax_and_legal_disclaimer_pdf
,tax_exemption_reason_code_id
,tax_reg_id
,tax_withheld
,termination_reason
,terms__conditions_link
,tier_1_partner_id
,tier_1_relationship_id
,tier_2_partner_id
,tier_2_relationship_id
,title
,to_be_emailed_custom_check
,to_contact_person_id
,to_subsidiary_code
,to_subsidiary_country_id
,to_subsidiary_state
,total_after_discount
,total_amount
,total_amount_2
,trace_reference_number
,trade_invoice_number_id
,trading_partner_code
,trading_partner_id
,trandate
,tranid
,trans_is_vsoe_bundle
,transaction_extid
,transaction_id
,transaction_number
,transaction_partner
,transaction_source
,transaction_type
,transaction_website
,transfer_location
,use_item_cost_as_transfer_cost
,vendor_number
,vendor_tax
,visible_in_customer_center
,wdem_payment_id
,wdem_settlement_id
,weighted_total
,withholding_tax_applies_to
,workday_er
,write_offbad_debt
,wt_applied
,wt_code_applied
,wt_rate
,wtax_base_url
,cmt
,related_customer_payment_id
,user_description
,wtax_cust_pay_posting_account
,all_hardware_fulfilled
,consolidated_tax_type_rate
,edocument_content
,edocument_sending_method_id
,edocument_status_id
,edocument_template_id
,einvoicing
,ic_vendor_account_id
,invoice_remit_name_1_id
,wtax_journal_reversal_flag
,account_name_reference
,account_number_reference
,amount_due_usd
,ap_bank_gl_account
,customer_subsidiary_code_refe
,date_contract_cost_accrual
,fiscal_rep_address
,hold_revenue_recognition
,is_advanced_intercompany
,is_reversal_0
,local_invoice_
,localization_for_us_english_id
,opportunity_classification
,order_subtype_id
,payment_purpose_code_ppc_1
,po_amount_usd
,purposereason_id
,rebill_state_id
,related_sales_transaction_id
,status_id
,total_usd
,wtax_base_amount
,ACCOUNT_NAME_NONLATIN
,BILL_TO_ADDRESS_NONLATIN
,BILL_TO_ADDRESS_PHONE_NONLATI
,BILL_TO_ADDRESSEE_NONLATIN
,BILL_TO_CITY_NONLATIN
,BILL_TO_COUNTRY_NONLATIN
,BILL_TO_STATE_NONLATIN
,BILL_TO_ZIP_CODE_NONLATIN
,CREDIT_REBILL_UNBILLED_AR_ADJ
,IC_HOLD
,INBOUND_EDOCUMENT_ID
,INCLUDES_REBILLED_LINES
,INDENT_ENTITIES_ID
,INVOICE_CANCELLATION_ERROR
,INVOICE_REVIEW_COMPLETE
,INVOICE_REVIEWED_BY_ID
,INVOICED_TO_BE_CANCELLED
,MARKET_OFFERING_ID
,RELATED_CANCELLED_INVOICE_ID
,RELATED_REVENUE_ELEMENT_ID
,SERVICE_OFFERING_ID
,WITHHOLDING_TAX_SCRIPT
,customer_subscription_name
,large_quote_id
,enable_role_restriction
,fx_manual_correction
,invoice_cancellation_reason_id
,LD_DT
,SWT_INS_DT
,d_source
,SWT_Ins_Date_Backup
)
select
account_based_number
,accounting_book_id
,accounting_period_id
,accrued_tax
,adjustment_journal
,adp_header_text
,adp_object_key
,advance_payment
,agreement_name
,agreement_number
,alternate_currency_id
,alternate_exchange_rate
,amount_after_discount
,amount_unbilled
,amount_withheld
,apttus_quote_
,ariba_bill_reference__payment
,ariba_po_number
,associated_revenue_arrangem_id
,associated_sales_transactio_id
,bank_status
,baseline_date
,batch_item_number
,batch_number
,begm
,bid_manager_id
,bill_check
,bill_pay_transaction
,bill_to_contact_id
,bill_to_country_pdf
,bill_type
,billaddress
,billing_account_id
,billing_instructions
,blended_rates
,bulk_submission_id
,business_style_id
,carrier
,cash_register
,central_bank_id
,closed
,company_status_id
,considered_by_kyriba_for_fore
,consolidated_billable_expense
,consolidated_product_type
,consolidated_tax_code
,contract_cost_amount
,contract_defer_expense_acct_id
,contract_expense_acct_id
,contract_term
,contract_terms_id
,cost_object
,create_date
,created_by_id
,created_from_id
,currency_code
,currency_id
,custom_form_id
,customer_bank_account_number
,customer_bank_routing_number
,customs_registration_number
,date_bid_close
,date_bid_open
,date_last_modified
,date_of_taxable_supply
,debooking_order_id
,debooking_processed
,delivery_terms_id
,delivery_without_approval
,deposit_bank_routing_number
,destination
,document_number
,due_date
,dwo_project_id
,edi_transaction_processed
,email
,end_date
,end_user_id
,end_user_shipping_address
,entity_id
,entity_tax_reg_num
,exchange_rate
,exchange_rate_to_usd
,expected_close
,export_to_openair
,exported_to_kyriba_for_paymen
,exported_to_openair
,external_ref_number
,fax
,federal
,file_attached
,fob
,forecast_type
,forecasting_last_export_date_
,payment_purpose_code_ppc_2
,payment_purpose_code_ppc_3
,from_contact_person_id
,from_subsidiary_country_id
,from_subsidiary_state
,functional_area_id
,go_to_market_route_id
,custom_functional_area_id
,custom_lcci_id
,custom_profit_center_id
,ic_error_message
,ic_invoice_number
,ic_je_number_id
,ic_ns_bill_number_id
,ic_ns_invoice_number_id
,ic_status_id
,ic_vendor_bill_number
,idt__bypass_tax_input_validat
,idt__do_not_calculate_tax
,include_in_forecast
,incoterm
,incoterms
,influencer_id
,inter_check
,intercompany_credit_memo_je_c
,intercompany_journal_entry_ch
,intercompany_transaction_id
,invoice_remit_name_id
,is_autocalculate_lag
,is_compliant
,is_created_from_merge
,is_finance_charge
,is_firmed
,is_intercompany
,is_merged_into_arrangements
,is_non_posting
,is_payment_hold
,is_reversal
,is_tax_reg_override
,is_wip
,iso_currency_code
,item_revision
,items_json
,itr_nexus
,je_subsidiary_netting_type_id
,je_to_subsidiary_settlement_id
,job_id
,journal_entry_amount
,kyriba_budget_code
,kyriba_payment_date
,kyriba_reference_number
,kyriba_transaction_last_ack
,kyriba_transaction_last_ack_d
,kyriba_transaction_status
,kyriba_transaction_status_dat
,kyriba_transaction_type_id
,landed_cost_allocation_method
,last_modified_date
,last_sales_activity
,lcci_id
,lead_source_id
,license_representative_id
,legacy_transaction_number
,legal_currency_exchange_rate
,legal_currency_id
,legal_currency_symbol
,letter_of_commitment
,legacy_cost_center
,license_sale_involved
,local_invoice_number
,localization_record_identif__0
,localization_record_identif__1
,localization_record_identif_id
,location_id
,lockbox_number
,lsa_link
,lsa_link_name
,memo
,memorized
,message
,misc_ic
,mode_of_transport_id
,nature_of_transaction_code_id
,needs_bill
,needs_revenue_commitment
,netsuite_project_id
,nexus_notc_id
,nondeductible_adjustment_jo_id
,nondeductible_tax_adjusted
,number_of_pricing_tiers
,onesource_document_number
,openair_created_from_time_e_id
,openair_expense_report_crea_id
,openair_expense_report_number
,openair_export_error
,openair_gsthst_amount
,openair_invoice_link
,openair_invoice_number
,openair_invoice_tax_amount
,openair_presales_id
,openair_pst_amount
,openair_revenue_recognition_i
,opening_balance_transaction
,opportunity__sfdc_id
,order_booking_owner_id
,order_source_id
,order_type_id
,original_invoice_number_id
,original_sales_order_number_id
,packing_list_instructions
,partner_id
,payer_account_number
,payer_name
,payer_routing_number
,payment_date
,payment_internal_id__source_id
,payment_method_id
,payment_terms_id
,payment_transaction_id
,pcard_number
,pn_ref_num
,po
,po_amount
,po_end_date
,po_start_date
,po_substitute
,po_substitute_type_id
,posted
,probability
,product_label_instructions
,profit_center_id
,projected_total
,promotion_code_id
,promotion_code_instance_id
,purchase_order_instructions
,quote_in_validation_date
,reason_1
,reason_2
,reason_3
,reason_4
,reason_code_id
,reason_for_hold
,rebate_create_automated_refun
,rebate_deal_id
,rebate_program_calendar_perio
,rebate_promotionprogram_id
,rebate_source_of_payment_id
,rebilled_invoice
,reference_document_internal_id
,reference_no__of_original_inv
,regime_code_of_supply_id
,region_id
,region_of_origin_id
,regular_ic
,related_sales_order_id
,related_tranid
,remittance_purpose_code
,remittance_reason_code_id
,renewal
,report_timestamp
,revenue_commitment_status
,revenue_committed
,revenue_recognition_method__id
,revenue_recognition_review
,revenue_status
,reversal_date
,reversal_number_id
,reverse_exchange_rate_id
,reversing_transaction_id
,risk_rating_id
,sales_effective_date
,sales_order_date
,sales_order_ref_id
,sales_rep_id
,scheduling_method_id
,ship_to_account_id
,ship_to_contact_id
,shipaddress
,shipment_notification_process
,shipment_received
,shipping_item_id
,sold_to_account_id
,sold_to_address_1
,sold_to_address_2
,sold_to_address_3
,sold_to_attention
,sold_to_city
,sold_to_country_id
,sold_to_phone
,sold_to_state
,sold_to_zip_code
,source_system_id
,special_instructions
,start_date
,status
,store_number
,subregion_id
,subsidiary_address_for_pdf
,tax_after_discount
,tax_and_legal_disclaimer_pdf
,tax_exemption_reason_code_id
,tax_reg_id
,tax_withheld
,termination_reason
,terms__conditions_link
,tier_1_partner_id
,tier_1_relationship_id
,tier_2_partner_id
,tier_2_relationship_id
,title
,to_be_emailed_custom_check
,to_contact_person_id
,to_subsidiary_code
,to_subsidiary_country_id
,to_subsidiary_state
,total_after_discount
,total_amount
,total_amount_2
,trace_reference_number
,trade_invoice_number_id
,trading_partner_code
,trading_partner_id
,trandate
,tranid
,trans_is_vsoe_bundle
,transaction_extid
,transaction_id
,transaction_number
,transaction_partner
,transaction_source
,transaction_type
,transaction_website
,transfer_location
,use_item_cost_as_transfer_cost
,vendor_number
,vendor_tax
,visible_in_customer_center
,wdem_payment_id
,wdem_settlement_id
,weighted_total
,withholding_tax_applies_to
,workday_er
,write_offbad_debt
,wt_applied
,wt_code_applied
,wt_rate
,wtax_base_url
,cmt
,related_customer_payment_id
,user_description
,wtax_cust_pay_posting_account
,all_hardware_fulfilled
,consolidated_tax_type_rate
,edocument_content
,edocument_sending_method_id
,edocument_status_id
,edocument_template_id
,einvoicing
,ic_vendor_account_id
,invoice_remit_name_1_id
,wtax_journal_reversal_flag
,account_name_reference
,account_number_reference
,amount_due_usd
,ap_bank_gl_account
,customer_subsidiary_code_refe
,date_contract_cost_accrual
,fiscal_rep_address
,hold_revenue_recognition
,is_advanced_intercompany
,is_reversal_0
,local_invoice_
,localization_for_us_english_id
,opportunity_classification
,order_subtype_id
,payment_purpose_code_ppc_1
,po_amount_usd
,purposereason_id
,rebill_state_id
,related_sales_transaction_id
,status_id
,total_usd
,wtax_base_amount
,ACCOUNT_NAME_NONLATIN
,BILL_TO_ADDRESS_NONLATIN
,BILL_TO_ADDRESS_PHONE_NONLATI
,BILL_TO_ADDRESSEE_NONLATIN
,BILL_TO_CITY_NONLATIN
,BILL_TO_COUNTRY_NONLATIN
,BILL_TO_STATE_NONLATIN
,BILL_TO_ZIP_CODE_NONLATIN
,CREDIT_REBILL_UNBILLED_AR_ADJ
,IC_HOLD
,INBOUND_EDOCUMENT_ID
,INCLUDES_REBILLED_LINES
,INDENT_ENTITIES_ID
,INVOICE_CANCELLATION_ERROR
,INVOICE_REVIEW_COMPLETE
,INVOICE_REVIEWED_BY_ID
,INVOICED_TO_BE_CANCELLED
,MARKET_OFFERING_ID
,RELATED_CANCELLED_INVOICE_ID
,RELATED_REVENUE_ELEMENT_ID
,SERVICE_OFFERING_ID
,WITHHOLDING_TAX_SCRIPT
,customer_subscription_name
,large_quote_id
,enable_role_restriction
,fx_manual_correction
,invoice_cancellation_reason_id
,SYSDATE AS LD_DT
,SWT_INS_DT
,'base'
,SWT_Ins_Date_Backup
FROM "swt_rpt_base".NS_Transactions WHERE transaction_id in
(SELECT STG.transaction_id FROM NS_Transactions_stg_Tmp_Key STG JOIN NS_Transactions_base_Tmp
ON STG.transaction_id = NS_Transactions_base_Tmp.transaction_id AND STG.last_modified_date >= NS_Transactions_base_Tmp.last_modified_date);



/* Deleting before seven days data from current date in the Historical Table */

delete /*+DIRECT*/ from "swt_rpt_stg"."NS_Transactions_Hist"  where LD_DT::date <= TIMESTAMPADD(DAY,-7,sysdate)::date;



/* Incremental VSQL script for loading data from Stage to Base */

DELETE /*+DIRECT*/ FROM "swt_rpt_base".NS_Transactions WHERE transaction_id in
(SELECT STG.transaction_id FROM NS_Transactions_stg_Tmp_Key STG JOIN NS_Transactions_base_Tmp
ON STG.transaction_id = NS_Transactions_base_Tmp.transaction_id AND STG.last_modified_date >= NS_Transactions_base_Tmp.last_modified_date);

INSERT /*+DIRECT*/ INTO "swt_rpt_base".NS_Transactions
(
account_based_number
,accounting_book_id
,accounting_period_id
,accrued_tax
,adjustment_journal
,adp_header_text
,adp_object_key
,advance_payment
,agreement_name
,agreement_number
,alternate_currency_id
,alternate_exchange_rate
,amount_after_discount
,amount_unbilled
,amount_withheld
,apttus_quote_
,ariba_bill_reference__payment
,ariba_po_number
,associated_revenue_arrangem_id
,associated_sales_transactio_id
,bank_status
,baseline_date
,batch_item_number
,batch_number
,begm
,bid_manager_id
,bill_check
,bill_pay_transaction
,bill_to_contact_id
,bill_to_country_pdf
,bill_type
,billaddress
,billing_account_id
,billing_instructions
,blended_rates
,bulk_submission_id
,business_style_id
,carrier
,cash_register
,central_bank_id
,closed
,company_status_id
,considered_by_kyriba_for_fore
,consolidated_billable_expense
,consolidated_product_type
,consolidated_tax_code
,contract_cost_amount
,contract_defer_expense_acct_id
,contract_expense_acct_id
,contract_term
,contract_terms_id
,cost_object
,create_date
,created_by_id
,created_from_id
,currency_code
,currency_id
,custom_form_id
,customer_bank_account_number
,customer_bank_routing_number
,customs_registration_number
,date_bid_close
,date_bid_open
,date_last_modified
,date_of_taxable_supply
,debooking_order_id
,debooking_processed
,delivery_terms_id
,delivery_without_approval
,deposit_bank_routing_number
,destination
,document_number
,due_date
,dwo_project_id
,edi_transaction_processed
,email
,end_date
,end_user_id
,end_user_shipping_address
,entity_id
,entity_tax_reg_num
,exchange_rate
,exchange_rate_to_usd
,expected_close
,export_to_openair
,exported_to_kyriba_for_paymen
,exported_to_openair
,external_ref_number
,fax
,federal
,file_attached
,fob
,forecast_type
,forecasting_last_export_date_
,payment_purpose_code_ppc_2
,payment_purpose_code_ppc_3
,from_contact_person_id
,from_subsidiary_country_id
,from_subsidiary_state
,functional_area_id
,go_to_market_route_id
,custom_functional_area_id
,custom_lcci_id
,custom_profit_center_id
,ic_error_message
,ic_invoice_number
,ic_je_number_id
,ic_ns_bill_number_id
,ic_ns_invoice_number_id
,ic_status_id
,ic_vendor_bill_number
,idt__bypass_tax_input_validat
,idt__do_not_calculate_tax
,include_in_forecast
,incoterm
,incoterms
,influencer_id
,inter_check
,intercompany_credit_memo_je_c
,intercompany_journal_entry_ch
,intercompany_transaction_id
,invoice_remit_name_id
,is_autocalculate_lag
,is_compliant
,is_created_from_merge
,is_finance_charge
,is_firmed
,is_intercompany
,is_merged_into_arrangements
,is_non_posting
,is_payment_hold
,is_reversal
,is_tax_reg_override
,is_wip
,iso_currency_code
,item_revision
,items_json
,itr_nexus
,je_subsidiary_netting_type_id
,je_to_subsidiary_settlement_id
,job_id
,journal_entry_amount
,kyriba_budget_code
,kyriba_payment_date
,kyriba_reference_number
,kyriba_transaction_last_ack
,kyriba_transaction_last_ack_d
,kyriba_transaction_status
,kyriba_transaction_status_dat
,kyriba_transaction_type_id
,landed_cost_allocation_method
,last_modified_date
,last_sales_activity
,lcci_id
,lead_source_id
,license_representative_id
,legacy_transaction_number
,legal_currency_exchange_rate
,legal_currency_id
,legal_currency_symbol
,letter_of_commitment
,legacy_cost_center
,license_sale_involved
,local_invoice_number
,localization_record_identif__0
,localization_record_identif__1
,localization_record_identif_id
,location_id
,lockbox_number
,lsa_link
,lsa_link_name
,memo
,memorized
,message
,misc_ic
,mode_of_transport_id
,nature_of_transaction_code_id
,needs_bill
,needs_revenue_commitment
,netsuite_project_id
,nexus_notc_id
,nondeductible_adjustment_jo_id
,nondeductible_tax_adjusted
,number_of_pricing_tiers
,onesource_document_number
,openair_created_from_time_e_id
,openair_expense_report_crea_id
,openair_expense_report_number
,openair_export_error
,openair_gsthst_amount
,openair_invoice_link
,openair_invoice_number
,openair_invoice_tax_amount
,openair_presales_id
,openair_pst_amount
,openair_revenue_recognition_i
,opening_balance_transaction
,opportunity__sfdc_id
,order_booking_owner_id
,order_source_id
,order_type_id
,original_invoice_number_id
,original_sales_order_number_id
,packing_list_instructions
,partner_id
,payer_account_number
,payer_name
,payer_routing_number
,payment_date
,payment_internal_id__source_id
,payment_method_id
,payment_terms_id
,payment_transaction_id
,pcard_number
,pn_ref_num
,po
,po_amount
,po_end_date
,po_start_date
,po_substitute
,po_substitute_type_id
,posted
,probability
,product_label_instructions
,profit_center_id
,projected_total
,promotion_code_id
,promotion_code_instance_id
,purchase_order_instructions
,quote_in_validation_date
,reason_1
,reason_2
,reason_3
,reason_4
,reason_code_id
,reason_for_hold
,rebate_create_automated_refun
,rebate_deal_id
,rebate_program_calendar_perio
,rebate_promotionprogram_id
,rebate_source_of_payment_id
,rebilled_invoice
,reference_document_internal_id
,reference_no__of_original_inv
,regime_code_of_supply_id
,region_id
,region_of_origin_id
,regular_ic
,related_sales_order_id
,related_tranid
,remittance_purpose_code
,remittance_reason_code_id
,renewal
,report_timestamp
,revenue_commitment_status
,revenue_committed
,revenue_recognition_method__id
,revenue_recognition_review
,revenue_status
,reversal_date
,reversal_number_id
,reverse_exchange_rate_id
,reversing_transaction_id
,risk_rating_id
,sales_effective_date
,sales_order_date
,sales_order_ref_id
,sales_rep_id
,scheduling_method_id
,ship_to_account_id
,ship_to_contact_id
,shipaddress
,shipment_notification_process
,shipment_received
,shipping_item_id
,sold_to_account_id
,sold_to_address_1
,sold_to_address_2
,sold_to_address_3
,sold_to_attention
,sold_to_city
,sold_to_country_id
,sold_to_phone
,sold_to_state
,sold_to_zip_code
,source_system_id
,special_instructions
,start_date
,status
,store_number
,subregion_id
,subsidiary_address_for_pdf
,tax_after_discount
,tax_and_legal_disclaimer_pdf
,tax_exemption_reason_code_id
,tax_reg_id
,tax_withheld
,termination_reason
,terms__conditions_link
,tier_1_partner_id
,tier_1_relationship_id
,tier_2_partner_id
,tier_2_relationship_id
,title
,to_be_emailed_custom_check
,to_contact_person_id
,to_subsidiary_code
,to_subsidiary_country_id
,to_subsidiary_state
,total_after_discount
,total_amount
,total_amount_2
,trace_reference_number
,trade_invoice_number_id
,trading_partner_code
,trading_partner_id
,trandate
,tranid
,trans_is_vsoe_bundle
,transaction_extid
,transaction_id
,transaction_number
,transaction_partner
,transaction_source
,transaction_type
,transaction_website
,transfer_location
,use_item_cost_as_transfer_cost
,vendor_number
,vendor_tax
,visible_in_customer_center
,wdem_payment_id
,wdem_settlement_id
,weighted_total
,withholding_tax_applies_to
,workday_er
,write_offbad_debt
,wt_applied
,wt_code_applied
,wt_rate
,wtax_base_url
,cmt
,related_customer_payment_id
,user_description
,wtax_cust_pay_posting_account
,all_hardware_fulfilled
,consolidated_tax_type_rate
,edocument_content
,edocument_sending_method_id
,edocument_status_id
,edocument_template_id
,einvoicing
,ic_vendor_account_id
,invoice_remit_name_1_id
,wtax_journal_reversal_flag
,account_name_reference
,account_number_reference
,amount_due_usd
,ap_bank_gl_account
,customer_subsidiary_code_refe
,date_contract_cost_accrual
,fiscal_rep_address
,hold_revenue_recognition
,is_advanced_intercompany
,is_reversal_0
,local_invoice_
,localization_for_us_english_id
,opportunity_classification
,order_subtype_id
,payment_purpose_code_ppc_1
,po_amount_usd
,purposereason_id
,rebill_state_id
,related_sales_transaction_id
,status_id
,total_usd
,wtax_base_amount
,ACCOUNT_NAME_NONLATIN
,BILL_TO_ADDRESS_NONLATIN
,BILL_TO_ADDRESS_PHONE_NONLATI
,BILL_TO_ADDRESSEE_NONLATIN
,BILL_TO_CITY_NONLATIN
,BILL_TO_COUNTRY_NONLATIN
,BILL_TO_STATE_NONLATIN
,BILL_TO_ZIP_CODE_NONLATIN
,CREDIT_REBILL_UNBILLED_AR_ADJ
,IC_HOLD
,INBOUND_EDOCUMENT_ID
,INCLUDES_REBILLED_LINES
,INDENT_ENTITIES_ID
,INVOICE_CANCELLATION_ERROR
,INVOICE_REVIEW_COMPLETE
,INVOICE_REVIEWED_BY_ID
,INVOICED_TO_BE_CANCELLED
,MARKET_OFFERING_ID
,RELATED_CANCELLED_INVOICE_ID
,RELATED_REVENUE_ELEMENT_ID
,SERVICE_OFFERING_ID
,WITHHOLDING_TAX_SCRIPT
,customer_subscription_name
,large_quote_id
,enable_role_restriction
,fx_manual_correction
,invoice_cancellation_reason_id
,SWT_INS_DT
,SWT_Ins_Date_Backup
)
SELECT DISTINCT 
account_based_number
,accounting_book_id
,accounting_period_id
,accrued_tax
,adjustment_journal
,adp_header_text
,adp_object_key
,advance_payment
,agreement_name
,agreement_number
,alternate_currency_id
,alternate_exchange_rate
,amount_after_discount
,amount_unbilled
,amount_withheld
,apttus_quote_
,ariba_bill_reference__payment
,ariba_po_number
,associated_revenue_arrangem_id
,associated_sales_transactio_id
,bank_status
,baseline_date
,batch_item_number
,batch_number
,begm
,bid_manager_id
,bill_check
,bill_pay_transaction
,bill_to_contact_id
,bill_to_country_pdf
,bill_type
,billaddress
,billing_account_id
,billing_instructions
,blended_rates
,bulk_submission_id
,business_style_id
,carrier
,cash_register
,central_bank_id
,closed
,company_status_id
,considered_by_kyriba_for_fore
,consolidated_billable_expense
,consolidated_product_type
,consolidated_tax_code
,contract_cost_amount
,contract_defer_expense_acct_id
,contract_expense_acct_id
,contract_term
,contract_terms_id
,cost_object
,create_date
,created_by_id
,created_from_id
,currency_code
,currency_id
,custom_form_id
,customer_bank_account_number
,customer_bank_routing_number
,customs_registration_number
,date_bid_close
,date_bid_open
,date_last_modified
,date_of_taxable_supply
,debooking_order_id
,debooking_processed
,delivery_terms_id
,delivery_without_approval
,deposit_bank_routing_number
,destination
,document_number
,due_date
,dwo_project_id
,edi_transaction_processed
,email
,end_date
,end_user_id
,end_user_shipping_address
,entity_id
,entity_tax_reg_num
,exchange_rate
,exchange_rate_to_usd
,expected_close
,export_to_openair
,exported_to_kyriba_for_paymen
,exported_to_openair
,external_ref_number
,fax
,federal
,file_attached
,fob
,forecast_type
,forecasting_last_export_date_
,payment_purpose_code_ppc_2
,payment_purpose_code_ppc_3
,from_contact_person_id
,from_subsidiary_country_id
,from_subsidiary_state
,functional_area_id
,go_to_market_route_id
,custom_functional_area_id
,custom_lcci_id
,custom_profit_center_id
,ic_error_message
,ic_invoice_number
,ic_je_number_id
,ic_ns_bill_number_id
,ic_ns_invoice_number_id
,ic_status_id
,ic_vendor_bill_number
,idt__bypass_tax_input_validat
,idt__do_not_calculate_tax
,include_in_forecast
,incoterm
,incoterms
,influencer_id
,inter_check
,intercompany_credit_memo_je_c
,intercompany_journal_entry_ch
,intercompany_transaction_id
,invoice_remit_name_id
,is_autocalculate_lag
,is_compliant
,is_created_from_merge
,is_finance_charge
,is_firmed
,is_intercompany
,is_merged_into_arrangements
,is_non_posting
,is_payment_hold
,is_reversal
,is_tax_reg_override
,is_wip
,iso_currency_code
,item_revision
,items_json
,itr_nexus
,je_subsidiary_netting_type_id
,je_to_subsidiary_settlement_id
,job_id
,journal_entry_amount
,kyriba_budget_code
,kyriba_payment_date
,kyriba_reference_number
,kyriba_transaction_last_ack
,kyriba_transaction_last_ack_d
,kyriba_transaction_status
,kyriba_transaction_status_dat
,kyriba_transaction_type_id
,landed_cost_allocation_method
,NS_Transactions_stg_Tmp.last_modified_date
,last_sales_activity
,lcci_id
,lead_source_id
,license_representative_id
,legacy_transaction_number
,legal_currency_exchange_rate
,legal_currency_id
,legal_currency_symbol
,letter_of_commitment
,legacy_cost_center
,license_sale_involved
,local_invoice_number
,localization_record_identif__0
,localization_record_identif__1
,localization_record_identif_id
,location_id
,lockbox_number
,lsa_link
,lsa_link_name
,memo
,memorized
,message
,misc_ic
,mode_of_transport_id
,nature_of_transaction_code_id
,needs_bill
,needs_revenue_commitment
,netsuite_project_id
,nexus_notc_id
,nondeductible_adjustment_jo_id
,nondeductible_tax_adjusted
,number_of_pricing_tiers
,onesource_document_number
,openair_created_from_time_e_id
,openair_expense_report_crea_id
,openair_expense_report_number
,openair_export_error
,openair_gsthst_amount
,openair_invoice_link
,openair_invoice_number
,openair_invoice_tax_amount
,openair_presales_id
,openair_pst_amount
,openair_revenue_recognition_i
,opening_balance_transaction
,opportunity__sfdc_id
,order_booking_owner_id
,order_source_id
,order_type_id
,original_invoice_number_id
,original_sales_order_number_id
,packing_list_instructions
,partner_id
,payer_account_number
,payer_name
,payer_routing_number
,payment_date
,payment_internal_id__source_id
,payment_method_id
,payment_terms_id
,payment_transaction_id
,pcard_number
,pn_ref_num
,po
,po_amount
,po_end_date
,po_start_date
,po_substitute
,po_substitute_type_id
,posted
,probability
,product_label_instructions
,profit_center_id
,projected_total
,promotion_code_id
,promotion_code_instance_id
,purchase_order_instructions
,quote_in_validation_date
,reason_1
,reason_2
,reason_3
,reason_4
,reason_code_id
,reason_for_hold
,rebate_create_automated_refun
,rebate_deal_id
,rebate_program_calendar_perio
,rebate_promotionprogram_id
,rebate_source_of_payment_id
,rebilled_invoice
,reference_document_internal_id
,reference_no__of_original_inv
,regime_code_of_supply_id
,region_id
,region_of_origin_id
,regular_ic
,related_sales_order_id
,related_tranid
,remittance_purpose_code
,remittance_reason_code_id
,renewal
,report_timestamp
,revenue_commitment_status
,revenue_committed
,revenue_recognition_method__id
,revenue_recognition_review
,revenue_status
,reversal_date
,reversal_number_id
,reverse_exchange_rate_id
,reversing_transaction_id
,risk_rating_id
,sales_effective_date
,sales_order_date
,sales_order_ref_id
,sales_rep_id
,scheduling_method_id
,ship_to_account_id
,ship_to_contact_id
,shipaddress
,shipment_notification_process
,shipment_received
,shipping_item_id
,sold_to_account_id
,sold_to_address_1
,sold_to_address_2
,sold_to_address_3
,sold_to_attention
,sold_to_city
,sold_to_country_id
,sold_to_phone
,sold_to_state
,sold_to_zip_code
,source_system_id
,special_instructions
,start_date
,status
,store_number
,subregion_id
,subsidiary_address_for_pdf
,tax_after_discount
,tax_and_legal_disclaimer_pdf
,tax_exemption_reason_code_id
,tax_reg_id
,tax_withheld
,termination_reason
,terms__conditions_link
,tier_1_partner_id
,tier_1_relationship_id
,tier_2_partner_id
,tier_2_relationship_id
,title
,to_be_emailed_custom_check
,to_contact_person_id
,to_subsidiary_code
,to_subsidiary_country_id
,to_subsidiary_state
,total_after_discount
,total_amount
,total_amount_2
,trace_reference_number
,trade_invoice_number_id
,trading_partner_code
,trading_partner_id
,trandate
,tranid
,trans_is_vsoe_bundle
,transaction_extid
,NS_Transactions_stg_Tmp.transaction_id
,transaction_number
,transaction_partner
,transaction_source
,transaction_type
,transaction_website
,transfer_location
,use_item_cost_as_transfer_cost
,vendor_number
,vendor_tax
,visible_in_customer_center
,wdem_payment_id
,wdem_settlement_id
,weighted_total
,withholding_tax_applies_to
,workday_er
,write_offbad_debt
,wt_applied
,wt_code_applied
,wt_rate
,wtax_base_url
,cmt
,related_customer_payment_id
,user_description
,wtax_cust_pay_posting_account
,all_hardware_fulfilled
,consolidated_tax_type_rate
,edocument_content
,edocument_sending_method_id
,edocument_status_id
,edocument_template_id
,einvoicing
,ic_vendor_account_id
,invoice_remit_name_1_id
,wtax_journal_reversal_flag
,account_name_reference
,account_number_reference
,amount_due_usd
,ap_bank_gl_account
,customer_subsidiary_code_refe
,date_contract_cost_accrual
,fiscal_rep_address
,hold_revenue_recognition
,is_advanced_intercompany
,is_reversal_0
,local_invoice_
,localization_for_us_english_id
,opportunity_classification
,order_subtype_id
,payment_purpose_code_ppc_1
,po_amount_usd
,purposereason_id
,rebill_state_id
,related_sales_transaction_id
,status_id
,total_usd
,wtax_base_amount
,ACCOUNT_NAME_NONLATIN
,BILL_TO_ADDRESS_NONLATIN
,BILL_TO_ADDRESS_PHONE_NONLATI
,BILL_TO_ADDRESSEE_NONLATIN
,BILL_TO_CITY_NONLATIN
,BILL_TO_COUNTRY_NONLATIN
,BILL_TO_STATE_NONLATIN
,BILL_TO_ZIP_CODE_NONLATIN
,CREDIT_REBILL_UNBILLED_AR_ADJ
,IC_HOLD
,INBOUND_EDOCUMENT_ID
,INCLUDES_REBILLED_LINES
,INDENT_ENTITIES_ID
,INVOICE_CANCELLATION_ERROR
,INVOICE_REVIEW_COMPLETE
,INVOICE_REVIEWED_BY_ID
,INVOICED_TO_BE_CANCELLED
,MARKET_OFFERING_ID
,RELATED_CANCELLED_INVOICE_ID
,RELATED_REVENUE_ELEMENT_ID
,SERVICE_OFFERING_ID
,WITHHOLDING_TAX_SCRIPT
,customer_subscription_name
,large_quote_id
,enable_role_restriction
,fx_manual_correction
,invoice_cancellation_reason_id
,sysdate as SWT_INS_DT
,sysdate as SWT_Ins_Date_Backup
FROM NS_Transactions_stg_Tmp JOIN NS_Transactions_stg_Tmp_Key ON NS_Transactions_stg_Tmp.transaction_id= NS_Transactions_stg_Tmp_Key.transaction_id AND NS_Transactions_stg_Tmp.last_modified_date=NS_Transactions_stg_Tmp_Key.last_modified_date
WHERE NOT EXISTS
(SELECT 1 FROM "swt_rpt_base".NS_Transactions BASE
WHERE NS_Transactions_stg_Tmp.transaction_id = BASE.transaction_id);

COMMIT;


CREATE LOCAL TEMP TABLE NS_Transactions_base_deleted ON COMMIT PRESERVE ROWS AS
(
SELECT DISTINCT * FROM swt_rpt_base.NS_Transactions where Is_Deleted <> 'true' and transaction_id  in ( select distinct internalid from "swt_rpt_stg"."NS_SS_Deleted_Records"))
SEGMENTED BY HASH(transaction_id) ALL NODES;

insert /*+DIRECT*/ into NS_Transactions_base_deleted
SELECT distinct t2.* FROM swt_rpt_stg.NS_Missing_Transaction_Types t1 join swt_rpt_base.NS_Transactions t2  
on t2.transaction_type=Ltrim(Rtrim(SPLIT_PART(name,'#',1))) and t2.tranid=Ltrim(Rtrim(SPLIT_PART(name,'#',2))) where t2.is_deleted<>'true';

DELETE /*+DIRECT*/ FROM swt_rpt_base.NS_Transactions where transaction_id  in ( select distinct transaction_id from NS_Transactions_base_deleted);

INSERT /*+DIRECT*/ INTO swt_rpt_base.NS_Transactions_Deleted_Ids
( transaction_id,
SWT_INS_DT,
status
)
SELECT
transaction_id,
SYSDATE,
'deleted'
FROM NS_Transactions_base_deleted;

INSERT /*+DIRECT*/ INTO swt_rpt_base.NS_Transactions
(
account_based_number
,accounting_book_id
,accounting_period_id
,accrued_tax
,adjustment_journal
,adp_header_text
,adp_object_key
,advance_payment
,agreement_name
,agreement_number
,alternate_currency_id
,alternate_exchange_rate
,amount_after_discount
,amount_unbilled
,amount_withheld
,apttus_quote_
,ariba_bill_reference__payment
,ariba_po_number
,associated_revenue_arrangem_id
,associated_sales_transactio_id
,bank_status
,baseline_date
,batch_item_number
,batch_number
,begm
,bid_manager_id
,bill_check
,bill_pay_transaction
,bill_to_contact_id
,bill_to_country_pdf
,bill_type
,billaddress
,billing_account_id
,billing_instructions
,blended_rates
,bulk_submission_id
,business_style_id
,carrier
,cash_register
,central_bank_id
,closed
,company_status_id
,considered_by_kyriba_for_fore
,consolidated_billable_expense
,consolidated_product_type
,consolidated_tax_code
,contract_cost_amount
,contract_defer_expense_acct_id
,contract_expense_acct_id
,contract_term
,contract_terms_id
,cost_object
,create_date
,created_by_id
,created_from_id
,currency_code
,currency_id
,custom_form_id
,customer_bank_account_number
,customer_bank_routing_number
,customs_registration_number
,date_bid_close
,date_bid_open
,date_last_modified
,date_of_taxable_supply
,debooking_order_id
,debooking_processed
,delivery_terms_id
,delivery_without_approval
,deposit_bank_routing_number
,destination
,document_number
,due_date
,dwo_project_id
,edi_transaction_processed
,email
,end_date
,end_user_id
,end_user_shipping_address
,entity_id
,entity_tax_reg_num
,exchange_rate
,exchange_rate_to_usd
,expected_close
,export_to_openair
,exported_to_kyriba_for_paymen
,exported_to_openair
,external_ref_number
,fax
,federal
,file_attached
,fob
,forecast_type
,forecasting_last_export_date_
,payment_purpose_code_ppc_2
,payment_purpose_code_ppc_3
,from_contact_person_id
,from_subsidiary_country_id
,from_subsidiary_state
,functional_area_id
,go_to_market_route_id
,custom_functional_area_id
,custom_lcci_id
,custom_profit_center_id
,ic_error_message
,ic_invoice_number
,ic_je_number_id
,ic_ns_bill_number_id
,ic_ns_invoice_number_id
,ic_status_id
,ic_vendor_bill_number
,idt__bypass_tax_input_validat
,idt__do_not_calculate_tax
,include_in_forecast
,incoterm
,incoterms
,influencer_id
,inter_check
,intercompany_credit_memo_je_c
,intercompany_journal_entry_ch
,intercompany_transaction_id
,invoice_remit_name_id
,is_autocalculate_lag
,is_compliant
,is_created_from_merge
,is_finance_charge
,is_firmed
,is_intercompany
,is_merged_into_arrangements
,is_non_posting
,is_payment_hold
,is_reversal
,is_tax_reg_override
,is_wip
,iso_currency_code
,item_revision
,items_json
,itr_nexus
,je_subsidiary_netting_type_id
,je_to_subsidiary_settlement_id
,job_id
,journal_entry_amount
,kyriba_budget_code
,kyriba_payment_date
,kyriba_reference_number
,kyriba_transaction_last_ack
,kyriba_transaction_last_ack_d
,kyriba_transaction_status
,kyriba_transaction_status_dat
,kyriba_transaction_type_id
,landed_cost_allocation_method
,last_modified_date
,last_sales_activity
,lcci_id
,lead_source_id
,license_representative_id
,legacy_transaction_number
,legal_currency_exchange_rate
,legal_currency_id
,legal_currency_symbol
,letter_of_commitment
,legacy_cost_center
,license_sale_involved
,local_invoice_number
,localization_record_identif__0
,localization_record_identif__1
,localization_record_identif_id
,location_id
,lockbox_number
,lsa_link
,lsa_link_name
,memo
,memorized
,message
,misc_ic
,mode_of_transport_id
,nature_of_transaction_code_id
,needs_bill
,needs_revenue_commitment
,netsuite_project_id
,nexus_notc_id
,nondeductible_adjustment_jo_id
,nondeductible_tax_adjusted
,number_of_pricing_tiers
,onesource_document_number
,openair_created_from_time_e_id
,openair_expense_report_crea_id
,openair_expense_report_number
,openair_export_error
,openair_gsthst_amount
,openair_invoice_link
,openair_invoice_number
,openair_invoice_tax_amount
,openair_presales_id
,openair_pst_amount
,openair_revenue_recognition_i
,opening_balance_transaction
,opportunity__sfdc_id
,order_booking_owner_id
,order_source_id
,order_type_id
,original_invoice_number_id
,original_sales_order_number_id
,packing_list_instructions
,partner_id
,payer_account_number
,payer_name
,payer_routing_number
,payment_date
,payment_internal_id__source_id
,payment_method_id
,payment_terms_id
,payment_transaction_id
,pcard_number
,pn_ref_num
,po
,po_amount
,po_end_date
,po_start_date
,po_substitute
,po_substitute_type_id
,posted
,probability
,product_label_instructions
,profit_center_id
,projected_total
,promotion_code_id
,promotion_code_instance_id
,purchase_order_instructions
,quote_in_validation_date
,reason_1
,reason_2
,reason_3
,reason_4
,reason_code_id
,reason_for_hold
,rebate_create_automated_refun
,rebate_deal_id
,rebate_program_calendar_perio
,rebate_promotionprogram_id
,rebate_source_of_payment_id
,rebilled_invoice
,reference_document_internal_id
,reference_no__of_original_inv
,regime_code_of_supply_id
,region_id
,region_of_origin_id
,regular_ic
,related_sales_order_id
,related_tranid
,remittance_purpose_code
,remittance_reason_code_id
,renewal
,report_timestamp
,revenue_commitment_status
,revenue_committed
,revenue_recognition_method__id
,revenue_recognition_review
,revenue_status
,reversal_date
,reversal_number_id
,reverse_exchange_rate_id
,reversing_transaction_id
,risk_rating_id
,sales_effective_date
,sales_order_date
,sales_order_ref_id
,sales_rep_id
,scheduling_method_id
,ship_to_account_id
,ship_to_contact_id
,shipaddress
,shipment_notification_process
,shipment_received
,shipping_item_id
,sold_to_account_id
,sold_to_address_1
,sold_to_address_2
,sold_to_address_3
,sold_to_attention
,sold_to_city
,sold_to_country_id
,sold_to_phone
,sold_to_state
,sold_to_zip_code
,source_system_id
,special_instructions
,start_date
,status
,store_number
,subregion_id
,subsidiary_address_for_pdf
,tax_after_discount
,tax_and_legal_disclaimer_pdf
,tax_exemption_reason_code_id
,tax_reg_id
,tax_withheld
,termination_reason
,terms__conditions_link
,tier_1_partner_id
,tier_1_relationship_id
,tier_2_partner_id
,tier_2_relationship_id
,title
,to_be_emailed_custom_check
,to_contact_person_id
,to_subsidiary_code
,to_subsidiary_country_id
,to_subsidiary_state
,total_after_discount
,total_amount
,total_amount_2
,trace_reference_number
,trade_invoice_number_id
,trading_partner_code
,trading_partner_id
,trandate
,tranid
,trans_is_vsoe_bundle
,transaction_extid
,transaction_id
,transaction_number
,transaction_partner
,transaction_source
,transaction_type
,transaction_website
,transfer_location
,use_item_cost_as_transfer_cost
,vendor_number
,vendor_tax
,visible_in_customer_center
,wdem_payment_id
,wdem_settlement_id
,weighted_total
,withholding_tax_applies_to
,workday_er
,write_offbad_debt
,wt_applied
,wt_code_applied
,wt_rate
,wtax_base_url
,cmt
,related_customer_payment_id
,user_description
,wtax_cust_pay_posting_account
,all_hardware_fulfilled
,consolidated_tax_type_rate
,edocument_content
,edocument_sending_method_id
,edocument_status_id
,edocument_template_id
,einvoicing
,ic_vendor_account_id
,invoice_remit_name_1_id
,wtax_journal_reversal_flag
,account_name_reference
,account_number_reference
,amount_due_usd
,ap_bank_gl_account
,customer_subsidiary_code_refe
,date_contract_cost_accrual
,fiscal_rep_address
,hold_revenue_recognition
,is_advanced_intercompany
,is_reversal_0
,local_invoice_
,localization_for_us_english_id
,opportunity_classification
,order_subtype_id
,payment_purpose_code_ppc_1
,po_amount_usd
,purposereason_id
,rebill_state_id
,related_sales_transaction_id
,status_id
,total_usd
,wtax_base_amount
,SWT_INS_DT
,account_name_nonlatin
,bill_to_address_nonlatin
,bill_to_address_phone_nonlati
,bill_to_addressee_nonlatin
,bill_to_city_nonlatin
,bill_to_country_nonlatin
,bill_to_state_nonlatin
,bill_to_zip_code_nonlatin
,credit_rebill_unbilled_ar_adj
,ic_hold
,inbound_edocument_id
,includes_rebilled_lines
,indent_entities_id
,invoice_cancellation_error
,invoice_review_complete
,invoice_reviewed_by_id
,invoiced_to_be_cancelled
,market_offering_id
,related_cancelled_invoice_id
,related_revenue_element_id
,service_offering_id
,withholding_tax_script
,customer_subscription_name
,large_quote_id
,enable_role_restriction
,fx_manual_correction
,invoice_cancellation_reason_id
,Is_Deleted
,SWT_Ins_Date_Backup
)
SELECT 
account_based_number
,accounting_book_id
,accounting_period_id
,accrued_tax
,adjustment_journal
,adp_header_text
,adp_object_key
,advance_payment
,agreement_name
,agreement_number
,alternate_currency_id
,alternate_exchange_rate
,amount_after_discount
,amount_unbilled
,amount_withheld
,apttus_quote_
,ariba_bill_reference__payment
,ariba_po_number
,associated_revenue_arrangem_id
,associated_sales_transactio_id
,bank_status
,baseline_date
,batch_item_number
,batch_number
,begm
,bid_manager_id
,bill_check
,bill_pay_transaction
,bill_to_contact_id
,bill_to_country_pdf
,bill_type
,billaddress
,billing_account_id
,billing_instructions
,blended_rates
,bulk_submission_id
,business_style_id
,carrier
,cash_register
,central_bank_id
,closed
,company_status_id
,considered_by_kyriba_for_fore
,consolidated_billable_expense
,consolidated_product_type
,consolidated_tax_code
,contract_cost_amount
,contract_defer_expense_acct_id
,contract_expense_acct_id
,contract_term
,contract_terms_id
,cost_object
,create_date
,created_by_id
,created_from_id
,currency_code
,currency_id
,custom_form_id
,customer_bank_account_number
,customer_bank_routing_number
,customs_registration_number
,date_bid_close
,date_bid_open
,date_last_modified
,date_of_taxable_supply
,debooking_order_id
,debooking_processed
,delivery_terms_id
,delivery_without_approval
,deposit_bank_routing_number
,destination
,document_number
,due_date
,dwo_project_id
,edi_transaction_processed
,email
,end_date
,end_user_id
,end_user_shipping_address
,entity_id
,entity_tax_reg_num
,exchange_rate
,exchange_rate_to_usd
,expected_close
,export_to_openair
,exported_to_kyriba_for_paymen
,exported_to_openair
,external_ref_number
,fax
,federal
,file_attached
,fob
,forecast_type
,forecasting_last_export_date_
,payment_purpose_code_ppc_2
,payment_purpose_code_ppc_3
,from_contact_person_id
,from_subsidiary_country_id
,from_subsidiary_state
,functional_area_id
,go_to_market_route_id
,custom_functional_area_id
,custom_lcci_id
,custom_profit_center_id
,ic_error_message
,ic_invoice_number
,ic_je_number_id
,ic_ns_bill_number_id
,ic_ns_invoice_number_id
,ic_status_id
,ic_vendor_bill_number
,idt__bypass_tax_input_validat
,idt__do_not_calculate_tax
,include_in_forecast
,incoterm
,incoterms
,influencer_id
,inter_check
,intercompany_credit_memo_je_c
,intercompany_journal_entry_ch
,intercompany_transaction_id
,invoice_remit_name_id
,is_autocalculate_lag
,is_compliant
,is_created_from_merge
,is_finance_charge
,is_firmed
,is_intercompany
,is_merged_into_arrangements
,is_non_posting
,is_payment_hold
,is_reversal
,is_tax_reg_override
,is_wip
,iso_currency_code
,item_revision
,items_json
,itr_nexus
,je_subsidiary_netting_type_id
,je_to_subsidiary_settlement_id
,job_id
,journal_entry_amount
,kyriba_budget_code
,kyriba_payment_date
,kyriba_reference_number
,kyriba_transaction_last_ack
,kyriba_transaction_last_ack_d
,kyriba_transaction_status
,kyriba_transaction_status_dat
,kyriba_transaction_type_id
,landed_cost_allocation_method
,last_modified_date
,last_sales_activity
,lcci_id
,lead_source_id
,license_representative_id
,legacy_transaction_number
,legal_currency_exchange_rate
,legal_currency_id
,legal_currency_symbol
,letter_of_commitment
,legacy_cost_center
,license_sale_involved
,local_invoice_number
,localization_record_identif__0
,localization_record_identif__1
,localization_record_identif_id
,location_id
,lockbox_number
,lsa_link
,lsa_link_name
,memo
,memorized
,message
,misc_ic
,mode_of_transport_id
,nature_of_transaction_code_id
,needs_bill
,needs_revenue_commitment
,netsuite_project_id
,nexus_notc_id
,nondeductible_adjustment_jo_id
,nondeductible_tax_adjusted
,number_of_pricing_tiers
,onesource_document_number
,openair_created_from_time_e_id
,openair_expense_report_crea_id
,openair_expense_report_number
,openair_export_error
,openair_gsthst_amount
,openair_invoice_link
,openair_invoice_number
,openair_invoice_tax_amount
,openair_presales_id
,openair_pst_amount
,openair_revenue_recognition_i
,opening_balance_transaction
,opportunity__sfdc_id
,order_booking_owner_id
,order_source_id
,order_type_id
,original_invoice_number_id
,original_sales_order_number_id
,packing_list_instructions
,partner_id
,payer_account_number
,payer_name
,payer_routing_number
,payment_date
,payment_internal_id__source_id
,payment_method_id
,payment_terms_id
,payment_transaction_id
,pcard_number
,pn_ref_num
,po
,po_amount
,po_end_date
,po_start_date
,po_substitute
,po_substitute_type_id
,posted
,probability
,product_label_instructions
,profit_center_id
,projected_total
,promotion_code_id
,promotion_code_instance_id
,purchase_order_instructions
,quote_in_validation_date
,reason_1
,reason_2
,reason_3
,reason_4
,reason_code_id
,reason_for_hold
,rebate_create_automated_refun
,rebate_deal_id
,rebate_program_calendar_perio
,rebate_promotionprogram_id
,rebate_source_of_payment_id
,rebilled_invoice
,reference_document_internal_id
,reference_no__of_original_inv
,regime_code_of_supply_id
,region_id
,region_of_origin_id
,regular_ic
,related_sales_order_id
,related_tranid
,remittance_purpose_code
,remittance_reason_code_id
,renewal
,report_timestamp
,revenue_commitment_status
,revenue_committed
,revenue_recognition_method__id
,revenue_recognition_review
,revenue_status
,reversal_date
,reversal_number_id
,reverse_exchange_rate_id
,reversing_transaction_id
,risk_rating_id
,sales_effective_date
,sales_order_date
,sales_order_ref_id
,sales_rep_id
,scheduling_method_id
,ship_to_account_id
,ship_to_contact_id
,shipaddress
,shipment_notification_process
,shipment_received
,shipping_item_id
,sold_to_account_id
,sold_to_address_1
,sold_to_address_2
,sold_to_address_3
,sold_to_attention
,sold_to_city
,sold_to_country_id
,sold_to_phone
,sold_to_state
,sold_to_zip_code
,source_system_id
,special_instructions
,start_date
,status
,store_number
,subregion_id
,subsidiary_address_for_pdf
,tax_after_discount
,tax_and_legal_disclaimer_pdf
,tax_exemption_reason_code_id
,tax_reg_id
,tax_withheld
,termination_reason
,terms__conditions_link
,tier_1_partner_id
,tier_1_relationship_id
,tier_2_partner_id
,tier_2_relationship_id
,title
,to_be_emailed_custom_check
,to_contact_person_id
,to_subsidiary_code
,to_subsidiary_country_id
,to_subsidiary_state
,total_after_discount
,total_amount
,total_amount_2
,trace_reference_number
,trade_invoice_number_id
,trading_partner_code
,trading_partner_id
,trandate
,tranid
,trans_is_vsoe_bundle
,transaction_extid
,transaction_id
,transaction_number
,transaction_partner
,transaction_source
,transaction_type
,transaction_website
,transfer_location
,use_item_cost_as_transfer_cost
,vendor_number
,vendor_tax
,visible_in_customer_center
,wdem_payment_id
,wdem_settlement_id
,weighted_total
,withholding_tax_applies_to
,workday_er
,write_offbad_debt
,wt_applied
,wt_code_applied
,wt_rate
,wtax_base_url
,cmt
,related_customer_payment_id
,user_description
,wtax_cust_pay_posting_account
,all_hardware_fulfilled
,consolidated_tax_type_rate
,edocument_content
,edocument_sending_method_id
,edocument_status_id
,edocument_template_id
,einvoicing
,ic_vendor_account_id
,invoice_remit_name_1_id
,wtax_journal_reversal_flag
,account_name_reference
,account_number_reference
,amount_due_usd
,ap_bank_gl_account
,customer_subsidiary_code_refe
,date_contract_cost_accrual
,fiscal_rep_address
,hold_revenue_recognition
,is_advanced_intercompany
,is_reversal_0
,local_invoice_
,localization_for_us_english_id
,opportunity_classification
,order_subtype_id
,payment_purpose_code_ppc_1
,po_amount_usd
,purposereason_id
,rebill_state_id
,related_sales_transaction_id
,status_id
,total_usd
,wtax_base_amount
,sysdate as SWT_INS_DT
,account_name_nonlatin
,bill_to_address_nonlatin
,bill_to_address_phone_nonlati
,bill_to_addressee_nonlatin
,bill_to_city_nonlatin
,bill_to_country_nonlatin
,bill_to_state_nonlatin
,bill_to_zip_code_nonlatin
,credit_rebill_unbilled_ar_adj
,ic_hold
,inbound_edocument_id
,includes_rebilled_lines
,indent_entities_id
,invoice_cancellation_error
,invoice_review_complete
,invoice_reviewed_by_id
,invoiced_to_be_cancelled
,market_offering_id
,related_cancelled_invoice_id
,related_revenue_element_id
,service_offering_id
,withholding_tax_script
,customer_subscription_name
,large_quote_id
,enable_role_restriction
,fx_manual_correction
,invoice_cancellation_reason_id
,'true'
,SWT_INS_DT
FROM NS_Transactions_base_deleted;


INSERT /*+DIRECT*/ INTO swt_rpt_base.NS_SS_Deleted_Records 
(
internalId,
externalId,
deletedDate,
type,
name,
SWT_INS_DT
)
SELECT
internalId,
externalId,
deletedDate,
type,
name,
sysdate
FROM "swt_rpt_stg"."NS_SS_Deleted_Records";


insert into swt_rpt_base.NS_Missing_Transaction_Types
(
Date_Deleted
,Deleted_By
,Context
,Record_Type
,Name
,SWT_INS_DT
)
select 
Date_Deleted
,Deleted_By
,Context
,Record_Type
,Name
,sysdate
FROM swt_rpt_stg.NS_Missing_Transaction_Types;

CREATE LOCAL TEMP TABLE NS_Transactions_base_active ON COMMIT PRESERVE ROWS AS
(
SELECT DISTINCT * FROM swt_rpt_base.NS_Transactions_deleted_Ids where status='deleted' and transaction_id in ( select distinct transaction_id from swt_rpt_base.NS_Transactions where Is_Deleted ='false'))
SEGMENTED BY HASH(transaction_id) ALL NODES;

INSERT /*+DIRECT*/ INTO swt_rpt_base.NS_Transactions_deleted_Ids 
(
transaction_id,
SWT_INS_DT,
status
)
SELECT
transaction_id,
SYSDATE,
'activated'
FROM NS_Transactions_base_active;

/* Deleting partial audit entry */

/*DELETE FROM swt_rpt_stg.FAST_LD_AUDT where SUBJECT_AREA = 'NETSUITE' and
TBL_NM = 'NS_Transactions' and
COMPLTN_STAT = 'N' and
LD_DT=sysdate::date and 
SEQ_ID = (select max(SEQ_ID) from swt_rpt_stg.FAST_LD_AUDT where  SUBJECT_AREA = 'NETSUITE' and  TBL_NM = 'NS_Transactions' and  COMPLTN_STAT = 'N');
*/

/* Inserting new audit entry with all stats */

INSERT INTO swt_rpt_stg.FAST_LD_AUDT
(
SUBJECT_AREA
,TBL_NM
,LD_DT
,START_DT_TIME
,END_DT_TIME
,SRC_REC_CNT
,TGT_REC_CNT
,COMPLTN_STAT
)
select 'NETSUITE','NS_Transactions',sysdate::date,(select st from Start_Time_Tmp),sysdate,(select count from Start_Time_Tmp) ,(select count(*) from swt_rpt_base.NS_Transactions where SWT_INS_DT::date = sysdate::date),'Y';

Commit;


SELECT DO_TM_TASK('mergeout', 'swt_rpt_base.NS_Transactions');
SELECT DO_TM_TASK('mergeout', 'swt_rpt_stg.NS_Transactions_Hist');
SELECT DO_TM_TASK('mergeout', 'swt_rpt_stg.FAST_LD_AUDT');
select ANALYZE_STATISTICS('swt_rpt_base.NS_Transactions');
SELECT ANALYZE_STATISTICS('swt_rpt_base.NS_Transactions_deleted_IDS');
TRUNCATE TABLE "swt_rpt_stg"."NS_SS_Deleted_Records";
TRUNCATE TABLE "swt_rpt_stg"."NS_Missing_Transaction_Types";



